// ============================================================
// DETAIL AMI - Data indikator per dokumen AMI 2024-2025
// Sumber: 15 dokumen AMI dari PPM UNITA
// ============================================================

export interface IndikatorAMI {
  no: number;
  indikator: string;
  capaian: string;
  target: string;
  status: "Tercapai" | "Belum Tercapai";
}

export interface DokumenAMI {
  id: string;
  namaDokumen: string;
  kodeDokumen: string;
  tanggal: string;
  rataSkor: string;
  kategori: string;
  standarTerkait: string;
  indikator: IndikatorAMI[];
}

// ============================================================
// 15 DOKUMEN AMI DENGAN INDIKATOR DETAIL
// ============================================================
export const DOKUMEN_AMI_DETAIL: DokumenAMI[] = [
  {
    id: "AMI-PENDIDIKAN",
    namaDokumen: "AMI Pendidikan",
    kodeDokumen: "SPMI/PPM/MONEV/PEND/2025",
    tanggal: "2024-2025",
    rataSkor: "87% Tercapai",
    kategori: "Pendidikan",
    standarTerkait: "Standar 1-5 (SKL, SPB, SPN, SPP, SIS) + Standar 6-8 (SDT, SSP, SPM)",
    indikator: [
      { no: 1, indikator: "Persentase lulusan terserap di dunia kerja", capaian: "86,50%", target: "≥ 70%", status: "Tercapai" },
      { no: 2, indikator: "Persentase lulusan menjadi wirausahawan", capaian: "18,20%", target: "≥ 10%", status: "Tercapai" },
      { no: 3, indikator: "Rata-rata IPK lulusan", capaian: "3,48", target: "≥ 3,00", status: "Tercapai" },
      { no: 4, indikator: "Rata-rata masa studi lulusan", capaian: "3,8 tahun", target: "≤ 4,5 tahun", status: "Tercapai" },
      { no: 5, indikator: "Rata-rata masa tunggu lulusan kerja", capaian: "3,2 bulan", target: "≤ 6 bulan", status: "Tercapai" },
      { no: 6, indikator: "Ketersediaan dan kelengkapan dokumen kurikulum", capaian: "100%", target: "100%", status: "Tercapai" },
      { no: 7, indikator: "Frekuensi tinjauan kurikulum per tahun", capaian: "2 kali/tahun", target: "≥ 1/tahun", status: "Tercapai" },
      { no: 8, indikator: "Rasio mahasiswa per dosen pembimbing akademik", capaian: "16", target: "≤ 20", status: "Tercapai" },
      { no: 9, indikator: "Rasio mahasiswa per dosen pembimbing TA", capaian: "8 mhs/dosen", target: "≤ 10", status: "Tercapai" },
      { no: 10, indikator: "Persentase bahan ajar dan referensi tersedia", capaian: "100%", target: "100%", status: "Tercapai" },
      { no: 11, indikator: "Persentase mata kuliah blended learning", capaian: "32%", target: "≥ 20%", status: "Tercapai" },
      { no: 12, indikator: "Rata-rata jumlah mahasiswa per kelas", capaian: "32", target: "≤ 40", status: "Tercapai" },
      { no: 13, indikator: "Frekuensi monitoring kehadiran dan pembelajaran", capaian: "2x/semester", target: "≥ 1x/semester", status: "Tercapai" },
      { no: 14, indikator: "Persentase dosen menerapkan berbagai metode penilaian", capaian: "100%", target: "100%", status: "Tercapai" },
      { no: 15, indikator: "Ketepatan waktu input nilai pasca ujian (≤10 hari kerja)", capaian: "100%", target: "100%", status: "Tercapai" },
      { no: 16, indikator: "Persentase dosen berkualifikasi S2/S3", capaian: "100%", target: "100%", status: "Tercapai" },
      { no: 17, indikator: "Persentase dosen dan tendik bersertifikat pendidik", capaian: "88,50%", target: "≥ 75%", status: "Tercapai" },
      { no: 18, indikator: "Ketersediaan fasilitas pembelajaran sesuai standar", capaian: "100%", target: "100%", status: "Tercapai" },
      { no: 19, indikator: "Ketersediaan dokumen RPS, laporan pelaksanaan", capaian: "100%", target: "100%", status: "Tercapai" },
    ]
  },
  {
    id: "AMI-PENELITIAN",
    namaDokumen: "AMI Penelitian",
    kodeDokumen: "SPMI/PPM/MONEV/PEN/2025",
    tanggal: "2024-2025",
    rataSkor: "94% Tercapai",
    kategori: "Penelitian",
    standarTerkait: "Standar 9-16 (Luaran, Proses, Masukan, Hasil, Publikasi, Paten, Diseminasi, Kolaborasi)",
    indikator: [
      { no: 1, indikator: "Ketersediaan panduan penelitian yang memuat standar", capaian: "100%", target: "Tersedia", status: "Tercapai" },
      { no: 2, indikator: "Terlaksananya sosialisasi panduan penelitian", capaian: "100%", target: "Terlaksana", status: "Tercapai" },
      { no: 3, indikator: "Persentase laporan akhir dari penelitian yang tersedia", capaian: "96,80%", target: "90%-100%", status: "Tercapai" },
      { no: 4, indikator: "Integrasi hasil penelitian ke dalam RPS atau mata kuliah", capaian: "93,50%", target: "≥ 10%-15%", status: "Tercapai" },
      { no: 5, indikator: "Kesesuaian penelitian dengan roadmap visi misi", capaian: "97,20%", target: "75%-85%", status: "Tercapai" },
      { no: 6, indikator: "Jumlah publikasi ilmiah dosen tetap per tahun per prodi", capaian: "95,60%", target: "10 dokumen/prodi", status: "Tercapai" },
      { no: 7, indikator: "Perolehan HKI (Paten, Hak Cipta, Desain Industri)", capaian: "93,40%", target: "Meningkat setiap tahun", status: "Tercapai" },
      { no: 8, indikator: "Jumlah sitasi karya ilmiah dan jumlah buku", capaian: "90,80%", target: "Meningkat setiap tahun", status: "Tercapai" },
      { no: 9, indikator: "Adopsi industri atau pemuatan hasil penelitian", capaian: "88,50%", target: "Ada setiap tahun", status: "Tercapai" },
      { no: 10, indikator: "Pelaksanaan sosialisasi dan pelatihan terkait penelitian", capaian: "100%", target: "Terlaksana", status: "Tercapai" },
      { no: 11, indikator: "Proporsi skema penelitian (Dasar dan Terapan)", capaian: "96,80%", target: "Dasar 25%, Terapan 75%", status: "Tercapai" },
      { no: 12, indikator: "Jumlah penelitian yang sesuai dengan roadmap", capaian: "93,40%", target: "Progresif hingga 120", status: "Tercapai" },
      { no: 13, indikator: "Jumlah proposal yang diajukan sesuai roadmap", capaian: "95,20%", target: "Sesuai roadmap", status: "Tercapai" },
      { no: 14, indikator: "Jumlah laporan kemajuan penelitian yang tersedia", capaian: "97,80%", target: "100% tersedia", status: "Tercapai" },
      { no: 15, indikator: "Persentase keterpenuhan laporan akhir penelitian", capaian: "96,50%", target: "90%-100%", status: "Tercapai" },
      { no: 16, indikator: "Ketersediaan panduan penilaian proposal, pelaksanaan, hasil", capaian: "100%", target: "Tersedia", status: "Tercapai" },
      { no: 17, indikator: "Tersedianya laporan penilaian pelaksanaan penelitian", capaian: "100%", target: "Tersedia", status: "Tercapai" },
      { no: 18, indikator: "Tersedianya laporan Monitoring dan Evaluasi penelitian", capaian: "100%", target: "Tersedia", status: "Tercapai" },
      { no: 19, indikator: "Tersedianya laporan Rencana Tindak Lanjut penelitian", capaian: "93,80%", target: "Tersedia", status: "Tercapai" },
      { no: 20, indikator: "Jumlah dosen yang memenuhi kriteria peneliti", capaian: "91,76%", target: "Meningkat", status: "Tercapai" },
    ]
  },
  {
    id: "AMI-PENGABDIAN",
    namaDokumen: "AMI Pengabdian kepada Masyarakat",
    kodeDokumen: "SPMI/PPM/MONEV/PKM/2025",
    tanggal: "2024-2025",
    rataSkor: "94% Tercapai",
    kategori: "PkM",
    standarTerkait: "Standar 17-24 (Luaran, Proses, Masukan, Hasil, Publikasi, Produk, Diseminasi, Kolaborasi)",
    indikator: [
      { no: 1, indikator: "Ketersediaan panduan PkM yang memuat standar", capaian: "100%", target: "Tersedia", status: "Tercapai" },
      { no: 2, indikator: "Terlaksananya sosialisasi panduan PkM", capaian: "100%", target: "Terlaksana", status: "Tercapai" },
      { no: 3, indikator: "Persentase laporan akhir dari kegiatan PkM", capaian: "96,20%", target: "90%-100%", status: "Tercapai" },
      { no: 4, indikator: "Integrasi hasil PkM ke dalam RPS atau mata kuliah", capaian: "92,80%", target: "≥ 10%-15%", status: "Tercapai" },
      { no: 5, indikator: "Kesesuaian PkM dengan roadmap visi misi", capaian: "95,40%", target: "75%-85%", status: "Tercapai" },
      { no: 6, indikator: "Jumlah publikasi ilmiah dosen dari hasil PkM", capaian: "94,50%", target: "Meningkat setiap tahun", status: "Tercapai" },
      { no: 7, indikator: "Perolehan HKI, Teknologi Tepat Guna (TTG)", capaian: "93,80%", target: "Meningkat setiap tahun", status: "Tercapai" },
      { no: 8, indikator: "Penyelesaian masalah oleh mitra/desa sasaran", capaian: "96,80%", target: "Aktif", status: "Tercapai" },
      { no: 9, indikator: "Adopsi hasil PkM oleh masyarakat atau industri", capaian: "91,20%", target: "Ada setiap tahun", status: "Tercapai" },
      { no: 10, indikator: "Pelaksanaan sosialisasi dan pelatihan terkait PkM", capaian: "100%", target: "Terlaksana", status: "Tercapai" },
      { no: 11, indikator: "Proporsi skema PkM (Pengembangan, Penerapan)", capaian: "95,60%", target: "Sesuai proporsi", status: "Tercapai" },
      { no: 12, indikator: "Jumlah kegiatan PkM yang sesuai dengan roadmap", capaian: "94,20%", target: "Progresif", status: "Tercapai" },
      { no: 13, indikator: "Jumlah proposal PkM yang diajukan sesuai roadmap", capaian: "95,80%", target: "Sesuai roadmap", status: "Tercapai" },
      { no: 14, indikator: "Jumlah laporan kemajuan kegiatan PkM yang tersedia", capaian: "97,60%", target: "100% tersedia", status: "Tercapai" },
      { no: 15, indikator: "Persentase keterpenuhan laporan akhir PkM", capaian: "96,20%", target: "90%-100%", status: "Tercapai" },
      { no: 16, indikator: "Ketersediaan panduan penilaian proposal, pelaksanaan, hasil", capaian: "100%", target: "Tersedia", status: "Tercapai" },
      { no: 17, indikator: "Tersedianya laporan penilaian pelaksanaan PkM", capaian: "100%", target: "Tersedia", status: "Tercapai" },
      { no: 18, indikator: "Tersedianya laporan Monitoring dan Evaluasi PkM", capaian: "100%", target: "Tersedia", status: "Tercapai" },
      { no: 19, indikator: "Tersedianya laporan Rencana Tindak Lanjut PkM", capaian: "93,50%", target: "Tersedia", status: "Tercapai" },
      { no: 20, indikator: "Jumlah dosen yang memenuhi kriteria pengabdi", capaian: "92,40%", target: "Meningkat", status: "Tercapai" },
    ]
  },
  {
    id: "AMI-VMTS",
    namaDokumen: "AMI VMTS (Visi, Misi, Tujuan, dan Strategi)",
    kodeDokumen: "SPMI/PPM/MONEV/VMTS/2025",
    tanggal: "2024-2025",
    rataSkor: "3,54/4 (Sangat Baik)",
    kategori: "Tambahan",
    standarTerkait: "Standar 25 (VMTS)",
    indikator: [
      { no: 1, indikator: "Pemahaman VMTS Universitas Tulungagung", capaian: "3,55", target: "≥ 3,50", status: "Tercapai" },
      { no: 2, indikator: "Pemahaman keterkaitan VMTS dengan program kerja", capaian: "3,50", target: "≥ 3,50", status: "Tercapai" },
      { no: 3, indikator: "VMTS disosialisasikan secara berkala kepada dosen", capaian: "3,42", target: "≥ 3,50", status: "Belum Tercapai" },
      { no: 4, indikator: "Media dan metode sosialisasi VMTS mudah dipahami", capaian: "3,38", target: "≥ 3,50", status: "Belum Tercapai" },
      { no: 5, indikator: "VMTS menjadi acuan pelaksanaan pendidikan", capaian: "3,62", target: "≥ 3,50", status: "Tercapai" },
      { no: 6, indikator: "VMTS menjadi acuan pelaksanaan penelitian", capaian: "3,56", target: "≥ 3,50", status: "Tercapai" },
      { no: 7, indikator: "VMTS menjadi acuan pelaksanaan pengabdian", capaian: "3,54", target: "≥ 3,50", status: "Tercapai" },
      { no: 8, indikator: "VMTS terintegrasi dalam kurikulum dan proses pembelajaran", capaian: "3,50", target: "≥ 3,50", status: "Tercapai" },
      { no: 9, indikator: "Pimpinan menunjukkan komitmen yang kuat dalam VMTS", capaian: "3,62", target: "≥ 3,50", status: "Tercapai" },
      { no: 10, indikator: "Kebijakan pimpinan selaras dengan VMTS", capaian: "3,58", target: "≥ 3,50", status: "Tercapai" },
      { no: 11, indikator: "Dosen dilibatkan dalam penyusunan/evaluasi VMTS", capaian: "3,48", target: "≥ 3,50", status: "Belum Tercapai" },
      { no: 12, indikator: "Dosen dilibatkan dalam evaluasi ketercapaian VMTS", capaian: "3,36", target: "≥ 3,50", status: "Belum Tercapai" },
      { no: 13, indikator: "VMTS relevan dengan perkembangan ilmu pengetahuan", capaian: "3,50", target: "≥ 3,50", status: "Tercapai" },
      { no: 14, indikator: "VMTS relevan dengan kebutuhan dunia kerja", capaian: "3,48", target: "≥ 3,50", status: "Belum Tercapai" },
      { no: 15, indikator: "Program universitas mendukung pencapaian VMTS", capaian: "3,40", target: "≥ 3,50", status: "Belum Tercapai" },
    ]
  },
  {
    id: "AMI-TPTK",
    namaDokumen: "AMI Tata Pamong dan Tata Kelola",
    kodeDokumen: "SPMI/PPM/MONEV/TPTK/2025",
    tanggal: "2024-2025",
    rataSkor: "3,59/4 (Sangat Baik)",
    kategori: "Tambahan",
    standarTerkait: "Standar 26 (TPTK)",
    indikator: [
      { no: 1, indikator: "Pemahaman struktur tata pamong dan tata kelola", capaian: "3,58", target: "≥ 3,50", status: "Tercapai" },
      { no: 2, indikator: "Kebijakan akademik disusun melalui mekanisme yang jelas", capaian: "3,62", target: "≥ 3,50", status: "Tercapai" },
      { no: 3, indikator: "Dosen dilibatkan dalam penyusunan dan evaluasi kebijakan", capaian: "3,48", target: "≥ 3,50", status: "Belum Tercapai" },
      { no: 4, indikator: "Pimpinan memberikan arahan yang jelas", capaian: "3,60", target: "≥ 3,50", status: "Tercapai" },
      { no: 5, indikator: "Pengambilan keputusan akademik objektif dan transparan", capaian: "3,57", target: "≥ 3,50", status: "Tercapai" },
      { no: 6, indikator: "Informasi kebijakan akademik mudah diakses dosen", capaian: "3,65", target: "≥ 3,50", status: "Tercapai" },
      { no: 7, indikator: "Koordinasi pimpinan, fakultas, prodi berjalan baik", capaian: "3,50", target: "≥ 3,50", status: "Tercapai" },
      { no: 8, indikator: "Tata kelola mendukung pelaksanaan Tridharma", capaian: "3,48", target: "≥ 3,50", status: "Belum Tercapai" },
      { no: 9, indikator: "Evaluasi pelaksanaan kebijakan akademik dilakukan", capaian: "3,60", target: "≥ 3,50", status: "Tercapai" },
      { no: 10, indikator: "Hasil evaluasi ditindaklanjuti untuk perbaikan", capaian: "3,52", target: "≥ 3,50", status: "Tercapai" },
      { no: 11, indikator: "Pimpinan bersikap terbuka terhadap masukan dosen", capaian: "3,49", target: "≥ 3,50", status: "Belum Tercapai" },
      { no: 12, indikator: "Sistem tata kelola mendukung pencapaian VMTS", capaian: "3,71", target: "≥ 3,50", status: "Tercapai" },
      { no: 13, indikator: "Pembagian tugas dan kewenangan antarunit berjalan", capaian: "3,55", target: "≥ 3,50", status: "Tercapai" },
      { no: 14, indikator: "Tata kelola menerapkan prinsip transparansi", capaian: "3,62", target: "≥ 3,50", status: "Tercapai" },
      { no: 15, indikator: "Tata pamong universitas berjalan efektif", capaian: "3,66", target: "≥ 3,50", status: "Tercapai" },
    ]
  },
  {
    id: "AMI-MAHASISWA",
    namaDokumen: "AMI Mahasiswa",
    kodeDokumen: "SPMI/PPM/MONEV/MHS/2025",
    tanggal: "5 Maret 2025",
    rataSkor: "14/14 Tercapai",
    kategori: "Tambahan",
    standarTerkait: "Standar 27 (Mahasiswa)",
    indikator: [
      { no: 1, indikator: "Angka Efisiensi Edukasi (AEE PT)", capaian: "92,50%", target: "≥ 90%", status: "Tercapai" },
      { no: 2, indikator: "Persentase lulusan bekerja, berwirausaha, atau melanjutkan studi", capaian: "84,30%", target: "≥ 80%", status: "Tercapai" },
      { no: 3, indikator: "Persentase mahasiswa berkegiatan atau berorganisasi", capaian: "68,40%", target: "≥ 60%", status: "Tercapai" },
      { no: 4, indikator: "Ketersediaan kebijakan dan pedoman penerimaan mahasiswa", capaian: "100%", target: "100%", status: "Tercapai" },
      { no: 5, indikator: "Ketersediaan sistem pengelolaan dan layanan kemahasiswaan", capaian: "100%", target: "100%", status: "Tercapai" },
      { no: 6, indikator: "Ketersediaan layanan pembelajaran di luar program reguler", capaian: "100%", target: "100%", status: "Tercapai" },
      { no: 7, indikator: "Program penguatan integritas akademik dan adaptasi", capaian: "95,00%", target: "≥ 90%", status: "Tercapai" },
      { no: 8, indikator: "Analisis prestasi mahasiswa, keterserapan lulusan", capaian: "100%", target: "100%", status: "Tercapai" },
      { no: 9, indikator: "Pengukuran capaian standar kompetensi lulusan", capaian: "91,80%", target: "≥ 90%", status: "Tercapai" },
      { no: 10, indikator: "Implementasi Pendidikan Anti Korupsi dalam kurikulum", capaian: "100%", target: "100%", status: "Tercapai" },
      { no: 11, indikator: "Program pencegahan dan penanganan kekerasan", capaian: "100%", target: "100%", status: "Tercapai" },
      { no: 12, indikator: "Pengakuan dan apresiasi kompetensi lulusan oleh DUDI", capaian: "82,40%", target: "≥ 80%", status: "Tercapai" },
      { no: 13, indikator: "Perbaikan proses pembelajaran berdasarkan hasil AMI", capaian: "94,50%", target: "≥ 90%", status: "Tercapai" },
      { no: 14, indikator: "Kontribusi mahasiswa dalam pencapaian SDGs", capaian: "76,20%", target: "≥ 70%", status: "Tercapai" },
    ]
  },
  {
    id: "AMI-SDM",
    namaDokumen: "AMI Sumber Daya Manusia",
    kodeDokumen: "SPMI/PPM/MONEV/SDM/2025",
    tanggal: "2024-2025",
    rataSkor: "16/18 Tercapai",
    kategori: "Tambahan",
    standarTerkait: "Standar 28 (SDM)",
    indikator: [
      { no: 1, indikator: "Kualifikasi akademik minimal S2 bagi dosen", capaian: "100%", target: "100%", status: "Tercapai" },
      { no: 2, indikator: "Persentase dosen tetap dengan jabatan fungsional minimal Lektor", capaian: "52,40%", target: "≥ 75%", status: "Belum Tercapai" },
      { no: 3, indikator: "Kepemilikan sertifikat pendidik atau sertifikat profesi dosen", capaian: "94,60%", target: "100%", status: "Belum Tercapai" },
      { no: 4, indikator: "Persentase dosen tidak tetap dengan sertifikat kompetensi", capaian: "16,20%", target: "< 20%", status: "Tercapai" },
      { no: 5, indikator: "Kualifikasi akademik minimal D3 untuk tenaga kependidikan", capaian: "100%", target: "100%", status: "Tercapai" },
      { no: 6, indikator: "Keanggotaan tenaga perpustakaan profesional", capaian: "100%", target: "100%", status: "Tercapai" },
      { no: 7, indikator: "Pelaksanaan uji kompetensi keahlian dalam bidangnya", capaian: "100%", target: "100%", status: "Tercapai" },
      { no: 8, indikator: "Ketersediaan laporan monev kinerja dosen", capaian: "100%", target: "100%", status: "Tercapai" },
      { no: 9, indikator: "Ketersediaan laporan monev kinerja tenaga kependidikan", capaian: "100%", target: "100%", status: "Tercapai" },
      { no: 10, indikator: "Ketersediaan dokumen Laporan DP3 sebagai evaluasi", capaian: "100%", target: "100%", status: "Tercapai" },
      { no: 11, indikator: "Ketersediaan dokumen Renstra/Renop pengelolaan SDM", capaian: "100%", target: "100%", status: "Tercapai" },
      { no: 12, indikator: "Terpenuhinya biaya pengembangan SDM dari anggaran", capaian: "88,70%", target: "85%-95%", status: "Tercapai" },
      { no: 13, indikator: "Ketersediaan Pedoman Kesejahteraan Karyawan", capaian: "100%", target: "100%", status: "Tercapai" },
      { no: 14, indikator: "Pelaksanaan survei kepuasan terhadap kesejahteraan", capaian: "100%", target: "100%", status: "Tercapai" },
      { no: 15, indikator: "Adanya bukti penyempurnaan pedoman kesejahteraan", capaian: "100%", target: "100%", status: "Tercapai" },
      { no: 16, indikator: "Efektivitas kebijakan dan sistem rekrutmen SDM", capaian: "95,20%", target: "≥ 90%", status: "Tercapai" },
      { no: 17, indikator: "Ketersediaan lembaga atau fungsi pengembangan SDM", capaian: "100%", target: "100%", status: "Tercapai" },
      { no: 18, indikator: "Ketersediaan dokumen struktur organisasi pengelolaan SDM", capaian: "100%", target: "100%", status: "Tercapai" },
    ]
  },
  {
    id: "AMI-KESEJAHTERAAN",
    namaDokumen: "AMI Kesejahteraan",
    kodeDokumen: "SPMI/PPM/MONEV/KSJH/2025",
    tanggal: "24 Mei 2025",
    rataSkor: "96,32% (Sangat Baik)",
    kategori: "Tambahan",
    standarTerkait: "Standar 28 (SDM - Kesejahteraan)",
    indikator: [
      { no: 1, indikator: "Ketersediaan Buku Pedoman Kesejahteraan", capaian: "100%", target: "Tersedia dan disahkan", status: "Tercapai" },
      { no: 2, indikator: "Ketersediaan SOP Pembayaran Gaji dan Tunjangan", capaian: "100%", target: "Tersedia", status: "Tercapai" },
      { no: 3, indikator: "Ketersediaan prosedur monitoring dan evaluasi", capaian: "100%", target: "Tersedia", status: "Tercapai" },
      { no: 4, indikator: "Sosialisasi dokumen standar kesejahteraan", capaian: "94,50%", target: "Terlaksana", status: "Tercapai" },
      { no: 5, indikator: "Pemenuhan hak karyawan (dosen dan tendik)", capaian: "96,80%", target: "100% terpenuhi", status: "Tercapai" },
      { no: 6, indikator: "Realisasi anggaran kesejahteraan dalam RENOP", capaian: "97,20%", target: "Terealisasi", status: "Tercapai" },
      { no: 7, indikator: "Sistem imbal jasa yang kompetitif", capaian: "93,40%", target: "Kompetitif", status: "Tercapai" },
      { no: 8, indikator: "Jaminan kesehatan/asuransi untuk seluruh karyawan", capaian: "100%", target: "100% tercover", status: "Tercapai" },
      { no: 9, indikator: "Pemberian hak cuti sesuai regulasi", capaian: "96,50%", target: "Sesuai regulasi", status: "Tercapai" },
      { no: 10, indikator: "Fasilitas bantuan (anak karyawan, pendidikan)", capaian: "90,80%", target: "Tersedia", status: "Tercapai" },
      { no: 11, indikator: "Program rekreasi (tour) dan santunan sosial", capaian: "95,60%", target: "Terlaksana", status: "Tercapai" },
      { no: 12, indikator: "Penyaluran bantuan dana sosial kepada karyawan", capaian: "94,20%", target: "Tersalurkan", status: "Tercapai" },
      { no: 13, indikator: "Alokasi dana reward prestasi dan pengembangan", capaian: "95,80%", target: "Teralokasi", status: "Tercapai" },
      { no: 14, indikator: "Ketersediaan instrumen/kuesioner survei kepuasan", capaian: "100%", target: "Tersedia", status: "Tercapai" },
      { no: 15, indikator: "Pelaksanaan survei kepuasan kesejahteraan", capaian: "100%", target: "Terlaksana", status: "Tercapai" },
      { no: 16, indikator: "Penyempurnaan pedoman kesejahteraan berdasarkan survei", capaian: "93,50%", target: "Terlaksana", status: "Tercapai" },
      { no: 17, indikator: "Tingkat kepuasan karyawan terhadap kesejahteraan", capaian: "94,80%", target: "≥ 85%", status: "Tercapai" },
      { no: 18, indikator: "Ketersediaan laporan Monev Kesejahteraan", capaian: "100%", target: "Tersedia", status: "Tercapai" },
      { no: 19, indikator: "Kecukupan dana pensiun/hari tua bagi karyawan", capaian: "92,60%", target: "Tersedia", status: "Tercapai" },
    ]
  },
  {
    id: "AMI-KEUANGAN",
    namaDokumen: "AMI Keuangan",
    kodeDokumen: "SPMI/PPM/MONEV/KEU/2025",
    tanggal: "15 Mei 2025",
    rataSkor: "14/14 Tercapai",
    kategori: "Tambahan",
    standarTerkait: "Standar 29 (Keuangan, Sarana, Prasarana)",
    indikator: [
      { no: 1, indikator: "Realisasi Pendapatan terhadap Target RENOP", capaian: "95,20%", target: "≥ 90%", status: "Tercapai" },
      { no: 2, indikator: "Realisasi Belanja Operasional Pendidikan", capaian: "94,80%", target: "≥ 90%", status: "Tercapai" },
      { no: 3, indikator: "Realisasi Belanja Kemahasiswaan terhadap target", capaian: "95,60%", target: "≥ 90%", status: "Tercapai" },
      { no: 4, indikator: "Realisasi Belanja Penelitian terhadap target", capaian: "96,10%", target: "≥ 90%", status: "Tercapai" },
      { no: 5, indikator: "Realisasi Belanja Pengabdian kepada Masyarakat", capaian: "94,30%", target: "≥ 90%", status: "Tercapai" },
      { no: 6, indikator: "Realisasi Belanja Investasi SDM terhadap target", capaian: "95,70%", target: "≥ 90%", status: "Tercapai" },
      { no: 7, indikator: "Realisasi Belanja Investasi Sarana terhadap target", capaian: "95,40%", target: "≥ 90%", status: "Tercapai" },
      { no: 8, indikator: "Realisasi Belanja Investasi Prasarana terhadap target", capaian: "94,90%", target: "≥ 90%", status: "Tercapai" },
      { no: 9, indikator: "Rasio Pendapatan terhadap Belanja (surplus)", capaian: "97,30%", target: "≥ 95%", status: "Tercapai" },
      { no: 10, indikator: "Ketersediaan kebijakan dan pedoman keuangan", capaian: "100%", target: "100%", status: "Tercapai" },
      { no: 11, indikator: "Ketersediaan sistem pelaporan keuangan", capaian: "100%", target: "100%", status: "Tercapai" },
      { no: 12, indikator: "Ketersediaan dokumen Rencana Operasional (RENOP)", capaian: "100%", target: "100%", status: "Tercapai" },
      { no: 13, indikator: "Efisiensi penyerapan anggaran secara keseluruhan", capaian: "95,30%", target: "≥ 90%", status: "Tercapai" },
      { no: 14, indikator: "Kepatuhan terhadap Kebijakan Umum Anggaran", capaian: "96,40%", target: "≥ 95%", status: "Tercapai" },
    ]
  },
  {
    id: "AMI-SARPRAS",
    namaDokumen: "AMI Sarana dan Prasarana",
    kodeDokumen: "SPMI/PPM/MONEV/SARPRAS/2025",
    tanggal: "2024-2025",
    rataSkor: "14/14 Tercapai",
    kategori: "Tambahan",
    standarTerkait: "Standar 29 (Keuangan, Sarana, Prasarana)",
    indikator: [
      { no: 1, indikator: "Persentase sarana dalam kondisi baik/terawat", capaian: "95,20%", target: "≥ 90%", status: "Tercapai" },
      { no: 2, indikator: "Persentase prasarana dalam kondisi baik/terawat", capaian: "95,80%", target: "≥ 90%", status: "Tercapai" },
      { no: 3, indikator: "Ketersediaan ruang kelas sesuai standar rasio", capaian: "94,50%", target: "≥ 90%", status: "Tercapai" },
      { no: 4, indikator: "Ketersediaan laboratorium dan studio sesuai standar", capaian: "96,30%", target: "≥ 90%", status: "Tercapai" },
      { no: 5, indikator: "Ketersediaan ruang dosen sesuai standar", capaian: "95,70%", target: "≥ 90%", status: "Tercapai" },
      { no: 6, indikator: "Ketersediaan perpustakaan dan sumber belajar", capaian: "97,20%", target: "≥ 90%", status: "Tercapai" },
      { no: 7, indikator: "Ketersediaan fasilitas ICT, jaringan internet, WiFi", capaian: "95,40%", target: "≥ 90%", status: "Tercapai" },
      { no: 8, indikator: "Ketersediaan fasilitas kemahasiswaan dan ekstrakurikuler", capaian: "94,80%", target: "≥ 90%", status: "Tercapai" },
      { no: 9, indikator: "Realisasi pemeliharaan sarana terhadap kebutuhan", capaian: "95,60%", target: "≥ 90%", status: "Tercapai" },
      { no: 10, indikator: "Realisasi pemeliharaan prasarana terhadap kebutuhan", capaian: "94,90%", target: "≥ 90%", status: "Tercapai" },
      { no: 11, indikator: "Ketersediaan kebijakan dan pedoman sarana-prasarana", capaian: "100%", target: "100%", status: "Tercapai" },
      { no: 12, indikator: "Ketersediaan sistem inventarisasi sarana-prasarana", capaian: "100%", target: "100%", status: "Tercapai" },
      { no: 13, indikator: "Efektivitas pelaksanaan pemeliharaan berkala", capaian: "95,10%", target: "≥ 90%", status: "Tercapai" },
      { no: 14, indikator: "Kepatuhan terhadap standar sarana prasarana", capaian: "96,40%", target: "≥ 90%", status: "Tercapai" },
    ]
  },
  {
    id: "AMI-MBKM",
    namaDokumen: "AMI Merdeka Belajar Kampus Merdeka",
    kodeDokumen: "SPMI/PPM/MONEV/MBKM/2025",
    tanggal: "5 Februari 2025",
    rataSkor: "95,50 (Sangat Baik)",
    kategori: "Tambahan",
    standarTerkait: "Standar 31 (MBKM)",
    indikator: [
      { no: 1, indikator: "Ketersediaan Standar dan Panduan MBKM", capaian: "95,50", target: "≥ 90", status: "Tercapai" },
      { no: 2, indikator: "Kerjasama dan Implementasi MBKM", capaian: "95,93", target: "≥ 90", status: "Tercapai" },
      { no: 3, indikator: "Partisipasi dan Capaian Mahasiswa MBKM", capaian: "94,40", target: "≥ 90", status: "Tercapai" },
      { no: 4, indikator: "Monitoring dan Evaluasi (Monev) MBKM", capaian: "94,53", target: "≥ 90", status: "Tercapai" },
    ]
  },
  {
    id: "AMI-PELAYANAN",
    namaDokumen: "AMI Pelayanan kepada Mahasiswa (Ganjil & Genap)",
    kodeDokumen: "SPMI/PPM/MONEV/PLYN/2025",
    tanggal: "Ganjil: 5 Feb 2025, Genap: 4 Agu 2025",
    rataSkor: "Ganjil 3,48 → Genap 3,58 (Sangat Baik)",
    kategori: "Tambahan",
    standarTerkait: "Standar 33 (Pelayanan kepada Mahasiswa)",
    indikator: [
      { no: 1, indikator: "Informasi jadwal perkuliahan disampaikan dengan jelas", capaian: "3,68", target: "≥ 3,50", status: "Tercapai" },
      { no: 2, indikator: "Kemudahan proses pendaftaran mata kuliah/KRS", capaian: "3,60", target: "≥ 3,50", status: "Tercapai" },
      { no: 3, indikator: "Akses Sistem Informasi Akademik (SIAKAD)", capaian: "3,70", target: "≥ 3,50", status: "Tercapai" },
      { no: 4, indikator: "Kecepatan respons UPPS terhadap keluhan akademik", capaian: "3,47", target: "≥ 3,50", status: "Belum Tercapai" },
      { no: 5, indikator: "Layanan akademik mendukung pencapaian target pembelajaran", capaian: "3,52", target: "≥ 3,50", status: "Tercapai" },
      { no: 6, indikator: "Informasi biaya kuliah dan pembayaran disampaikan jelas", capaian: "3,57", target: "≥ 3,50", status: "Tercapai" },
      { no: 7, indikator: "Kemudahan proses pembayaran SPP", capaian: "3,54", target: "≥ 3,50", status: "Tercapai" },
      { no: 8, indikator: "Transparansi penggunaan dana/biaya kuliah", capaian: "3,46", target: "≥ 3,50", status: "Belum Tercapai" },
      { no: 9, indikator: "Layanan beasiswa, keringanan biaya, cicilan", capaian: "3,60", target: "≥ 3,50", status: "Tercapai" },
      { no: 10, indikator: "Kecepatan proses verifikasi/pengembalian dana", capaian: "3,48", target: "≥ 3,50", status: "Belum Tercapai" },
      { no: 11, indikator: "Akses informasi kegiatan organisasi mahasiswa dan event", capaian: "3,49", target: "≥ 3,50", status: "Belum Tercapai" },
      { no: 12, indikator: "Kemudahan akses dokumen akademik (transkrip, KHS)", capaian: "3,56", target: "≥ 3,50", status: "Tercapai" },
      { no: 13, indikator: "Akses laboratorium sesuai kurikulum", capaian: "3,55", target: "≥ 3,50", status: "Tercapai" },
      { no: 14, indikator: "Akses perpustakaan dan koleksi buku/jurnal", capaian: "3,52", target: "≥ 3,50", status: "Tercapai" },
      { no: 15, indikator: "Ketersediaan fasilitas WiFi dan internet kampus", capaian: "3,50", target: "≥ 3,50", status: "Tercapai" },
      { no: 16, indikator: "Jadwal pembimbingan akademik periodik terstruktur", capaian: "3,48", target: "≥ 3,50", status: "Belum Tercapai" },
      { no: 17, indikator: "Layanan tracer study dan pendampingan karir", capaian: "3,50", target: "≥ 3,50", status: "Tercapai" },
      { no: 18, indikator: "Pendampingan PKM oleh dosen pembimbing", capaian: "3,49", target: "≥ 3,50", status: "Belum Tercapai" },
      { no: 19, indikator: "Fasilitas kebersihan (toilet, tempat sampah)", capaian: "3,44", target: "≥ 3,50", status: "Belum Tercapai" },
      { no: 20, indikator: "Layanan fasilitas kesehatan (poliklinik)", capaian: "3,52", target: "≥ 3,50", status: "Tercapai" },
    ]
  },
  {
    id: "AMI-PROSES-PEMBELAJARAN",
    namaDokumen: "AMI Proses Pembelajaran (Ganjil & Genap)",
    kodeDokumen: "SPMI/PPM/MONEV/SPB/2025",
    tanggal: "Ganjil & Genap 2024-2025",
    rataSkor: "Ganjil 3,49 → Genap 3,59 (Sangat Baik)",
    kategori: "Pendidikan",
    standarTerkait: "Standar 2 (Proses Pembelajaran)",
    indikator: [
      { no: 1, indikator: "Efektivitas metode Hybrid Learning", capaian: "3,74", target: "≥ 3,50", status: "Tercapai" },
      { no: 2, indikator: "Efektivitas metode Luring (offline)", capaian: "3,76", target: "≥ 3,50", status: "Tercapai" },
      { no: 3, indikator: "Efektivitas metode Daring (online)", capaian: "3,65", target: "≥ 3,50", status: "Tercapai" },
      { no: 4, indikator: "Dosen menyampaikan RPS pada pertemuan pertama", capaian: "3,78", target: "≥ 3,50", status: "Tercapai" },
      { no: 5, indikator: "Tahapan perkuliahan (pendahuluan, isi, penutup)", capaian: "3,77", target: "≥ 3,50", status: "Tercapai" },
      { no: 6, indikator: "Dosen menggunakan metode pembelajaran efektif", capaian: "3,76", target: "≥ 3,50", status: "Tercapai" },
      { no: 7, indikator: "Dosen menggunakan media pembelajaran", capaian: "3,75", target: "≥ 3,50", status: "Tercapai" },
      { no: 8, indikator: "Dosen menggunakan sumber belajar sesuai RPS", capaian: "3,76", target: "≥ 3,50", status: "Tercapai" },
      { no: 9, indikator: "Dosen menguasai materi perkuliahan", capaian: "3,82", target: "≥ 3,50", status: "Tercapai" },
      { no: 10, indikator: "Dosen mengaitkan materi dengan konteks", capaian: "3,78", target: "≥ 3,50", status: "Tercapai" },
      { no: 11, indikator: "Dosen mengintegrasikan teori dari disiplin ilmu lain", capaian: "3,76", target: "≥ 3,50", status: "Tercapai" },
      { no: 12, indikator: "Dosen merespon setiap pertanyaan mahasiswa", capaian: "3,80", target: "≥ 3,50", status: "Tercapai" },
      { no: 13, indikator: "Dosen menggunakan hasil penelitian sebagai rujukan", capaian: "3,74", target: "≥ 3,50", status: "Tercapai" },
      { no: 14, indikator: "Dosen menerapkan hasil penelitian dalam pembelajaran", capaian: "3,75", target: "≥ 3,50", status: "Tercapai" },
      { no: 15, indikator: "Dosen memberikan materi studi kasus", capaian: "3,75", target: "≥ 3,50", status: "Tercapai" },
      { no: 16, indikator: "Dosen menggunakan hasil PkM untuk memperkaya materi", capaian: "3,73", target: "≥ 3,50", status: "Tercapai" },
      { no: 17, indikator: "Dosen mengelola kelas pada setiap pertemuan", capaian: "3,75", target: "≥ 3,50", status: "Tercapai" },
      { no: 18, indikator: "Dosen memotivasi keaktifan mahasiswa", capaian: "3,80", target: "≥ 3,50", status: "Tercapai" },
      { no: 19, indikator: "Dosen melibatkan mahasiswa dalam kegiatan akademik", capaian: "3,75", target: "≥ 3,50", status: "Tercapai" },
      { no: 20, indikator: "Dosen melaksanakan pembelajaran dengan waktu proporsional", capaian: "3,76", target: "≥ 3,50", status: "Tercapai" },
    ]
  },
];
