// ============================================================
// DATA: 38 FORMULIR MUTU - DENGAN ASPEK/INDIKATOR TERISI PENUH
// ============================================================

const { cell } = require("./formulir_mutu_core.js");

// Helper tanda tangan
function ttdKaProdi() {
  return [
    { label: "Disusun oleh:\nKa. Prodi / GKM", nama: "(...........................)", jabatan: "Ka. Prodi", nip: "NIDN/NIP: ................" },
    { label: "Diperiksa oleh:\nKa. LPM Fakultas", nama: "(...........................)", jabatan: "Ka. LPM", nip: "NIDN/NIP: ................" },
    { label: "Disetujui oleh:\nKa. PPM", nama: "(...........................)", jabatan: "Ka. PPM", nip: "NIDN/NIP: ................" },
  ];
}

function ttdKaLPPM() {
  return [
    { label: "Disusun oleh:\nPeneliti/Pelaksana", nama: "(...........................)", jabatan: "Peneliti", nip: "NIDN/NIP: ................" },
    { label: "Diperiksa oleh:\nKa. LPPM", nama: "(...........................)", jabatan: "Ka. LPPM", nip: "NIDN/NIP: ................" },
    { label: "Disetujui oleh:\nKa. PPM", nama: "(...........................)", jabatan: "Ka. PPM", nip: "NIDN/NIP: ................" },
  ];
}

function ttdKaUnit() {
  return [
    { label: "Disusun oleh:\nKa. Unit", nama: "(...........................)", jabatan: "Ka. Unit", nip: "NIDN/NIP: ................" },
    { label: "Diperiksa oleh:\nKa. PPM", nama: "(...........................)", jabatan: "Ka. PPM", nip: "NIDN/NIP: ................" },
    { label: "Mengetahui:\nWakil Rektor", nama: "(...........................)", jabatan: "Wakil Rektor", nip: "NIDN/NIP: ................" },
  ];
}

function ttdDosen() {
  return [
    { label: "Dosen Pengampu", nama: "(...........................)", jabatan: "Dosen", nip: "NIDN: ................" },
    { label: "Ka. Prodi", nama: "(...........................)", jabatan: "Ka. Prodi", nip: "NIDN: ................" },
  ];
}

// Helper untuk tabel aspek (skor 1-5)
function tabelAspekSkor(judul, aspekList, kolomSkor = "Skor (1-5)") {
  return {
    title: judul,
    headers: ["No", "Aspek yang Dinilai", kolomSkor, "Catatan"],
    widths: [5, 65, 10, 20],
    rows: aspekList.map((asp, i) => [String(i + 1), asp, "", ""]),
  };
}

// Helper untuk tabel indikator dengan beberapa kolom nilai
function tabelIndikatorMulti(judul, indikatorList, kolomNilai = ["1", "2", "3", "4", "5"]) {
  const headers = ["No", "Indikator", ...kolomNilai];
  const widths = [5, 50, ...kolomNilai.map(() => Math.floor(45 / kolomNilai.length))];
  return {
    title: judul,
    headers: headers,
    widths: widths,
    rows: indikatorList.map((ind, i) => [String(i + 1), ind, ...kolomNilai.map(() => "")]),
  };
}

// ============================================================
// 38 FORMULIR MUTU - ASPEK/INDIKATOR TERISI PENUH
// ============================================================

const FORMULIR_LIST = [
  // === BAB III: FORMULIR STANDAR PENDIDIKAN ===
  {
    nomor: 1,
    namaFormulir: "FORMULIR MONITORING EVALUASI PROSES PEMBELAJARAN",
    kodeFormulir: "FM-PBM-01",
    kategori: "FORM",
    matchStandar: "Standar Proses Pembelajaran (SPB) - Pasal 11-24 Permen 39/2025",
    deskripsi: [
      "Formulir ini digunakan untuk monitoring dan evaluasi pelaksanaan proses pembelajaran di setiap program studi. Formulir mengacu pada Standar Proses Pembelajaran (SPB) sebagaimana diatur dalam Pasal 11-24 Permen 39 Tahun 2025.",
      "Formulir diisi oleh mahasiswa (emonev) di akhir semester, diolah oleh GKM, dan menjadi bahan bagi AMI dan RTM tahunan.",
    ],
    instruksi: "Berikan penilaian dengan skala 1-5 (1=sangat tidak baik, 5=sangat baik). Isi catatan untuk aspek yang perlu perbaikan.",
    fieldTables: [
      {
        title: "A. Identitas",
        headers: ["Komponen", "Isian"],
        widths: [30, 70],
        rows: [
          ["Program Studi", ""],
          ["Semester / Tahun Akademik", ""],
          ["Mata Kuliah", ""],
          ["Kode Mata Kuliah / SKS", ""],
          ["Dosen Pengampu", ""],
          ["Tanggal Pengisian", ""],
          ["Jumlah Responden (Mahasiswa)", ""],
        ],
      },
      tabelAspekSkor("B. Penilaian Aspek Pembelajaran", [
        "Efektivitas perkuliahan dilaksanakan dengan metode Hybrid Learning",
        "Efektivitas perkuliahan dilaksanakan dengan metode Luring (offline)",
        "Efektivitas perkuliahan dilaksanakan dengan metode Daring (online)",
        "Dosen menyampaikan RPS pada pertemuan pertama",
        "Dosen melakukan tahapan perkuliahan (pendahuluan, isi, penutup) pada setiap pertemuan",
        "Dosen menggunakan metode pembelajaran yang efektif pada setiap pertemuan",
        "Dosen menggunakan media pembelajaran pada setiap pertemuan",
        "Dosen menggunakan sumber belajar sesuai dengan RPS",
        "Dosen menguasai materi perkuliahan",
        "Dosen mengaitkan materi yang diajarkan sesuai dengan konteks",
        "Dosen mengintegrasikan berbagai teori dari disiplin ilmu lain ke dalam topik pembelajaran",
        "Dosen merespon setiap pertanyaan mahasiswa",
        "Dosen menggunakan hasil penelitian (artikel, buku) sebagai rujukan dalam pembelajaran",
        "Dosen menerapkan hasil penelitiannya ke dalam topik pembelajaran",
        "Dosen memberikan materi penelitian atau studi kasus topik pembelajaran",
        "Dosen menggunakan hasil pengabdiannya kepada masyarakat untuk memperkaya materi perkuliahan",
        "Dosen mengelola kelas pada setiap pertemuan",
        "Dosen memotivasi keaktifan mahasiswa dalam setiap pembelajaran",
        "Dosen melibatkan mahasiswa dalam kegiatan akademik (pengajaran, penelitian, pengabdian)",
        "Dosen melaksanakan pembelajaran dengan waktu yang proporsional pada setiap pertemuan",
        "Dosen mengakui keterbatasannya dalam pembelajaran",
        "Dosen menerima kritik dan saran tentang proses pembelajaran",
        "Dosen memberikan umpan balik terhadap setiap hasil pekerjaan mahasiswa",
        "Dosen melakukan penilaian perkuliahan secara objektif dan transparan",
        "Dosen menepati jadwal perkuliahan sesuai kalender akademik",
      ]),
      {
        title: "C. Rekomendasi dan Tindak Lanjut",
        headers: ["No", "Rekomendasi", "Penanggung Jawab", "Target Waktu"],
        widths: [5, 55, 25, 15],
        emptyRows: 5,
      },
    ],
    tandaTangan: ttdKaProdi(),
  },
  {
    nomor: 2,
    namaFormulir: "FORMULIR MONITORING EVALUASI KOMPETENSI LULUSAN",
    kodeFormulir: "FM-PBM-02",
    kategori: "FORM",
    matchStandar: "Standar Kompetensi Lulusan (SKL) - Pasal 6-10 Permen 39/2025",
    deskripsi: [
      "Formulir ini digunakan untuk monitoring dan evaluasi capaian CPL lulusan berdasarkan tracer study dan survey pengguna lulusan. Mengacu pada Standar Kompetensi Lulusan (SKL) Permen 39 Tahun 2025.",
    ],
    instruksi: "Isi formulir dengan data tracer study dan analisis CPL lulusan. Berikan penilaian dan rekomendasi perbaikan.",
    fieldTables: [
      {
        title: "A. Identitas",
        headers: ["Komponen", "Isian"],
        widths: [30, 70],
        rows: [
          ["Program Studi", ""],
          ["Tahun Lulus", ""],
          ["Jumlah Lulusan", ""],
          ["Response Rate Tracer Study", ""],
          ["Tanggal Evaluasi", ""],
        ],
      },
      {
        title: "B. Capaian CPL Berdasarkan Tracer Study",
        headers: ["No", "Komponen CPL", "Target (%)", "Capaian (%)", "Skor (1-5)", "Analisis"],
        widths: [5, 30, 12, 12, 10, 31],
        rows: [
          ["1", "Sikap (attitude) - beriman, bertakwa, berakhlak mulia", "100", "", "", ""],
          ["2", "Pengetahuan (knowledge) - penguasaan IPTEK", "100", "", "", ""],
          ["3", "Keterampilan Umum (general skills) - kecakapan dasar", "100", "", "", ""],
          ["4", "Keterampilan Khusus (specific skills) - keahlian bidang", "100", "", "", ""],
          ["5", "Penguasaan IPTEK untuk bidang keilmuan tertentu", "100", "", "", ""],
          ["6", "Kecakapan umum untuk penguasaan IPTEK", "100", "", "", ""],
          ["7", "Pengetahuan untuk dunia kerja/lanjut studi", "100", "", "", ""],
          ["8", "Kemampuan intelektual berpikir mandiri dan kritis", "100", "", "", ""],
        ],
      },
      tabelAspekSkor("C. Tingkat Kepuasan Pengguna Lulusan (Skor 1-5)", [
        "Kemampuan teknis lulusan sesuai bidang kerja",
        "Kemampuan analitis dan pemecahan masalah",
        "Kemampuan komunikasi lisan dan tulisan",
        "Kemampuan kerjasama dalam tim",
        "Kemampuan kepemimpinan",
        "Kemampuan adaptasi terhadap perubahan",
        "Kemampuan kewirausahaan",
        "Kemampuan penguasaan teknologi informasi",
        "Etika dan profesionalisme kerja",
        "Kemampuan bahasa Inggris",
        "Kemampuan berpikir kritis dan kreatif",
        "Kemampuan belajar sepanjang hayat (lifelong learning)",
        "Kesesuaian kurikulum dengan kebutuhan DUDI",
        "Kesesuaian kompetensi lulusan dengan tuntutan jabatan",
        "Kesiapan kerja lulusan (waktu tunggu kerja pertama)",
      ]),
      {
        title: "D. Rekomendasi Perbaikan CPL",
        headers: ["No", "Rekomendasi", "Penanggung Jawab", "Target Waktu"],
        widths: [5, 55, 25, 15],
        emptyRows: 5,
      },
    ],
    tandaTangan: ttdKaProdi(),
  },
  {
    nomor: 3,
    namaFormulir: "FORMULIR MONITORING EVALUASI PENILAIAN",
    kodeFormulir: "FM-PBM-03",
    kategori: "FORM",
    matchStandar: "Standar Penilaian (SPN) - Pasal 25 Permen 39/2025",
    deskripsi: [
      "Formulir ini digunakan untuk monitoring dan evaluasi sistem penilaian di setiap program studi, mencakup rubrik, transparansi, dan ketepatan waktu. Mengacu pada Standar Penilaian (SPN) Permen 39 Tahun 2025.",
    ],
    instruksi: "Isi formulir dengan data audit penilaian minimal 5 mata kuliah sample.",
    fieldTables: [
      {
        title: "A. Identitas",
        headers: ["Komponen", "Isian"],
        widths: [30, 70],
        rows: [
          ["Program Studi", ""],
          ["Semester / Tahun Akademik", ""],
          ["Jumlah Mata Kuliah Diaudit", ""],
          ["Tanggal Audit", ""],
          ["Auditor (GKM)", ""],
        ],
      },
      tabelAspekSkor("B. Audit Penilaian per Mata Kuliah Sample", [
        "Rubrik penilaian tersedia dan jelas",
        "Rubrik disampaikan kepada mahasiswa di awal semester",
        "Penilaian formatif dilakukan secara berkala",
        "Penilaian sumatif dilakukan sesuai jadwal",
        "Bobot penilaian sesuai proporsi formatif-sumatif (minimal 40% formatif)",
        "Penilaian autentik diterapkan (proyek, portofolio, presentasi)",
        "Transparansi nilai melalui SIAKAD",
        "Ketepatan waktu penginputan nilai (<5 hari kerja setelah UAS)",
        "Objektivitas penilaian antar-dosen",
        "Konsistensi penilaian dengan CPMK",
        "Mekanisme banding/koreksi nilai tersedia",
        "Analisis butir soal UTS/UAS dilakukan",
        "Dokumentasi nilai tersimpan minimal 5 tahun",
        "Feedback atas tugas/ujian diberikan kepada mahasiswa",
        "Penilaian mengukur ketercapaian CPL",
      ]),
      {
        title: "C. Rekomendasi Perbaikan Penilaian",
        headers: ["No", "Rekomendasi", "Penanggung Jawab", "Target Waktu"],
        widths: [5, 55, 25, 15],
        emptyRows: 5,
      },
    ],
    tandaTangan: ttdKaProdi(),
  },
  {
    nomor: 4,
    namaFormulir: "FORMULIR MONITORING EVALUASI PENGELOLAAN PROGRAM STUDI",
    kodeFormulir: "FM-PBM-04",
    kategori: "FORM",
    matchStandar: "Standar Pengelolaan (SPP) - Pasal 26-30 Permen 39/2025",
    deskripsi: [
      "Formulir ini digunakan untuk monitoring dan evaluasi pengelolaan program studi oleh UPPS. Mengacu pada Standar Pengelolaan (SPP) Permen 39 Tahun 2025.",
    ],
    instruksi: "Isi formulir dengan data pengelolaan program studi semester berjalan.",
    fieldTables: [
      {
        title: "A. Identitas",
        headers: ["Komponen", "Isian"],
        widths: [30, 70],
        rows: [
          ["Program Studi", ""],
          ["Ka. Prodi (UPPS)", ""],
          ["Tanggal Monitoring", ""],
          ["Pemonitor (LPM)", ""],
        ],
      },
      tabelAspekSkor("B. Indikator Kinerja Pengelolaan", [
        "Ketersediaan SOTK yang terdokumentasi dan disosialisasikan",
        "Ketersediaan rencana operasional tahunan",
        "Ketersediaan SOP untuk aktivitas strategis",
        "Pelaksanaan rencana operasional sesuai jadwal",
        "Monitoring dan evaluasi berkala oleh UPPS",
        "Ketersediaan laporan kinerja tahunan",
        "Ketersediaan dashboard kinerja digital",
        "Rapat koordinasi UPPS-GKM-LPM-PPM rutin",
        "Evaluasi diri tahunan oleh UPPS",
        "Benchmarking dengan prodi sejenis",
        "Kerjasama DUDI untuk MBKM/magang",
        "Integrasi data prodi dengan PD Dikti",
        "Tingkat kepuasan mahasiswa terhadap layanan prodi",
        "Tingkat kepuasan dosen terhadap pengelolaan prodi",
        "Persentase rekomendasi evaluasi yang ditindaklanjuti",
      ]),
      {
        title: "C. Rekomendasi",
        headers: ["No", "Rekomendasi", "Penanggung Jawab", "Target Waktu"],
        widths: [5, 55, 25, 15],
        emptyRows: 5,
      },
    ],
    tandaTangan: ttdKaProdi(),
  },
  {
    nomor: 5,
    namaFormulir: "FORMULIR MONITORING EVALUASI ISI / KURIKULUM",
    kodeFormulir: "FM-PBM-05",
    kategori: "FORM",
    matchStandar: "Standar Isi (SIS) - Pasal 31-39 Permen 39/2025",
    deskripsi: [
      "Formulir ini digunakan untuk monitoring dan evaluasi kurikulum, mencakup review kurikulum 2 tahunan, MBKM, dan konstruktif alignment. Mengacu pada Standar Isi (SIS) Permen 39 Tahun 2025.",
    ],
    instruksi: "Isi formulir dengan data review kurikulum dan implementasi MBKM.",
    fieldTables: [
      {
        title: "A. Identitas",
        headers: ["Komponen", "Isian"],
        widths: [30, 70],
        rows: [
          ["Program Studi", ""],
          ["Tanggal Review", ""],
          ["Tim Reviewer", ""],
        ],
      },
      tabelAspekSkor("B. Review Kurikulum", [
        "Kurikulum disusun berdasarkan CPL",
        "Struktur kurikulum sesuai jenjang (D3/S1/S2/S3)",
        "Proporsi MK wajib universitas/fakultas/prodi seimbang",
        "MK pilihan tersedia untuk pendalaman bidang",
        "MK MBKM tersedia dengan pengakuan SKS",
        "Konstruktif alignment CPL-CPMK-materi-metode-penilaian",
        "Beban SKS sesuai dengan waktu belajar (1 SKS = 170 menit/minggu)",
        "Integrasi soft skills (komunikasi, kerjasama, kepemimpinan)",
        "Integrasi digital literacy sebagai kompetensi abad 21",
        "Mata kuliah dengan course outline (deskripsi) lengkap",
        "Review kurikulum dilakukan minimal 2 tahunan",
        "Keterlibatan DUDI dalam review kurikulum",
        "Keterlibatan asosiasi prodi dalam review kurikulum",
        "Kurikulum dipublikasikan di SIAKAD dan situs web prodi",
        "Tingkat kepuasan mahasiswa terhadap kurikulum",
      ]),
      {
        title: "C. Implementasi MBKM",
        headers: ["No", "Skema MBKM", "Jumlah Mahasiswa", "Mitra DUDI", "Capaian"],
        widths: [5, 25, 18, 25, 27],
        rows: [
          ["1", "Magang Industri", "", "", ""],
          ["2", "Studi Independen", "", "", ""],
          ["3", "Pertukaran Pelajar", "", "", ""],
          ["4", "Asistensi Mengajar", "", "", ""],
          ["5", "Proyek Kemanusiaan", "", "", ""],
          ["6", "Kegiatan Wirausaha", "", "", ""],
        ],
      },
      {
        title: "D. Rekomendasi Perbaikan Kurikulum",
        headers: ["No", "Rekomendasi", "Penanggung Jawab", "Target Waktu"],
        widths: [5, 55, 25, 15],
        emptyRows: 5,
      },
    ],
    tandaTangan: ttdKaProdi(),
  },
  {
    nomor: 6,
    namaFormulir: "FORMULIR MONITORING EVALUASI DOSEN DAN TENAGA KEPENDIDIKAN",
    kodeFormulir: "FM-PBM-06",
    kategori: "FORM",
    matchStandar: "Standar Dosen dan Tenaga Kependidikan (SDT) - Pasal 40-45 Permen 39/2025",
    deskripsi: [
      "Formulir ini digunakan untuk monitoring dan evaluasi dosen dan tenaga kependidikan. Mengacu pada Standar Dosen dan Tenaga Kependidikan (SDT) Permen 39 Tahun 2025.",
    ],
    instruksi: "Isi formulir dengan data SDM per program studi/unit kerja.",
    fieldTables: [
      {
        title: "A. Identitas",
        headers: ["Komponen", "Isian"],
        widths: [30, 70],
        rows: [
          ["Program Studi / Unit", ""],
          ["Tanggal Monitoring", ""],
          ["Pemonitor (BAKU/PPM)", ""],
        ],
      },
      tabelAspekSkor("B. Indikator Dosen", [
        "Kualifikasi dosen minimal S2 untuk S1, S3 untuk S2/S3",
        "Persentase dosen dengan sertifikat pendidik (Serdos)",
        "Rasio dosen-mahasiswa sesuai standar (S1 maks 1:45)",
        "Beban kerja dosen 12-16 SKS per semester",
        "Keseimbangan beban pendidikan-penelitian-PkM",
        "Jabatan akademik (Asisten Ahli - Guru Besar)",
        "Kompetensi pedagogik dosen",
        "Kompetensi profesional dosen",
        "Kompetensi kepribadian dosen",
        "Kompetensi sosial dosen",
        "Pengembangan karir dosen (promosi jabatan akademik)",
        "Studi lanjut bagi dosen S1/S2",
        "Pelatihan Serdos bagi dosen",
        "Reward dan apresiasi dosen berprestasi",
        "Sistem penilaian kinerja (SKP) dosen",
      ]),
      tabelAspekSkor("C. Indikator Tenaga Kependidikan", [
        "Kualifikasi tendik minimal D3",
        "Kompetensi tendik sesuai bidang tugas",
        "Pelatihan teknis tendik berkala",
        "Pelatihan manajemen tendik",
        "Sertifikasi profesi tendik",
        "Beban kerja tendik sesuai tugas",
        "Reward dan apresiasi tendik berprestasi",
        "Sistem penilaian kinerja (SKP) tendik",
        "Pengembangan karir tendik",
        "Tingkat retensi tendik",
      ]),
      {
        title: "D. Rasio dan Beban Kerja",
        headers: ["Indikator", "Target", "Capaian", "Selisih"],
        widths: [40, 20, 20, 20],
        rows: [
          ["Rasio Dosen-Mahasiswa (S1)", "1:35", "", ""],
          ["Beban Kerja Rata-rata Dosen (SKS)", "12-16", "", ""],
          ["Persentase Dosen dengan Serdos", "≥50%", "", ""],
          ["Persentase Dosen S3", "≥30%", "", ""],
          ["Jumlah Dosen Lektor Kepala", "≥15", "", ""],
          ["Jumlah Dosen Guru Besar", "≥3", "", ""],
        ],
      },
    ],
    tandaTangan: ttdKaUnit(),
  },
  {
    nomor: 7,
    namaFormulir: "FORMULIR MONITORING EVALUASI SARANA DAN PRASARANA",
    kodeFormulir: "FM-PBM-07",
    kategori: "FORM",
    matchStandar: "Standar Sarana dan Prasarana (SSP) - Pasal 46-47 Permen 39/2025",
    deskripsi: [
      "Formulir ini digunakan untuk monitoring dan evaluasi sarana dan prasarana. Mengacu pada Standar Sarana dan Prasarana (SSP) Permen 39 Tahun 2025.",
    ],
    instruksi: "Isi formulir dengan data audit fasilitas minimal 1 kali per tahun.",
    fieldTables: [
      {
        title: "A. Identitas",
        headers: ["Komponen", "Isian"],
        widths: [30, 70],
        rows: [
          ["Unit", ""],
          ["Tanggal Audit", ""],
          ["Auditor (BAU)", ""],
        ],
      },
      tabelAspekSkor("B. Audit Fasilitas Pendidikan", [
        "Ruang perkuliahan dengan kapasitas sesuai",
        "Rasio ruang kelas (m² per mahasiswa) ≥1.5",
        "Kondisi ruang kelas (AC, proyektor, sound system)",
        "Laboratorium sesuai karakteristik keilmuan",
        "Peralatan laboratorium memenuhi standar",
        "Perpustakaan dengan koleksi cetak memadai",
        "Perpustakaan digital dengan akses e-journal/e-book",
        "Fasilitas ibadah (musola/masjid)",
        "Fasilitas olahraga",
        "Fasilitas kafetaria/kantin",
        "Fasilitas parkir",
        "Fasilitas keamanan 24 jam",
        "Akses WiFi campus-wide",
        "Smart classroom dengan teknologi IT",
        "Fasilitas dengan akses disabilitas (universal design)",
        "Sistem manajemen fasilitas berbasis IT",
        "Maintenance fasilitas secara berkala",
        "Ruang dosen (work space) yang memadai",
        "Ruang mahasiswa (student lounge/study area)",
        "Kondisi kebersihan ruangan",
      ]),
      {
        title: "C. Indikator Kinerja Sarana",
        headers: ["Indikator", "Target", "Capaian", "Selisih"],
        widths: [40, 20, 20, 20],
        rows: [
          ["Rasio ruang kelas (m²/mahasiswa)", "≥1.5", "", ""],
          ["Persentase lab dengan peralatan standar", "≥80%", "", ""],
          ["Jumlah koleksi perpustakaan", "≥15.000", "", ""],
          ["Persentase gedung dengan akses disabilitas", "≥55%", "", ""],
          ["Persentase fasilitas terpelihara", "≥85%", "", ""],
          ["Jumlah smart classroom", "≥15", "", ""],
          ["Persentase area kampus dengan WiFi", "≥75%", "", ""],
        ],
      },
      {
        title: "D. Rekomendasi",
        headers: ["No", "Rekomendasi", "Penanggung Jawab", "Target Waktu"],
        widths: [5, 55, 25, 15],
        emptyRows: 5,
      },
    ],
    tandaTangan: ttdKaUnit(),
  },
  {
    nomor: 8,
    namaFormulir: "FORMULIR MONITORING EVALUASI PEMBIAYAAN",
    kodeFormulir: "FM-PBM-08",
    kategori: "FORM",
    matchStandar: "Standar Pembiayaan (SPM) - Pasal 48-51 Permen 39/2025",
    deskripsi: [
      "Formulir ini digunakan untuk monitoring dan evaluasi pembiayaan. Mengacu pada Standar Pembiayaan (SPM) Permen 39 Tahun 2025.",
    ],
    instruksi: "Isi formulir dengan data anggaran dan realisasi tahun berjalan.",
    fieldTables: [
      {
        title: "A. Identitas",
        headers: ["Komponen", "Isian"],
        widths: [30, 70],
        rows: [
          ["Tahun Anggaran", ""],
          ["Tanggal Monitoring", ""],
          ["Pemonitor (BAKU/SPI)", ""],
        ],
      },
      tabelAspekSkor("B. Indikator Pembiayaan", [
        "BOP per mahasiswa per tahun ≥standar minimal",
        "Alokasi anggaran penelitian ≥10% dari anggaran tahunan",
        "Alokasi anggaran PkM ≥5% dari anggaran tahunan",
        "Pendanaan dari sumber berkelanjutan (SPP, hibah, kerjasama, RGU)",
        "Sistem akuntansi sesuai standar (PSAK/SAK ETAP)",
        "Audit keuangan internal oleh SPI",
        "Audit keuangan eksternal oleh KAP",
        "Opini audit (WTP/WDP/Disclaimer)",
        "Publikasi laporan keuangan kepada pemangku kepentingan",
        "Anggaran berbasis kinerja",
        "Sistem informasi manajemen keuangan terintegrasi",
        "Beasiswa bagi mahasiswa kurang mampu (≥5% pendapatan SPP)",
        "Rasio biaya operasional terhadap pendapatan sehat",
        "Pengembangan RGU (Revenue Generating Unit)",
        "Kerjasama DUDI untuk pendanaan",
      ]),
      {
        title: "C. Capaian Indikator Pembiayaan",
        headers: ["No", "Indikator", "Target", "Capaian", "Selisih", "Catatan"],
        widths: [5, 35, 12, 12, 10, 26],
        rows: [
          ["1", "BOP per mahasiswa (Rp juta)", "≥9.5", "", "", ""],
          ["2", "Persentase pendapatan RGU", "≥9%", "", "", ""],
          ["3", "Persentase anggaran penelitian", "≥12%", "", "", ""],
          ["4", "Persentase anggaran PkM", "≥6%", "", "", ""],
          ["5", "Opini audit eksternal", "WTP", "", "", ""],
          ["6", "Persentase beasiswa dari SPP", "≥5%", "", "", ""],
          ["7", "Rasio biaya operasional/pendapatan", "≤82%", "", "", ""],
        ],
      },
      {
        title: "D. Rekomendasi",
        headers: ["No", "Rekomendasi", "Penanggung Jawab", "Target Waktu"],
        widths: [5, 55, 25, 15],
        emptyRows: 5,
      },
    ],
    tandaTangan: ttdKaUnit(),
  },

  // === BAB IV: FORMULIR PENELITIAN DAN PkM ===
  {
    nomor: 9,
    namaFormulir: "FORMULIR PROPOSAL PENELITIAN",
    kodeFormulir: "FM-PEN-01",
    kategori: "FORM",
    matchStandar: "Standar Proses Penelitian (PEN-PRS) - Pasal 54-55 Permen 39/2025",
    deskripsi: [
      "Formulir ini digunakan untuk pengajuan proposal penelitian internal/eksternal di Universitas Tulungagung.",
    ],
    instruksi: "Isi formulir dengan lengkap dan lampirkan proposal ilmiah. Ajukan ke LPPM minimal 2 bulan sebelum pelaksanaan.",
    fieldTables: [
      {
        title: "A. Identitas Penelitian",
        headers: ["Komponen", "Isian"],
        widths: [30, 70],
        rows: [
          ["Judul Penelitian", ""],
          ["Jenis Penelitian", "(Skripsi/Tesis/Riset Dosen/Hibah Eksternal)"],
          ["Bidang Ilmu", ""],
          ["Lama Penelitian (bulan)", ""],
          ["Total Anggaran (Rp)", ""],
        ],
      },
      {
        title: "B. Identitas Peneliti",
        headers: ["Komponen", "Ketua", "Anggota 1", "Anggota 2"],
        widths: [25, 25, 25, 25],
        rows: [
          ["Nama Lengkap", "", "", ""],
          ["NIDN/NIP", "", "", ""],
          ["Jabatan Akademik", "", "", ""],
          ["Program Studi", "", "", ""],
          ["No. HP/Email", "", "", ""],
          ["Serdos", "", "", ""],
        ],
      },
      {
        title: "C. Ringkasan Proposal",
        headers: ["Komponen", "Isian"],
        widths: [30, 70],
        rows: [
          ["Latar Belakang (maks 200 kata)", ""],
          ["Rumusan Masalah", ""],
          ["Tujuan Penelitian", ""],
          ["Metode Penelitian", ""],
          ["Luaran yang Diharapkan", ""],
        ],
      },
      {
        title: "D. Timeline dan Anggaran",
        headers: ["No", "Kegiatan", "Bulan 1-2", "Bulan 3-4", "Bulan 5-6", "Anggaran (Rp)"],
        widths: [5, 30, 15, 15, 15, 20],
        rows: [
          ["1", "Penyusunan instrumen", "", "", "", ""],
          ["2", "Pengumpulan data", "", "", "", ""],
          ["3", "Analisis data", "", "", "", ""],
          ["4", "Penyusunan laporan", "", "", "", ""],
          ["5", "Publikasi/diseminasi", "", "", "", ""],
        ],
      },
      {
        title: "E. Persetujuan Etik (jika melibatkan manusia/hewan)",
        headers: ["Komponen", "Isian"],
        widths: [30, 70],
        rows: [
          ["Persetujuan Etik", "(Ada/Tidak)"],
          ["No. Persetujuan Etik", ""],
          ["Tanggal Persetujuan", ""],
        ],
      },
    ],
    tandaTangan: ttdKaLPPM(),
  },
  {
    nomor: 10,
    namaFormulir: "FORMULIR MONITORING PELAKSANAAN PENELITIAN",
    kodeFormulir: "FM-PEN-02",
    kategori: "FORM",
    matchStandar: "Standar Proses Penelitian (PEN-PRS) - Pasal 54-55 Permen 39/2025",
    deskripsi: [
      "Formulir ini digunakan untuk monitoring pelaksanaan penelitian oleh LPPM.",
    ],
    instruksi: "Isi formulir saat monitoring lapangan oleh LPPM.",
    fieldTables: [
      {
        title: "A. Identitas",
        headers: ["Komponen", "Isian"],
        widths: [30, 70],
        rows: [
          ["Judul Penelitian", ""],
          ["Ketua Peneliti", ""],
          ["Tanggal Monitoring", ""],
          ["Pemonitor (LPPM)", ""],
        ],
      },
      tabelAspekSkor("B. Hasil Monitoring", [
        "Kesesuaian pelaksanaan dengan proposal",
        "Kesesuaian timeline dengan jadwal",
        "Kesesuaian anggaran dengan RAB",
        "Kesesuaian metode dengan proposal",
        "Ketersediaan sarana penelitian",
        "Kualitas data yang dikumpulkan",
        "Pemenuhan etika penelitian",
        "Pemenuhan informed consent (jika ada subjek manusia)",
        "Kesesuaian luaran antara dengan target",
        "Dokumentasi kegiatan penelitian",
        "Kerjasama tim peneliti",
        "Komunikasi dengan LPPM",
        "Pelaporan kemajuan (progress report)",
        "Tindak lanjut rekomendasi monitoring sebelumnya",
        "Potensi luaran akhir (publikasi/paten/HKI)",
      ]),
      {
        title: "C. Rekomendasi",
        headers: ["No", "Rekomendasi", "Penanggung Jawab", "Target Waktu"],
        widths: [5, 55, 25, 15],
        emptyRows: 5,
      },
    ],
    tandaTangan: ttdKaLPPM(),
  },
  {
    nomor: 11,
    namaFormulir: "FORMULIR LAPORAN AKHIR PENELITIAN",
    kodeFormulir: "FM-PEN-03",
    kategori: "FORM",
    matchStandar: "Standar Hasil Penelitian (PEN-HSL) - Pasal 52-53 Permen 39/2025",
    deskripsi: [
      "Formulir ini digunakan untuk laporan akhir penelitian, mencakup hasil, luaran, dan keuangan.",
    ],
    instruksi: "Isi formulir maksimal 30 hari setelah penelitian selesai. Lampirkan laporan ilmiah lengkap.",
    fieldTables: [
      {
        title: "A. Identitas",
        headers: ["Komponen", "Isian"],
        widths: [30, 70],
        rows: [
          ["Judul Penelitian", ""],
          ["Ketua Peneliti", ""],
          ["No. Kontrak", ""],
          ["Periode Penelitian", ""],
          ["Tanggal Laporan", ""],
        ],
      },
      {
        title: "B. Luaran Penelitian",
        headers: ["No", "Jenis Luaran", "Judul/Deskripsi", "Status", "Evidence"],
        widths: [5, 20, 35, 15, 25],
        rows: [
          ["1", "Publikasi jurnal SINTA", "", "", ""],
          ["2", "Publikasi Scopus/WoS", "", "", ""],
          ["3", "Prosiding seminar", "", "", ""],
          ["4", "Paten/HKI", "", "", ""],
          ["5", "Buku/textbook", "", "", ""],
          ["6", "Teknologi Tepat Guna", "", "", ""],
          ["7", "Produk komersial", "", "", ""],
        ],
      },
      {
        title: "C. Realisasi Anggaran",
        headers: ["No", "Komponen Biaya", "Anggaran (Rp)", "Realisasi (Rp)", "Selisih"],
        widths: [5, 35, 20, 20, 20],
        rows: [
          ["1", "Bahan dan alat", "", "", ""],
          ["2", "Perjalanan dan transportasi", "", "", ""],
          ["3", "Honor peneliti", "", "", ""],
          ["4", "Honor responden", "", "", ""],
          ["5", "Publikasi/page charges", "", "", ""],
          ["6", "Lain-lain", "", "", ""],
          ["", "TOTAL", "", "", ""],
        ],
      },
      {
        title: "D. Ringkasan Hasil",
        headers: ["Komponen", "Isian"],
        widths: [30, 70],
        rows: [
          ["Hasil utama penelitian", ""],
          ["Kontribusi terhadap IPTEK", ""],
          ["Dampak bagi masyarakat", ""],
          ["Rekomendasi tindak lanjut", ""],
        ],
      },
    ],
    tandaTangan: ttdKaLPPM(),
  },
  {
    nomor: 12,
    namaFormulir: "FORMULIR PENDAFTARAN HKI / PATEN",
    kodeFormulir: "FM-PEN-04",
    kategori: "FORM",
    matchStandar: "Standar Paten dan HKI Penelitian (PEN-PTN)",
    deskripsi: [
      "Formulir ini digunakan untuk pendaftaran paten dan HKI atas hasil penelitian.",
    ],
    instruksi: "Isi formulir dan lampirkan dokumen pendukung (deskripsi, klaim, abstrak, gambar).",
    fieldTables: [
      {
        title: "A. Identitas Pemohon",
        headers: ["Komponen", "Isian"],
        widths: [30, 70],
        rows: [
          ["Nama Pemohon (Peneliti)", ""],
          ["NIDN/NIP", ""],
          ["Program Studi", ""],
          ["No. HP/Email", ""],
        ],
      },
      {
        title: "B. Identitas Invensi",
        headers: ["Komponen", "Isian"],
        widths: [30, 70],
        rows: [
          ["Judul Invensi", ""],
          ["Jenis HKI", "(Paten/Paten Sederhana/Hak Cipta/Desain Industri/Merek)"],
          ["Bidang Teknologi", ""],
          ["Tanggal Penemuan", ""],
          ["Sumber Dana Penelitian", ""],
        ],
      },
      {
        title: "C. Uraian Invensi",
        headers: ["Komponen", "Isian"],
        widths: [30, 70],
        rows: [
          ["Latar belakang", ""],
          ["Masalah yang dipecahkan", ""],
          ["Solusi yang ditawarkan", ""],
          ["Keunggulan dibanding yang ada", ""],
          ["Potensi komersialisasi", ""],
        ],
      },
      {
        title: "D. Lampiran",
        headers: ["No", "Dokumen", "Status"],
        widths: [5, 70, 25],
        rows: [
          ["1", "Surat Pernyataan Pemilikan HKI", "(Ada/Belum)"],
          ["2", "Dokumen Deskripsi Invensi", "(Ada/Belum)"],
          ["3", "Dokumen Klaim", "(Ada/Belum)"],
          ["4", "Abstrak", "(Ada/Belum)"],
          ["5", "Gambar Teknis", "(Ada/Belum)"],
        ],
      },
    ],
    tandaTangan: ttdKaLPPM(),
  },
  {
    nomor: 13,
    namaFormulir: "FORMULIR PENDAFTARAN PUBLIKASI JURNAL",
    kodeFormulir: "FM-PEN-05",
    kategori: "FORM",
    matchStandar: "Standar Publikasi Ilmiah Penelitian (PEN-PUB)",
    deskripsi: [
      "Formulir ini digunakan untuk pendaftaran klaim insentif dan page charges publikasi jurnal.",
    ],
    instruksi: "Isi formulir dan lampirkan bukti publikasi (article, letter of acceptance, bukti bayar).",
    fieldTables: [
      {
        title: "A. Identitas Penulis",
        headers: ["Komponen", "Isian"],
        widths: [30, 70],
        rows: [
          ["Nama Penulis (Ketua)", ""],
          ["NIDN/NIP", ""],
          ["Program Studi", ""],
          ["Email", ""],
        ],
      },
      {
        title: "B. Identitas Publikasi",
        headers: ["Komponen", "Isian"],
        widths: [30, 70],
        rows: [
          ["Judul Artikel", ""],
          ["Nama Jurnal", ""],
          ["Penerbit", ""],
          ["Akreditasi (SINTA/Scopus/WoS)", ""],
          ["Volume/Issue/Tahun", ""],
          ["DOI", ""],
          ["URL Artikel", ""],
        ],
      },
      {
        title: "C. Klaim Insentif",
        headers: ["No", "Jenis Klaim", "Jumlah (Rp)", "Bukti"],
        widths: [5, 50, 20, 25],
        rows: [
          ["1", "Insentif publikasi SINTA 1-3", "", ""],
          ["2", "Insentif publikasi Scopus Q1-Q2", "", ""],
          ["3", "Insentif publikasi Scopus Q3-Q4", "", ""],
          ["4", "Page charges", "", ""],
          ["5", "Translation/editing", "", ""],
        ],
      },
      {
        title: "D. Daftar Penulis",
        headers: ["No", "Nama Penulis", "Affiliation", "Peran", "NIDN"],
        widths: [5, 30, 25, 20, 20],
        rows: [
          ["1", "", "", "Penulis Utama", ""],
          ["2", "", "", "Penulis Pendamping", ""],
          ["3", "", "", "Penulis Pendamping", ""],
          ["4", "", "", "Penulis Pendamping", ""],
          ["5", "", "", "Penulis Pendamping", ""],
        ],
      },
    ],
    tandaTangan: ttdKaLPPM(),
  },
  {
    nomor: 14,
    namaFormulir: "FORMULIR PROPOSAL PENGABDIAN KEPADA MASYARAKAT",
    kodeFormulir: "FM-PKM-01",
    kategori: "FORM",
    matchStandar: "Standar Proses PkM (PKM-PRS) - Pasal 59-61 Permen 39/2025",
    deskripsi: [
      "Formulir ini digunakan untuk pengajuan proposal PkM internal/eksternal.",
    ],
    instruksi: "Isi formulir dengan lengkap dan lampirkan proposal ilmiah. Ajukan ke LPPM minimal 2 bulan sebelum pelaksanaan.",
    fieldTables: [
      {
        title: "A. Identitas PkM",
        headers: ["Komponen", "Isian"],
        widths: [30, 70],
        rows: [
          ["Judul PkM", ""],
          ["Jenis PkM", "(Skripsi/Tesis/PkM Dosen/Hibah Eksternal)"],
          ["Bidang PkM", ""],
          ["Lama PkM (bulan)", ""],
          ["Total Anggaran (Rp)", ""],
        ],
      },
      {
        title: "B. Identitas Mitra PkM",
        headers: ["Komponen", "Isian"],
        widths: [30, 70],
        rows: [
          ["Nama Mitra/Kelompok Masyarakat", ""],
          ["Lokasi PkM", ""],
          ["Jumlah Penerima Manfaat", ""],
          ["Kontak Mitra", ""],
        ],
      },
      {
        title: "C. Identitas Pelaksana",
        headers: ["Komponen", "Ketua", "Anggota 1", "Anggota 2"],
        widths: [25, 25, 25, 25],
        rows: [
          ["Nama Lengkap", "", "", ""],
          ["NIDN/NIP", "", "", ""],
          ["Program Studi", "", "", ""],
          ["No. HP/Email", "", "", ""],
        ],
      },
      {
        title: "D. Ringkasan Proposal",
        headers: ["Komponen", "Isian"],
        widths: [30, 70],
        rows: [
          ["Latar Belakang", ""],
          ["Masalah Masyarakat", ""],
          ["Tujuan PkM", ""],
          ["Metode PkM", ""],
          ["Luaran yang Diharapkan", ""],
          ["Dampak yang Diharapkan", ""],
        ],
      },
      {
        title: "E. Persetujuan Mitra (Informed Consent)",
        headers: ["Komponen", "Isian"],
        widths: [30, 70],
        rows: [
          ["Persetujuan Mitra", "(Ada/Tidak)"],
          ["Tanggal Persetujuan", ""],
          ["Tanda Tangan Mitra", ""],
        ],
      },
    ],
    tandaTangan: ttdKaLPPM(),
  },
  {
    nomor: 15,
    namaFormulir: "FORMULIR MONITORING PELAKSANAAN PkM",
    kodeFormulir: "FM-PKM-02",
    kategori: "FORM",
    matchStandar: "Standar Proses PkM (PKM-PRS) - Pasal 59-61 Permen 39/2025",
    deskripsi: [
      "Formulir ini digunakan untuk monitoring pelaksanaan PkM oleh LPPM.",
    ],
    instruksi: "Isi formulir saat monitoring lapangan oleh LPPM.",
    fieldTables: [
      {
        title: "A. Identitas",
        headers: ["Komponen", "Isian"],
        widths: [30, 70],
        rows: [
          ["Judul PkM", ""],
          ["Ketua Pelaksana", ""],
          ["Tanggal Monitoring", ""],
          ["Pemonitor (LPPM)", ""],
        ],
      },
      tabelAspekSkor("B. Hasil Monitoring", [
        "Kesesuaian pelaksanaan dengan proposal",
        "Kesesuaian timeline dengan jadwal",
        "Kesesuaian anggaran dengan RAB",
        "Kesesuaian metode dengan proposal",
        "Partisipasi aktif mitra dalam pelaksanaan",
        "Pemenuhan etika PkM",
        "Pemenuhan informed consent mitra",
        "Kualitas luaran antara",
        "Dokumentasi kegiatan PkM",
        "Kerjasama tim pelaksana",
        "Komunikasi dengan LPPM",
        "Pelaporan kemajuan (progress report)",
        "Tindak lanjut rekomendasi monitoring sebelumnya",
        "Potensi dampak bagi masyarakat",
        "Potensi replikasi di lokasi lain",
      ]),
      {
        title: "C. Rekomendasi",
        headers: ["No", "Rekomendasi", "Penanggung Jawab", "Target Waktu"],
        widths: [5, 55, 25, 15],
        emptyRows: 5,
      },
    ],
    tandaTangan: ttdKaLPPM(),
  },
  {
    nomor: 16,
    namaFormulir: "FORMULIR LAPORAN AKHIR PENGABDIAN KEPADA MASYARAKAT",
    kodeFormulir: "FM-PKM-03",
    kategori: "FORM",
    matchStandar: "Standar Hasil PkM (PKM-HSL) - Pasal 57-58 Permen 39/2025",
    deskripsi: [
      "Formulir ini digunakan untuk laporan akhir PkM, mencakup hasil, luaran, dan keuangan.",
    ],
    instruksi: "Isi formulir maksimal 30 hari setelah PkM selesai.",
    fieldTables: [
      {
        title: "A. Identitas",
        headers: ["Komponen", "Isian"],
        widths: [30, 70],
        rows: [
          ["Judul PkM", ""],
          ["Ketua Pelaksana", ""],
          ["No. Kontrak", ""],
          ["Periode PkM", ""],
          ["Tanggal Laporan", ""],
        ],
      },
      {
        title: "B. Luaran PkM",
        headers: ["No", "Jenis Luaran", "Deskripsi", "Status", "Penerima Manfaat"],
        widths: [5, 20, 30, 15, 30],
        rows: [
          ["1", "Produk PkM", "", "", ""],
          ["2", "Jasa PkM", "", "", ""],
          ["3", "Metode PkM", "", "", ""],
          ["4", "Publikasi PkM", "", "", ""],
          ["5", "Best practice", "", "", ""],
        ],
      },
      tabelAspekSkor("C. Dampak PkM (Skor 1-5)", [
        "Peningkatan kapasitas masyarakat (pelatihan, pendampingan)",
        "Produk/jasa yang dimanfaatkan masyarakat",
        "Kebijakan publik yang dipengaruhi",
        "Pemberdayaan ekonomi masyarakat",
        "Peningkatan kualitas hidup masyarakat",
        "Kontinuitas PkM (berkelanjutan >2 tahun)",
        "Replikasi di lokasi/masyarakat lain",
        "Adopsi produk/jasa oleh masyarakat",
        "Tingkat kepuasan mitra",
        "Potensi komersialisasi produk PkM",
      ]),
      {
        title: "D. Realisasi Anggaran",
        headers: ["No", "Komponen Biaya", "Anggaran (Rp)", "Realisasi (Rp)", "Selisih"],
        widths: [5, 35, 20, 20, 20],
        rows: [
          ["1", "Bahan dan alat", "", "", ""],
          ["2", "Perjalanan dan transportasi", "", "", ""],
          ["3", "Honor pelaksana", "", "", ""],
          ["4", "Konsumsi", "", "", ""],
          ["5", "Publikasi", "", "", ""],
          ["6", "Lain-lain", "", "", ""],
          ["", "TOTAL", "", "", ""],
        ],
      },
    ],
    tandaTangan: ttdKaLPPM(),
  },
  {
    nomor: 17,
    namaFormulir: "FORMULIR PENDAFTARAN PRODUK PkM",
    kodeFormulir: "FM-PKM-04",
    kategori: "FORM",
    matchStandar: "Standar Produk dan Jasa PkM (PKM-PRD)",
    deskripsi: [
      "Formulir ini digunakan untuk pendaftaran produk PkM untuk dokumentasi dan potensi komersialisasi.",
    ],
    instruksi: "Isi formulir dan lampirkan dokumentasi produk.",
    fieldTables: [
      {
        title: "A. Identitas Produk",
        headers: ["Komponen", "Isian"],
        widths: [30, 70],
        rows: [
          ["Nama Produk", ""],
          ["Jenis Produk", "(Fisik/Digital/Intelektual)"],
          ["Asal Produk", "(Hasil Penelitian/PkM/Kolaborasi DUDI)"],
          ["Tanggal Pengembangan", ""],
          ["Penanggung Jawab", ""],
        ],
      },
      {
        title: "B. Deskripsi Produk",
        headers: ["Komponen", "Isian"],
        widths: [30, 70],
        rows: [
          ["Fungsi produk", ""],
          ["Keunggulan produk", ""],
          ["Pengguna/penerima manfaat", ""],
          ["Potensi komersialisasi", ""],
          ["Status HKI", "(Sudah/Belum)"],
        ],
      },
      {
        title: "C. Dokumentasi",
        headers: ["No", "Dokumen", "Status"],
        widths: [5, 70, 25],
        rows: [
          ["1", "Foto produk", "(Ada/Belum)"],
          ["2", "Manual penggunaan", "(Ada/Belum)"],
          ["3", "Sertifikat HKI (jika ada)", "(Ada/Belum)"],
          ["4", "Bukti adopsi masyarakat", "(Ada/Belum)"],
          ["5", "Video demo produk", "(Ada/Belum)"],
        ],
      },
    ],
    tandaTangan: ttdKaLPPM(),
  },
  {
    nomor: 18,
    namaFormulir: "FORMULIR KUESIONER KEPUASAN MITRA PkM",
    kodeFormulir: "FM-PKM-05",
    kategori: "FORM",
    matchStandar: "Standar Hasil PkM (PKM-HSL)",
    deskripsi: [
      "Formulir ini digunakan untuk mengukur tingkat kepuasan mitra PkM terhadap pelaksanaan PkM.",
    ],
    instruksi: "Berikan kuesioner kepada mitra PkM di akhir kegiatan. Skala 1-5 (1=sangat tidak puas, 5=sangat puas).",
    fieldTables: [
      {
        title: "A. Identitas Mitra",
        headers: ["Komponen", "Isian"],
        widths: [30, 70],
        rows: [
          ["Nama Mitra", ""],
          ["Lokasi", ""],
          ["Judul PkM", ""],
          ["Tanggal Kuesioner", ""],
        ],
      },
      tabelAspekSkor("B. Penilaian Kepuasan (Skor 1-5)", [
        "Kesesuaian pelaksanaan dengan rencana",
        "Kualitas luaran PkM",
        "Dampak terhadap masyarakat",
        "Sikap pelaksana PkM",
        "Keberlanjutan PkM",
        "Komunikasi dengan mitra",
        "Kerjasama tim pelaksana dengan mitra",
        "Tanggung jawab pelaksana terhadap mitra",
        "Transparansi dalam pelaksanaan",
        "Pemenuhan komitmen yang dijanjikan",
        "Pendampingan pasca PkM",
        "Transfer pengetahuan kepada mitra",
        "Pemberdayaan mitra untuk mandiri",
        "Penyelesaian masalah masyarakat",
        "Rekomendasi untuk replikasi",
      ]),
      {
        title: "C. Saran dan Masukan",
        headers: ["Komponen", "Isian"],
        widths: [30, 70],
        rows: [
          ["Saran untuk perbaikan", ""],
          ["Rekomendasi untuk PkM berikutnya", ""],
        ],
      },
    ],
    tandaTangan: [
      { label: "Mitra PkM", nama: "(...........................)", jabatan: "Mitra", nip: "" },
      { label: "Pelaksana PkM", nama: "(...........................)", jabatan: "Pelaksana", nip: "" },
    ],
  },

  // === BAB V: FORMULIR STANDAR TAMBAHAN ===
  {
    nomor: 19,
    namaFormulir: "FORMULIR MONITORING EVALUASI VISI MISI TUJUAN DAN STRATEGI",
    kodeFormulir: "FM-TMB-01",
    kategori: "FORM",
    matchStandar: "Standar Visi, Misi, Tujuan, dan Strategi (VMTS)",
    deskripsi: [
      "Formulir ini digunakan untuk monitoring dan evaluasi ketercapaian VMTS, dengan baseline 2025 dan target 2026-2030.",
    ],
    instruksi: "Isi formulir setiap tahun oleh Senat Universitas bersama PPM.",
    fieldTables: [
      {
        title: "A. Identitas",
        headers: ["Komponen", "Isian"],
        widths: [30, 70],
        rows: [
          ["Tahun Evaluasi", ""],
          ["Tanggal Evaluasi", ""],
          ["Penanggung Jawab", "Senat Universitas"],
          ["Pemonitor", "Ka. PPM"],
        ],
      },
      {
        title: "B. Indikator Ketercapaian VMTS",
        headers: ["No", "Indikator", "Baseline 2025", "Target 2030", "Capaian", "Skor (1-5)"],
        widths: [5, 35, 12, 12, 12, 24],
        rows: [
          ["1", "Universitas memiliki RIP", "1", "1", "", ""],
          ["2", "Universitas memiliki Renstra", "1", "1", "", ""],
          ["3", "Fakultas memiliki Renstra", "5", "5", "", ""],
          ["4", "Tingkat pemahaman sivitas terhadap VMTS", "75%", "98%", "", ""],
          ["5", "Persentase unit kerja mengintegrasikan VMTS dalam Renop", "80%", "100%", "", ""],
          ["6", "Jumlah review VMTS per 5 tahun", "1", "1", "", ""],
          ["7", "Persentase milestone yang tercapai", "70%", "100%", "", ""],
          ["8", "Jumlah publikasi VMTS di situs web", "1", "6", "", ""],
          ["9", "Jumlah workshop penyusunan RIP/Renstra/Renop per tahun", "2", "18", "", ""],
          ["10", "Persentase indikator VMTS termonitor real-time", "40%", "100%", "", ""],
        ],
      },
      tabelAspekSkor("C. Tinjauan VMTS", [
        "Relevansi VMTS dengan dinamika eksternal",
        "Pemahaman sivitas akademika terhadap VMTS",
        "Integrasi VMTS dalam Renstra/Renop",
        "Publikasi VMTS kepada pemangku kepentingan",
        "Proses partisipatif dalam penyusunan VMTS",
        "Keterlibatan DUDI dalam review VMTS",
        "Sosialisasi VMTS secara berkala",
        "Dashboard monitoring VMTS real-time",
        "Tingkat kepuasan pemangku kepentingan terhadap VMTS",
        "Konsistensi VMTS dengan regulasi terkini",
      ]),
      {
        title: "D. Rekomendasi",
        headers: ["No", "Rekomendasi", "Penanggung Jawab", "Target Waktu"],
        widths: [5, 55, 25, 15],
        emptyRows: 5,
      },
    ],
    tandaTangan: [
      { label: "Ka. PPM", nama: "(...........................)", jabatan: "Ka. PPM", nip: "NIDN: ................" },
      { label: "Ketua Senat", nama: "(...........................)", jabatan: "Ketua Senat", nip: "NIDN: ................" },
      { label: "Rektor", nama: "(...........................)", jabatan: "Rektor", nip: "NIDN: 0714046001" },
    ],
  },
  {
    nomor: 20,
    namaFormulir: "FORMULIR MONITORING EVALUASI TATA PAMONG DAN TATA KELOLA",
    kodeFormulir: "FM-TMB-02",
    kategori: "FORM",
    matchStandar: "Standar Tata Pamong dan Tata Kelola (TPTK) - Pasal 67 Permen 39/2025",
    deskripsi: [
      "Formulir ini digunakan untuk monitoring dan evaluasi tata pamong dan tata kelola, mencakup SOTK, audit internal, dan kepuasan pemangku kepentingan.",
    ],
    instruksi: "Isi formulir setiap tahun oleh SPI bersama PPM.",
    fieldTables: [
      {
        title: "A. Identitas",
        headers: ["Komponen", "Isian"],
        widths: [30, 70],
        rows: [
          ["Tahun Evaluasi", ""],
          ["Tanggal Evaluasi", ""],
          ["Pemonitor", "Ka. SPI / Ka. PPM"],
        ],
      },
      tabelAspekSkor("B. Indikator Tata Pamong", [
        "SOTK terdokumentasi dan disosialisasikan",
        "Penerapan prinsip akuntabilitas",
        "Penerapan prinsip transparansi",
        "Penerapan prinsip nirlaba",
        "Penerapan prinsip efektivitas",
        "Penerapan prinsip efisiensi",
        "Penerapan prinsip peningkatan mutu berkelanjutan",
        "Sistem pengelolaan strategis dan operasional efektif",
        "Sistem penjaminan mutu yang sahih dan andal",
        "Mekanisme pengawasan oleh Senat",
        "Mekanisme pengawasan oleh SPI",
        "Review tata pamong secara berkala",
        "Kode etik bagi sivitas akademika",
        "Sistem informasi untuk transparansi",
        "Mekanisme whistleblowing",
      ]),
      {
        title: "C. Audit Internal SPI",
        headers: ["No", "Jenis Audit", "Tanggal", "Opini", "Status Tindak Lanjut"],
        widths: [5, 35, 15, 15, 30],
        rows: [
          ["1", "Audit keuangan tahunan", "", "", ""],
          ["2", "Audit operasional", "", "", ""],
          ["3", "Audit kepatuhan", "", "", ""],
          ["4", "Audit kinerja", "", "", ""],
          ["5", "Audit SPMI", "", "", ""],
        ],
      },
      {
        title: "D. Rekomendasi",
        headers: ["No", "Rekomendasi", "Penanggung Jawab", "Target Waktu"],
        widths: [5, 55, 25, 15],
        emptyRows: 5,
      },
    ],
    tandaTangan: [
      { label: "Ka. SPI", nama: "(...........................)", jabatan: "Ka. SPI", nip: "NIDN: ................" },
      { label: "Ka. PPM", nama: "(...........................)", jabatan: "Ka. PPM", nip: "NIDN: ................" },
      { label: "Rektor", nama: "(...........................)", jabatan: "Rektor", nip: "NIDN: 0714046001" },
    ],
  },
  {
    nomor: 21,
    namaFormulir: "FORMULIR MONITORING EVALUASI MAHASISWA",
    kodeFormulir: "FM-TMB-03",
    kategori: "FORM",
    matchStandar: "Standar Mahasiswa (MHS)",
    deskripsi: [
      "Formulir ini digunakan untuk monitoring dan evaluasi pengelolaan mahasiswa, mencakup penerimaan, beasiswa, organisasi, dan layanan.",
    ],
    instruksi: "Isi formulir setiap tahun oleh Wakil Rektor III bersama PPM.",
    fieldTables: [
      {
        title: "A. Identitas",
        headers: ["Komponen", "Isian"],
        widths: [30, 70],
        rows: [
          ["Tahun Akademik", ""],
          ["Tanggal Evaluasi", ""],
          ["Pemonitor", "Wakil Rektor III / Ka. PPM"],
        ],
      },
      tabelAspekSkor("B. Indikator Mahasiswa", [
        "Sistem penerimaan mahasiswa transparan dan akuntabel",
        "Layanan kemahasiswaan lengkap (beasiswa, konseling, minat-bakat)",
        "Organisasi kemahasiswaan aktif dan demokratis",
        "Layanan karir untuk kesiapan kerja lulusan",
        "Akses pendidikan bagi kelompok rentan",
        "Penerimaan mahasiswa transfer dan internasional",
        "Sistem informasi kemahasiswaan terintegrasi",
        "Orientasi mahasiswa baru yang bermutu",
        "Fasilitas kemahasiswaan memadai",
        "Tracer study mahasiswa sebagai umpan balik",
        "Tingkat retensi mahasiswa",
        "Tingkat kepuasan mahasiswa terhadap layanan",
        "Jumlah mahasiswa dengan beasiswa",
        "Jumlah organisasi mahasiswa aktif",
        "Persentase lulusan terserap DUDI <6 bulan",
      ]),
      {
        title: "C. Capaian Indikator Mahasiswa",
        headers: ["No", "Indikator", "Target 2030", "Capaian", "Selisih"],
        widths: [5, 40, 20, 20, 15],
        rows: [
          ["1", "Jumlah mahasiswa aktif", "10500", "", ""],
          ["2", "Persentase mahasiswa dengan beasiswa", "≥52%", "", ""],
          ["3", "Tingkat retensi mahasiswa", "≥95%", "", ""],
          ["4", "Jumlah organisasi mahasiswa aktif", "≥62", "", ""],
          ["5", "Persentase lulusan terserap DUDI <6 bln", "≥92%", "", ""],
          ["6", "Jumlah mahasiswa internasional", "155", "", ""],
          ["7", "Tingkat kepuasan mahasiswa", "≥97%", "", ""],
        ],
      },
      {
        title: "D. Rekomendasi",
        headers: ["No", "Rekomendasi", "Penanggung Jawab", "Target Waktu"],
        widths: [5, 55, 25, 15],
        emptyRows: 5,
      },
    ],
    tandaTangan: [
      { label: "Wakil Rektor III", nama: "(...........................)", jabatan: "Wakil Rektor III", nip: "NIDN: ................" },
      { label: "Ka. PPM", nama: "(...........................)", jabatan: "Ka. PPM", nip: "NIDN: ................" },
    ],
  },
  {
    nomor: 22,
    namaFormulir: "FORMULIR MONITORING EVALUASI SUMBER DAYA MANUSIA",
    kodeFormulir: "FM-TMB-04",
    kategori: "FORM",
    matchStandar: "Standar Sumber Daya Manusia (SDM)",
    deskripsi: [
      "Formulir ini digunakan untuk monitoring dan evaluasi SDM, mencakup rekrutmen, pelatihan, kinerja, dan retensi.",
    ],
    instruksi: "Isi formulir setiap tahun oleh BAKU bersama PPM.",
    fieldTables: [
      {
        title: "A. Identitas",
        headers: ["Komponen", "Isian"],
        widths: [30, 70],
        rows: [
          ["Tahun Evaluasi", ""],
          ["Tanggal Evaluasi", ""],
          ["Pemonitor", "Ka. BAKU / Ka. PPM"],
        ],
      },
      tabelAspekSkor("B. Indikator SDM", [
        "Rencana SDM jangka menengah yang diturunkan dari Renstra",
        "Rekrutmen SDM transparan, akuntabel, berbasis kompetensi",
        "Program pengembangan SDM berkelanjutan",
        "Sistem penilaian kinerja objektif dan transparan (SKP)",
        "Sistem retensi SDM yang adil (kompensasi, benefit)",
        "Sistem informasi SDM terintegrasi",
        "Sistem promosi yang transparan",
        "Mutasi SDM berdasarkan kebutuhan dan kompetensi",
        "Program studi lanjut bagi dosen",
        "Pelatihan kompetensi tenaga kependidikan",
        "Program mentoring bagi SDM muda",
        "Reward dan apresiasi SDM berprestasi",
        "Tingkat retensi SDM (5 tahun)",
        "Persentase SDM dengan SKP >80",
        "Tingkat kepuasan SDM terhadap lingkungan kerja",
      ]),
      {
        title: "C. Capaian Indikator SDM",
        headers: ["No", "Indikator", "Target 2030", "Capaian", "Selisih"],
        widths: [5, 40, 20, 20, 15],
        rows: [
          ["1", "Jumlah SDM (dosen + tendik)", "545", "", ""],
          ["2", "Persentase SDM dengan kompetensi sesuai", "100%", "", ""],
          ["3", "Jumlah program pelatihan SDM per tahun", "95", "", ""],
          ["4", "Tingkat retensi SDM (5 tahun)", "≥97%", "", ""],
          ["5", "Persentase SDM dengan SKP >80", "≥98%", "", ""],
          ["6", "Jumlah SDM dengan sertifikasi profesi", "145", "", ""],
          ["7", "Tingkat kepuasan SDM terhadap lingkungan kerja", "≥97%", "", ""],
        ],
      },
      {
        title: "D. Rekomendasi",
        headers: ["No", "Rekomendasi", "Penanggung Jawab", "Target Waktu"],
        widths: [5, 55, 25, 15],
        emptyRows: 5,
      },
    ],
    tandaTangan: [
      { label: "Ka. BAKU", nama: "(...........................)", jabatan: "Ka. BAKU", nip: "NIP: ................" },
      { label: "Ka. PPM", nama: "(...........................)", jabatan: "Ka. PPM", nip: "NIDN: ................" },
      { label: "Wakil Rektor II", nama: "(...........................)", jabatan: "Wakil Rektor II", nip: "NIDN: ................" },
    ],
  },
  {
    nomor: 23,
    namaFormulir: "FORMULIR MONITORING EVALUASI KEUANGAN, SARANA, DAN PRASARANA",
    kodeFormulir: "FM-TMB-05",
    kategori: "FORM",
    matchStandar: "Standar Keuangan, Sarana, dan Prasarana (KSP)",
    deskripsi: [
      "Formulir ini digunakan untuk monitoring dan evaluasi pengelolaan keuangan, sarana, dan prasarana secara terintegrasi.",
    ],
    instruksi: "Isi formulir setiap tahun oleh BAKU bersama BAU dan SPI.",
    fieldTables: [
      {
        title: "A. Identitas",
        headers: ["Komponen", "Isian"],
        widths: [30, 70],
        rows: [
          ["Tahun Anggaran", ""],
          ["Tanggal Evaluasi", ""],
          ["Pemonitor", "Ka. BAKU / Ka. BAU / Ka. SPI"],
        ],
      },
      tabelAspekSkor("B. Indikator Keuangan", [
        "Pengelolaan keuangan transparan, akuntabel, efisien",
        "Sistem akuntansi sesuai standar (PSAK/SAK ETAP)",
        "Audit internal oleh SPI",
        "Audit eksternal oleh KAP",
        "Opini audit (target WTP)",
        "Anggaran berbasis kinerja",
        "Sistem informasi manajemen keuangan terintegrasi",
        "Publikasi laporan keuangan",
        "Pengembangan RGU",
        "Kerjasama DUDI untuk pendanaan",
      ]),
      tabelAspekSkor("C. Indikator Sarana dan Prasarana", [
        "Pengelolaan sarana-prasarana terencana dan terdokumentasi",
        "Sistem inventarisasi berbasis IT",
        "Sarana-prasarana berbasis IT untuk efisiensi",
        "Maintenance sarana-prasarana berkala",
        "Sistem manajemen fasilitas berbasis IT",
        "Smart campus (WiFi, smart classroom, IoT)",
        "Investasi sarana-prasarana berkala",
        "Kerjasama DUDI untuk pendanaan sarana",
        "Universal design untuk akses disabilitas",
        "Tingkat kepuasan sivitas terhadap fasilitas",
      ]),
      {
        title: "D. Capaian Indikator",
        headers: ["No", "Indikator", "Target 2030", "Capaian", "Selisih"],
        widths: [5, 40, 20, 20, 15],
        rows: [
          ["1", "Anggaran tahunan (Rp miliar)", "165", "", ""],
          ["2", "Opini audit eksternal", "WTP", "", ""],
          ["3", "Persentase sarana terinventarisasi", "100%", "", ""],
          ["4", "Persentase prasarana terpelihara", "100%", "", ""],
          ["5", "Jumlah smart campus components", "55", "", ""],
          ["6", "Jumlah investasi sarana-prasarana (Rp juta)", "3000", "", ""],
        ],
      },
      {
        title: "E. Rekomendasi",
        headers: ["No", "Rekomendasi", "Penanggung Jawab", "Target Waktu"],
        widths: [5, 55, 25, 15],
        emptyRows: 5,
      },
    ],
    tandaTangan: [
      { label: "Ka. BAKU", nama: "(...........................)", jabatan: "Ka. BAKU", nip: "NIP: ................" },
      { label: "Ka. BAU", nama: "(...........................)", jabatan: "Ka. BAU", nip: "NIP: ................" },
      { label: "Ka. SPI", nama: "(...........................)", jabatan: "Ka. SPI", nip: "NIDN: ................" },
    ],
  },
  {
    nomor: 24,
    namaFormulir: "FORMULIR MONITORING EVALUASI KERJASAMA",
    kodeFormulir: "FM-TMB-06",
    kategori: "FORM",
    matchStandar: "Standar Kerjasama (KJS)",
    deskripsi: [
      "Formulir ini digunakan untuk monitoring dan evaluasi kerja sama, mencakup MoU, MoA, dan implementasi.",
    ],
    instruksi: "Isi formulir setiap tahun oleh BAU bersama PPM.",
    fieldTables: [
      {
        title: "A. Identitas",
        headers: ["Komponen", "Isian"],
        widths: [30, 70],
        rows: [
          ["Tahun Evaluasi", ""],
          ["Tanggal Evaluasi", ""],
          ["Pemonitor", "Ka. BAU / Ka. PPM"],
        ],
      },
      tabelAspekSkor("B. Indikator Kerjasama", [
        "Pengembangan kerjasama dengan PT lain, DUDI, pemerintah, internasional",
        "Dokumentasi kerjasama dalam MoU/MoA yang jelas",
        "Sistem pengelolaan kerjasama transparan",
        "Evaluasi kerjasama berkala",
        "Kerjasama strategis berorientasi output berkelanjutan",
        "Kerjasama internasional untuk reputasi global",
        "Kerjasama akademik, penelitian, PkM, DUDI seimbang",
        "Aktif dalam asosiasi profesi dan konsorsium PT",
        "Penanggung jawab kerjasama yang jelas",
        "Database kerjasama terintegrasi PD Dikti",
        "Reward bagi unit kerja aktif kerjasama",
        "Kerjasama berdampak besar",
      ]),
      {
        title: "C. Capaian Indikator Kerjasama",
        headers: ["No", "Indikator", "Target 2030", "Capaian", "Selisih"],
        widths: [5, 40, 20, 20, 15],
        rows: [
          ["1", "Jumlah MoU aktif", "190", "", ""],
          ["2", "Jumlah MoA aktif", "305", "", ""],
          ["3", "Jumlah kerjasama internasional aktif", "88", "", ""],
          ["4", "Persentase kerjasama dengan implementasi nyata", "100%", "", ""],
          ["5", "Jumlah joint program dengan PT mitra", "32", "", ""],
          ["6", "Jumlah kerjasama dengan pemerintah daerah", "45", "", ""],
          ["7", "Jumlah keanggotaan asosiasi profesi", "45", "", ""],
        ],
      },
      {
        title: "D. Daftar Kerjasama Aktif",
        headers: ["No", "Mitra", "Jenis (MoU/MoA)", "Bidang", "Status Implementasi"],
        widths: [5, 25, 15, 20, 35],
        emptyRows: 10,
      },
      {
        title: "E. Rekomendasi",
        headers: ["No", "Rekomendasi", "Penanggung Jawab", "Target Waktu"],
        widths: [5, 55, 25, 15],
        emptyRows: 5,
      },
    ],
    tandaTangan: ttdKaUnit(),
  },
  {
    nomor: 25,
    namaFormulir: "FORMULIR MONITORING EVALUASI MBKM",
    kodeFormulir: "FM-TMB-07",
    kategori: "FORM",
    matchStandar: "Standar Merdeka Belajar Kampus Merdeka (MBKM)",
    deskripsi: [
      "Formulir ini digunakan untuk monitoring dan evaluasi pelaksanaan MBKM, mencakup skema, mitra DUDI, dan mahasiswa.",
    ],
    instruksi: "Isi formulir setiap semester oleh UPPS bersama PPM.",
    fieldTables: [
      {
        title: "A. Identitas",
        headers: ["Komponen", "Isian"],
        widths: [30, 70],
        rows: [
          ["Semester / Tahun Akademik", ""],
          ["Tanggal Evaluasi", ""],
          ["Pemonitor", "Ka. UPPS / Ka. PPM"],
        ],
      },
      tabelAspekSkor("B. Indikator MBKM", [
        "Pemberian ruang bagi mahasiswa untuk MBKM 1-2 semester",
        "Pengembangan berbagai skema MBKM",
        "Pengakuan SKS atas kegiatan MBKM",
        "Kemitraan DUDI untuk kesempatan MBKM",
        "Sistem pengelolaan MBKM transparan",
        "Monitoring dan evaluasi MBKM berkala",
        "Kurikulum MBKM dengan capaian pembelajaran terukur",
        "Pembimbing MBKM (dosen dan mentor DUDI)",
        "Sertifikat MBKM bagi mahasiswa",
        "Tracer study MBKM sebagai umpan balik",
        "Tingkat kepuasan mahasiswa terhadap MBKM",
        "Tingkat kelulusan mahasiswa MBKM",
        "Konversi SKS MBKM yang baik",
      ]),
      {
        title: "C. Skema MBKM",
        headers: ["No", "Skema MBKM", "Jumlah Mahasiswa", "Mitra DUDI", "Konversi SKS"],
        widths: [5, 25, 18, 25, 27],
        rows: [
          ["1", "Magang Industri", "", "", ""],
          ["2", "Studi Independen", "", "", ""],
          ["3", "Pertukaran Pelajar", "", "", ""],
          ["4", "Asistensi Mengajar", "", "", ""],
          ["5", "Proyek Kemanusiaan", "", "", ""],
          ["6", "Kegiatan Wirausaha", "", "", ""],
        ],
      },
      {
        title: "D. Capaian Indikator MBKM",
        headers: ["No", "Indikator", "Target 2030", "Capaian", "Selisih"],
        widths: [5, 40, 20, 20, 15],
        rows: [
          ["1", "Persentase prodi yang menerapkan MBKM", "100%", "", ""],
          ["2", "Jumlah mahasiswa MBKM per tahun", "1650", "", ""],
          ["3", "Jumlah mitra DUDI untuk MBKM", "180", "", ""],
          ["4", "Tingkat kepuasan mahasiswa MBKM", "≥96%", "", ""],
          ["5", "Persentase mahasiswa MBKM terserap DUDI", "90%", "", ""],
        ],
      },
      {
        title: "E. Rekomendasi",
        headers: ["No", "Rekomendasi", "Penanggung Jawab", "Target Waktu"],
        widths: [5, 55, 25, 15],
        emptyRows: 5,
      },
    ],
    tandaTangan: ttdKaProdi(),
  },
  {
    nomor: 26,
    namaFormulir: "FORMULIR MONITORING EVALUASI LUARAN DAN CAPAIAN TRIDHARMA",
    kodeFormulir: "FM-TMB-08",
    kategori: "FORM",
    matchStandar: "Standar Luaran dan Capaian Tridharma (LCT)",
    deskripsi: [
      "Formulir ini digunakan untuk monitoring dan evaluasi luaran dan capaian Tridharma secara terintegrasi.",
    ],
    instruksi: "Isi formulir setiap tahun oleh PPM, dilaporkan dalam RTM tahunan.",
    fieldTables: [
      {
        title: "A. Identitas",
        headers: ["Komponen", "Isian"],
        widths: [30, 70],
        rows: [
          ["Tahun Evaluasi", ""],
          ["Tanggal Evaluasi", ""],
          ["Pemonitor", "Ka. PPM"],
        ],
      },
      {
        title: "B. Capaian 8 IKU (Baseline 2025 - Target 2030)",
        headers: ["No", "IKU", "Baseline 2025", "Target 2030", "Capaian", "Skor (1-5)"],
        widths: [5, 35, 12, 12, 12, 24],
        rows: [
          ["1", "Lulusan terserap DUDI <6 bulan", "60%", "92%", "", ""],
          ["2", "Mahasiswa mendapat pengalaman di luar kampus", "20%", "40%", "", ""],
          ["3", "Dosen berkegiatan di luar kampus", "15%", "35%", "", ""],
          ["4", "Praktisi mengajar di kampus", "2/prodi", "6/prodi", "", ""],
          ["5", "Hasil kerja dosen digunakan masyarakat", "15", "35", "", ""],
          ["6", "Prodi berkerjasama dengan DUDI", "3/prodi", "7/prodi", "", ""],
          ["7", "Mata kuliah dengan metode praktik", "40%", "60%", "", ""],
          ["8", "Prodi terakreditasi unggul", "30%", "70%", "", ""],
        ],
      },
      {
        title: "C. Luaran Tridharma",
        headers: ["Jenis Luaran", "Baseline 2025", "Target 2030", "Capaian"],
        widths: [40, 20, 20, 20],
        rows: [
          ["Lulusan per tahun", "1500", "2750", ""],
          ["Publikasi Tridharma per tahun", "200", "980", ""],
          ["Paten/HKI per tahun", "15", "125", ""],
          ["Produk PkM per tahun", "30", "210", ""],
          ["Jumlah publikasi Scopus per tahun", "20", "145", ""],
          ["Jumlah publikasi SINTA 1-3 per tahun", "30", "180", ""],
        ],
      },
      {
        title: "D. Rekomendasi",
        headers: ["No", "Rekomendasi", "Penanggung Jawab", "Target Waktu"],
        widths: [5, 55, 25, 15],
        emptyRows: 5,
      },
    ],
    tandaTangan: [
      { label: "Ka. PPM", nama: "(...........................)", jabatan: "Ka. PPM", nip: "NIDN: ................" },
      { label: "Rektor", nama: "(...........................)", jabatan: "Rektor", nip: "NIDN: 0714046001" },
    ],
  },
  {
    nomor: 27,
    namaFormulir: "FORMULIR MONITORING EVALUASI PELAYANAN KEPADA MAHASISWA",
    kodeFormulir: "FM-TMB-09",
    kategori: "FORM",
    matchStandar: "Standar Pelayanan Kepada Mahasiswa (PKM-MHS)",
    deskripsi: [
      "Formulir ini digunakan untuk monitoring dan evaluasi pelayanan kepada mahasiswa, mencakup layanan akademik, administrasi, dan penunjang.",
    ],
    instruksi: "Isi formulir setiap semester oleh BAA bersama PPM.",
    fieldTables: [
      {
        title: "A. Identitas",
        headers: ["Komponen", "Isian"],
        widths: [30, 70],
        rows: [
          ["Semester / Tahun Akademik", ""],
          ["Tanggal Evaluasi", ""],
          ["Pemonitor", "Ka. BAA / Ka. PPM"],
        ],
      },
      tabelAspekSkor("B. Indikator Pelayanan", [
        "Layanan akademik yang lengkap dan mudah diakses",
        "Layanan administrasi yang cepat dan akurat",
        "One-Stop Service di tingkat universitas dan fakultas",
        "Sistem informasi untuk akses layanan digital",
        "Survey kepuasan mahasiswa setiap semester",
        "Tindak lanjut pengaduan mahasiswa cepat dan transparan",
        "Layanan kemahasiswaan lengkap (beasiswa, konseling, karir)",
        "Layanan penunjang memadai (perpustakaan, lab, kafetaria)",
        "Penerapan prinsip customer service yang baik",
        "Aplikasi mobile untuk akses layanan mahasiswa",
        "Helpdesk untuk membantu mahasiswa",
        "Evaluasi kualitas layanan secara berkala",
      ]),
      {
        title: "C. Survey Kepuasan Mahasiswa per Layanan",
        headers: ["No", "Jenis Layanan", "Jumlah Responden", "Skor (1-5)", "Catatan"],
        widths: [5, 35, 18, 12, 30],
        rows: [
          ["1", "KRS dan nilai online (SIAKAD)", "", "", ""],
          ["2", "KTM, transkrip, ijazah", "", "", ""],
          ["3", "Beasiswa", "", "", ""],
          ["4", "Konseling", "", "", ""],
          ["5", "Pusat karir", "", "", ""],
          ["6", "Perpustakaan", "", "", ""],
          ["7", "Laboratorium", "", "", ""],
          ["8", "Kafetaria", "", "", ""],
          ["9", "Parkir dan keamanan", "", "", ""],
          ["10", "WiFi/Internet kampus", "", "", ""],
          ["11", "Fasilitas ibadah", "", "", ""],
          ["12", "UKM dan organisasi mahasiswa", "", "", ""],
        ],
      },
      {
        title: "D. Capaian Indikator Pelayanan",
        headers: ["No", "Indikator", "Target 2030", "Capaian", "Selisih"],
        widths: [5, 40, 20, 20, 15],
        rows: [
          ["1", "Tingkat kepuasan layanan akademik", "≥97%", "", ""],
          ["2", "Tingkat kepuasan layanan administrasi", "≥96%", "", ""],
          ["3", "Persentase layanan digital", "100%", "", ""],
          ["4", "Waktu penyelesaian pengaduan (hari)", "≤1", "", ""],
          ["5", "Jumlah layanan One-Stop Service", "20", "", ""],
        ],
      },
      {
        title: "E. Rekomendasi",
        headers: ["No", "Rekomendasi", "Penanggung Jawab", "Target Waktu"],
        widths: [5, 55, 25, 15],
        emptyRows: 5,
      },
    ],
    tandaTangan: ttdKaUnit(),
  },

  // === BAB VI: FORMULIR AMI DAN RTM ===
  {
    nomor: 28,
    namaFormulir: "FORMULIR PERMOHONAN AUDIT MUTU INTERNAL (AMI)",
    kodeFormulir: "FM-AMI-01",
    kategori: "FORM",
    matchStandar: "Manual Mutu SPMI UNITA - Bab VI AMI (Pasal 68 Permen 39/2025)",
    deskripsi: [
      "Formulir ini digunakan untuk permohonan AMI oleh unit kerja kepada PPM. Sesuai Manual Mutu Bab VI dan Pasal 68 ayat (2) Permen 39 Tahun 2025.",
    ],
    instruksi: "Isi formulir minimal 1 bulan sebelum jadwal AMI yang diusulkan.",
    fieldTables: [
      {
        title: "A. Identitas Auditee",
        headers: ["Komponen", "Isian"],
        widths: [30, 70],
        rows: [
          ["Unit Kerja / Program Studi", ""],
          ["Ka. Unit / Ka. Prodi", ""],
          ["Alamat", ""],
          ["Kontak (HP/Email)", ""],
          ["Tanggal Permohonan", ""],
        ],
      },
      {
        title: "B. Lingkup Audit yang Dimohon",
        headers: ["No", "Standar yang Diaudit", "Periode Audit"],
        widths: [5, 65, 30],
        rows: [
          ["1", "Standar Kompetensi Lulusan", ""],
          ["2", "Standar Proses Pembelajaran", ""],
          ["3", "Standar Penilaian", ""],
          ["4", "Standar Pengelolaan", ""],
          ["5", "Standar Isi", ""],
          ["6", "Standar Dosen dan Tenaga Kependidikan", ""],
          ["7", "Standar Sarana dan Prasarana", ""],
          ["8", "Standar Pembiayaan", ""],
        ],
      },
      {
        title: "C. Jadwal AMI yang Diusulkan",
        headers: ["No", "Tahapan AMI", "Tanggal Usulan"],
        widths: [5, 65, 30],
        rows: [
          ["1", "Persiapan & evaluasi diri", ""],
          ["2", "Pelaksanaan audit (visitasi)", ""],
          ["3", "Penyusunan laporan", ""],
        ],
      },
      {
        title: "D. Tim Auditee",
        headers: ["No", "Nama", "Jabatan dalam Tim", "NIDN/NIP"],
        widths: [5, 40, 30, 25],
        emptyRows: 5,
      },
    ],
    tandaTangan: [
      { label: "Ka. Unit / Ka. Prodi", nama: "(...........................)", jabatan: "Ka. Unit", nip: "NIDN: ................" },
      { label: "Ka. PPM", nama: "(...........................)", jabatan: "Ka. PPM", nip: "NIDN: ................" },
    ],
  },
  {
    nomor: 29,
    namaFormulir: "FORMULIR LAPORAN EVALUASI DIRI AUDITEE",
    kodeFormulir: "FM-AMI-02",
    kategori: "FORM",
    matchStandar: "Manual Mutu SPMI UNITA - Bab VI AMI",
    deskripsi: [
      "Formulir ini digunakan oleh auditee untuk menyusun laporan evaluasi diri sebelum AMI. Sesuai Manual Mutu Bab VI.",
    ],
    instruksi: "Isi formulir minimal 2 minggu sebelum jadwal AMI.",
    fieldTables: [
      {
        title: "A. Identitas Auditee",
        headers: ["Komponen", "Isian"],
        widths: [30, 70],
        rows: [
          ["Unit Kerja / Program Studi", ""],
          ["Periode Evaluasi Diri", ""],
          ["Tanggal Penyusunan", ""],
          ["Penanggung Jawab", ""],
        ],
      },
      {
        title: "B. Evaluasi Diri per Standar",
        headers: ["No", "Standar", "Target", "Capaian", "Bukti", "Skor (1-5)"],
        widths: [5, 30, 10, 10, 25, 20],
        rows: [
          ["1", "Standar Kompetensi Lulusan", "", "", "", ""],
          ["2", "Standar Proses Pembelajaran", "", "", "", ""],
          ["3", "Standar Penilaian", "", "", "", ""],
          ["4", "Standar Pengelolaan", "", "", "", ""],
          ["5", "Standar Isi", "", "", "", ""],
          ["6", "Standar Dosen dan Tendik", "", "", "", ""],
          ["7", "Standar Sarana dan Prasarana", "", "", "", ""],
          ["8", "Standar Pembiayaan", "", "", "", ""],
          ["9", "Standar Penelitian", "", "", "", ""],
          ["10", "Standar PkM", "", "", "", ""],
        ],
      },
      {
        title: "C. Identifikasi Masalah",
        headers: ["No", "Masalah", "Penyebab", "Dampak", "Usulan Solusi"],
        widths: [5, 30, 20, 20, 25],
        emptyRows: 5,
      },
      {
        title: "D. Rencana Tindak Lanjut",
        headers: ["No", "Rencana", "Penanggung Jawab", "Target Waktu"],
        widths: [5, 55, 25, 15],
        emptyRows: 5,
      },
    ],
    tandaTangan: ttdKaUnit(),
  },
  {
    nomor: 30,
    namaFormulir: "FORMULIR LAPORAN HASIL AMI",
    kodeFormulir: "FM-AMI-03",
    kategori: "FORM",
    matchStandar: "Manual Mutu SPMI UNITA - Bab VI AMI (Pasal 68 Permen 39/2025)",
    deskripsi: [
      "Formulir ini digunakan oleh auditor untuk melaporkan hasil AMI. Sesuai Manual Mutu Bab VI dan Pasal 68 ayat (2-3) Permen 39 Tahun 2025.",
    ],
    instruksi: "Isi formulir maksimal 2 minggu setelah pelaksanaan AMI.",
    fieldTables: [
      {
        title: "A. Identitas Audit",
        headers: ["Komponen", "Isian"],
        widths: [30, 70],
        rows: [
          ["Unit Kerja / Program Studi (Auditee)", ""],
          ["Tim Auditor", ""],
          ["Tanggal Audit", ""],
          ["Lokasi Audit", ""],
          ["No. Surat Tugas", ""],
        ],
      },
      {
        title: "B. Temuan Audit per Standar",
        headers: ["No", "Standar", "Temuan", "Kategori*", "Rekomendasi"],
        widths: [5, 25, 30, 10, 30],
        rows: [
          ["1", "Standar Kompetensi Lulusan", "", "", ""],
          ["2", "Standar Proses Pembelajaran", "", "", ""],
          ["3", "Standar Penilaian", "", "", ""],
          ["4", "Standar Pengelolaan", "", "", ""],
          ["5", "Standar Isi", "", "", ""],
          ["6", "Standar Dosen dan Tendik", "", "", ""],
          ["7", "Standar Sarana dan Prasarana", "", "", ""],
          ["8", "Standar Pembiayaan", "", "", ""],
          ["9", "Standar Penelitian", "", "", ""],
          ["10", "Standar PkM", "", "", ""],
        ],
        notes: ["*Kategori: MS (Mencapai Standar), ML (Melampaui Standar), BS (Belum mencapai Standar), MSV (Menyimpang dari Standar)"],
      },
      {
        title: "C. Permintaan Tindakan Koreksi (PTK)",
        headers: ["No", "PTK", "Penanggung Jawab", "Target Waktu", "Status"],
        widths: [5, 40, 20, 15, 20],
        emptyRows: 6,
      },
      {
        title: "D. Kesimpulan Auditor",
        headers: ["Komponen", "Isian"],
        widths: [30, 70],
        rows: [
          ["Kesimpulan umum", ""],
          ["Rekomendasi prioritas", ""],
          ["Tindak lanjut yang diharapkan", ""],
        ],
      },
    ],
    tandaTangan: [
      { label: "Ketua Tim Auditor", nama: "(...........................)", jabatan: "Ketua Auditor", nip: "NIDN: ................" },
      { label: "Ka. Bag. Audit dan Monevin", nama: "(...........................)", jabatan: "Ka. Bag. AM", nip: "NIDN: ................" },
      { label: "Ka. PPM", nama: "(...........................)", jabatan: "Ka. PPM", nip: "NIDN: ................" },
    ],
  },
  {
    nomor: 31,
    namaFormulir: "FORMULIR BERITA ACARA RAPAT TINJAUAN MANAJEMEN (RTM)",
    kodeFormulir: "FM-AMI-04",
    kategori: "FORM",
    matchStandar: "Manual Mutu SPMI UNITA - Bab VIII RTM",
    deskripsi: [
      "Formulir ini digunakan untuk berita acara RTM tahunan, sesuai Manual Mutu Bab VIII. RTM membahas 7 unsur sebagaimana diatur dalam Manual Mutu.",
    ],
    instruksi: "Isi formulir saat pelaksanaan RTM tahunan oleh Rektor bersama pimpinan.",
    fieldTables: [
      {
        title: "A. Identitas RTM",
        headers: ["Komponen", "Isian"],
        widths: [30, 70],
        rows: [
          ["Tahun RTM", ""],
          ["Tanggal RTM", ""],
          ["Lokasi RTM", ""],
          ["Pimpinan RTM", "Rektor"],
          ["Sekretariat", "PPM"],
        ],
      },
      {
        title: "B. Daftar Hadir",
        headers: ["No", "Nama", "Jabatan", "Tanda Tangan"],
        widths: [5, 40, 30, 25],
        emptyRows: 15,
      },
      {
        title: "C. Agenda 7 Unsur RTM",
        headers: ["No", "Unsur", "Skor (1-5)", "Keputusan / Tindak Lanjut"],
        widths: [5, 35, 10, 50],
        rows: [
          ["1", "Hasil Audit Mutu Internal (AMI)", "", ""],
          ["2", "Umpan balik dari pemangku kepentingan", "", ""],
          ["3", "Pencapaian sasaran mutu / IKU", "", ""],
          ["4", "Tindak lanjut permintaan koreksi (PTK)", "", ""],
          ["5", "Status tindak lanjut RTM periode sebelumnya", "", ""],
          ["6", "Perubahan yang mempengaruhi sistem mutu", "", ""],
          ["7", "Rekomendasi peningkatan", "", ""],
        ],
      },
      {
        title: "D. Keputusan RTM",
        headers: ["No", "Keputusan", "Penanggung Jawab", "Target Waktu"],
        widths: [5, 55, 25, 15],
        emptyRows: 8,
      },
    ],
    tandaTangan: [
      { label: "Sekretariat RTM\nKa. PPM", nama: "(...........................)", jabatan: "Ka. PPM", nip: "NIDN: ................" },
      { label: "Pimpinan RTM\nRektor", nama: "Dr. Muharsono, M.Si.", jabatan: "Rektor", nip: "NIDN: 0714046001" },
    ],
  },

  // === BAB VII: FORMULIR AKADEMIK ===
  {
    nomor: 32,
    namaFormulir: "FORMULIR RENCANA PEMBELAJARAN SEMESTER (RPS)",
    kodeFormulir: "FM-AKD-01",
    kategori: "FORM",
    matchStandar: "Standar Proses Pembelajaran (SPB) - Pasal 11-24 Permen 39/2025",
    deskripsi: [
      "Formulir ini digunakan oleh dosen untuk menyusun RPS setiap mata kuliah. Mengacu pada Standar Proses Pembelajaran (SPB) Permen 39 Tahun 2025.",
    ],
    instruksi: "RPS disusun sebelum semester dimulai dan disetujui Ka. Prodi.",
    fieldTables: [
      {
        title: "A. Identitas Mata Kuliah",
        headers: ["Komponen", "Isian"],
        widths: [30, 70],
        rows: [
          ["Nama Mata Kuliah", ""],
          ["Kode Mata Kuliah / SKS", ""],
          ["Program Studi", ""],
          ["Semester", ""],
          ["Dosen Pengampu", ""],
          ["NIDN", ""],
          ["Tahun Akademik", ""],
        ],
      },
      {
        title: "B. Capaian Pembelajaran",
        headers: ["Komponen", "Isian"],
        widths: [30, 70],
        rows: [
          ["CPL yang dibebankan (dari CPL Prodi)", ""],
          ["CPMK Mata Kuliah", ""],
          ["Sub-CPMK", ""],
        ],
      },
      {
        title: "C. Deskripsi Mata Kuliah",
        headers: ["Komponen", "Isian"],
        widths: [30, 70],
        rows: [
          ["Deskripsi singkat", ""],
          ["Bahan kajian / materi", ""],
          ["Pustaka utama", ""],
          ["Pustaka pendukung", ""],
        ],
      },
      {
        title: "D. Rencana Pembelajaran Mingguan",
        headers: ["Minggu", "Sub-CPMK", "Materi", "Metode", "Pengalaman Belajar", "Bobot Penilaian"],
        widths: [7, 18, 25, 12, 25, 13],
        rows: [
          ["1", "", "", "", "", ""],
          ["2", "", "", "", "", ""],
          ["3", "", "", "", "", ""],
          ["4", "", "", "", "", ""],
          ["5", "", "", "", "", ""],
          ["6", "", "", "", "", ""],
          ["7", "", "", "", "", ""],
          ["8", "UTS", "Ujian Tengah Semester", "Tes tertulis", "Persiapan UTS", "15-25%"],
          ["9", "", "", "", "", ""],
          ["10", "", "", "", "", ""],
          ["11", "", "", "", "", ""],
          ["12", "", "", "", "", ""],
          ["13", "", "", "", "", ""],
          ["14", "", "", "", "", ""],
          ["15", "", "", "", "", ""],
          ["16", "UAS", "Ujian Akhir Semester", "Tes tertulis", "Persiapan UAS", "20-30%"],
        ],
      },
      {
        title: "E. Komponen Penilaian",
        headers: ["No", "Komponen", "Bobot (%)", "Keterangan"],
        widths: [5, 50, 15, 30],
        rows: [
          ["1", "Kehadiran dan partisipasi", "", ""],
          ["2", "Tugas individu", "", ""],
          ["3", "Tugas kelompok", "", ""],
          ["4", "UTS", "", ""],
          ["5", "UAS", "", ""],
          ["6", "Lain-lain", "", ""],
          ["", "TOTAL", "100%", ""],
        ],
      },
      {
        title: "F. Rubrik Penilaian",
        headers: ["Komponen", "Skor 1", "Skor 2", "Skor 3", "Skor 4", "Skor 5"],
        widths: [30, 14, 14, 14, 14, 14],
        rows: [
          ["Kehadiran", "≤50%", "51-60%", "61-70%", "71-80%", "≥81%"],
          ["Partisipasi", "Pasif", "Kurang aktif", "Cukup aktif", "Aktif", "Sangat aktif"],
          ["Tugas individu", "Buruk", "Kurang", "Cukup", "Baik", "Sangat baik"],
          ["Tugas kelompok", "Buruk", "Kurang", "Cukup", "Baik", "Sangat baik"],
          ["UTS/UAS", "≤40", "41-55", "56-70", "71-85", "≥86"],
        ],
      },
    ],
    tandaTangan: ttdDosen(),
  },
  {
    nomor: 33,
    namaFormulir: "FORMULIR BERITA ACARA UJIAN TENGAH SEMESTER / UJIAN AKHIR SEMESTER",
    kodeFormulir: "FM-AKD-02",
    kategori: "FORM",
    matchStandar: "Standar Penilaian (SPN) - Pasal 25 Permen 39/2025",
    deskripsi: [
      "Formulir ini digunakan untuk berita acara pelaksanaan UTS/UAS. Mengacu pada Standar Penilaian (SPN) Permen 39 Tahun 2025.",
    ],
    instruksi: "Isi formulir saat pelaksanaan UTS/UAS oleh pengawas.",
    fieldTables: [
      {
        title: "A. Identitas Ujian",
        headers: ["Komponen", "Isian"],
        widths: [30, 70],
        rows: [
          ["Jenis Ujian", "(UTS / UAS)"],
          ["Mata Kuliah", ""],
          ["Kode Mata Kuliah / SKS", ""],
          ["Program Studi", ""],
          ["Dosen Pengampu", ""],
          ["Tanggal Ujian", ""],
          ["Waktu / Ruang", ""],
          ["Semester / Tahun Akademik", ""],
        ],
      },
      {
        title: "B. Pelaksanaan Ujian",
        headers: ["Komponen", "Isian"],
        widths: [30, 70],
        rows: [
          ["Jumlah mahasiswa terdaftar", ""],
          ["Jumlah mahasiswa hadir", ""],
          ["Jumlah mahasiswa tidak hadir", ""],
          ["Pengawas 1", ""],
          ["Pengawas 2", ""],
          ["Waktu mulai", ""],
          ["Waktu selesai", ""],
        ],
      },
      {
        title: "C. Catatan Pelaksanaan",
        headers: ["No", "Catatan", "Tindak Lanjut"],
        widths: [5, 65, 30],
        rows: [
          ["1", "Ketersediaan soal tepat waktu", ""],
          ["2", "Kondisi ruang ujian", ""],
          ["3", "Pelanggaran akademik (jika ada)", ""],
          ["4", "Mahasiswa dengan kebutuhan khusus", ""],
          ["5", "Kondisi pengawasan", ""],
        ],
      },
      {
        title: "D. Kondisi Ujian",
        headers: ["Aspek", "Status", "Catatan"],
        widths: [40, 20, 40],
        rows: [
          ["Soal tersedia tepat waktu", "(Ya/Tidak)", ""],
          ["Kondisi ruang memadai", "(Ya/Tidak)", ""],
          ["Pelanggaran akademik", "(Ada/Tidak)", ""],
          ["Mahasiswa dengan khusus", "(Ada/Tidak)", ""],
          ["Acara soal sesuai RPS", "(Ya/Tidak)", ""],
        ],
      },
    ],
    tandaTangan: [
      { label: "Pengawas 1", nama: "(...........................)", jabatan: "Dosen", nip: "NIDN: ................" },
      { label: "Pengawas 2", nama: "(...........................)", jabatan: "Dosen", nip: "NIDN: ................" },
      { label: "Dosen Pengampu", nama: "(...........................)", jabatan: "Dosen", nip: "NIDN: ................" },
    ],
  },
  {
    nomor: 34,
    namaFormulir: "FORMULIR BIMBINGAN TUGAS AKHIR / SKRIPSI / TESIS",
    kodeFormulir: "FM-AKD-03",
    kategori: "FORM",
    matchStandar: "Standar Proses Pembelajaran (SPB)",
    deskripsi: [
      "Formulir ini digunakan untuk pencatatan bimbingan tugas akhir/skripsi/tesis.",
    ],
    instruksi: "Isi formulir setiap kali bimbingan oleh mahasiswa dan dosen pembimbing.",
    fieldTables: [
      {
        title: "A. Identitas",
        headers: ["Komponen", "Isian"],
        widths: [30, 70],
        rows: [
          ["Nama Mahasiswa", ""],
          ["NIM", ""],
          ["Program Studi", ""],
          ["Judul Tugas Akhir / Skripsi", ""],
          ["Dosen Pembimbing 1", ""],
          ["Dosen Pembimbing 2", ""],
          ["Tanggal Mulai Bimbingan", ""],
        ],
      },
      {
        title: "B. Log Bimbingan",
        headers: ["No", "Tanggal", "Materi Bimbingan", "Catatan Dosen", "Paraf Dosen"],
        widths: [5, 12, 35, 30, 18],
        emptyRows: 15,
      },
      {
        title: "C. Persetujuan Seminar Proposal / Hasil / Sidang",
        headers: ["Tahapan", "Status", "Tanggal", "Catatan"],
        widths: [30, 20, 20, 30],
        rows: [
          ["Seminar Proposal", "(Disetujui/Belum)", "", ""],
          ["Seminar Hasil", "(Disetujui/Belum)", "", ""],
          ["Sidang Akhir", "(Disetujui/Belum)", "", ""],
        ],
      },
    ],
    tandaTangan: [
      { label: "Mahasiswa", nama: "(...........................)", jabatan: "Mahasiswa", nip: "NIM: ................" },
      { label: "Dosen Pembimbing 1", nama: "(...........................)", jabatan: "Pembimbing 1", nip: "NIDN: ................" },
      { label: "Dosen Pembimbing 2", nama: "(...........................)", jabatan: "Pembimbing 2", nip: "NIDN: ................" },
    ],
  },
  {
    nomor: 35,
    namaFormulir: "FORMULIR BERITA ACARA KONTRAK PERKULIAHAN",
    kodeFormulir: "FM-AKD-04",
    kategori: "FORM",
    matchStandar: "Standar Proses Pembelajaran (SPB)",
    deskripsi: [
      "Formulir ini digunakan untuk berita acara kontrak perkuliahan antara dosen dan mahasiswa pada awal semester.",
    ],
    instruksi: "Isi formulir pada pertemuan pertama perkuliahan.",
    fieldTables: [
      {
        title: "A. Identitas Mata Kuliah",
        headers: ["Komponen", "Isian"],
        widths: [30, 70],
        rows: [
          ["Mata Kuliah", ""],
          ["Kode Mata Kuliah / SKS", ""],
          ["Program Studi", ""],
          ["Semester / Tahun Akademik", ""],
          ["Dosen Pengampu", ""],
          ["NIDN", ""],
          ["Jumlah Pertemuan", ""],
          ["Jadwal Perkuliahan", ""],
        ],
      },
      {
        title: "B. Kontrak Perkuliahan",
        headers: ["No", "Komponen Kontrak", "Isian"],
        widths: [5, 35, 60],
        rows: [
          ["1", "Capaian Pembelajaran (CPMK)", ""],
          ["2", "Materi pokok", ""],
          ["3", "Metode pembelajaran", ""],
          ["4", "Kriteria penilaian", ""],
          ["5", "Bobot penilaian", ""],
          ["6", "Aturan kehadiran", "Minimal 75% kehadiran untuk mengikuti UAS"],
          ["7", "Pustaka utama", ""],
          ["8", "Tugas-tugas", ""],
          ["9", "Ujian (UTS/UAS)", ""],
          ["10", "Aturan lain", ""],
        ],
      },
      {
        title: "C. Pernyataan",
        headers: ["Komponen", "Isian"],
        widths: [30, 70],
        rows: [
          ["Pernyataan Dosen", "Saya berkomitmen melaksanakan perkuliahan sesuai kontrak di atas."],
          ["Pernyataan Mahasiswa", "Kami berkomitmen mengikuti perkuliahan sesuai kontrak di atas."],
        ],
      },
      {
        title: "D. Daftar Hadir Mahasiswa (Pertemuan Pertama)",
        headers: ["No", "NIM", "Nama Mahasiswa", "Tanda Tangan"],
        widths: [5, 18, 50, 27],
        emptyRows: 20,
      },
    ],
    tandaTangan: ttdDosen(),
  },

  // === BAB VIII: FORMULIR PD DIKTI DAN TRIANGULASI ===
  {
    nomor: 36,
    namaFormulir: "FORMULIR VERIFIKASI DATA PANGKALAN DATA PENDIDIKAN TINGGI (PD DIKTI)",
    kodeFormulir: "FM-PDD-01",
    kategori: "FORM",
    matchStandar: "Bab IV Kebijakan Mutu - Prinsip Triangulasi (Pasal 66 & 111 Permen 39/2025)",
    deskripsi: [
      "Formulir ini digunakan untuk verifikasi data PD Dikti oleh unit kerja, sesuai Pasal 66 (triangulasi) dan Pasal 111 (PD Dikti sebagai sumber data utama) Permen 39 Tahun 2025.",
      "Universitas Tulungagung bertanggung jawab terhadap kebenaran dan ketepatan data PD Dikti sebagaimana diatur dalam Pasal 111 ayat (4) Permen 39 Tahun 2025.",
    ],
    instruksi: "Isi formulir minimal 2 kali per tahun (per semester) oleh operator PD Dikti unit kerja.",
    fieldTables: [
      {
        title: "A. Identitas Unit",
        headers: ["Komponen", "Isian"],
        widths: [30, 70],
        rows: [
          ["Unit Kerja", ""],
          ["Penanggung Jawab Penginputan", ""],
          ["Operator PD Dikti", ""],
          ["Periode Verifikasi (Semester)", ""],
          ["Tanggal Verifikasi", ""],
        ],
      },
      {
        title: "B. Verifikasi Data Mahasiswa",
        headers: ["No", "Jenis Data", "Jumlah di SIAKAD", "Jumlah di PD Dikti", "Status", "Tindak Lanjut"],
        widths: [5, 30, 15, 15, 12, 23],
        rows: [
          ["1", "Mahasiswa aktif", "", "", "", ""],
          ["2", "Mahasiswa baru", "", "", "", ""],
          ["3", "Mahasiswa cuti", "", "", "", ""],
          ["4", "Mahasiswa non-aktif", "", "", "", ""],
          ["5", "Lulusan", "", "", "", ""],
          ["6", "Mahasiswa transfer masuk", "", "", "", ""],
          ["7", "Mahasiswa transfer keluar", "", "", "", ""],
          ["8", "Mahasiswa internasional", "", "", "", ""],
        ],
      },
      {
        title: "C. Verifikasi Data Dosen",
        headers: ["No", "Jenis Data", "Jumlah Internal", "Jumlah PD Dikti", "Status", "Tindak Lanjut"],
        widths: [5, 30, 15, 15, 12, 23],
        rows: [
          ["1", "Dosen tetap (NIDN)", "", "", "", ""],
          ["2", "Dosen tidak tetap (NIDK)", "", "", "", ""],
          ["3", "Dosen dengan Serdos", "", "", "", ""],
          ["4", "Dosen S3", "", "", "", ""],
          ["5", "Dosen Lektor Kepala", "", "", "", ""],
          ["6", "Dosen Guru Besar", "", "", "", ""],
          ["7", "Tendik", "", "", "", ""],
        ],
      },
      {
        title: "D. Verifikasi Data Akademik",
        headers: ["No", "Jenis Data", "Jumlah Internal", "Jumlah PD Dikti", "Status", "Tindak Lanjut"],
        widths: [5, 30, 15, 15, 12, 23],
        rows: [
          ["1", "Mata kuliah", "", "", "", ""],
          ["2", "Kurikulum", "", "", "", ""],
          ["3", "Publikasi jurnal", "", "", "", ""],
          ["4", "Penelitian", "", "", "", ""],
          ["5", "PkM", "", "", "", ""],
          ["6", "Paten/HKI", "", "", "", ""],
          ["7", "Kerjasama (MoU/MoA)", "", "", "", ""],
          ["8", "Status akreditasi prodi", "", "", "", ""],
        ],
      },
      {
        title: "E. Triangulasi Data (Pasal 66 Permen 39/2025)",
        headers: ["Sumber Data", "Bentuk Data", "Penanggung Jawab"],
        widths: [25, 50, 25],
        rows: [
          ["PD Dikti (Data Primer)", "Data mahasiswa, dosen, kurikulum, lulusan, Tridharma", "UPT SI / BAA / BAKU / LPPM / UPPS"],
          ["Evaluasi Internal", "Hasil AMI, evaluasi diri, monitoring rutin, RTM", "PPM / LPM / GKM / Tim Evaluasi"],
          ["Stakeholder Eksternal", "Akreditasi BAN-PT/LAM, umpan balik lulusan, DUDI, pengaduan", "PPM / LPPM / Pusat Karir / UPPS"],
        ],
      },
      tabelAspekSkor("F. Indikator Kualitas Data PD Dikti", [
        "Akurasi data (sesuai dokumen sumber)",
        "Ketepatan waktu penginputan",
        "Konsistensi data antara SIAKAD-PD Dikti",
        "Kelengkapan data semua field",
        "Verifikasi data oleh penanggung jawab",
        "Pemutakhiran data berkala",
        "Dokumentasi proses penginputan",
        "Tindak lanjut koreksi data",
        "Integrasi dengan sistem internal",
        "Tanggung jawab terhadap kebenaran data (Pasal 111 ayat 4)",
      ]),
      {
        title: "G. Catatan dan Tindak Lanjut",
        headers: ["No", "Catatan", "Tindak Lanjut", "Penanggung Jawab", "Target Waktu"],
        widths: [5, 35, 25, 20, 15],
        emptyRows: 5,
      },
    ],
    tandaTangan: [
      { label: "Operator PD Dikti", nama: "(...........................)", jabatan: "Operator", nip: "NIP: ................" },
      { label: "Ka. Unit Kerja", nama: "(...........................)", jabatan: "Ka. Unit", nip: "NIDN: ................" },
      { label: "Verifikator PPM", nama: "(...........................)", jabatan: "Ka. PPM", nip: "NIDN: ................" },
    ],
  },
  {
    nomor: 37,
    namaFormulir: "FORMULIR SURVEY KEPUASAN MAHASISWA (EMONEV)",
    kodeFormulir: "FM-PDD-02",
    kategori: "FORM",
    matchStandar: "Standar Proses Pembelajaran (SPB) & Pelayanan Kepada Mahasiswa (PKM-MHS) - Pasal 66 Permen 39/2025",
    deskripsi: [
      "Formulir ini digunakan untuk survey kepuasan mahasiswa terhadap proses pembelajaran dan layanan, sebagai bagian dari prinsip triangulasi (Pasal 66 Permen 39 Tahun 2025).",
    ],
    instruksi: "Sebarkan kuesioner setiap akhir semester kepada seluruh mahasiswa. Skala 1-5 (1=sangat tidak puas, 5=sangat puas).",
    fieldTables: [
      {
        title: "A. Identitas Responden",
        headers: ["Komponen", "Isian"],
        widths: [30, 70],
        rows: [
          ["Program Studi", ""],
          ["Semester Mahasiswa", ""],
          ["Mata Kuliah (untuk emonev per MK)", ""],
          ["Dosen Pengampu", ""],
          ["Tanggal Isi", ""],
        ],
      },
      tabelAspekSkor("B. Penilaian Proses Pembelajaran (Skor 1-5)", [
        "Kesesuaian RPS dengan pelaksanaan",
        "Penguasaan materi oleh dosen",
        "Metode pembelajaran interaktif",
        "Penggunaan media/teknologi",
        "Ketersediaan materi di LMS",
        "Waktu perkuliahan tepat waktu",
        "Penilaian objektif dan transparan",
        "Feedback atas tugas/ujian",
        "Kesediaan dosen untuk konsultasi",
        "Suasana kelas kondusif",
        "Kesesuaian materi dengan CPMK",
        "Penggunaan hasil penelitian dalam pembelajaran",
        "Penggunaan hasil PkM dalam pembelajaran",
        "Pelaksanaan pembelajaran sesuai jadwal",
        "Dosen menerima kritik dan saran",
        "Dosen memberikan umpan balik",
        "Manajemen kelas yang baik",
        "Motivasi dosen terhadap mahasiswa",
        "Keterlibatan mahasiswa dalam pembelajaran",
        "Pengelolaan waktu pembelajaran",
        "Pengakuan keterbatasan dosen",
        "Penilaian objektif",
        "Komitmen dosen terhadap perkuliahan",
        "Kualitas presentasi dosen",
        "Kesesuaian penilaian dengan rubrik",
      ]),
      tabelAspekSkor("C. Penilaian Layanan (Skor 1-5)", [
        "Layanan akademik (KRS, nilai)",
        "Layanan administrasi (KTM, transkrip)",
        "Layanan perpustakaan",
        "Layanan laboratorium",
        "Layanan WiFi/Internet",
        "Layanan keamanan & parkir",
        "Layanan kafetaria",
        "Layanan BAA/BAU/BAK",
        "Layanan konseling mahasiswa",
        "Layanan beasiswa",
        "Layanan pusat karir",
        "Layanan UKM dan organisasi mahasiswa",
        "Layanan fasilitas ibadah",
        "Layanan fasilitas olahraga",
        "Layanan sarana transportasi kampus",
        "Layanan ruang mahasiswa (student lounge)",
        "Layanan kebersihan kampus",
        "Layanan One-Stop Service",
        "Layanan aplikasi mobile",
        "Layanan helpdesk",
      ]),
      {
        title: "D. Saran dan Masukan",
        headers: ["Komponen", "Isian"],
        widths: [30, 70],
        rows: [
          ["Saran untuk dosen pengampu", ""],
          ["Saran untuk program studi", ""],
          ["Saran untuk universitas", ""],
          ["Komplain/pengaduan (jika ada)", ""],
        ],
      },
    ],
    tandaTangan: [
      { label: "Responden (Mahasiswa)", nama: "(Anonim)", jabatan: "Mahasiswa", nip: "" },
    ],
  },
  {
    nomor: 38,
    namaFormulir: "FORMULIR PERMOHONAN KOREKSI / BANDING NILAI",
    kodeFormulir: "FM-AKD-05",
    kategori: "FORM",
    matchStandar: "Standar Penilaian (SPN) - Pasal 25 Permen 39/2025",
    deskripsi: [
      "Formulir ini digunakan oleh mahasiswa untuk permohonan koreksi atau banding nilai, sesuai dengan SOP penilaian.",
    ],
    instruksi: "Isi formulir maksimal 7 hari kerja setelah pengumuman nilai.",
    fieldTables: [
      {
        title: "A. Identitas Mahasiswa",
        headers: ["Komponen", "Isian"],
        widths: [30, 70],
        rows: [
          ["Nama Mahasiswa", ""],
          ["NIM", ""],
          ["Program Studi", ""],
          ["Semester / Tahun Akademik", ""],
          ["No. HP/Email", ""],
        ],
      },
      {
        title: "B. Identitas Mata Kuliah",
        headers: ["Komponen", "Isian"],
        widths: [30, 70],
        rows: [
          ["Mata Kuliah", ""],
          ["Kode Mata Kuliah / SKS", ""],
          ["Dosen Pengampu", ""],
          ["Nilai yang Diberikan", ""],
          ["Nilai yang Diharapkan", ""],
        ],
      },
      {
        title: "C. Alasan Permohonan",
        headers: ["Komponen", "Isian"],
        widths: [30, 70],
        rows: [
          ["Jenis permohonan", "(Koreksi/Banding)"],
          ["Alasan (detail)", ""],
          ["Bukti pendukung (jika ada)", ""],
        ],
      },
      {
        title: "D. Proses Penanganan",
        headers: ["Tahap", "Tanggal", "Hasil", "Paraf"],
        widths: [35, 20, 30, 15],
        rows: [
          ["Diterima oleh Ka. Prodi", "", "", ""],
          ["Diteruskan ke Dosen Pengampu", "", "", ""],
          ["Respon Dosen Pengampu", "", "", ""],
          ["Keputusan Akhir", "", "", ""],
        ],
      },
    ],
    tandaTangan: [
      { label: "Mahasiswa Pemohon", nama: "(...........................)", jabatan: "Mahasiswa", nip: "NIM: ................" },
      { label: "Dosen Pengampu", nama: "(...........................)", jabatan: "Dosen", nip: "NIDN: ................" },
      { label: "Ka. Prodi", nama: "(...........................)", jabatan: "Ka. Prodi", nip: "NIDN: ................" },
    ],
  },
];

module.exports = { FORMULIR_LIST };
