// ============================================================
// DATA EXPANDED: 8 STANDAR PENELITIAN (12-15 indikator per standar)
// ============================================================

const {
  PJ_DEFAULT_AKADEMIK,
  PJ_DEFAULT_PENELITIAN,
  PJ_DEFAULT_PKM,
  PJ_DEFAULT_NONAKADEMIK,
  DOKUMEN_TERKAIT_DEFAULT,
} = require("./standar_mutu_data1.js");

// ============================================================
// 8 STANDAR PENELITIAN (EXPANDED)
// ============================================================
const STANDAR_PENELITIAN = [
  {
    namaStandar: "STANDAR LUARAN PENELITIAN",
    kodeStandar: "PEN-LRN",
    rasional: [
      "Standar Luaran Penelitian mengatur kriteria minimal hasil penelitian yang dihasilkan oleh perguruan tinggi. Luaran penelitian mencakup publikasi ilmiah, buku, paten, karya inovatif, dan teknologi tepat guna. Standar ini menjadi tolok ukur kualitas dan produktivitas penelitian Universitas Tulungagung, serta menjadi indikator utama bagi evaluasi eksternal dalam akreditasi.",
      "Universitas Tulungagung menargetkan peningkatan kuantitas dan kualitas luaran penelitian, khususnya publikasi pada jurnal terakreditasi nasional dan internasional bereputasi. Hal ini sejalan dengan sasaran strategis ke-4 Universitas Tulungagung, yaitu tercapainya kualitas dan kuantitas kegiatan penelitian berupa publikasi hasil penelitian pada jurnal terakreditasi nasional dan internasional. Peningkatan luaran penelitian juga menjadi indikator utama bagi BAN-PT/LAM dalam menilai kelayakan akreditasi program studi dan perguruan tinggi.",
      "Sesuai dengan Pasal 52-53 Permen 39 Tahun 2025, standar luaran penelitian mengatur kriteria minimal hasil penelitian yang dihasilkan oleh perguruan tinggi. Universitas Tulungagung memastikan bahwa setiap penelitian menghasilkan luaran yang terdokumentasi, baik berupa publikasi, paten, HKI, maupun karya inovatif lainnya. Setiap luaran didokumentasikan dalam sistem informasi LPPM dan PD Dikti, sehingga dapat dimonitor dan dilaporkan kepada pemangku kepentingan.",
      "Selain kuantitas, Universitas Tulungagung juga memperhatikan kualitas luaran penelitian. Kualitas diukur melalui tingkat akreditasi jurnal (SINTA 1-6, Scopus Q1-Q4, Web of Science), jumlah sitasi, dan adopsi hasil penelitian oleh masyarakat atau DUDI. Universitas Tulungagung mengembangkan ekosistem yang mendukung dosen untuk menghasilkan luaran penelitian yang tidak hanya banyak, tetapi juga berkualitas dan berdampak nyata.",
    ],
    pihakPJ: PJ_DEFAULT_PENELITIAN,
    definisi: [
      ["a.", "Luaran Penelitian", "hasil penelitian yang dapat berupa publikasi, paten, karya inovatif, atau teknologi tepat guna."],
      ["b.", "Publikasi Ilmiah", "karya tulis ilmiah yang dipublikasikan dalam jurnal, prosiding, atau buku."],
      ["c.", "Paten", "hak eksklusif atas invensi yang diberikan oleh negara untuk jangka waktu tertentu."],
      ["d.", "Hak Kekayaan Intelektual (HKI)", "hak eksklusif atas karya intelektual, mencakup paten, merek, hak cipta, desain industri."],
      ["e.", "Jurnal Terakreditasi", "jurnal yang telah terakreditasi SINTA 1-6 oleh Diktiristek."],
      ["f.", "Jurnal Internasional Bereputasi", "jurnal internasional yang terindeks Scopus atau Web of Science."],
      ["g.", "Teknologi Tepat Guna", "teknologi yang sesuai dengan kebutuhan dan kondisi masyarakat pengguna."],
      ["h.", "Sitasi", "kutipan terhadap publikasi oleh peneliti lain, indikator dampak penelitian."],
      ["i.", "SINTA", "Science and Technology Index, portal indeksasi jurnal nasional terakreditasi."],
    ],
    pernyataan: [
      "Setiap dosen wajib menghasilkan luaran penelitian minimal satu per tahun, berupa publikasi atau karya ilmiah lainnya.",
      "Universitas Tulungagung menargetkan peningkatan publikasi pada jurnal terakreditasi nasional (SINTA) dan internasional bereputasi (Scopus/WoS).",
      "Luaran penelitian didokumentasikan dalam sistem informasi LPPM dan PD Dikti, dengan metadata yang lengkap.",
      "Universitas Tulungagung mendorong pengajuan paten dan HKI atas hasil penelitian yang berpotensi komersialisasi.",
      "Luaran penelitian menjadi salah satu kriteria penilaian kinerja dosen dan promosi jabatan akademik.",
      "Universitas Tulungagung mengembangkan ekosistem publikasi yang mendukung dosen, mulai dari pelatihan, pendanaan, hingga mentoring.",
      "Universitas Tulungagung memberikan insentif bagi dosen yang mempublikasikan artikel di jurnal terakreditasi dan internasional bereputasi.",
      "Universitas Tulungagung mengembangkan jurnal universitas dengan target akreditasi SINTA, sebagai wadah publikasi dosen.",
      "Setiap penelitian wajib menghasilkan minimal satu luaran, sesuai dengan jenis dan tingkat penelitian.",
      "Luaran penelitian dievaluasi kualitasnya melalui tingkat akreditasi jurnal, jumlah sitasi, dan adopsi hasil.",
      "Universitas Tulungagung mendorong publikasi open access, sehingga hasil penelitian dapat diakses masyarakat luas.",
      "Luaran penelitian yang berpotensi komersial difasilitasi untuk komersialisasi melalui inkubator bisnis universitas.",
    ],
    strategi: [
      "Memberikan insentif bagi dosen yang mempublikasikan artikel di jurnal terakreditasi, dengan tingkat insentif berbeda untuk SINTA dan Scopus.",
      "Menyelenggarakan workshop penulisan artikel ilmiah berkala, dengan narasumber editor jurnal terakreditasi.",
      "Menyediakan dana hibah penelitian internal dengan skema kompetitif, sebagai pendamping hibah eksternal.",
      "Mengembangkan kerja sama dengan jurnal-jurnal terakreditasi untuk memfasilitasi publikasi dosen.",
      "Mengintegrasikan sistem informasi LPPM dengan PD Dikti untuk dokumentasi luaran secara real-time.",
      "Menyediakan dana page charges untuk publikasi di jurnal internasional bereputasi (Scopus/WoS).",
      "Mengembangkan jurnal universitas dengan target akreditasi SINTA, dengan editorial board profesional.",
      "Memberikan pendampingan pengajuan paten dan HKI, melalui kerja sama dengan konsultan HKI profesional.",
    ],
    indikator: [
      { indikator: "Jumlah publikasi jurnal per tahun", strategi: "Insentif & workshop", unit: "LPPM", baseline: 150, target: [220, 300, 400, 520, 650] },
      { indikator: "Jumlah publikasi jurnal internasional bereputasi (Scopus/WoS)", strategi: "Pendanaan page charges", unit: "LPPM", baseline: 20, target: [35, 55, 80, 110, 145] },
      { indikator: "Jumlah publikasi jurnal SINTA 1-3 per tahun", strategi: "Insentif", unit: "LPPM", baseline: 30, target: [50, 75, 105, 140, 180] },
      { indikator: "Jumlah paten yang diajukan per tahun", strategi: "Pendampingan HKI", unit: "LPPM", baseline: 3, target: [6, 10, 15, 22, 30] },
      { indikator: "Jumlah paten granted per tahun", strategi: "Kualitas penelitian", unit: "LPPM", baseline: 1, target: [2, 4, 7, 10, 15] },
      { indikator: "Jumlah buku/textbook per tahun", strategi: "Hibah buku", unit: "LPPM", baseline: 8, target: [12, 18, 25, 32, 40] },
      { indikator: "Persentase dosen dengan publikasi per tahun", strategi: "SKP & insentif", unit: "LPPM", baseline: 35, target: [45, 55, 65, 75, 85] },
      { indikator: "Jumlah sitasi publikasi per tahun", strategi: "Diseminasi & open access", unit: "LPPM", baseline: 200, target: [350, 550, 800, 1100, 1500] },
      { indikator: "Jumlah HKI lainnya (hak cipta, merek) per tahun", strategi: "Sosialisasi", unit: "LPPM", baseline: 10, target: [18, 28, 40, 55, 70] },
      { indikator: "Jumlah penelitian dengan luaran terdokumentasi", strategi: "Monitoring", unit: "LPPM", baseline: 80, target: [110, 150, 200, 260, 320] },
      { indikator: "Persentase luaran terintegrasi PD Dikti", strategi: "IT integration", unit: "UPT SI", baseline: 70, target: [85, 95, 100, 100, 100] },
      { indikator: "Jumlah workshop penulisan artikel per tahun", strategi: "Program diklat", unit: "LPPM", baseline: 5, target: [8, 12, 18, 25, 32] },
      { indikator: "Jumlah publikasi open access per tahun", strategi: "Open access mandate", unit: "LPPM", baseline: 30, target: [55, 85, 120, 160, 200] },
      { indikator: "Jumlah luaran dikomersialisasi", strategi: "Inkubator bisnis", unit: "LPPM", baseline: 2, target: [4, 8, 14, 22, 32] },
      { indikator: "Pendapatan dari komersialisasi luaran (Rp juta)", strategi: "Kerjasama DUDI", unit: "BAKU", baseline: 10, target: [25, 60, 120, 220, 380] },
    ],
    dokumenTerkait: DOKUMEN_TERKAIT_DEFAULT,
  },
  {
    namaStandar: "STANDAR PROSES PENELITIAN",
    kodeStandar: "PEN-PRS",
    rasional: [
      "Standar Proses Penelitian mengatur kriteria minimal pelaksanaan penelitian, mulai dari perencanaan, pelaksanaan, hingga pelaporan. Standar ini memastikan bahwa penelitian di Universitas Tulungagung dilaksanakan secara sistematis, etis, dan akuntabel. Proses penelitian yang baik menjadi prasyarat bagi dihasilkannya luaran penelitian yang bermutu dan berdampak.",
      "Universitas Tulungagung menerapkan mekanisme penelitian yang terstruktur, mulai dari pengajuan proposal, review, pelaksanaan, monitoring, hingga pelaporan akhir. Setiap tahapan didokumentasikan secara sistematis, dan dosen peneliti wajib mematuhi etika penelitian dan prinsip-prinsip penelitian yang baik. Mekanisme ini sejalan dengan Pasal 54-55 Permen 39 Tahun 2025 yang mengatur standar proses penelitian.",
      "Setiap penelitian di Universitas Tulungagung diawali dengan pengajuan proposal yang memuat latar belakang, tujuan, metode, jadwal, dan anggaran. Proposal direview oleh reviewer internal atau eksternal untuk menilai kelayakan dan kualitas. Penelitian yang disetujui dilaksanakan sesuai jadwal, dengan monitoring oleh LPPM. Setelah selesai, peneliti wajib menyusun laporan akhir dan laporan keuangan, serta mempublikasikan hasil penelitian.",
      "Universitas Tulungagung juga menerapkan prinsip-prinsip etika penelitian, termasuk integritas akademik, perlindungan subjek penelitian, dan pengelolaan data yang transparan. Setiap penelitian yang melibatkan manusia atau hewan wajib memperoleh persetujuan etik dari komisi etik penelitian. Pelanggaran etika penelitian dapat berdampak pada sanksi akademik dan administratif, sehingga Universitas Tulungagung memastikan bahwa seluruh dosen memahami dan mematuhi prinsip-prinsip etika.",
    ],
    pihakPJ: PJ_DEFAULT_PENELITIAN,
    definisi: [
      ["a.", "Proposal Penelitian", "dokumen rencana penelitian yang memuat latar belakang, tujuan, metode, jadwal, dan anggaran."],
      ["b.", "Review Proposal", "proses penilaian proposal oleh reviewer untuk menilai kelayakan dan kualitas penelitian."],
      ["c.", "Monitoring", "kegiatan pengawasan dan pendampingan selama pelaksanaan penelitian."],
      ["d.", "Laporan Akhir", "dokumen yang berisi hasil pelaksanaan penelitian dan luaran yang dihasilkan."],
      ["e.", "Laporan Kemajuan", "laporan periodik tentang kemajuan pelaksanaan penelitian."],
      ["f.", "Etika Penelitian", "prinsip-prinsip etis dalam pelaksanaan penelitian, mencakup integritas, perlindungan subjek, transparansi."],
      ["g.", "Komitmen Etik", "persetujuan dari komisi etik penelitian untuk penelitian yang melibatkan manusia atau hewan."],
      ["h.", "Reviewer", "ahli yang menilai kelayakan dan kualitas proposal penelitian."],
      ["i.", "Hibah Penelitian", "dana yang diberikan untuk pelaksanaan penelitian, dari internal atau eksternal."],
    ],
    pernyataan: [
      "Setiap penelitian diawali dengan pengajuan proposal yang memuat latar belakang, tujuan, metode, jadwal, dan anggaran.",
      "Proposal penelitian direview oleh reviewer internal atau eksternal untuk menilai kelayakan dan kualitas, dengan minimal 2 reviewer per proposal.",
      "Pelaksanaan penelitian mengikuti etika penelitian dan prinsip-prinsip penelitian yang baik, dengan dokumentasi yang sistematis.",
      "LPPM melakukan monitoring berkala terhadap pelaksanaan penelitian, minimal 1 kali selama masa penelitian.",
      "Peneliti wajib menyusun laporan kemajuan (progress report) minimal 1 kali selama masa penelitian, dan laporan akhir setelah selesai.",
      "Peneliti wajib menyusun laporan keuangan yang sesuai dengan standar akuntansi, sebagai bentuk akuntabilitas.",
      "Setiap penelitian yang melibatkan manusia atau hewan wajib memperoleh persetujuan etik dari komisi etik penelitian.",
      "Seluruh proses penelitian didokumentasikan dalam sistem informasi LPPM, dengan akses untuk monitoring.",
      "Universitas Tulungagung menerapkan prinsip-prinsip integritas akademik, dengan sanksi tegas bagi pelanggaran.",
      "Peneliti wajib mempublikasikan hasil penelitian minimal 1 publikasi per penelitian, sebagai bentuk diseminasi.",
      "Penelitian yang dibiayai hibah eksternal mengikuti ketentuan dari pemberi hibah, dengan adaptasi ke standar Universitas Tulungagung.",
      "Universitas Tulungagung menyediakan dukungan administratif bagi peneliti, sehingga peneliti dapat fokus pada substansi penelitian.",
    ],
    strategi: [
      "Menyusun panduan penelitian yang jelas dan mudah diakses oleh dosen, dengan template proposal dan laporan.",
      "Mengembangkan sistem informasi LPPM terintegrasi untuk pengelolaan proposal hingga laporan, dengan workflow digital.",
      "Menyelenggarakan workshop penulisan proposal bagi dosen muda, dengan narasumber peneliti berpengalaman.",
      "Membentuk tim reviewer internal yang kompeten dan independen, dengan pelatihan reviewer berkala.",
      "Melakukan monitoring lapangan untuk penelitian yang memerlukan verifikasi, minimal 1 kali selama masa penelitian.",
      "Membentuk komisi etik penelitian yang aktif, dengan SOP review etik yang jelas dan timeline yang tertib.",
      "Menyediakan dukungan administratif (keuangan, logistik) bagi peneliti, sehingga beban administratif berkurang.",
      "Melakukan evaluasi tahunan terhadap kinerja tim reviewer dan komisi etik, untuk peningkatan kualitas.",
    ],
    indikator: [
      { indikator: "Persentase proposal dengan dokumentasi lengkap", strategi: "Audit", unit: "LPPM", baseline: 75, target: [88, 95, 100, 100, 100] },
      { indikator: "Persentase penelitian dengan laporan akhir tepat waktu", strategi: "Monitoring", unit: "LPPM", baseline: 70, target: [82, 92, 100, 100, 100] },
      { indikator: "Jumlah penelitian dengan monitoring lapangan", strategi: "Pendampingan", unit: "LPPM", baseline: 30, target: [45, 65, 90, 120, 155] },
      { indikator: "Persentase penelitian sesuai etika", strategi: "Komisi etik", unit: "LPPM", baseline: 85, target: [93, 98, 100, 100, 100] },
      { indikator: "Jumlah reviewer internal bersertifikat", strategi: "Pelatihan reviewer", unit: "LPPM", baseline: 15, target: [25, 38, 55, 75, 95] },
      { indikator: "Persentase penelitian dengan laporan kemajuan", strategi: "Monitoring", unit: "LPPM", baseline: 65, target: [78, 88, 95, 100, 100] },
      { indikator: "Jumlah workshop penulisan proposal per tahun", strategi: "Program diklat", unit: "LPPM", baseline: 4, target: [8, 12, 18, 25, 32] },
      { indikator: "Persentase proposal direview tepat waktu", strategi: "SOP review", unit: "LPPM", baseline: 70, target: [85, 95, 100, 100, 100] },
      { indikator: "Jumlah komisi etik yang aktif", strategi: "Penguatan kelembagaan", unit: "LPPM", baseline: 1, target: [1, 2, 2, 3, 3] },
      { indikator: "Persentase penelitian dengan publikasi hasil", strategi: "Monitoring", unit: "LPPM", baseline: 75, target: [85, 92, 97, 100, 100] },
      { indikator: "Jumlah pelatihan reviewer per tahun", strategi: "Program diklat", unit: "LPPM", baseline: 2, target: [4, 6, 10, 14, 18] },
      { indikator: "Persentase penelitian dengan laporan keuangan sesuai standar", strategi: "Audit keuangan", unit: "SPI", baseline: 70, target: [82, 92, 98, 100, 100] },
      { indikator: "Jumlah dukungan administratif untuk peneliti", strategi: "Penguatan SDM", unit: "LPPM", baseline: 3, target: [5, 8, 12, 16, 22] },
      { indikator: "Tingkat kepuasan peneliti terhadap layanan LPPM", strategi: "Survey", unit: "PPM", baseline: 65, target: [75, 84, 90, 95, 98] },
      { indikator: "Persentase penelitian hibah eksternal sesuai ketentuan", strategi: "Compliance monitoring", unit: "LPPM", baseline: 80, target: [90, 96, 100, 100, 100] },
    ],
    dokumenTerkait: DOKUMEN_TERKAIT_DEFAULT,
  },
  {
    namaStandar: "STANDAR MASUKAN PENELITIAN",
    kodeStandar: "PEN-MSK",
    rasional: [
      "Standar Masukan Penelitian mengatur kriteria minimal sumber daya yang diperlukan untuk pelaksanaan penelitian, mencakup pendanaan, SDM, sarana prasarana, dan sistem informasi. Standar ini memastikan bahwa penelitian di Universitas Tulungagung didukung oleh sumber daya yang memadai untuk menghasilkan luaran yang bermutu. Sesuai Pasal 56 Permen 39 Tahun 2025, standar masukan penelitian mengatur kriteria minimal sumber daya termasuk pendanaan, SDM, sarana, dan sistem informasi.",
      "Universitas Tulungagung berkomitmen untuk menyediakan sumber daya penelitian yang memadai, melalui alokasi anggaran internal, pengembangan SDM, investasi sarana prasarana, dan pengembangan sistem informasi. Universitas Tulungagung juga aktif mencari pendanaan eksternal dari Diktiristek, DUDI, dan lembaga internasional. Pendanaan eksternal menjadi indikator kemandirian dan reputasi penelitian perguruan tinggi.",
      "Selain pendanaan, SDM penelitian juga menjadi masukan kritis. Universitas Tulungagung memastikan bahwa setiap peneliti memiliki kualifikasi dan kompetensi yang sesuai dengan bidang penelitian, serta mendapat pelatihan metodologi penelitian secara berkala. Universitas Tulungagung juga mengembangkan laboratorium riset dengan peralatan terkini, sebagai sarana penelitian yang memadai.",
      "Sistem informasi penelitian yang terintegrasi dengan PD Dikti menjadi sarana penting untuk pengelolaan data penelitian. Universitas Tulungagung mengembangkan sistem informasi LPPM yang terintegrasi, dengan modul pengelolaan proposal, monitoring, laporan, dan dokumentasi luaran. Sistem ini memungkinkan monitoring real-time dan pelaporan yang akurat kepada pimpinan dan pemangku kepentingan.",
    ],
    pihakPJ: PJ_DEFAULT_PENELITIAN,
    definisi: [
      ["a.", "Pendanaan Penelitian", "dana yang dialokasikan untuk pelaksanaan penelitian, dari internal atau eksternal."],
      ["b.", "Peneliti", "dosen atau tim dosen yang melaksanakan penelitian, dengan kualifikasi sesuai bidang."],
      ["c.", "Sarana Penelitian", "peralatan dan fasilitas untuk pelaksanaan penelitian, termasuk laboratorium dan instrumen."],
      ["d.", "Sistem Informasi Penelitian", "platform digital untuk pengelolaan data dan informasi penelitian."],
      ["e.", "Hibah Eksternal", "pendanaan penelitian dari sumber eksternal (Diktiristek, DUDI, lembaga internasional)."],
      ["f.", "Hibah Internal", "pendanaan penelitian dari anggaran Universitas Tulungagung."],
      ["g.", "Laboratorium Riset", "laboratorium khusus untuk penelitian, dengan peralatan terkini."],
      ["h.", "Kompetensi Peneliti", "kualifikasi dan keterampilan peneliti, termasuk metodologi dan analisis data."],
      ["i.", "Sumber Daya Penelitian", "keseluruhan masukan untuk pelaksanaan penelitian: dana, SDM, sarana, informasi."],
    ],
    pernyataan: [
      "Universitas Tulungagung mengalokasikan dana penelitian internal minimal 10% dari anggaran tahunan.",
      "Universitas Tulungagung aktif mencari pendanaan eksternal dari Diktiristek, DUDI, dan lembaga internasional.",
      "Setiap peneliti memiliki kualifikasi dan kompetensi yang sesuai dengan bidang penelitian, dengan pelatihan metodologi berkala.",
      "Universitas Tulungagung menyediakan sarana penelitian yang memadai, termasuk laboratorium riset dan peralatan terkini.",
      "Sistem informasi LPPM terintegrasi dengan PD Dikti untuk pengelolaan data penelitian secara real-time.",
      "Universitas Tulungagung mengembangkan SDM penelitian melalui pelatihan metodologi, analisis data, dan penulisan ilmiah.",
      "Universitas Tulungagung menyediakan akses ke database jurnal internasional dan perangkat lunak analisis data.",
      "Universitas Tulungagung mengembangkan laboratorium riset dengan peralatan terkini, melalui investasi tahunan.",
      "Sistem informasi LPPM mencakup modul pengelolaan proposal, monitoring, laporan, dan dokumentasi luaran.",
      "Universitas Tulungagung menyediakan dukungan administratif bagi peneliti, sehingga beban administratif berkurang.",
      "Universitas Tulungagung mengembangkan kerja sama dengan lembaga penelitian eksternal untuk berbagi sumber daya.",
      "Universitas Tulungagung menargetkan peningkatan pendanaan eksternal setiap tahun, sebagai indikator reputasi penelitian.",
    ],
    strategi: [
      "Meningkatkan alokasi anggaran penelitian internal secara bertahap, dengan target 15% dari anggaran tahunan pada 2030.",
      "Membentuk tim khusus untuk pencarian pendanaan eksternal, dengan target proposal hibah setiap tahun.",
      "Mengembangkan laboratorium riset dengan peralatan terkini, melalui investasi tahunan dan kerja sama DUDI.",
      "Menyelenggarakan pelatihan metodologi penelitian, analisis data, dan penulisan ilmiah bagi dosen peneliti.",
      "Mengintegrasikan sistem informasi LPPM dengan PD Dikti, untuk pengelolaan data penelitian secara real-time.",
      "Menyediakan akses ke database jurnal internasional (Scopus, Web of Science, ScienceDirect) dan perangkat lunak analisis.",
      "Mengembangkan kerja sama dengan lembaga penelitian eksternal (BRIN, LIPI, DUDI) untuk berbagi sumber daya.",
      "Menyediakan dukungan administratif (keuangan, logistik, perjalanan) bagi peneliti, dengan SDM khusus.",
    ],
    indikator: [
      { indikator: "Pendanaan penelitian internal (Rp juta/tahun)", strategi: "Alokasi anggaran", unit: "BAKU", baseline: 500, target: [750, 1050, 1450, 1950, 2500] },
      { indikator: "Pendanaan penelitian eksternal (Rp juta/tahun)", strategi: "Pencarian hibah", unit: "LPPM", baseline: 300, target: [550, 900, 1400, 2000, 2800] },
      { indikator: "Jumlah peneliti aktif per tahun", strategi: "Pendampingan", unit: "LPPM", baseline: 80, target: [110, 145, 185, 230, 280] },
      { indikator: "Persentase laboratorium dengan peralatan standar", strategi: "Investasi", unit: "UPPS", baseline: 70, target: [80, 88, 94, 98, 100] },
      { indikator: "Persentase data penelitian terintegrasi PD Dikti", strategi: "IT integration", unit: "UPT SI", baseline: 60, target: [78, 90, 97, 100, 100] },
      { indikator: "Jumlah pelatihan metodologi per tahun", strategi: "Program diklat", unit: "LPPM", baseline: 4, target: [8, 14, 22, 32, 42] },
      { indikator: "Jumlah akses database jurnal internasional", strategi: "Investasi", unit: "UPT Perpus", baseline: 5, target: [8, 12, 16, 20, 25] },
      { indikator: "Jumlah kerjasama dengan lembaga penelitian eksternal", strategi: "Networking", unit: "LPPM", baseline: 5, target: [10, 18, 28, 40, 55] },
      { indikator: "Jumlah proposal hibah eksternal diajukan per tahun", strategi: "Tim khusus", unit: "LPPM", baseline: 25, target: [40, 60, 85, 115, 150] },
      { indikator: "Persentase proposal hibah yang disetujui", strategi: "Kualitas proposal", unit: "LPPM", baseline: 40, target: [50, 60, 70, 78, 85] },
      { indikator: "Jumlah SDM dukungan administratif penelitian", strategi: "Penguatan SDM", unit: "LPPM", baseline: 3, target: [5, 8, 12, 16, 22] },
      { indikator: "Persentase peneliti dengan kompetensi metodologi baik", strategi: "Pelatihan", unit: "LPPM", baseline: 65, target: [75, 84, 92, 97, 100] },
      { indikator: "Jumlah perangkat lunak analisis data tersedia", strategi: "Investasi", unit: "UPT SI", baseline: 5, target: [8, 12, 18, 25, 32] },
      { indikator: "Tingkat kepuasan peneliti terhadap sarana penelitian", strategi: "Survey", unit: "PPM", baseline: 65, target: [74, 82, 88, 93, 96] },
      { indikator: "Persentase laboratorium riset dengan SOTK dan SOP", strategi: "Dokumentasi", unit: "LPPM", baseline: 60, target: [75, 88, 96, 100, 100] },
    ],
    dokumenTerkait: DOKUMEN_TERKAIT_DEFAULT,
  },
  {
    namaStandar: "STANDAR HASIL PENELITIAN",
    kodeStandar: "PEN-HSL",
    rasional: [
      "Standar Hasil Penelitian mengatur kriteria minimal kualitas hasil penelitian yang dihasilkan oleh Universitas Tulungagung. Hasil penelitian yang baik harus orisinal, bermutu, dan berdampak bagi pengembangan IPTEK dan kesejahteraan masyarakat. Standar ini berbeda dengan Standar Luaran yang lebih fokus pada produk publikasi, karena Standar Hasil fokus pada substansi kontribusi penelitian.",
      "Universitas Tulungagung mendorong dosen untuk menghasilkan penelitian yang tidak hanya publikasi, tetapi juga memberikan kontribusi nyata bagi pengembangan ilmu dan masyarakat. Hal ini sejalan dengan sasaran strategis ke-5 Universitas Tulungagung, yaitu menghasilkan produk unggulan berbasis Teknologi Tepat Guna yang berdampak untuk kesejahteraan masyarakat. Hasil penelitian yang berdampak menjadi indikator utama reputasi perguruan tinggi.",
      "Hasil penelitian dapat berupa: (a) kontribusi teoretis terhadap pengembangan ilmu; (b) inovasi teknologi atau metode baru; (c) produk/jasa yang dapat dimanfaatkan masyarakat; (d) kebijakan publik yang dipengaruhi; atau (e) pengembangan kurikulum dan pembelajaran. Universitas Tulungagung memastikan bahwa setiap penelitian menghasilkan minimal satu bentuk kontribusi tersebut, dengan dokumentasi yang sistematis.",
      "Universitas Tulungagung juga mengembangkan mekanisme evaluasi dampak penelitian, melalui tracer study penelitian (pelacakan adopsi hasil), survey pengguna, dan analisis sitasi. Hasil evaluasi menjadi basis bagi perbaikan strategi penelitian, dan dilaporkan kepada pimpinan dalam RTM tahunan. Universitas Tulungagung juga mengembangkan inkubator bisnis untuk mengfasilitasi komersialisasi hasil penelitian yang berpotensi.",
    ],
    pihakPJ: PJ_DEFAULT_PENELITIAN,
    definisi: [
      ["a.", "Hasil Penelitian", "substansi kontribusi penelitian terhadap pengembangan IPTEK atau kesejahteraan masyarakat."],
      ["b.", "Orisinalitas", "kebaruan hasil penelitian dibandingkan dengan penelitian sebelumnya."],
      ["c.", "Dampak", "kontribusi penelitian terhadap pengembangan ilmu, masyarakat, atau industri."],
      ["d.", "Teknologi Tepat Guna", "teknologi yang sesuai dengan kebutuhan dan kondisi masyarakat pengguna."],
      ["e.", "Inovasi", "penemuan baru yang memberikan solusi atas masalah eksisting."],
      ["f.", "Kontribusi Teoretis", "sumbangan penelitian terhadap pengembangan teori dalam suatu bidang ilmu."],
      ["g.", "Tracer Study Penelitian", "studi pelacakan adopsi hasil penelitian oleh pengguna."],
      ["h.", "Inkubator Bisnis", "lembaga yang memfasilitasi komersialisasi hasil penelitian."],
      ["i.", "Adopsi Hasil", "penggunaan hasil penelitian oleh masyarakat, DUDI, atau pemerintah."],
    ],
    pernyataan: [
      "Hasil penelitian harus orisinal dan memberikan kontribusi terhadap pengembangan IPTEK atau kesejahteraan masyarakat.",
      "Universitas Tulungagung mendorong penelitian yang berdampak bagi masyarakat dan industri, dengan dokumentasi dampak.",
      "Hasil penelitian didokumentasikan dalam bentuk laporan akhir, publikasi, atau karya inovatif.",
      "Universitas Tulungagung mendorong komersialisasi hasil penelitian yang berpotensi melalui inkubator bisnis.",
      "Hasil penelitian menjadi bahan bagi pengembangan kurikulum dan pembelajaran melalui research-based learning.",
      "Universitas Tulungagung melakukan tracer study penelitian untuk melacak adopsi hasil oleh pengguna.",
      "Hasil penelitian yang berdampak mendapat apresiasi melalui award tahunan, sebagai motivasi dosen.",
      "Universitas Tulungagung mengembangkan mekanisme evaluasi dampak penelitian, dengan indikator yang terukur.",
      "Hasil penelitian yang berpotensi komersial difasilitasi untuk pengajuan paten dan HKI.",
      "Universitas Tulungagung mengembangkan kerja sama dengan DUDI untuk mengidentifikasi hasil penelitian yang berpotensi komersialisasi.",
      "Hasil penelitian dilaporkan kepada pimpinan dalam RTM tahunan, dengan analisis dampak.",
      "Universitas Tulungagung mengintegrasikan hasil penelitian dalam pembelajaran, sehingga mahasiswa terpapar pada riset terkini.",
    ],
    strategi: [
      "Menyelenggarakan forum diskusi hasil penelitian setiap semester, dengan presentasi dan diskusi.",
      "Mengembangkan inkubator bisnis untuk komersialisasi hasil penelitian, dengan dukungan mentoring dan pendanaan.",
      "Mengintegrasikan hasil penelitian dalam pembelajaran melalui research-based learning, sehingga mahasiswa terlibat.",
      "Mengundang DUDI untuk mengidentifikasi hasil penelitian yang berpotensi komersialisasi.",
      "Mengembangkan sistem informasi untuk dokumentasi hasil penelitian, dengan database yang dapat dicari.",
      "Melakukan tracer study penelitian setiap 2 tahun, untuk melacak adopsi hasil oleh pengguna.",
      "Memberikan award tahunan bagi hasil penelitian berdampak, sebagai apresiasi dan motivasi.",
      "Mengembangkan kerja sama dengan DUDI untuk pengembangan produk berbasis hasil penelitian.",
    ],
    indikator: [
      { indikator: "Jumlah hasil penelitian yang dikomersialisasi per tahun", strategi: "Inkubator bisnis", unit: "LPPM", baseline: 2, target: [5, 9, 16, 25, 36] },
      { indikator: "Jumlah Teknologi Tepat Guna yang dihasilkan", strategi: "Hibah TTG", unit: "LPPM", baseline: 10, target: [18, 28, 42, 60, 80] },
      { indikator: "Jumlah sitasi publikasi per tahun", strategi: "Diseminasi", unit: "LPPM", baseline: 200, target: [350, 550, 800, 1100, 1500] },
      { indikator: "Jumlah penelitian yang diintegrasikan ke kurikulum", strategi: "RBL", unit: "UPPS", baseline: 25, target: [45, 70, 100, 135, 175] },
      { indikator: "Tingkat adopsi hasil penelitian oleh masyarakat/industri", strategi: "Diseminasi", unit: "LPPM", baseline: 30, target: [42, 58, 75, 88, 98] },
      { indikator: "Jumlah forum diskusi hasil penelitian per tahun", strategi: "Forum ilmiah", unit: "LPPM", baseline: 4, target: [8, 14, 22, 32, 42] },
      { indikator: "Jumlah award hasil penelitian berdampak per tahun", strategi: "Reward system", unit: "Rektor", baseline: 3, target: [6, 10, 16, 24, 32] },
      { indikator: "Jumlah tracer study penelitian per 2 tahun", strategi: "Tracer study", unit: "LPPM", baseline: 1, target: [2, 2, 3, 3, 4] },
      { indikator: "Persentase penelitian dengan dokumentasi dampak", strategi: "Sistem informasi", unit: "LPPM", baseline: 50, target: [65, 78, 88, 95, 100] },
      { indikator: "Jumlah kerjasama DUDI untuk pengembangan produk", strategi: "Networking", unit: "LPPM", baseline: 5, target: [10, 18, 30, 45, 65] },
      { indikator: "Jumlah inovasi yang dihasilkan per tahun", strategi: "Hibah inovasi", unit: "LPPM", baseline: 8, target: [15, 25, 38, 55, 75] },
      { indikator: "Jumlah kebijakan publik yang dipengaruhi", strategi: "Policy brief", unit: "LPPM", baseline: 2, target: [4, 7, 12, 18, 25] },
      { indikator: "Persentase hasil penelitian terintegrasi pembelajaran", strategi: "RBL integration", unit: "UPPS", baseline: 30, target: [42, 55, 70, 85, 95] },
      { indikator: "Jumlah produk hasil penelitian yang dipasarkan", strategi: "Komersialisasi", unit: "LPPM", baseline: 1, target: [3, 6, 10, 16, 24] },
      { indikator: "Tingkat kepuasan pengguna terhadap hasil penelitian", strategi: "Survey", unit: "LPPM", baseline: 70, target: [78, 85, 90, 94, 97] },
    ],
    dokumenTerkait: DOKUMEN_TERKAIT_DEFAULT,
  },
  {
    namaStandar: "STANDAR PUBLIKASI ILMIAH PENELITIAN",
    kodeStandar: "PEN-PUB",
    rasional: [
      "Standar Publikasi Ilmiah Penelitian mengatur kriteria minimal publikasi hasil penelitian. Publikasi menjadi sarana diseminasi pengetahuan dan indikator utama produktivitas ilmiah perguruan tinggi. Universitas Tulungagung menargetkan peningkatan publikasi pada jurnal terakreditasi nasional dan internasional bereputasi, sebagaimana tertuang dalam sasaran strategis ke-4.",
      "Universitas Tulungagung menyadari bahwa publikasi yang bermutu memerlukan dukungan sistemik—mulai dari pendanaan, pelatihan, hingga akses jurnal. Oleh karena itu, Universitas Tulungagung mengembangkan ekosistem publikasi yang mendukung dosen untuk mempublikasikan hasil penelitiannya pada jurnal-jurnal berkualitas. Ekosistem ini mencakup insentif publikasi, pendanaan page charges, pelatihan penulisan, dan akses ke database jurnal.",
      "Publikasi diukur kualitasnya melalui tingkat akreditasi jurnal: SINTA 1-6 untuk jurnal nasional, dan Scopus/WoS untuk jurnal internasional. Universitas Tulungagung menargetkan peningkatan publikasi pada SINTA 1-3 dan Scopus Q1-Q2, sebagai indikator kualitas. Selain itu, Universitas Tulungagung juga mengembangkan jurnal universitas dengan target akreditasi SINTA, sebagai wadah publikasi dosen.",
      "Universitas Tulungagung juga mendorong publikasi open access, sehingga hasil penelitian dapat diakses masyarakat luas dan memberikan dampak yang lebih besar. Selain itu, Universitas Tulungagung juga mendorong publikasi pada prosiding seminar internasional bereputasi, sebagai sarana diseminasi dan networking dengan akademisi internasional.",
    ],
    pihakPJ: PJ_DEFAULT_PENELITIAN,
    definisi: [
      ["a.", "Publikasi Ilmiah", "karya tulis ilmiah yang dipublikasikan dalam jurnal, prosiding, atau buku."],
      ["b.", "Jurnal Terakreditasi", "jurnal yang terakreditasi SINTA 1-6 oleh Diktiristek."],
      ["c.", "Jurnal Internasional Bereputasi", "jurnal internasional yang terindeks Scopus atau Web of Science."],
      ["d.", "Prosiding", "kumpulan makalah yang dipresentasikan dalam seminar ilmiah dan diterbitkan."],
      ["e.", "Page Charges", "biaya publikasi yang dibebankan kepada penulis oleh jurnal open access."],
      ["f.", "Open Access", "model publikasi yang memberikan akses gratis kepada pembaca."],
      ["g.", "SINTA", "Science and Technology Index, portal indeksasi jurnal nasional terakreditasi."],
      ["h.", "Scopus", "database abstrak dan sitasi jurnal internasional milik Elsevier."],
      ["i.", "Editorial Board", "tim editor yang mengelola jurnal ilmiah, bertanggung jawab atas kualitas publikasi."],
    ],
    pernyataan: [
      "Setiap penelitian wajib menghasilkan publikasi ilmiah minimal satu artikel, sesuai dengan jenis dan tingkat penelitian.",
      "Universitas Tulungagung menargetkan publikasi pada jurnal terakreditasi SINTA dan internasional bereputasi (Scopus/WoS).",
      "Publikasi didokumentasikan dalam sistem informasi LPPM dan PD Dikti, dengan metadata lengkap.",
      "Universitas Tulungagung menyediakan dana pendukung publikasi (page charges) bagi dosen, khususnya untuk jurnal internasional.",
      "Universitas Tulungagung mendorong publikasi pada prosiding seminar internasional bereputasi.",
      "Universitas Tulungagung mengembangkan jurnal universitas dengan target akreditasi SINTA, sebagai wadah publikasi dosen.",
      "Universitas Tulungagung mendorong publikasi open access, sehingga hasil penelitian dapat diakses masyarakat luas.",
      "Universitas Tulungagung menyediakan akses ke database jurnal internasional (Scopus, Web of Science, ScienceDirect).",
      "Setiap publikasi wajib mematuhi etika publikasi, mencakup orisinalitas, sitasi yang benar, dan tidak adanya plagiarisme.",
      "Universitas Tulungagung memberikan insentif bagi dosen yang mempublikasikan artikel di jurnal terakreditasi dan internasional.",
      "Universitas Tulungagung menargetkan peningkatan publikasi pada SINTA 1-3 dan Scopus Q1-Q2, sebagai indikator kualitas.",
      "Publikasi dipublikasikan dalam repository universitas, sehingga dapat diakses masyarakat luas.",
    ],
    strategi: [
      "Menyediakan dana page charges untuk publikasi di jurnal internasional bereputasi, dengan SOP yang jelas.",
      "Menyelenggarakan workshop penulisan artikel ilmiah berkala, dengan narasumber editor jurnal terakreditasi.",
      "Mengembangkan jurnal universitas dengan target akreditasi SINTA, dengan editorial board profesional.",
      "Mengundang editor jurnal untuk memberikan pelatihan kepada dosen, sebagai bagian dari capacity building.",
      "Mengembangkan sistem informasi publikasi yang terintegrasi dengan PD Dikti, untuk dokumentasi real-time.",
      "Memberikan insentif bagi dosen yang mempublikasikan di SINTA 1-3 dan Scopus Q1-Q2, dengan tingkat insentif berbeda.",
      "Menyediakan akses ke database jurnal internasional (Scopus, Web of Science, ScienceDirect, IEEE, Springer).",
      "Mengembangkan repository universitas dengan Open Journal System (OJS), untuk publikasi open access.",
    ],
    indikator: [
      { indikator: "Jumlah publikasi jurnal SINTA 1-3 per tahun", strategi: "Insentif", unit: "LPPM", baseline: 30, target: [50, 75, 105, 140, 180] },
      { indikator: "Jumlah publikasi Scopus/Web of Science per tahun", strategi: "Pendanaan page charges", unit: "LPPM", baseline: 15, target: [28, 45, 68, 95, 125] },
      { indikator: "Jumlah prosiding seminar internasional per tahun", strategi: "Hibat", unit: "LPPM", baseline: 40, target: [60, 85, 115, 150, 190] },
      { indikator: "Persentase penelitian dengan publikasi", strategi: "Monitoring", unit: "LPPM", baseline: 75, target: [85, 92, 97, 100, 100] },
      { indikator: "Jumlah dosen dengan publikasi internasional per tahun", strategi: "Pendampingan", unit: "LPPM", baseline: 25, target: [42, 65, 92, 125, 160] },
      { indikator: "Jumlah publikasi open access per tahun", strategi: "Open access mandate", unit: "LPPM", baseline: 25, target: [45, 75, 110, 155, 200] },
      { indikator: "Jumlah workshop penulisan artikel per tahun", strategi: "Program diklat", unit: "LPPM", baseline: 5, target: [10, 16, 24, 34, 45] },
      { indikator: "Jumlah akses database jurnal internasional", strategi: "Investasi", unit: "UPT Perpus", baseline: 5, target: [8, 12, 16, 20, 25] },
      { indikator: "Jumlah jurnal universitas terakreditasi SINTA", strategi: "Pengembangan jurnal", unit: "LPPM", baseline: 1, target: [2, 3, 5, 7, 9] },
      { indikator: "Persentase publikasi terintegrasi PD Dikti", strategi: "IT integration", unit: "UPT SI", baseline: 75, target: [88, 95, 100, 100, 100] },
      { indikator: "Jumlah insentif publikasi yang diberikan per tahun", strategi: "Reward system", unit: "LPPM", baseline: 50, target: [80, 120, 170, 230, 300] },
      { indikator: "Jumlah pelatihan dengan editor jurnal per tahun", strategi: "Capacity building", unit: "LPPM", baseline: 3, target: [6, 10, 16, 24, 32] },
      { indikator: "Jumlah publikasi di repository universitas per tahun", strategi: "Open access", unit: "UPT SI", baseline: 100, target: [180, 280, 400, 550, 720] },
      { indikator: "Tingkat kepuasan dosen terhadap dukungan publikasi", strategi: "Survey", unit: "PPM", baseline: 65, target: [75, 84, 90, 95, 98] },
      { indikator: "Jumlah publikasi Scopus Q1-Q2 per tahun", strategi: "Pendampingan intensif", unit: "LPPM", baseline: 8, target: [15, 25, 38, 55, 75] },
    ],
    dokumenTerkait: DOKUMEN_TERKAIT_DEFAULT,
  },
  {
    namaStandar: "STANDAR PATEN DAN HKI PENELITIAN",
    kodeStandar: "PEN-PTN",
    rasional: [
      "Standar Paten dan HKI Penelitian mengatur kriteria minimal pengelolaan hak kekayaan intelektual atas hasil penelitian. Paten dan HKI menjadi indikator inovasi perguruan tinggi dan menjadi sumber pendapatan potensial melalui komersialisasi. Universitas Tulungagung mendorong dosen untuk mengajukan paten dan HKI atas hasil penelitian yang berpotensi komersial.",
      "Pengelolaan HKI yang baik juga melindungi hak dosen dan Universitas Tulungagung atas karya intelektual yang dihasilkan. Universitas Tulungagung menyediakan pendampingan untuk pengajuan paten dan HKI, serta mengembangkan mekanisme pembagian keuntungan dari komersialisasi yang adil. Mekanisme ini diatur dalam kebijakan HKI Universitas Tulungagung, yang selaras dengan undang-undang HKI dan regulasi terkait.",
      "Jenis HKI yang dikelola Universitas Tulungagung mencakup: paten (untuk invensi), hak cipta (untuk karya tulis, software, seni), merek (untuk identitas produk), desain industri (untuk desain produk), dan rahasia dagang (untuk informasi rahasia). Setiap jenis HKI memiliki persyaratan dan prosedur pengajuan yang berbeda, sehingga Universitas Tulungagung menyediakan konsultan HKI profesional untuk pendampingan.",
      "Komersialisasi HKI dilakukan melalui mekanisme lisensi (izin penggunaan dengan royalti), spin-off (perusahaan baru berbasis HKI universitas), atau penjualan HKI. Universitas Tulungagung mengembangkan inkubator bisnis untuk memfasilitasi spin-off, dan mengembangkan kerja sama dengan DUDI untuk lisensi. Pembagian keuntungan dari komersialisasi diatur dengan proporsi yang adil antara peneliti, universitas, dan pemerintah (untuk penelitian yang didanai pemerintah).",
    ],
    pihakPJ: PJ_DEFAULT_PENELITIAN,
    definisi: [
      ["a.", "Paten", "hak eksklusif atas invensi yang diberikan oleh negara untuk jangka waktu tertentu (20 tahun)."],
      ["b.", "HKI", "Hak Kekayaan Intelektual, mencakup paten, merek, hak cipta, desain industri, dan rahasia dagang."],
      ["c.", "Komersialisasi", "proses mengubah hasil penelitian menjadi produk atau jasa komersial."],
      ["d.", "Lisensi", "izin penggunaan HKI kepada pihak lain dengan kompensasi royalti."],
      ["e.", "Spin-off", "perusahaan baru yang dibentuk berbasis HKI universitas."],
      ["f.", "Hak Cipta", "hak eksklusif atas karya tulis, software, seni, yang berlaku seumur hidup + 70 tahun."],
      ["g.", "Merek", "tanda yang mengidentifikasi produk atau jasa, berlaku 10 tahun dan dapat diperpanjang."],
      ["h.", "Royalti", "pembayaran berkala kepada pemilik HKI atas penggunaan HKI."],
      ["i.", "Konsultan HKI", "profesional yang mendampingi pengajuan dan pengelolaan HKI."],
    ],
    pernyataan: [
      "Universitas Tulungagung mendorong pengajuan paten dan HKI atas hasil penelitian yang berpotensi komersial.",
      "Universitas Tulungagung menyediakan pendampingan untuk pengajuan paten dan HKI, melalui konsultan HKI profesional.",
      "Universitas Tulungagung memiliki kebijakan pembagian keuntungan dari komersialisasi HKI yang adil, diatur dalam kebijakan HKI.",
      "Paten dan HKI didokumentasikan dalam sistem informasi LPPM dan PD Dikti, dengan metadata lengkap.",
      "Universitas Tulungagung mengembangkan kerja sama dengan DUDI untuk komersialisasi HKI, melalui lisensi atau spin-off.",
      "Universitas Tulungagung mengembangkan inkubator bisnis untuk memfasilitasi spin-off berbasis HKI universitas.",
      "Setiap penelitian yang berpotensi komersial wajib didokumentasikan potensi HKI-nya dalam laporan akhir.",
      "Universitas Tulungagung menyediakan dana untuk pengajuan paten dan HKI, sebagai investasi masa depan.",
      "Pemilik HKI (peneliti) wajib mematuhi ketentuan HKI nasional dan internasional.",
      "Universitas Tulungagung memberikan reward bagi peneliti yang berhasil memperoleh paten granted atau mengkomersialisasi HKI.",
      "Universitas Tulungagung mengembangkan portfolio HKI yang aktif, sebagai indikator inovasi perguruan tinggi.",
      "HKI yang dimiliki Universitas Tulungagung dievaluasi dampaknya setiap tahun, untuk perbaikan strategi komersialisasi.",
    ],
    strategi: [
      "Menyelenggarakan workshop HKI bagi dosen peneliti, dengan narasumber konsultan HKI profesional.",
      "Menyediakan dana untuk pengajuan paten dan HKI, sebagai investasi masa depan.",
      "Bekerja sama dengan konsultan HKI profesional untuk pendampingan pengajuan dan pengelolaan HKI.",
      "Mengembangkan inkubator bisnis untuk komersialisasi HKI, dengan dukungan mentoring dan pendanaan.",
      "Mengintegrasikan dokumentasi HKI dengan PD Dikti, untuk monitoring real-time.",
      "Mengembangkan kerja sama dengan DUDI untuk lisensi HKI, melalui pendekatan aktif.",
      "Menyusun kebijakan HKI yang jelas, dengan pembagian keuntungan yang adil dan transparan.",
      "Memberikan reward bagi peneliti yang memperoleh paten granted atau mengkomersialisasi HKI.",
    ],
    indikator: [
      { indikator: "Jumlah paten diajukan per tahun", strategi: "Pendampingan", unit: "LPPM", baseline: 3, target: [7, 12, 18, 26, 35] },
      { indikator: "Jumlah paten granted per tahun", strategi: "Kualitas penelitian", unit: "LPPM", baseline: 1, target: [2, 4, 7, 10, 15] },
      { indikator: "Jumlah HKI lainnya (hak cipta, merek) per tahun", strategi: "Sosialisasi", unit: "LPPM", baseline: 10, target: [18, 28, 42, 60, 80] },
      { indikator: "Jumlah HKI yang dikomersialisasi", strategi: "Inkubator bisnis", unit: "LPPM", baseline: 1, target: [3, 6, 10, 16, 24] },
      { indikator: "Pendapatan dari komersialisasi HKI (Rp juta)", strategi: "Kerjasama DUDI", unit: "BAKU", baseline: 10, target: [30, 75, 150, 280, 450] },
      { indikator: "Jumlah workshop HKI per tahun", strategi: "Program diklat", unit: "LPPM", baseline: 2, target: [4, 7, 12, 18, 25] },
      { indikator: "Jumlah spin-off yang dibentuk per tahun", strategi: "Inkubator bisnis", unit: "LPPM", baseline: 0, target: [1, 2, 4, 7, 10] },
      { indikator: "Jumlah konsultan HKI yang bekerjasama", strategi: "Kerjasama profesional", unit: "LPPM", baseline: 1, target: [2, 3, 5, 7, 10] },
      { indikator: "Persentase penelitian dengan dokumentasi potensi HKI", strategi: "Monitoring", unit: "LPPM", baseline: 30, target: [50, 70, 85, 95, 100] },
      { indikator: "Jumlah reward paten/HKI per tahun", strategi: "Reward system", unit: "Rektor", baseline: 2, target: [5, 9, 15, 22, 32] },
      { indikator: "Persentase HKI terintegrasi PD Dikti", strategi: "IT integration", unit: "UPT SI", baseline: 60, target: [78, 90, 97, 100, 100] },
      { indikator: "Jumlah lisensi HKI ke DUDI per tahun", strategi: "Pendekatan DUDI", unit: "LPPM", baseline: 0, target: [1, 3, 6, 10, 15] },
      { indikator: "Jumlah portfolio HKI aktif universitas", strategi: "Pengembangan portfolio", unit: "LPPM", baseline: 8, target: [15, 25, 40, 60, 85] },
      { indikator: "Jumlah HKI yang dievaluasi dampaknya per tahun", strategi: "Evaluasi dampak", unit: "LPPM", baseline: 3, target: [6, 12, 20, 32, 48] },
      { indikator: "Tingkat kepuasan peneliti terhadap dukungan HKI", strategi: "Survey", unit: "PPM", baseline: 60, target: [72, 82, 90, 95, 98] },
    ],
    dokumenTerkait: DOKUMEN_TERKAIT_DEFAULT,
  },
  {
    namaStandar: "STANDAR DISEMINASI PENELITIAN",
    kodeStandar: "PEN-DSM",
    rasional: [
      "Standar Diseminasi Penelitian mengatur kriteria minimal penyebarluasan hasil penelitian kepada masyarakat akademik dan publik. Diseminasi yang baik meningkatkan dampak penelitian dan reputasi perguruan tinggi. Universitas Tulungagung menyelenggarakan berbagai forum diseminasi—seperti seminar, konferensi, dan publikasi media—untuk menyebarluaskan hasil penelitian.",
      "Diseminasi juga menjadi sarana untuk memperoleh umpan balik dari masyarakat akademik dan publik, sehingga dapat meningkatkan kualitas penelitian selanjutnya. Universitas Tulungagung mendorong dosen untuk aktif menyebarkan hasil penelitian melalui berbagai saluran, baik akademik maupun publik. Saluran akademik mencakup seminar, konferensi, dan jurnal; sedangkan saluran publik mencakup media massa, media sosial, dan forum publik.",
      "Universitas Tulungagung menyelenggarakan seminar nasional tahunan sebagai forum diseminasi utama bagi dosen. Selain itu, Universitas Tulungagung juga mendorong dosen untuk presentasi di konferensi internasional, dengan pendanaan khusus. Universitas Tulungagung juga mengembangkan repository digital untuk dokumentasi hasil penelitian, sehingga dapat diakses masyarakat luas.",
      "Diseminasi melalui media massa menjadi sarana untuk menjangkau publik luas, sehingga hasil penelitian dapat memberikan dampak yang lebih besar. Universitas Tulungagung bekerja sama dengan media massa lokal dan nasional untuk publikasi artikel populer berbasis hasil penelitian. Selain itu, Universitas Tulungagung juga mengembangkan kanal media sosial untuk diseminasi yang lebih cepat dan interaktif.",
    ],
    pihakPJ: PJ_DEFAULT_PENELITIAN,
    definisi: [
      ["a.", "Diseminasi", "penyebarluasan hasil penelitian kepada masyarakat akademik dan publik."],
      ["b.", "Seminar", "forum pertemuan ilmiah untuk presentasi dan diskusi hasil penelitian."],
      ["c.", "Konferensi", "pertemuan ilmiah berskala besar dengan peserta dari berbagai institusi."],
      ["d.", "Publikasi Media", "penyampaian hasil penelitian melalui media massa untuk publik luas."],
      ["e.", "Repository", "platform digital untuk dokumentasi dan akses hasil penelitian."],
      ["f.", "Artikel Populer", "artikel yang ditulis untuk publik umum, berbasis hasil penelitian."],
      ["g.", "Seminar Nasional", "seminar berskala nasional, biasanya diselenggarakan tahunan oleh universitas."],
      ["h.", "Konferensi Internasional", "konferensi dengan peserta internasional, biasanya diselenggarakan oleh asosiasi profesi."],
      ["i.", "Media Sosial", "platform digital untuk komunikasi cepat dan interaktif dengan publik."],
    ],
    pernyataan: [
      "Universitas Tulungagung menyelenggarakan seminar dan konferensi ilmiah secara berkala, minimal 1 seminar nasional per tahun.",
      "Universitas Tulungagung mendorong dosen untuk mempresentasikan hasil penelitian di forum ilmiah, dengan pendanaan khusus.",
      "Hasil penelitian disebarkan juga melalui media massa untuk publik luas, melalui artikel populer dan wawancara.",
      "Universitas Tulungagung mengembangkan platform digital (repository) untuk diseminasi penelitian, dengan akses terbuka.",
      "Hasil diseminasi didokumentasikan dalam sistem informasi LPPM, dengan metadata lengkap.",
      "Universitas Tulungagung mengembangkan kanal media sosial untuk diseminasi yang cepat dan interaktif.",
      "Universitas Tulungagung mengundang akademisi eksternal untuk seminar di Universitas Tulungagung, sebagai pertukaran ilmu.",
      "Universitas Tulungagung mengembangkan kerja sama dengan media massa untuk publikasi artikel populer berbasis hasil penelitian.",
      "Diseminasi melalui konferensi internasional didukung dengan pendanaan khusus, sebagai bagian dari reputasi internasional.",
      "Universitas Tulungagung menargetkan peningkatan jumlah dosen yang presentasi di konferensi internasional setiap tahun.",
      "Repository universitas diintegrasikan dengan PD Dikti, sehingga hasil penelitian dapat diakses dari satu portal nasional.",
      "Diseminasi melalui media sosial dikelola oleh tim khusus, dengan konten yang menarik dan informatif.",
    ],
    strategi: [
      "Menyelenggarakan seminar nasional tahunan Universitas Tulungagung, dengan tema yang relevan dengan isu terkini.",
      "Memberikan pendanaan bagi dosen yang presentasi di konferensi internasional, dengan SOP yang jelas.",
      "Bekerja sama dengan media massa untuk publikasi hasil penelitian, melalui MoU dengan redaksi media.",
      "Mengembangkan repository digital dengan Open Journal System (OJS) untuk dokumentasi hasil penelitian.",
      "Mengundang akademisi eksternal untuk seminar di Universitas Tulungagung, melalui kerja sama dengan PT lain.",
      "Mengembangkan kanal media sosial (YouTube, Instagram, LinkedIn) untuk diseminasi yang cepat dan interaktif.",
      "Menyusun panduan penulisan artikel populer bagi dosen, sehingga dapat menulis untuk media massa.",
      "Mengembangkan kerja sama dengan radio dan TV kampus untuk diseminasi melalui siaran.",
    ],
    indikator: [
      { indikator: "Jumlah seminar/konferensi diselenggarakan per tahun", strategi: "Pendanaan", unit: "LPPM", baseline: 5, target: [9, 15, 22, 32, 45] },
      { indikator: "Jumlah dosen presentasi di konferensi internasional", strategi: "Hibah", unit: "LPPM", baseline: 30, target: [50, 78, 110, 150, 195] },
      { indikator: "Jumlah publikasi di media massa per tahun", strategi: "Kerjasama media", unit: "LPPM", baseline: 15, target: [28, 48, 75, 110, 150] },
      { indikator: "Jumlah akses repository per tahun", strategi: "Pengembangan digital", unit: "UPT SI", baseline: 5000, target: [9000, 15000, 23000, 33000, 45000] },
      { indikator: "Jumlah undangan akademisi eksternal", strategi: "Networking", unit: "LPPM", baseline: 10, target: [18, 30, 45, 65, 88] },
      { indikator: "Jumlah artikel populer di media per tahun", strategi: "Panduan penulisan", unit: "LPPM", baseline: 8, target: [16, 28, 45, 68, 95] },
      { indikator: "Jumlah pengikut media sosial LPPM", strategi: "Pengembangan kanal", unit: "LPPM", baseline: 500, target: [1500, 4000, 9000, 18000, 30000] },
      { indikator: "Jumlah MoU dengan media massa", strategi: "Networking", unit: "BAU", baseline: 2, target: [4, 7, 12, 18, 25] },
      { indikator: "Persentase hasil penelitian di repository", strategi: "Open access mandate", unit: "LPPM", baseline: 60, target: [75, 88, 96, 100, 100] },
      { indikator: "Jumlah siaran radio/TV kampus per tahun", strategi: "Kerjasama media", unit: "LPPM", baseline: 12, target: [24, 40, 62, 90, 125] },
      { indikator: "Jumlah seminar nasional tahunan UNITA", strategi: "Pendanaan", unit: "LPPM", baseline: 1, target: [2, 3, 4, 5, 6] },
      { indikator: "Persentase repository terintegrasi PD Dikti", strategi: "IT integration", unit: "UPT SI", baseline: 60, target: [78, 90, 97, 100, 100] },
      { indikator: "Jumlah pendanaan presentasi konferensi internasional", strategi: "Hibah", unit: "LPPM", baseline: 20, target: [40, 70, 110, 165, 230] },
      { indikator: "Tingkat kepuasan dosen terhadap dukungan diseminasi", strategi: "Survey", unit: "PPM", baseline: 65, target: [75, 84, 90, 95, 98] },
      { indikator: "Jumlah views konten media sosial LPPM per tahun", strategi: "Pengembangan konten", unit: "LPPM", baseline: 10000, target: [30000, 80000, 180000, 350000, 600000] },
    ],
    dokumenTerkait: DOKUMEN_TERKAIT_DEFAULT,
  },
  {
    namaStandar: "STANDAR KOLABORASI PENELITIAN",
    kodeStandar: "PEN-KLB",
    rasional: [
      "Standar Kolaborasi Penelitian mengatur kriteria minimal kerja sama penelitian dengan institusi lain, baik nasional maupun internasional. Kolaborasi menjadi sarana untuk memperluas jaringan, berbagi sumber daya, dan meningkatkan kualitas penelitian. Universitas Tulungagung aktif mengembangkan kerja sama penelitian dengan perguruan tinggi lain, DUDI, dan lembaga penelitian.",
      "Kolaborasi internasional menjadi salah satu indikator reputasi perguruan tinggi. Universitas Tulungagung menargetkan peningkatan kerja sama internasional, khususnya dengan perguruan tinggi di Asia Tenggara, Australia, dan Eropa. Hal ini sejalan dengan visi Universitas Tulungagung untuk berkompetisi berskala internasional. Kolaborasi internasional juga membuka peluang bagi dosen untuk mengakses sumber daya penelitian yang lebih luas.",
      "Bentuk kolaborasi penelitian mencakup: joint research (penelitian bersama), joint publication (publikasi bersama), visiting researcher (peneliti tamu), exchange program (pertukaran peneliti), dan joint degree (program gelar bersama). Universitas Tulungagung mengembangkan berbagai bentuk kolaborasi tersebut, sesuai dengan kebutuhan dan peluang.",
      "Kolaborasi yang baik harus saling menguntungkan, terdokumentasi, dan dievaluasi secara berkala. Universitas Tulungagung memiliki sistem pengelolaan kerja sama yang transparan, mulai dari pengajuan MoU/MoA, pelaksanaan, hingga evaluasi. Setiap kerja sama didokumentasikan dalam database kerja sama, dan dievaluasi dampaknya setiap tahun.",
    ],
    pihakPJ: PJ_DEFAULT_PENELITIAN,
    definisi: [
      ["a.", "Kolaborasi Penelitian", "kerja sama penelitian antara dua atau lebih institusi, dengan tujuan dan output bersama."],
      ["b.", "MoU", "Memorandum of Understanding, perjanjian kerja sama tingkat umum."],
      ["c.", "MoA", "Memorandum of Agreement, perjanjian kerja sama spesifik dengan detail pelaksanaan."],
      ["d.", "Joint Research", "penelitian bersama yang melibatkan peneliti dari beberapa institusi."],
      ["e.", "Joint Publication", "publikasi bersama yang melibatkan penulis dari beberapa institusi."],
      ["f.", "Visiting Researcher", "peneliti tamu yang melakukan penelitian di institusi lain untuk periode tertentu."],
      ["g.", "Exchange Program", "program pertukaran peneliti antar-institusi untuk periode tertentu."],
      ["h.", "Joint Degree", "program gelar bersama yang diselenggarakan oleh dua atau lebih institusi."],
      ["i.", "Networking", "pengembangan jaringan profesional dengan akademisi dan peneliti lain."],
    ],
    pernyataan: [
      "Universitas Tulungagung aktif mengembangkan kerja sama penelitian dengan PT lain, DUDI, dan lembaga penelitian.",
      "Kerja sama penelitian didokumentasikan dalam bentuk MoU/MoA yang jelas, dengan detail pelaksanaan.",
      "Universitas Tulungagung mengembangkan joint research dengan institusi nasional dan internasional.",
      "Kerja sama penelitian dilaporkan dalam sistem informasi LPPM dan PD Dikti, dengan metadata lengkap.",
      "Universitas Tulungagung memberikan dukungan administratif dan finansial untuk kolaborasi penelitian.",
      "Universitas Tulungagung mengembangkan program visiting researcher dan exchange program dengan PT mitra.",
      "Universitas Tulungagung menargetkan peningkatan joint publication dengan institusi internasional setiap tahun.",
      "Universitas Tulungagung mengembangkan kerja sama dengan DUDI untuk penelitian terapan yang berdampak.",
      "Setiap kerja sama penelitian dievaluasi dampaknya setiap tahun, sebagai basis untuk perbaikan strategi.",
      "Universitas Tulungagung mengembangkan networking dengan asosiasi profesi dan konsorsium penelitian.",
      "Universitas Tulungagung menargetkan peningkatan jumlah kerja sama internasional, khususnya dengan PT di Asia Tenggara, Australia, dan Eropa.",
      "Kerja sama penelitian yang berdampak besar mendapat apresiasi melalui award tahunan.",
    ],
    strategi: [
      "Mengembangkan kerja sama strategis dengan PT unggulan nasional dan internasional, melalui MoU/MoA.",
      "Mengundang peneliti eksternal sebagai visiting researcher, dengan pendanaan khusus.",
      "Menyelenggarakan joint conference dengan PT mitra, sebagai forum diseminasi dan networking.",
      "Mengembangkan program joint degree dengan PT internasional, sebagai program unggulan.",
      "Memberikan insentif bagi dosen yang aktif dalam kolaborasi penelitian, terutama internasional.",
      "Mengembangkan kerja sama dengan DUDI untuk penelitian terapan, melalui pendekatan aktif.",
      "Mengembangkan networking dengan asosiasi profesi dan konsorsium penelitian internasional.",
      "Mengintegrasikan database kerja sama dengan PD Dikti, untuk monitoring real-time.",
    ],
    indikator: [
      { indikator: "Jumlah MoU/MoA penelitian aktif", strategi: "Networking", unit: "LPPM", baseline: 20, target: [32, 48, 70, 95, 125] },
      { indikator: "Jumlah joint research per tahun", strategi: "Pendanaan", unit: "LPPM", baseline: 5, target: [10, 18, 30, 45, 62] },
      { indikator: "Jumlah kerjasama internasional aktif", strategi: "Ekspansi", unit: "LPPM", baseline: 5, target: [10, 20, 32, 48, 65] },
      { indikator: "Jumlah visiting researcher per tahun", strategi: "Pendanaan", unit: "LPPM", baseline: 3, target: [7, 14, 22, 35, 50] },
      { indikator: "Jumlah joint publication per tahun", strategi: "Insentif", unit: "LPPM", baseline: 10, target: [20, 35, 55, 80, 110] },
      { indikator: "Jumlah exchange program per tahun", strategi: "Kerjasama", unit: "LPPM", baseline: 2, target: [5, 10, 16, 25, 35] },
      { indikator: "Jumlah kerjasama dengan DUDI untuk penelitian", strategi: "Pendekatan DUDI", unit: "LPPM", baseline: 8, target: [15, 25, 38, 55, 75] },
      { indikator: "Jumlah joint degree program", strategi: "Pengembangan", unit: "UPPS", baseline: 0, target: [1, 2, 4, 7, 10] },
      { indikator: "Persentase kerjasama dengan evaluasi dampak", strategi: "Monitoring", unit: "LPPM", baseline: 50, target: [70, 85, 95, 100, 100] },
      { indikator: "Jumlah networking dengan asosiasi profesi", strategi: "Networking", unit: "LPPM", baseline: 3, target: [6, 10, 16, 24, 32] },
      { indikator: "Jumlah award kerjasama berdampak per tahun", strategi: "Reward system", unit: "Rektor", baseline: 1, target: [3, 6, 10, 16, 22] },
      { indikator: "Persentase kerjasama terintegrasi PD Dikti", strategi: "IT integration", unit: "UPT SI", baseline: 65, target: [80, 92, 98, 100, 100] },
      { indikator: "Jumlah pendanaan untuk kolaborasi internasional (Rp juta)", strategi: "Pendanaan", unit: "LPPM", baseline: 50, target: [120, 250, 450, 750, 1100] },
      { indikator: "Tingkat kepuasan mitra terhadap kolaborasi", strategi: "Survey", unit: "LPPM", baseline: 70, target: [78, 85, 90, 95, 98] },
      { indikator: "Jumlah conference bersama dengan PT mitra per tahun", strategi: "Kerjasama", unit: "LPPM", baseline: 2, target: [4, 8, 14, 22, 32] },
    ],
    dokumenTerkait: DOKUMEN_TERKAIT_DEFAULT,
  },
];

module.exports = {
  STANDAR_PENELITIAN,
};
