// ============================================================
// DATA EXPANDED: 8 STANDAR PENDIDIKAN (12-15 indikator per standar)
// ============================================================

const PJ_DEFAULT_AKADEMIK = [
  { pihak: "Senat Universitas", penetapan: true, pelaksanaan: false, evaluasi: false, pengendalian: false, peningkatan: true },
  { pihak: "Rektor", penetapan: false, pelaksanaan: true, evaluasi: true, pengendalian: true, peningkatan: true },
  { pihak: "Wakil Rektor I (Akademik)", penetapan: false, pelaksanaan: true, evaluasi: true, pengendalian: true, peningkatan: true },
  { pihak: "Wakil Rektor II (Umum & Keuangan)", penetapan: false, pelaksanaan: true, evaluasi: true, pengendalian: true, peningkatan: true },
  { pihak: "Dekan", penetapan: false, pelaksanaan: true, evaluasi: true, pengendalian: true, peningkatan: true },
  { pihak: "Ka. Prodi (UPPS)", penetapan: false, pelaksanaan: true, evaluasi: true, pengendalian: true, peningkatan: true },
  { pihak: "Ka. PPM", penetapan: false, pelaksanaan: true, evaluasi: true, pengendalian: true, peningkatan: true },
  { pihak: "Ka. LPM Fakultas", penetapan: false, pelaksanaan: true, evaluasi: true, pengendalian: true, peningkatan: true },
  { pihak: "GKM Prodi", penetapan: false, pelaksanaan: true, evaluasi: true, pengendalian: true, peningkatan: true },
  { pihak: "Ka. LPPM", penetapan: false, pelaksanaan: true, evaluasi: true, pengendalian: true, peningkatan: true },
];

const PJ_DEFAULT_PENELITIAN = PJ_DEFAULT_AKADEMIK;
const PJ_DEFAULT_PKM = PJ_DEFAULT_AKADEMIK;

const PJ_DEFAULT_NONAKADEMIK = [
  { pihak: "Senat Universitas", penetapan: true, pelaksanaan: false, evaluasi: false, pengendalian: false, peningkatan: true },
  { pihak: "Rektor", penetapan: false, pelaksanaan: true, evaluasi: true, pengendalian: true, peningkatan: true },
  { pihak: "Wakil Rektor II (Umum & Keuangan)", penetapan: false, pelaksanaan: true, evaluasi: true, pengendalian: true, peningkatan: true },
  { pihak: "Wakil Rektor III (Kemahasiswaan)", penetapan: false, pelaksanaan: true, evaluasi: true, pengendalian: true, peningkatan: true },
  { pihak: "Ka. PPM", penetapan: false, pelaksanaan: true, evaluasi: true, pengendalian: true, peningkatan: true },
  { pihak: "Ka. BAKU", penetapan: false, pelaksanaan: true, evaluasi: true, pengendalian: true, peningkatan: true },
  { pihak: "Ka. BAA", penetapan: false, pelaksanaan: true, evaluasi: true, pengendalian: true, peningkatan: true },
  { pihak: "Ka. BAU", penetapan: false, pelaksanaan: true, evaluasi: true, pengendalian: true, peningkatan: true },
  { pihak: "Dekan", penetapan: false, pelaksanaan: true, evaluasi: true, pengendalian: true, peningkatan: true },
  { pihak: "Ka. SPI", penetapan: false, pelaksanaan: true, evaluasi: true, pengendalian: true, peningkatan: true },
];

const DOKUMEN_TERKAIT_DEFAULT = [
  "Dokumen Kebijakan Mutu SPMI UNITA 2025",
  "Dokumen Manual Mutu SPMI UNITA 2025",
  "Statuta Universitas Tulungagung",
  "Rencana Induk Pengembangan (RIP) Universitas Tulungagung",
  "Rencana Strategis (Renstra) Universitas Tulungagung",
  "Laporan Audit Mutu Internal (AMI) Tahunan",
  "Berita Acara Rapat Tinjauan Manajemen (RTM)",
  "Rencana Tindak Lanjut (RTL) Hasil RTM",
  "Sistem Informasi Akademik (SIAKAD) Universitas Tulungagung",
  "Pangkalan Data Pendidikan Tinggi (PD Dikti)",
];

// ============================================================
// 8 STANDAR PENDIDIKAN (EXPANDED)
// ============================================================
const STANDAR_PENDIDIKAN = [
  {
    namaStandar: "STANDAR KOMPETENSI LULUSAN",
    kodeStandar: "SKL",
    rasional: [
      "Standar Kompetensi Lulusan merupakan standar luaran pendidikan yang menjadi acuan utama bagi setiap program studi dalam menyelenggaraan pendidikan tinggi. Sesuai dengan Peraturan Menteri Pendidikan Tinggi, Sains, dan Teknologi Nomor 39 Tahun 2025, standar kompetensi lulusan merupakan kriteria minimal mengenai kesatuan kompetensi sikap, keterampilan, dan pengetahuan yang menunjukkan capaian mahasiswa dari hasil pembelajarannya pada akhir program pendidikan tinggi. Standar ini menjadi tolok ukur utama bagi evaluasi kualitas lulusan dan menjadi dasar bagi penyusunan kurikulum, proses pembelajaran, dan penilaian.",
      "Universitas Tulungagung memandang Standar Kompetensi Lulusan sebagai standar strategis yang menentukan daya saing lulusan di pasar kerja nasional dan internasional. Dalam konteks akreditasi sebagaimana diatur dalam Pasal 75 ayat (2) Permen 39 Tahun 2025, instrumen Akreditasi disusun berdasarkan kriteria pada standar luaran, standar proses, dan standar masukan dengan mengutamakan kriteria pada standar luaran. Oleh karena itu, pemenuhan Standar Kompetensi Lulusan menjadi prioritas tertinggi bagi setiap program studi di Universitas Tulungagung, dan menjadi indikator utama bagi BAN-PT dan LAM dalam menilai kelayakan program studi untuk memperoleh status terakreditasi atau terakreditasi unggul.",
      "Capaian pembelajaran lulusan untuk setiap program studi di Universitas Tulungagung mencakup empat kompetensi sebagaimana diatur dalam Pasal 7 Permen 39 Tahun 2025: (a) penguasaan ilmu pengetahuan dan teknologi, kecakapan/keterampilan spesifik dan aplikasinya untuk satu atau sekumpulan bidang keilmuan tertentu; (b) kecakapan umum yang dibutuhkan sebagai dasar untuk penguasaan IPTEK serta bidang kerja yang relevan; (c) pengetahuan dan keterampilan yang dibutuhkan untuk dunia kerja dan/atau melanjutkan studi pada jenjang yang lebih tinggi ataupun untuk mendapatkan sertifikat profesi; serta (d) kemampuan intelektual untuk berpikir secara mandiri dan kritis sebagai pembelajar sepanjang hayat. Universitas Tulungagung memastikan bahwa setiap program studi merumuskan CPL yang mencakup keempat kompetensi tersebut, dengan mengacu pada KKNI, kerangka kualifikasi profesi (jika ada), dan kompetensi utama yang disusun oleh asosiasi program studi sejenis.",
      "Sebagai perguruan tinggi swasta, Universitas Tulungagung juga memperhatikan kebutuhan spesifik pemangku kepentingan lokal—pemerintah daerah, DUDI di Jawa Timur, dan masyarakat—dalam merumuskan CPL. Hal ini dilakukan melalui keterlibatan aktif pemangku kepentingan dalam rapat kurikulum, tracer study, dan benchmarking dengan perguruan tinggi sejenis. Hasil dari keterlibatan ini adalah CPL yang tidak hanya memenuhi standar nasional, tetapi juga relevan dengan kebutuhan stakeholder lokal dan global, sehingga lulusan Universitas Tulungagung memiliki daya saing yang kuat di pasar kerja.",
    ],
    pihakPJ: PJ_DEFAULT_AKADEMIK,
    definisi: [
      ["a.", "Kompetensi", "kesatuan sikap, keterampilan, dan pengetahuan yang dimiliki oleh lulusan sebagai hasil pembelajaran."],
      ["b.", "Capaian Pembelajaran Lulusan (CPL)", "rumusan kompetensi lulusan yang dirumuskan dari standar kompetensi lulusan untuk setiap program studi, mencakup sikap, keterampilan umum, keterampilan khusus, dan pengetahuan."],
      ["c.", "Capaian Pembelajaran Mata Kuliah (CPMK)", "rumusan kompetensi mata kuliah yang berkontribusi pada pencapaian CPL."],
      ["d.", "Capaian Pembelajaran Tugas Akhir (CPTA)", "rumusan kompetensi tugas akhir/skripsi/tesis yang berkontribusi pada pencapaian CPL."],
      ["e.", "Kurikulum", "seperangkat rencana dan pengaturan mengenai capaian pembelajaran lulusan, mata kuliah, beban belajar, dan strategi pembelajaran."],
      ["f.", "Asosiasi Program Studi", "lembaga yang merumuskan kompetensi utama lulusan program studi sejenis bersama pihak lain yang terkait."],
      ["g.", "KKNI", "Kerangka Kualifikasi Nasional Indonesia, kerangka penjenjangan kualifikasi kompetensi yang menyandingkan hasil pendidikan dengan bidang kerja."],
      ["h.", "DUDI", "Dunia Usaha, Dunia Industri, dan Dunia Kerja sebagai pemangku kepentingan utama pengguna lulusan."],
      ["i.", "Tracer Study", "studi pelacakan lulusan untuk memperoleh umpan balik tentang relevansi kompetensi lulusan dengan kebutuhan DUDI."],
    ],
    pernyataan: [
      "Setiap program studi di Universitas Tulungagung wajib menyusun Capaian Pembelajaran Lulusan (CPL) yang mencakup kompetensi sikap, keterampilan umum, keterampilan khusus, dan pengetahuan, sesuai dengan jenjang program (D3, S1, S1 Terapan, Profesi, S2, S3) dan ranah keilmuan.",
      "CPL disusun oleh Unit Pengelola Program Studi (UPPS) dengan melibatkan pemangku kepentingan internal (dosen, mahasiswa, alumni) dan eksternal (DUDI, asosiasi program studi, pemerintah daerah).",
      "CPL memperhatikan tujuh aspek sebagaimana diatur dalam Permen 39 Tahun 2025: (a) visi dan misi perguruan tinggi; (b) KKNI; (c) perkembangan IPTEK; (d) kebutuhan kompetensi kerja dari DUDI; (e) ranah keilmuan program studi; (f) kompetensi utama lulusan program studi; serta (g) kurikulum program studi sejenis.",
      "CPL diinformasikan kepada mahasiswa pada program studi tersebut melalui RPS, handbook mahasiswa, dan SIAKAD, sehingga mahasiswa memahami kompetensi yang akan dicapai sejak awal studi.",
      "CPL disusun ke dalam mata kuliah pada setiap program studi, dengan setiap mata kuliah memiliki CPMK yang berkontribusi pada pencapaian CPL melalui pemetaan CPL-CPMK yang terdokumentasi.",
      "Kompetensi utama lulusan program studi memenuhi ketentuan minimal sesuai jenjang sebagaimana diatur dalam Pasal 9 Permen 39 Tahun 2025, mulai dari D1 hingga subspesialis.",
      "CPL mengacu pada kompetensi utama lulusan yang disusun oleh asosiasi program studi sejenis, apabila asosiasi telah terbentuk. Apabila belum terbentuk, CPL disusun oleh Universitas Tulungagung dengan mengacu pada praktik baik perguruan tinggi sejenis.",
      "CPL dievaluasi minimal setiap dua tahun atau sesuai perubahan regulasi, dengan melibatkan DUDI, asosiasi program studi, dan alumni, untuk memastikan relevansi dengan kebutuhan pasar kerja.",
      "Universitas Tulungagung menyelenggarakan rapat kurikulum tahunan di tingkat program studi dan fakultas untuk memastikan keselarasan CPL dengan CPMK, materi mata kuliah, dan penilaian.",
      "Tracer study dilakukan secara berkala minimal setiap dua tahun untuk memperoleh umpan balik dari pengguna lulusan dan menyelaraskan CPL dengan kebutuhan dunia kerja.",
      "CPL diintegrasikan dalam Sistem Informasi Akademik (SIAKAD) sehingga dapat diakses oleh mahasiswa, dosen, dan pemangku kepentingan, dan menjadi referensi bagi penyusunan RPS dan penilaian.",
      "CPL dipublikasikan kepada masyarakat melalui situs web program studi dan universitas, sebagai bentuk transparansi dan akuntabilitas kepada calon mahasiswa dan pemangku kepentingan eksternal.",
    ],
    strategi: [
      "Melakukan kaji ulang CPL setiap program studi setiap dua tahun atau sesuai perubahan regulasi, dengan melibatkan DUDI, asosiasi program studi, dan alumni sebagai narasumber.",
      "Menyelenggarakan rapat kurikulum tahunan di tingkat program studi, fakultas, dan universitas untuk memastikan keselarasan CPL dengan CPMK dan materi mata kuliah.",
      "Melakukan tracer study secara berkala minimal setiap dua tahun, dengan target response rate ≥30%, untuk memperoleh umpan balik dari pengguna lulusan dan menyelaraskan CPL.",
      "Mengintegrasikan CPL dalam Sistem Informasi Akademik (SIAKAD) sehingga dapat diakses oleh mahasiswa, dosen, dan pemangku kepentingan, dengan dashboard monitoring ketercapaian CPL.",
      "Menyelenggarakan workshop penyusunan CPL bagi pengelola program studi dan dosen, dengan narasumber dari asosiasi program studi, DUDI, atau ahli kurikulum pendidikan tinggi.",
      "Mengembangkan kerja sama dengan asosiasi program studi untuk mengadopsi kompetensi utama lulusan yang telah disusun oleh asosiasi, dan berpartisipasi aktif dalam forum asosiasi.",
      "Mengundang DUDI sebagai narasumber tamu dalam mata kuliah, sehingga mahasiswa memahami kebutuhan dunia kerja sejak awal studi.",
      "Mengembangkan sistem pemetaan CPL-CPMK-materi mata kuliah yang terdokumentasi dan dapat diaudit oleh GKM dan PPM.",
    ],
    indikator: [
      { indikator: "Persentase program studi yang telah menyusun CPL sesuai Permen 39/2025", strategi: "Sosialisasi & pendampingan", unit: "UPPS", baseline: 100, target: [100, 100, 100, 100, 100] },
      { indikator: "Persentase CPL yang mencakup 4 kompetensi (sikap, keterampilan umum, keterampilan khusus, pengetahuan)", strategi: "Audit CPL", unit: "UPPS", baseline: 85, target: [95, 100, 100, 100, 100] },
      { indikator: "Persentase CPL yang diinformasikan kepada mahasiswa melalui RPS dan SIAKAD", strategi: "Integrasi SIAKAD", unit: "UPPS", baseline: 90, target: [98, 100, 100, 100, 100] },
      { indikator: "Jumlah program studi yang mengikuti CPL asosiasi", strategi: "Koordinasi asosiasi", unit: "UPPS", baseline: 15, target: [22, 30, 38, 45, 50] },
      { indikator: "Persentase mata kuliah dengan CPMK yang terdokumentasi dan dipetakan ke CPL", strategi: "Audit RPS", unit: "GKM", baseline: 85, target: [92, 97, 100, 100, 100] },
      { indikator: "Tingkat kepuasan pengguna lulusan terhadap kompetensi lulusan", strategi: "Tracer study", unit: "PPM", baseline: 72, target: [76, 80, 84, 88, 92] },
      { indikator: "Jumlah program studi yang melakukan review CPL 2 tahunan", strategi: "Monitoring", unit: "UPPS", baseline: 60, target: [80, 100, 100, 100, 100] },
      { indikator: "Persentase program studi yang melibatkan DUDI dalam penyusunan CPL", strategi: "Kerjasama DUDI", unit: "UPPS", baseline: 55, target: [70, 85, 95, 100, 100] },
      { indikator: "Jumlah workshop penyusunan CPL per tahun", strategi: "Program diklat", unit: "PPM", baseline: 3, target: [5, 8, 12, 16, 20] },
      { indikator: "Persentase CPL yang dipublikasikan di situs web prodi", strategi: "Transparansi", unit: "UPT SI", baseline: 70, target: [85, 95, 100, 100, 100] },
      { indikator: "Tingkat kepuasan mahasiswa terhadap informasi CPL", strategi: "Survey emonev", unit: "PPM", baseline: 70, target: [78, 84, 90, 94, 97] },
      { indikator: "Jumlah DUDI yang dilibatkan dalam rapat kurikulum per tahun", strategi: "Networking", unit: "UPPS", baseline: 25, target: [40, 60, 85, 110, 140] },
      { indikator: "Persentase lulusan terserap DUDI <6 bulan setelah lulus", strategi: "Pusat karir", unit: "UPPS", baseline: 60, target: [68, 75, 82, 88, 92] },
      { indikator: "Response rate tracer study", strategi: "Insentif & follow-up", unit: "PPM", baseline: 20, target: [28, 35, 42, 50, 55] },
      { indikator: "Jumlah program studi dengan pemetaan CPL-CPMK terdigitalisasi", strategi: "Pengembangan IT", unit: "UPT SI", baseline: 8, target: [18, 30, 45, 65, 85] },
    ],
    dokumenTerkait: DOKUMEN_TERKAIT_DEFAULT,
  },
  {
    namaStandar: "STANDAR PROSES PEMBELAJARAN",
    kodeStandar: "SPB",
    rasional: [
      "Standar Proses Pembelajaran merupakan bagian dari standar proses pendidikan yang mengatur kriteria minimal proses pembelajaran untuk mencapai standar kompetensi lulusan. Sesuai Permen 39 Tahun 2025, standar proses pembelajaran meliputi perencanaan, pelaksanaan, dan penilaian proses pembelajaran. Standar ini menjadi acuan operasional bagi dosen dalam menyelenggaraan kegiatan pembelajaran yang efektif, interaktif, dan bermutu.",
      "Universitas Tulungagung memandang proses pembelajaran sebagai jantung dari penyelenggaraan pendidikan tinggi. Kualitas proses pembelajaran menentukan kualitas lulusan, sehingga standar ini dikelola dengan sangat hati-hati melalui siklus PPEPP yang konsisten. Universitas Tulungagung juga mendorong inovasi pembelajaran—seperti project-based learning, case-based learning, blended learning, dan pemanfaatan teknologi—untuk meningkatkan kualitas pengalaman belajar mahasiswa.",
      "Perencanaan proses pembelajaran mencakup perumusan capaian pembelajaran mata kuliah, materi, metode, sumber belajar, dan kriteria penilaian. Pelaksanaan proses pembelajaran dilakukan melalui berbagai bentuk interaksi akademik—kuliah, praktikum, kerja lapangan, daring, dan/atau blended learning—sesuai karakteristik program studi. Penilaian proses pembelajaran dilakukan secara formatif dan sumatif untuk mengukur ketercapaian capaian pembelajaran. Universitas Tulungagung memastikan bahwa ketiga tahapan ini dikelola secara terintegrasi dan terdokumentasi.",
      "Universitas Tulungagung mengembangkan ekosistem pembelajaran yang mendukung student-centered learning, di mana mahasiswa menjadi pelaku aktif dalam proses pembelajaran, sementara dosen berperan sebagai fasilitator. Pendekatan ini sejalan dengan tren pendidikan tinggi modern dan MBKM, serta mempersiapkan mahasiswa untuk menjadi pembelajar sepanjang hayat. Universitas Tulungagung juga mengembangkan infrastruktur digital—LMS, video conference, dan repository materi—untuk mendukung pembelajaran yang fleksibel dan adaptif.",
    ],
    pihakPJ: PJ_DEFAULT_AKADEMIK,
    definisi: [
      ["a.", "Proses Pembelajaran", "proses interaksi mahasiswa dengan dosen dan sumber belajar pada suatu lingkungan belajar, baik tatap muka, daring, maupun campuran."],
      ["b.", "Rencana Pembelajaran Semester (RPS)", "dokumen perencanaan pembelajaran untuk satu semester yang memuat capaian, materi, metode, sumber belajar, dan kriteria penilaian."],
      ["c.", "Bentuk Pembelajaran", "metode pelaksanaan pembelajaran meliputi kuliah tatap muka, praktikum, kerja lapangan, simulasi, daring, dan/atau blended learning."],
      ["d.", "Beban Belajar", "jumlah waktu yang dibutuhkan mahasiswa untuk menyelesaikan suatu mata kuliah, dinyatakan dalam Satuan Kredit Semester (SKS)."],
      ["e.", "Student-Centered Learning", "pendekatan pembelajaran yang menempatkan mahasiswa sebagai pelaku aktif, dengan dosen sebagai fasilitator."],
      ["f.", "Blended Learning", "kombinasi pembelajaran tatap muka dan daring yang dirancang untuk mencapai capaian pembelajaran secara optimal."],
      ["g.", "Project-Based Learning", "pendekatan pembelajaran berbasis proyek, di mana mahasiswa mengerjakan proyek nyata untuk mencapai capaian pembelajaran."],
      ["h.", "Learning Management System (LMS)", "platform digital untuk mengelola pembelajaran, materi, tugas, dan penilaian."],
      ["i.", "Satuan Kredit Semester (SKS)", "satuan ukur besarnya beban belajar mahasiswa, dengan 1 SKS setara 170 menit aktivitas per minggu."],
    ],
    pernyataan: [
      "Perencanaan proses pembelajaran meliputi perumusan capaian pembelajaran mata kuliah (CPMK), materi, metode, sumber belajar, dan kriteria penilaian yang dituangkan dalam Rencana Pembelajaran Semester (RPS).",
      "Setiap dosen wajib menyusun RPS untuk setiap mata kuliah yang diampu, dengan mengacu pada CPMK dan struktur kurikulum program studi, dan RPS disahkan oleh Ka. Prodi.",
      "Pelaksanaan proses pembelajaran dilakukan melalui berbagai bentuk interaksi akademik—kuliah tatap muka, praktikum, kerja lapangan, simulasi, daring, dan/atau blended learning—sesuai karakteristik program studi dan capaian pembelajaran.",
      "Beban belajar mahasiswa dihitung berdasarkan waktu yang dibutuhkan untuk aktivitas pembelajaran terstruktur (tatap muka) dan mandiri (self-study), dengan 1 SKS setara dengan 170 menit aktivitas per minggu (50 menit tatap muka + 120 menit mandiri).",
      "Proses pembelajaran dilaksanakan secara interaktif, kolaboratif, dan mendorong kemandirian mahasiswa dalam belajar (student-centered learning).",
      "Universitas Tulungagung mendorong inovasi pembelajaran melalui pemanfaatan teknologi informasi dan pendekatan student-centered learning, termasuk project-based learning, case-based learning, dan flipped classroom.",
      "Setiap dosen wajib melaksanakan pembelajaran minimal 14 kali pertemuan per semester untuk setiap mata kuliah, dengan dokumentasi kehadiran dosen dan mahasiswa.",
      "Universitas Tulungagung menyediakan fasilitas pembelajaran yang memadai—ruang kelas dengan kapasitas sesuai, laboratorium, akses internet, dan platform LMS—untuk mendukung pelaksanaan pembelajaran.",
      "Universitas Tulungagung mendorong dosen untuk melakukan peer teaching observation sebagai mekanisme pembelajaran antar-dosen dan peningkatan kualitas pembelajaran.",
      "Universitas Tulungagung melakukan monitoring pelaksanaan pembelajaran melalui emonev oleh mahasiswa setiap semester, dengan hasil ditindaklanjuti oleh dosen dan Ka. Prodi.",
      "Dosen wajib melaksanakan konsultasi (jam konsultasi) minimal 2 jam per minggu untuk setiap mata kuliah yang diampu, agar mahasiswa dapat berdiskusi di luar jam kelas.",
      "Universitas Tulungagung mengintegrasikan teknologi informasi dalam pembelajaran melalui LMS yang wajib digunakan oleh seluruh dosen untuk materi, tugas, dan komunikasi dengan mahasiswa.",
    ],
    strategi: [
      "Menyelenggarakan pelatihan penyusunan RPS bagi dosen setiap awal semester, dengan template RPS yang baku dan contoh best practice.",
      "Mengembangkan sistem informasi akademik (SIAKAD) yang mendukung pengelolaan RPS secara digital, termasuk template, review, dan approval.",
      "Mendorong dosen untuk mengadopsi metode pembelajaran inovatif melalui workshop, sharing session, dan reward untuk best practice.",
      "Melakukan peer teaching observation antar-dosen minimal 1 kali per semester untuk monitoring kualitas pembelajaran dan pembelajaran antar-dosen.",
      "Menyediakan fasilitas pembelajaran yang memadai—ruang kelas, laboratorium, akses internet, dan platform LMS—dengan maintenance berkala.",
      "Melakukan monitoring pelaksanaan pembelajaran melalui emonev oleh mahasiswa setiap semester, dengan hasil ditindaklanjuti oleh dosen dan Ka. Prodi.",
      "Mengembangkan program pengembangan dosen (academic development) melalui pelatihan pedagogi, andragogi, dan pemanfaatan teknologi pembelajaran.",
      "Menyelenggarakan kompetisi dosen berprestasi setiap tahun untuk mendorong kualitas pembelajaran dan reward bagi dosen yang berkinerja baik.",
    ],
    indikator: [
      { indikator: "Persentase dosen yang menyusun RPS sesuai template baku", strategi: "Pelatihan & monitoring", unit: "GKM", baseline: 90, target: [96, 100, 100, 100, 100] },
      { indikator: "Persentase RPS yang sesuai CPMK dan dipetakan ke CPL", strategi: "Audit RPS", unit: "GKM", baseline: 80, target: [88, 94, 100, 100, 100] },
      { indikator: "Persentase mata kuliah dengan metode pembelajaran inovatif (PBL, CBL, flipped)", strategi: "Workshop & reward", unit: "UPPS", baseline: 35, target: [50, 65, 78, 88, 95] },
      { indikator: "Tingkat kepuasan mahasiswa terhadap proses pembelajaran (emonev)", strategi: "Survey emonev", unit: "PPM", baseline: 72, target: [78, 83, 87, 91, 95] },
      { indikator: "Jumlah mata kuliah yang menggunakan LMS", strategi: "Integrasi IT", unit: "UPT SI", baseline: 55, target: [70, 82, 92, 100, 100] },
      { indikator: "Jumlah pertemuan per semester rata-rata per mata kuliah", strategi: "Monitoring absensi", unit: "GKM", baseline: 12, target: [13, 14, 14, 14, 14] },
      { indikator: "Persentase dosen yang melaksanakan jam konsultasi", strategi: "Monitoring", unit: "GKM", baseline: 50, target: [65, 78, 88, 95, 100] },
      { indikator: "Jumlah peer teaching observation per semester", strategi: "Program pengembangan", unit: "UPPS", baseline: 30, target: [50, 75, 105, 140, 180] },
      { indikator: "Persentase RPS yang disetujui Ka. Prodi sebelum semester dimulai", strategi: "SOP approval", unit: "UPPS", baseline: 75, target: [85, 92, 97, 100, 100] },
      { indikator: "Jumlah dosen yang mengikuti pelatihan pedagogi per tahun", strategi: "Program diklat", unit: "PPM", baseline: 40, target: [60, 85, 115, 145, 180] },
      { indikator: "Tingkat kehadiran dosen dalam pembelajaran", strategi: "Monitoring", unit: "GKM", baseline: 88, target: [92, 95, 97, 99, 100] },
      { indikator: "Tingkat kehadiran mahasiswa dalam pembelajaran", strategi: "Monitoring", unit: "GKM", baseline: 80, target: [85, 90, 93, 96, 98] },
      { indikator: "Jumlah mata kuliah dengan blended learning", strategi: "Pengembangan IT", unit: "UPT SI", baseline: 20, target: [35, 55, 80, 110, 145] },
      { indikator: "Jumlah dosen penerima reward dosen berprestasi per tahun", strategi: "Reward system", unit: "Rektor", baseline: 5, target: [8, 12, 18, 25, 35] },
      { indikator: "Persentase kelas dengan fasilitas IT memadai (proyektor, AC, WiFi)", strategi: "Investasi", unit: "BAU", baseline: 70, target: [80, 88, 94, 98, 100] },
    ],
    dokumenTerkait: DOKUMEN_TERKAIT_DEFAULT,
  },
  {
    namaStandar: "STANDAR PENILAIAN",
    kodeStandar: "SPN",
    rasional: [
      "Standar Penilaian merupakan bagian dari standar proses pendidikan yang mengatur kriteria minimal penilaian proses pembelajaran oleh dosen dan penilaian capaian pembelajaran. Penilaian dilakukan secara objektif, transparan, akuntabel, dan berkeadilan, menggunakan berbagai metode yang sesuai dengan karakteristik mata kuliah dan capaian pembelajaran. Hasil penilaian digunakan untuk perbaikan proses pembelajaran dan menjadi bahan evaluasi kinerja dosen serta kualitas kurikulum.",
      "Universitas Tulungagung memandang penilaian sebagai instrumen strategis untuk memastikan ketercapaian CPL dan kualitas lulusan. Penilaian yang baik bukan sekadar pemberian angka, melainkan proses sistematis untuk mengukur, menganalisis, dan memperbaiki pembelajaran. Universitas Tulungagung mendorong pendekatan penilaian autentik (authentic assessment) yang mengukur kompetensi nyata mahasiswa, bukan sekadar hafalan.",
      "Penilaian harus mencakup penilaian formatif (selama proses pembelajaran) dan sumatif (di akhir periode pembelajaran), dengan proporsi yang seimbang. Penilaian formatif digunakan untuk monitoring kemajuan mahasiswa dan perbaikan proses pembelajaran, sedangkan penilaian sumatif digunakan untuk menentukan kelulusan. Universitas Tulungagung mengembangkan rubrik penilaian yang baku untuk setiap jenis tugas, sehingga penilaian menjadi objektif dan konsisten antar-dosen.",
      "Hasil penilaian didokumentasikan secara sistematis dalam SIAKAD, dan dapat diakses oleh mahasiswa secara real-time. Universitas Tulungagung juga melakukan analisis hasil penilaian untuk mengidentifikasi mata kuliah dengan tingkat kelulusan rendah, sehingga dapat dilakukan intervensi yang tepat. Selain itu, hasil penilaian juga menjadi bahan bagi evaluasi kurikulum dan evaluasi kinerja dosen dalam RTM tahunan.",
    ],
    pihakPJ: PJ_DEFAULT_AKADEMIK,
    definisi: [
      ["a.", "Penilaian", "proses pengumpulan dan pengolahan informasi untuk mengukur ketercapaian capaian pembelajaran."],
      ["b.", "Penilaian Formatif", "penilaian yang dilakukan selama proses pembelajaran untuk monitoring kemajuan mahasiswa dan perbaikan proses."],
      ["c.", "Penilaian Sumatif", "penilaian yang dilakukan pada akhir periode pembelajaran untuk menentukan kelulusan."],
      ["d.", "Penilaian Autentik", "penilaian yang mengukur kompetensi nyata mahasiswa melalui tugas atau proyek kontekstual."],
      ["e.", "Rubrik", "dokumen yang memuat kriteria penilaian dan deskripsi level kinerja untuk setiap kriteria."],
      ["f.", "Norm-Referenced Assessment", "penilaian yang membandingkan kinerja mahasiswa dengan kinerja kelompok."],
      ["g.", "Criterion-Referenced Assessment", "penilaian yang membandingkan kinerja mahasiswa dengan kriteria yang ditetapkan."],
      ["h.", "Analisis Butir Soal", "analisis kualitas soal berdasarkan tingkat kesukaran dan daya beda."],
      ["i.", "Bobot Penilaian", "proporsi nilai dari setiap komponen penilaian (tugas, UTS, UAS, praktikum, dll.) terhadap nilai akhir."],
    ],
    pernyataan: [
      "Penilaian proses pembelajaran oleh dosen dilakukan secara objektif, transparan, akuntabel, dan berkeadilan, dengan kriteria yang disampaikan kepada mahasiswa di awal semester.",
      "Penilaian menggunakan berbagai metode yang sesuai dengan karakteristik mata kuliah dan capaian pembelajaran, meliputi penilaian formatif (tugas, kuis, presentasi) dan sumatif (UTS, UAS, tugas akhir).",
      "Kriteria dan rubrik penilaian disampaikan kepada mahasiswa pada awal semester melalui RPS, sehingga mahasiswa memahami expectation dan cara dinilai.",
      "Universitas Tulungagung mendorong penerapan penilaian autentik yang mengukur kompetensi nyata mahasiswa, seperti proyek, portofolio, presentasi, dan simulasi.",
      "Hasil penilaian didokumentasikan secara sistematis dalam SIAKAD dan dapat diakses oleh mahasiswa secara real-time.",
      "Dosen wajib menginput nilai minimal 5 hari kerja setelah pelaksanaan UAS, dengan konsekuensi administratif bagi yang terlambat.",
      "Universitas Tulungagung menerapkan bobot penilaian yang seimbang antara penilaian formatif (minimal 40%) dan sumatif (maksimal 60%).",
      "Setiap dosen wajib menyusun rubrik penilaian untuk tugas-tugas mahasiswa, dan rubrik didokumentasikan dalam RPS dan SIAKAD.",
      "Universitas Tulungagung melakukan audit penilaian oleh GKM minimal 1 kali per semester untuk memastikan objektivitas dan konsistensi.",
      "Hasil penilaian dianalisis untuk perbaikan proses pembelajaran dan evaluasi kualitas kurikulum, dengan analisis mata kuliah dengan tingkat kelulusan rendah.",
      "Mahasiswa berhak melakukan klarifikasi atau banding atas nilai yang diberikan, dengan mekanisme yang diatur dalam SOP penilaian.",
      "Universitas Tulungagung melakukan analisis butir soal untuk soal-soal UTS dan UAS, sebagai bagian dari quality assurance penilaian.",
    ],
    strategi: [
      "Menyelenggarakan pelatihan penilaian autentik dan penyusunan rubrik bagi dosen setiap tahun, dengan narasumber ahli evaluasi pendidikan.",
      "Menyediakan template rubrik penilaian yang dapat diadaptasi dosen untuk berbagai jenis tugas, dan didistribusikan melalui SIAKAD.",
      "Mengintegrasikan sistem penilaian dengan SIAKAD untuk transparansi dan dokumentasi, dengan akses real-time bagi mahasiswa.",
      "Melakukan audit penilaian oleh GKM minimal 1 kali per semester untuk memastikan objektivitas dan konsistensi antar-dosen.",
      "Menggunakan hasil penilaian sebagai bahan analisis kelulusan dan capaian CPL dalam RTM tahunan, dengan fokus pada mata kuliah dengan kelulusan rendah.",
      "Menyelenggarakan workshop analisis butir soal bagi dosen, sehingga kualitas soal UTS dan UAS dapat terjamin.",
      "Mengembangkan sistem banding nilai yang transparan dan akuntabel, dengan SOP yang jelas dan timeline yang tertib.",
      "Mengintegrasikan penilaian dengan LMS untuk otomatisasi penilaian tugas, kuis, dan presentasi, sehingga beban administratif dosen berkurang.",
    ],
    indikator: [
      { indikator: "Persentase mata kuliah dengan rubrik penilaian", strategi: "Audit rubrik", unit: "GKM", baseline: 65, target: [78, 88, 95, 100, 100] },
      { indikator: "Persentase dosen yang menerapkan penilaian autentik", strategi: "Pelatihan", unit: "UPPS", baseline: 30, target: [45, 60, 75, 88, 95] },
      { indikator: "Tingkat kepuasan mahasiswa terhadap transparansi penilaian", strategi: "Survey emonev", unit: "PPM", baseline: 68, target: [76, 82, 88, 93, 96] },
      { indikator: "Persentase nilai yang diinput tepat waktu di SIAKAD (<5 hari kerja)", strategi: "Monitoring & sanksi", unit: "BAA", baseline: 80, target: [88, 94, 98, 100, 100] },
      { indikator: "Jumlah analisis capaian CPL berbasis hasil penilaian", strategi: "Workshop", unit: "GKM", baseline: 10, target: [18, 28, 40, 55, 70] },
      { indikator: "Persentase mata kuliah dengan bobot formatif ≥40%", strategi: "Audit RPS", unit: "GKM", baseline: 60, target: [72, 82, 90, 96, 100] },
      { indikator: "Jumlah audit penilaian oleh GKM per semester", strategi: "Program audit", unit: "GKM", baseline: 15, target: [22, 32, 45, 60, 75] },
      { indikator: "Persentase soal UTS/UAS dengan analisis butir soal", strategi: "Workshop ABS", unit: "GKM", baseline: 20, target: [35, 50, 65, 80, 92] },
      { indikator: "Jumlah banding nilai yang diproses per semester", strategi: "SOP banding", unit: "BAA", baseline: 25, target: [15, 10, 8, 5, 3] },
      { indikator: "Persentase dosen yang mengikuti pelatihan penilaian per tahun", strategi: "Program diklat", unit: "PPM", baseline: 35, target: [50, 65, 80, 92, 100] },
      { indikator: "Tingkat kelulusan mata kuliah rata-rata", strategi: "Analisis & intervensi", unit: "GKM", baseline: 85, target: [88, 91, 93, 95, 96] },
      { indikator: "Jumlah mata kuliah dengan integrasi LMS untuk penilaian", strategi: "Pengembangan IT", unit: "UPT SI", baseline: 40, target: [60, 80, 95, 100, 100] },
      { indikator: "Persentase mahasiswa yang dapat akses nilai real-time di SIAKAD", strategi: "Transparansi", unit: "UPT SI", baseline: 90, target: [98, 100, 100, 100, 100] },
      { indikator: "Jumlah dosen yang menggunakan rubrik digital di LMS", strategi: "Pengembangan IT", unit: "UPT SI", baseline: 25, target: [45, 70, 95, 120, 145] },
      { indikator: "Tingkat kepuasan dosen terhadap sistem penilaian SIAKAD", strategi: "Survey", unit: "PPM", baseline: 65, target: [75, 84, 90, 94, 97] },
    ],
    dokumenTerkait: DOKUMEN_TERKAIT_DEFAULT,
  },
  {
    namaStandar: "STANDAR PENGELOLAAN",
    kodeStandar: "SPP",
    rasional: [
      "Standar Pengelolaan merupakan bagian dari standar proses pendidikan yang mengatur kriteria minimal pengelolaan program studi oleh Unit Pengelola Program Studi (UPPS). Standar ini mencakup perencanaan, pelaksanaan, monitoring, evaluasi, dan perbaikan. UPPS bertanggung jawab atas penyelenggaraan program studi secara menyeluruh, termasuk pengelolaan kurikulum, dosen, mahasiswa, sarana prasarana, dan kerja sama. Standar ini memastikan bahwa setiap program studi dikelola secara profesional dan akuntabel.",
      "Universitas Tulungagung memandang pengelolaan program studi sebagai proses manajemen yang memerlukan kapasitas struktural, sistem informasi, dan mekanisme evaluasi yang kuat. Pengelolaan yang baik menjadi prasyarat bagi tercapainya kualitas Tridharma, sehingga standar ini menjadi fondasi bagi standar-standar lainnya. Universitas Tulungagung berkomitmen untuk memperkuat kapasitas UPPS melalui pelatihan, pendampingan, dan pemanfaatan teknologi informasi.",
      "UPPS bertanggung jawab atas penyusunan rencana operasional tahunan, pelaksanaan kurikulum, monitoring kinerja dosen dan mahasiswa, evaluasi capaian, dan pelaporan kepada Dekan dan Rektor. UPPS juga berkoordinasi dengan GKM, LPM, dan PPM dalam pelaksanaan SPMI di tingkat program studi. Universitas Tulungagung memastikan bahwa setiap UPPS memiliki struktur organisasi yang jelas, SOP yang terdokumentasi, dan mekanisme evaluasi yang efektif.",
      "Sebagai bagian daritata kelola perguruan tinggi yang baik sebagaimana diatur dalam Pasal 67 ayat (2) Permen 39 Tahun 2025, pengelolaan program studi harus menerapkan prinsip akuntabilitas, transparansi, nirlaba, efektivitas, efisiensi, dan peningkatan mutu berkelanjutan. Universitas Tulungagung mengembangkan sistem informasi manajemen program studi yang terintegrasi, sehingga UPPS dapat mengelola data dan informasi secara efisien dan akuntabel.",
    ],
    pihakPJ: PJ_DEFAULT_AKADEMIK,
    definisi: [
      ["a.", "Pengelolaan", "serangkaian kegiatan perencanaan, pelaksanaan, monitoring, evaluasi, dan perbaikan program studi."],
      ["b.", "UPPS", "Unit Pengelola Program Studi yang bertanggung jawab atas penyelenggaraan program studi."],
      ["c.", "SOTK", "Struktur Organisasi dan Tata Kerja yang mengatur pembagian tugas dan wewenang."],
      ["d.", "Sistem Informasi", "platform digital untuk pengelolaan data dan informasi program studi."],
      ["e.", "Rencana Operasional", "dokumen perencanaan tahunan yang diturunkan dari Renstra, memuat kegiatan, target, dan anggaran."],
      ["f.", "Monitoring", "kegiatan pengawasan rutin terhadap pelaksanaan rencana operasional."],
      ["g.", "Evaluasi", "kegiatan penilaian terhadap capaian kinerja program studi."],
      ["h.", "Dashboard Kinerja", "tampilan visual data kinerja program studi yang dapat diakses real-time."],
      ["i.", "Kerja Sama", "hubungan formal dengan pihak eksternal untuk mendukung penyelenggaraan program studi."],
    ],
    pernyataan: [
      "UPPS memiliki struktur organisasi dan tata kerja (SOTK) yang jelas, dengan pembagian tugas dan wewenang yang terdokumentasi.",
      "UPPS menyusun rencana operasional tahunan yang diturunkan dari Renstra universitas dan fakultas, dengan target dan indikator yang terukur.",
      "UPPS melaksanakan rencana operasional dengan koordinasi antar-fungsi (akademik, kemahasiswaan, SDM, sarpras) dan dokumentasi yang sistematis.",
      "UPPS melakukan monitoring berkala terhadap pelaksanaan program studi, melalui rapat rutin, observasi, dan analisis data.",
      "UPPS memiliki sistem informasi yang terintegrasi untuk pengelolaan data mahasiswa, dosen, kurikulum, dan lulusan.",
      "UPPS berkoordinasi dengan GKM, LPM, dan PPM dalam pelaksanaan SPMI di tingkat program studi, dengan rapat rutin dan dokumentasi.",
      "UPPS menyusun laporan kinerja tahunan yang disampaikan kepada Dekan dan Rektor, dengan analisis pencapaian dan rekomendasi.",
      "UPPS melakukan evaluasi diri tahunan dengan instrumen yang baku, dan hasil evaluasi menjadi basis bagi perbaikan berkelanjutan.",
      "UPPS memiliki SOP untuk setiap aktivitas strategis—penerimaan mahasiswa, registrasi, pembelajaran, penilaian, kelulusan, dan layanan mahasiswa.",
      "UPPS mengelola kerja sama dengan DUDI untuk MBKM, magang, dan penelitian, dengan dokumentasi MoU/MoA yang jelas.",
      "UPPS memiliki dashboard kinerja digital yang dapat diakses oleh pimpinan dan pemangku kepentingan, dengan data real-time.",
      "UPPS melakukan benchmarking dengan program studi sejenis di PT lain minimal 1 kali per tahun untuk pembelajaran dan perbaikan.",
    ],
    strategi: [
      "Memperkuat kapasitas UPPS melalui pelatihan manajemen pendidikan tinggi, dengan kurikulum yang mencakup perencanaan, monitoring, dan evaluasi.",
      "Mengembangkan sistem informasi terintegrasi untuk pengelolaan program studi, dengan modul mahasiswa, dosen, kurikulum, keuangan, dan lulusan.",
      "Melakukan monitoring dan evaluasi berkala oleh Dekan terhadap kinerja UPPS, dengan dashboard kinerja dan rapat rutin.",
      "Menyelenggarakan rapat koordinasi rutin antara UPPS, GKM, LPM, dan PPM minimal 1 kali per bulan.",
      "Mengembangkan dashboard kinerja program studi yang dapat diakses real-time oleh pimpinan dan pemangku kepentingan.",
      "Menyusun SOP baku untuk setiap aktivitas strategis UPPS, dengan template dan contoh best practice.",
      "Melakukan benchmarking tahunan dengan program studi sejenis di PT unggulan, dan mengadopsi praktik baik.",
      "Mengembangkan sistem pengelolaan kerja sama DUDI yang terpusat di fakultas, dengan database MoU/MoA yang terintegrasi.",
    ],
    indikator: [
      { indikator: "Persentase prodi dengan SOTK terdokumentasi dan disosialisasikan", strategi: "Audit SOTK", unit: "UPPS", baseline: 85, target: [92, 97, 100, 100, 100] },
      { indikator: "Persentase prodi dengan rencana operasional tahunan", strategi: "Monitoring", unit: "UPPS", baseline: 80, target: [92, 100, 100, 100, 100] },
      { indikator: "Persentase prodi dengan laporan kinerja tahunan", strategi: "Audit", unit: "UPPS", baseline: 75, target: [88, 96, 100, 100, 100] },
      { indikator: "Tingkat kepuasan mahasiswa terhadap layanan prodi", strategi: "Survey", unit: "PPM", baseline: 70, target: [76, 82, 87, 92, 96] },
      { indikator: "Jumlah prodi dengan dashboard kinerja digital", strategi: "Pengembangan IT", unit: "UPT SI", baseline: 5, target: [15, 30, 50, 75, 100] },
      { indikator: "Jumlah rapat koordinasi UPPS-GKM-LPM-PPM per tahun", strategi: "Jadwal rutin", unit: "UPPS", baseline: 60, target: [80, 100, 120, 140, 160] },
      { indikator: "Persentase prodi dengan SOP baku untuk aktivitas strategis", strategi: "Penyusunan SOP", unit: "UPPS", baseline: 60, target: [75, 88, 95, 100, 100] },
      { indikator: "Jumlah benchmarking dengan prodi sejenis per tahun", strategi: "Networking", unit: "UPPS", baseline: 10, target: [20, 30, 45, 60, 80] },
      { indikator: "Persentase prodi dengan evaluasi diri tahunan", strategi: "Monitoring", unit: "PPM", baseline: 70, target: [85, 95, 100, 100, 100] },
      { indikator: "Jumlah kerjasama DUDI per prodi per tahun", strategi: "Pengembangan", unit: "UPPS", baseline: 3, target: [5, 8, 12, 18, 25] },
      { indikator: "Persentase data prodi terintegrasi dengan PD Dikti", strategi: "IT integration", unit: "UPT SI", baseline: 70, target: [82, 92, 98, 100, 100] },
      { indikator: "Jumlah pelatihan manajemen UPPS per tahun", strategi: "Program diklat", unit: "PPM", baseline: 2, target: [4, 6, 10, 14, 18] },
      { indikator: "Tingkat kepuasan dosen terhadap pengelolaan prodi", strategi: "Survey", unit: "PPM", baseline: 68, target: [75, 82, 88, 93, 96] },
      { indikator: "Persentase rekomendasi evaluasi yang ditindaklanjuti", strategi: "Monitoring", unit: "UPPS", baseline: 60, target: [72, 82, 90, 96, 100] },
      { indikator: "Jumlah prodi yang mengadopsi praktik baik dari benchmarking", strategi: "Adopsi best practice", unit: "UPPS", baseline: 8, target: [15, 25, 38, 55, 75] },
    ],
    dokumenTerkait: DOKUMEN_TERKAIT_DEFAULT,
  },
  {
    namaStandar: "STANDAR ISI",
    kodeStandar: "SIS",
    rasional: [
      "Standar Isi merupakan bagian dari standar masukan pendidikan yang mengatur kriteria minimal substansi kurikulum dan bahan ajar. Standar ini mencakup struktur kurikulum, mata kuliah, beban belajar, dan capaian pembelajaran mata kuliah. Standar Isi juga mengatur tentang Merdeka Belajar Kampus Merdeka (MBKM) yang memungkinkan mahasiswa mengambil kegiatan di luar program studi selama 1-2 semester dengan pengakuan SKS. Standar ini menjadi acuan bagi setiap program studi dalam menyusun dan mengevaluasi kurikulum.",
      "Universitas Tulungagung memandang kurikulum sebagai jantung dari penyelenggaraan pendidikan tinggi. Kurikulum yang baik harus selaras dengan kebutuhan DUDI, perkembangan IPTEK, dan visi-misi perguruan tinggi. Universitas Tulungagung mendorong setiap program studi untuk melakukan review kurikulum secara berkala—minimal setiap dua tahun—dengan melibatkan DUDI, asosiasi program studi, dan alumni, sehingga kurikulum selalu relevan dengan kebutuhan zaman.",
      "Kurikulum harus disusun dengan pendekatan konstruktif alignment, di mana CPL diturunkan ke CPMK, dan CPMK diturunkan ke materi mata kuliah, metode pembelajaran, dan penilaian. Pendekatan ini memastikan bahwa setiap elemen kurikulum berkontribusi pada pencapaian CPL, sehingga lulusan benar-benar memiliki kompetensi yang diharapkan. Universitas Tulungagung mengembangkan template kurikulum yang baku, dengan struktur yang jelas: MK wajib universitas, MK wajib fakultas, MK inti prodi, MK pilihan, dan MK MBKM.",
      "Sebagai bagian dari MBKM, Universitas Tulungagung memberikan ruang bagi mahasiswa untuk mengambil kegiatan di luar program studi selama 1-2 semester, dengan pengakuan SKS setara 20-40 SKS. Kegiatan MBKM yang dapat diambil mencakup magang, studi independen, pertukaran pelajar, asistensi mengajar, proyek kemanusiaan, dan kegiatan wirausaha. Universitas Tulungagung mengembangkan berbagai skema MBKM yang sesuai dengan karakteristik setiap program studi.",
    ],
    pihakPJ: PJ_DEFAULT_AKADEMIK,
    definisi: [
      ["a.", "Kurikulum", "seperangkat rencana dan pengaturan mengenai capaian pembelajaran lulusan, mata kuliah, beban belajar, dan strategi pembelajaran."],
      ["b.", "Mata Kuliah", "satuan pendidikan yang memiliki CPL, CPMK, materi, dan beban belajar tertentu, dinyatakan dalam SKS."],
      ["c.", "Beban Belajar", "jumlah waktu yang dibutuhkan mahasiswa untuk menyelesaikan suatu mata kuliah, dinyatakan dalam SKS."],
      ["d.", "MBKM", "Merdeka Belajar Kampus Merdeka, kebijakan yang memberikan ruang bagi mahasiswa untuk mengambil kegiatan di luar program studi."],
      ["e.", "Konstruktif Alignment", "pendekatan penyusunan kurikulum di mana CPL diturunkan ke CPMK, materi, metode, dan penilaian secara konsisten."],
      ["f.", "MK Wajib Universitas", "mata kuliah wajib yang ditetapkan oleh universitas untuk seluruh program studi (mis. agama, pancasila, bahasa Inggris)."],
      ["g.", "MK Inti Prodi", "mata kuliah inti yang menjadi substansi keilmuan program studi."],
      ["h.", "MK Pilihan", "mata kuliah pilihan yang dapat dipilih mahasiswa untuk memperdalam bidang tertentu."],
      ["i.", "Capaian Pembelajaran Nasional Khusus (CPNK)", "capaian pembelajaran khusus untuk program studi profesi."],
    ],
    pernyataan: [
      "Setiap program studi memiliki kurikulum yang disusun berdasarkan CPL dan memenuhi struktur kurikulum sesuai jenjang (D3, S1, S2, S3).",
      "Kurikulum memuat MK wajib universitas, MK wajib fakultas, MK inti prodi, MK pilihan, dan MK MBKM dengan proporsi yang sesuai dengan karakteristik program studi.",
      "Kurikulum mengintegrasikan CPNK (Capaian Pembelajaran Nasional Khusus) untuk program studi profesi.",
      "Setiap mata kuliah memiliki bobot SKS yang sesuai dengan beban belajar, dengan 1 SKS setara dengan 170 menit aktivitas per minggu (50 menit tatap muka + 120 menit mandiri).",
      "Universitas Tulungagung memberikan ruang bagi mahasiswa untuk mengambil kegiatan MBKM selama 1-2 semester dengan pengakuan SKS setara 20-40 SKS.",
      "Kegiatan MBKM yang dapat diambil mencakup magang, studi independen, pertukaran pelajar, asistensi mengajar, proyek kemanusiaan, dan kegiatan wirausaha.",
      "Kurikulum disusun dengan pendekatan konstruktif alignment, di mana CPL diturunkan ke CPMK, materi, metode, dan penilaian secara konsisten.",
      "Kurikulum dievaluasi secara berkala minimal setiap dua tahun, dengan melibatkan DUDI, asosiasi program studi, dan alumni.",
      "Universitas Tulungagung menyediakan template kurikulum yang baku, dengan struktur yang jelas dan dokumentasi yang sistematis.",
      "Setiap program studi memiliki deskripsi mata kuliah (course outline) yang memuat CPL, CPMK, materi, metode, dan penilaian.",
      "Kurikulum mengintegrasikan soft skills (komunikasi, kerjasama, kepemimpinan, kewirausahaan) dan digital literacy sebagai kompetensi abad 21.",
      "Kurikulum dipublikasikan kepada mahasiswa dan masyarakat melalui SIAKAD dan situs web program studi, sebagai bentuk transparansi.",
    ],
    strategi: [
      "Melakukan review kurikulum setiap dua tahun dengan pendekatan konstruktif alignment, melibatkan DUDI, asosiasi, dan alumni.",
      "Mengembangkan model MBKM yang sesuai dengan karakteristik setiap program studi, dengan skema magang, studi independen, dan pertukaran.",
      "Menyelenggarakan rapat kurikulum tahunan di tingkat program studi dan fakultas, dengan template dan dokumentasi yang baku.",
      "Melibatkan DUDI dan asosiasi program studi dalam penyusunan dan evaluasi kurikulum, melalui focus group discussion dan workshop.",
      "Mengintegrasikan kurikulum dengan SIAKAD untuk monitoring pelaksanaan, dengan dashboard mata kuliah dan CPL.",
      "Menyediakan template course outline (deskripsi mata kuliah) yang baku, dan didistribusikan kepada dosen untuk adaptasi.",
      "Mengembangkan modul soft skills dan digital literacy yang terintegrasi dalam mata kuliah, atau sebagai mata kuliah tersendiri.",
      "Mengundang akademisi eksternal dan praktisi DUDI sebagai reviewer kurikulum, untuk memperoleh perspektif eksternal.",
    ],
    indikator: [
      { indikator: "Persentase prodi yang melakukan review kurikulum 2 tahunan", strategi: "Monitoring", unit: "UPPS", baseline: 65, target: [80, 95, 100, 100, 100] },
      { indikator: "Jumlah prodi yang mengimplementasikan MBKM", strategi: "Sosialisasi", unit: "UPPS", baseline: 25, target: [40, 55, 70, 85, 100] },
      { indikator: "Jumlah mahasiswa yang mengikuti MBKM per tahun", strategi: "Kerjasama DUDI", unit: "UPPS", baseline: 200, target: [350, 550, 800, 1100, 1500] },
      { indikator: "Persentase mata kuliah dengan CPL-CPMK terdokumentasi", strategi: "Audit", unit: "GKM", baseline: 80, target: [90, 96, 100, 100, 100] },
      { indikator: "Jumlah kerjasama DUDI untuk MBKM", strategi: "Pengembangan", unit: "UPPS", baseline: 30, target: [50, 75, 105, 140, 180] },
      { indikator: "Persentase prodi dengan konstruktik alignment terdokumentasi", strategi: "Workshop", unit: "GKM", baseline: 50, target: [70, 85, 95, 100, 100] },
      { indikator: "Jumlah prodi yang melibatkan DUDI dalam review kurikulum", strategi: "Networking", unit: "UPPS", baseline: 20, target: [35, 55, 75, 90, 100] },
      { indikator: "Jumlah modul soft skills yang terintegrasi", strategi: "Pengembangan", unit: "UPPS", baseline: 15, target: [25, 40, 60, 80, 100] },
      { indikator: "Persentase MK dengan course outline lengkap", strategi: "Audit", unit: "GKM", baseline: 75, target: [85, 92, 97, 100, 100] },
      { indikator: "Jumlah prodi dengan kurikulum dipublikasikan di web", strategi: "Transparansi", unit: "UPT SI", baseline: 60, target: [75, 88, 95, 100, 100] },
      { indikator: "Tingkat kepuasan mahasiswa terhadap kurikulum", strategi: "Survey", unit: "PPM", baseline: 70, target: [76, 82, 87, 92, 96] },
      { indikator: "Jumlah prodi yang mengintegrasikan digital literacy", strategi: "Pengembangan", unit: "UPPS", baseline: 15, target: [30, 50, 70, 88, 100] },
      { indikator: "Jumlah reviewer eksternal yang dilibatkan per tahun", strategi: "Networking", unit: "UPPS", baseline: 10, target: [18, 28, 40, 55, 70] },
      { indikator: "Persentase prodi dengan kurikulum terintegrasi SIAKAD", strategi: "IT integration", unit: "UPT SI", baseline: 70, target: [82, 92, 98, 100, 100] },
      { indikator: "Jumlah skema MBKM yang dikembangkan per prodi", strategi: "Inovasi", unit: "UPPS", baseline: 2, target: [4, 6, 8, 10, 12] },
    ],
    dokumenTerkait: DOKUMEN_TERKAIT_DEFAULT,
  },
  {
    namaStandar: "STANDAR DOSEN DAN TENAGA KEPENDIDIKAN",
    kodeStandar: "SDT",
    rasional: [
      "Standar Dosen dan Tenaga Kependidikan merupakan bagian dari standar masukan pendidikan yang mengatur kriteria minimal kualifikasi, kompetensi, dan beban kerja dosen serta tenaga kependidikan. Dosen wajib memiliki kualifikasi minimal magister untuk program sarjana dan doktor untuk program magister/doktor, serta memiliki sertifikat pendidik. Tenaga kependidikan wajib memiliki kualifikasi dan kompetensi yang sesuai dengan tugasnya.",
      "Universitas Tulungagung memandang dosen dan tenaga kependidikan sebagai aset strategis yang menentukan kualitas Tridharma. Universitas Tulungagung berkomitmen untuk meningkatkan kualifikasi dan kompetensi dosen melalui studi lanjut, pelatihan, dan sertifikasi. Selain itu, Universitas Tulungagung juga memastikan rasio dosen-mahasiswa memenuhi standar dan beban kerja dosen seimbang antara pendidikan, penelitian, dan PkM.",
      "Beban kerja dosen di Universitas Tulungagung dihitung berdasarkan ekuivalen SKS, dengan total minimal 12 SKS dan maksimal 16 SKS per semester. Beban kerja ini mencakup pendidikan (kuliah, praktikum, pembimbingan), penelitian (riset, publikasi), dan PkM (pengabdian, konsultasi). Universitas Tulungagung memastikan bahwa beban kerja dosen seimbang, sehingga dosen dapat memberikan kontribusi optimal pada Tridharma tanpa kelelahan yang berlebihan.",
      "Universitas Tulungagung juga mengembangkan sistem pengembangan karir dosen yang jelas, mulai dari Asisten Ahli hingga Guru Besar, dengan kriteria promosi yang transparan. Selain itu, Universitas Tulungagung juga menyediakan program pengembangan kapasitas tenaga kependidikan—pelatihan teknis, pelatihan manajemen, dan sertifikasi profesi—sehingga tenaga kependidikan dapat memberikan dukungan optimal bagi penyelenggaraan Tridharma.",
    ],
    pihakPJ: PJ_DEFAULT_NONAKADEMIK,
    definisi: [
      ["a.", "Dosen", "pendidik profesional dan ilmuwan dengan tugas utama mentransformasi, mengembangkan, dan menyebarluaskan IPTEK melalui pendidikan, penelitian, dan PkM."],
      ["b.", "Tenaga Kependidikan", "anggota sivitas akademika yang bertugas mengelola, menyelenggarakan, dan/atau melayani urusan administrasi pendidikan."],
      ["c.", "Sertifikat Pendidik (Serdos)", "pengakuan formal terhadap kompetensi dosen sebagai pendidik profesional."],
      ["d.", "Beban Kerja Dosen", "jumlah kegiatan dosen dalam pendidikan, penelitian, dan PkM, dinyatakan dalam ekuivalen SKS."],
      ["e.", "Jabatan Akademik", "jenjang karir dosen: Asisten Ahli, Lektor, Lektor Kepala, Guru Besar."],
      ["f.", "NIDN", "Nomor Induk Dosen Nasional, identitas dosen tetap di PD Dikti."],
      ["g.", "NIDK", "Nomor Induk Dosen Khusus, identitas dosen tidak tetap di PD Dikti."],
      ["h.", "SKP", "Sasaran Kinerja Pegawai, dokumen penilaian kinerja dosen dan tenaga kependidikan."],
      ["i.", "Kompetensi Dosen", "kompetensi pedagogik, profesional, kepribadian, dan sosial yang dimiliki dosen."],
    ],
    pernyataan: [
      "Dosen wajib memiliki kualifikasi minimal magister untuk program sarjana dan doktor untuk program magister/doktor.",
      "Dosen wajib memiliki sertifikat pendidik profesional (Serdos) yang diterbitkan oleh Diktiristek.",
      "Rasio dosen-mahasiswa memenuhi standar minimal sesuai jenjang program (S1 maks 1:45, S2 maks 1:20, S3 maks 1:10).",
      "Beban kerja dosen seimbang antara pendidikan, penelitian, dan PkM, dengan total minimal 12 SKS dan maksimal 16 SKS per semester.",
      "Tenaga kependidikan memiliki kualifikasi dan kompetensi yang sesuai dengan tugasnya, minimal D3 untuk pekerjaan administratif.",
      "Universitas Tulungagung menyediakan program pengembangan kapasitas dosen dan tenaga kependidikan secara berkelanjutan.",
      "Universitas Tulungagung mengembangkan sistem pengembangan karir dosen yang jelas, dari Asisten Ahli hingga Guru Besar, dengan kriteria promosi transparan.",
      "Setiap dosen wajib menyusun SKP (Sasaran Kinerja Pegawai) tahunan, dengan penilaian oleh atasan dan dokumentasi yang sistematis.",
      "Universitas Tulungagung memastikan bahwa beban kerja dosen tidak melebihi 16 SKS per semester, untuk menjaga keseimbangan dan kualitas.",
      "Universitas Tulungagung memberikan dukungan studi lanjut (S2/S3) bagi dosen yang belum memenuhi kualifikasi minimal.",
      "Universitas Tulungagung menyediakan pelatihan kompetensi dosen (pedagogik, profesional, kepribadian, sosial) secara berkala.",
      "Universitas Tulungagung mengembangkan sistem informasi SDM yang terintegrasi dengan PD Dikti, untuk monitoring kualifikasi dan beban kerja.",
    ],
    strategi: [
      "Memberikan dukungan studi lanjut (beasiswa, cuti studi) bagi dosen untuk mencapai kualifikasi minimal yang dipersyaratkan.",
      "Menyelenggarakan pelatihan Serdos dan sertifikasi profesi bagi dosen, dengan target peningkatan jumlah Serdos setiap tahun.",
      "Melakukan audit beban kerja dosen setiap semester untuk memastikan keseimbangan, dengan eskalasi ke pimpinan bagi yang melampaui 16 SKS.",
      "Menyelenggarakan pelatihan kompetensi bagi tenaga kependidikan sesuai bidang tugas, dengan target setiap tendik mengikuti 1 pelatihan per tahun.",
      "Mengembangkan sistem informasi SDM untuk monitoring kualifikasi, beban kerja, dan kinerja dosen dan tenaga kependidikan.",
      "Menyusun SOP promosi jabatan akademik yang transparan, dengan kriteria yang jelas dan timeline yang tertib.",
      "Memberikan reward dan apresiasi bagi dosen dan tenaga kependidikan yang berprestasi, melalui award tahunan.",
      "Mengembangkan program mentoring bagi dosen muda oleh dosen senior, untuk transfer pengetahuan dan pengalaman.",
    ],
    indikator: [
      { indikator: "Persentase dosen S1 yang sedang studi lanjut S2/S3", strategi: "Dukungan studi", unit: "BAKU", baseline: 15, target: [22, 30, 38, 45, 52] },
      { indikator: "Persentase dosen dengan Serdos", strategi: "Pelatihan Serdos", unit: "BAKU", baseline: 40, target: [52, 65, 76, 86, 93] },
      { indikator: "Rasio dosen-mahasiswa rata-rata (S1)", strategi: "Rekrutmen", unit: "BAKU", baseline: "1:35", target: ["1:32", "1:30", "1:28", "1:25", "1:22"] },
      { indikator: "Persentase dosen dengan beban kerja 12-16 SKS", strategi: "Audit beban", unit: "GKM", baseline: 65, target: [78, 88, 95, 100, 100] },
      { indikator: "Jumlah pelatihan tenaga kependidikan per tahun", strategi: "Program diklat", unit: "BAKU", baseline: 10, target: [16, 24, 32, 42, 52] },
      { indikator: "Persentase tendik dengan kualifikasi minimal D3", strategi: "Studi lanjut", unit: "BAKU", baseline: 75, target: [82, 88, 94, 98, 100] },
      { indikator: "Jumlah dosen yang dipromosikan jabatan akademik per tahun", strategi: "SOP promosi", unit: "BAKU", baseline: 8, target: [14, 22, 32, 45, 60] },
      { indikator: "Persentase dosen dengan SKP >80", strategi: "Penilaian kinerja", unit: "BAKU", baseline: 60, target: [72, 82, 90, 95, 98] },
      { indikator: "Jumlah dosen Guru Besar", strategi: "Pengembangan karir", unit: "BAKU", baseline: 3, target: [5, 8, 12, 18, 25] },
      { indikator: "Jumlah dosen Lektor Kepala", strategi: "Pengembangan karir", unit: "BAKU", baseline: 15, target: [22, 30, 40, 52, 65] },
      { indikator: "Persentase dosen dengan kompetensi pedagogik baik", strategi: "Pelatihan", unit: "PPM", baseline: 70, target: [78, 85, 92, 96, 100] },
      { indikator: "Jumlah mentoring dosen muda per tahun", strategi: "Program mentoring", unit: "PPM", baseline: 10, target: [18, 28, 40, 55, 70] },
      { indikator: "Jumlah award dosen/tendik berprestasi per tahun", strategi: "Reward system", unit: "Rektor", baseline: 5, target: [10, 15, 22, 30, 40] },
      { indikator: "Persentase data SDM terintegrasi PD Dikti", strategi: "IT integration", unit: "UPT SI", baseline: 80, target: [90, 96, 100, 100, 100] },
      { indikator: "Tingkat kepuasan dosen terhadap lingkungan kerja", strategi: "Survey", unit: "SPI", baseline: 68, target: [75, 82, 88, 93, 96] },
    ],
    dokumenTerkait: DOKUMEN_TERKAIT_DEFAULT,
  },
  {
    namaStandar: "STANDAR SARANA DAN PRASARANA",
    kodeStandar: "SSP",
    rasional: [
      "Standar Sarana dan Prasarana merupakan bagian dari standar masukan pendidikan yang mengatur kriteria minimal sarana fisik dan prasarana pendukung penyelenggaraan pendidikan. Standar ini mencakup ruang perkuliahan, laboratorium, perpustakaan, fasilitas ibadah, fasilitas olahraga, dan fasilitas penunjang lainnya. Universitas Tulungagung memastikan bahwa setiap program studi memiliki sarana dan prasarana yang memadai, sesuai dengan karakteristik keilmuan dan jumlah mahasiswa, serta terpelihara dengan baik melalui sistem manajemen fasilitas yang terdokumentasi.",
      "Sarana dan prasarana yang memadai menjadi prasyarat bagi penyelenggaraan Tridharma yang bermutu. Universitas Tulungagung berkomitmen untuk berinvestasi dalam pengembangan sarana dan prasarana secara berkala, dengan prioritas pada laboratorium, perpustakaan digital, dan fasilitas pembelajaran berbasis teknologi. Selain itu, Universitas Tulungagung juga memastikan aksesibilitas sarana bagi seluruh sivitas akademika, termasuk penyandang disabilitas.",
      "Universitas Tulungagung mengelola sarana dan prasarana melalui sistem manajemen fasilitas yang terdokumentasi, meliputi inventarisasi, maintenance, dan pengembangan. Setiap fasilitas memiliki penanggung jawab yang jelas, dan kelayakan fasilitas diaudit secara berkala. Universitas Tulungagung juga mengembangkan smart campus—dengan WiFi campus-wide, smart classroom, dan IoT—untuk meningkatkan efisiensi dan kualitas pelayanan.",
      "Selain sarana fisik, Universitas Tulungagung juga menyediakan sarana digital—seperti LMS, e-library, repository, dan video conference—yang menjadi sarana penunjang pembelajaran modern. Sarana digital ini menjadi semakin penting dalam era MBKM dan blended learning, sehingga Universitas Tulungagung berinvestasi dalam pengembangan dan pemeliharaan sarana digital secara berkelanjutan.",
    ],
    pihakPJ: PJ_DEFAULT_NONAKADEMIK,
    definisi: [
      ["a.", "Sarana", "peralatan dan bahan yang diperlukan untuk penyelenggaraan pendidikan, penelitian, dan PkM."],
      ["b.", "Prasarana", "fasilitas fisik seperti gedung, ruang, lapangan, dan jaringan utilitas."],
      ["c.", "Laboratorium", "fasilitas untuk kegiatan praktikum dan eksperimen, dengan peralatan sesuai standar."],
      ["d.", "Perpustakaan", "fasilitas untuk menyediakan sumber belajar dan referensi akademik, cetak dan digital."],
      ["e.", "Smart Classroom", "ruang kelas dengan teknologi IT (proyektor, smartboard, WiFi, video conference)."],
      ["f.", "Smart Campus", "kampus dengan ekosistem IT terintegrasi (WiFi campus-wide, IoT, mobile apps)."],
      ["g.", "LMS", "Learning Management System, platform digital untuk pengelolaan pembelajaran."],
      ["h.", "E-Library", "perpustakaan digital dengan akses e-book, jurnal, dan database internasional."],
      ["i.", "Sistem Manajemen Fasilitas", "sistem untuk inventarisasi, maintenance, dan pengembangan fasilitas."],
    ],
    pernyataan: [
      "Setiap program studi memiliki ruang perkuliahan yang memadai sesuai jumlah mahasiswa, dengan rasio minimal 1.5 m² per mahasiswa.",
      "Setiap program studi memiliki laboratorium yang sesuai dengan karakteristik keilmuan, dengan peralatan yang memenuhi standar.",
      "Universitas Tulungagung menyediakan perpustakaan dengan koleksi cetak dan digital yang relevan dengan seluruh program studi.",
      "Fasilitas ibadah (musola/masjid), fasilitas olahraga, dan fasilitas penunjang tersedia bagi seluruh sivitas akademika.",
      "Sarana dan prasarana terpelihara dengan baik melalui sistem manajemen fasilitas yang terdokumentasi, dengan maintenance berkala.",
      "Sarana dan prasarana dapat diakses oleh seluruh sivitas akademika, termasuk penyandang disabilitas (universal design).",
      "Universitas Tulungagung menyediakan sarana digital—LMS, e-library, repository, video conference—untuk mendukung pembelajaran modern.",
      "Universitas Tulungagung mengembangkan smart campus dengan WiFi campus-wide, smart classroom, dan mobile apps.",
      "Setiap fasilitas memiliki penanggung jawab yang jelas, dan kelayakan fasilitas diaudit secara berkala minimal 1 kali per tahun.",
      "Universitas Tulungagung menyediakan ruang untuk dosen (work space) yang memadai, sehingga dosen dapat bekerja dengan nyaman.",
      "Universitas Tulungagung menyediakan ruang untuk mahasiswa (student lounge, study area) yang kondusif untuk belajar.",
      "Universitas Tulungagung mengembangkan sistem informasi manajemen fasilitas berbasis IT, untuk monitoring dan maintenance.",
    ],
    strategi: [
      "Menyusun rencana investasi sarana dan prasarana jangka menengah 5 tahunan, dengan prioritas pada laboratorium dan perpustakaan digital.",
      "Melakukan audit fasilitas secara berkala minimal 1 kali per tahun untuk memastikan kelayakan dan keamanan.",
      "Mengembangkan perpustakaan digital dengan akses jurnal dan e-book internasional, melalui kerja sama dengan penyedia database.",
      "Memperluas laboratorium dengan peralatan terkini sesuai kebutuhan program studi, dengan budget tahunan khusus.",
      "Mengimplementasikan sistem manajemen fasilitas berbasis IT untuk monitoring dan maintenance, dengan dashboard real-time.",
      "Mengembangkan smart campus dengan WiFi campus-wide, smart classroom, dan mobile apps untuk civitas akademika.",
      "Menyediakan sarana digital—LMS, e-library, repository, video conference—dengan maintenance dan update berkala.",
      "Mengembangkan universal design untuk seluruh fasilitas baru, sehingga dapat diakses oleh penyandang disabilitas.",
    ],
    indikator: [
      { indikator: "Rasio ruang kelas terhadap mahasiswa (m² per mahasiswa)", strategi: "Investasi", unit: "BAU", baseline: 1.5, target: [1.8, 2.1, 2.4, 2.7, 3.0] },
      { indikator: "Persentase laboratorium dengan peralatan standar", strategi: "Audit & investasi", unit: "UPPS", baseline: 70, target: [80, 88, 94, 98, 100] },
      { indikator: "Jumlah koleksi perpustakaan (cetak + digital)", strategi: "Pengembangan", unit: "UPT Perpus", baseline: 15000, target: [20000, 27000, 35000, 45000, 55000] },
      { indikator: "Persentase gedung dengan akses disabilitas", strategi: "Renovasi", unit: "BAU", baseline: 40, target: [55, 70, 82, 92, 100] },
      { indikator: "Persentase fasilitas terpelihara sesuai standar", strategi: "Sistem manajemen", unit: "BAU", baseline: 75, target: [85, 92, 96, 100, 100] },
      { indikator: "Jumlah smart classroom", strategi: "Investasi IT", unit: "UPT SI", baseline: 15, target: [30, 50, 75, 100, 130] },
      { indikator: "Persentase area kampus dengan WiFi", strategi: "Smart campus", unit: "UPT SI", baseline: 60, target: [75, 88, 95, 100, 100] },
      { indikator: "Jumlah akses e-library per tahun", strategi: "Promosi", unit: "UPT Perpus", baseline: 10000, target: [18000, 28000, 40000, 55000, 70000] },
      { indikator: "Persentase laboratorium dengan SOTK dan SOP", strategi: "Dokumentasi", unit: "UPPS", baseline: 65, target: [80, 92, 100, 100, 100] },
      { indikator: "Jumlah audit fasilitas per tahun", strategi: "Program audit", unit: "BAU", baseline: 2, target: [4, 6, 8, 10, 12] },
      { indikator: "Persentase ruang dosen yang memadai", strategi: "Renovasi", unit: "BAU", baseline: 70, target: [80, 88, 94, 98, 100] },
      { indikator: "Jumlah student lounge/study area", strategi: "Investasi", unit: "BAU", baseline: 5, target: [10, 18, 28, 40, 55] },
      { indikator: "Persentase fasilitas dengan sistem manajemen IT", strategi: "Pengembangan IT", unit: "UPT SI", baseline: 40, target: [55, 70, 85, 95, 100] },
      { indikator: "Tingkat kepuasan sivitas terhadap fasilitas", strategi: "Survey", unit: "PPM", baseline: 65, target: [74, 82, 88, 93, 96] },
      { indikator: "Jumlah fasilitas yang diaudit kelayakan per tahun", strategi: "Audit kelayakan", unit: "BAU", baseline: 8, target: [15, 25, 38, 55, 75] },
    ],
    dokumenTerkait: DOKUMEN_TERKAIT_DEFAULT,
  },
  {
    namaStandar: "STANDAR PEMBIAYAAN",
    kodeStandar: "SPM",
    rasional: [
      "Standar Pembiayaan merupakan bagian dari standar masukan pendidikan yang mengatur kriteria minimal biaya operasional penyelenggaraan pendidikan per mahasiswa. Pembiayaan mencakup biaya pendidikan, biaya penelitian, dan biaya pengabdian kepada masyarakat. Pembiayaan harus dihitung secara transparan dan akuntabel, dengan sumber pendanaan yang berkelanjutan. Universitas Tulungagung memastikan bahwa alokasi anggaran untuk Tridharma mencukupi kebutuhan operasional dan investasi peningkatan mutu, serta dipublikasikan secara terbuka kepada pemangku kepentingan.",
      "Pembiayaan yang memadai menjadi prasyarat bagi penyelenggaraan Tridharma yang bermutu. Universitas Tulungagung mengelola keuangan secara transparan dan akuntabel, dengan mekanisme audit internal dan eksternal yang rutin. Universitas Tulungagung juga mengembangkan sumber pendanaan alternatif—seperti kerja sama DUDI, hibah penelitian, dan program Revenue Generating Unit (RGU)—untuk memperkuat kemandirian finansial.",
      "Biaya Operasional Pendidikan (BOP) per mahasiswa di Universitas Tulungagung dihitung berdasarkan komponen: gaji dosen, honor mengajar, fasilitas, operasional, dan investasi pengembangan. Universitas Tulungagung memastikan bahwa BOP per mahasiswa memenuhi standar minimal yang dipersyaratkan, dan dialokasikan secara proporsional untuk mendukung Tridharma. Selain itu, Universitas Tulungagung juga mengalokasikan dana untuk penelitian dan PkM minimal 15% dari anggaran tahunan, untuk mendukung produktivitas Tridharma.",
      "Sebagai bagian dari tata kelola yang baik, Universitas Tulungagung melakukan audit keuangan internal oleh SPI setiap tahun, dan audit eksternal oleh Kantor Akuntan Publik (KAP) setiap tahun. Opini audit eksternal menjadi indikator kualitas tata kelola keuangan, dan Universitas Tulungagung menargetkan opini Wajar Tanpa Pengecualian (WTP) setiap tahun. Laporan keuangan tahunan dipublikasikan kepada pemangku kepentingan melalui situs web resmi.",
    ],
    pihakPJ: PJ_DEFAULT_NONAKADEMIK,
    definisi: [
      ["a.", "Biaya Pendidikan", "biaya operasional untuk penyelenggaraan pendidikan per mahasiswa per tahun, mencakup gaji dosen, fasilitas, operasional."],
      ["b.", "Biaya Penelitian", "biaya untuk pelaksanaan penelitian dan pengembangan IPTEK."],
      ["c.", "Biaya PkM", "biaya untuk pelaksanaan pengabdian kepada masyarakat."],
      ["d.", "BOP", "Biaya Operasional Pendidikan, dana yang dialokasikan untuk operasional pendidikan per mahasiswa."],
      ["e.", "RGU", "Revenue Generating Unit, unit yang menghasilkan pendapatan bagi universitas."],
      ["f.", "Audit Internal", "pemeriksaan keuangan oleh Satuan Pengawas Internal (SPI) Universitas Tulungagung."],
      ["g.", "Audit Eksternal", "pemeriksaan keuangan oleh Kantor Akuntan Publik (KAP) independen."],
      ["h.", "Opini Audit", "pendapat auditor atas kewajaran laporan keuangan: WTP, WDP, Disclaimer, atau Buruk."],
      ["i.", "Anggaran Berbasis Kinerja", "sistem anggaran yang mengaitkan dialokasian dana dengan kinerja yang diharapkan."],
    ],
    pernyataan: [
      "Universitas Tulungagung mengalokasikan anggaran untuk Tridharma sesuai standar minimal BOP per mahasiswa per tahun.",
      "Pembiayaan dihitung secara transparan dan akuntabel, dengan dokumentasi yang sistematis dan dapat diaudit.",
      "Sumber pendanaan Universitas Tulungagung bersifat berkelanjutan, mencakup SPP, hibah, kerja sama, dan RGU.",
      "Universitas Tulungagung mengalokasikan dana untuk penelitian minimal 10% dan PkM minimal 5% dari anggaran tahunan.",
      "Universitas Tulungagung menjalankan audit keuangan internal oleh SPI setiap tahun dan audit eksternal oleh KAP setiap tahun.",
      "Laporan keuangan Universitas Tulungagung dipublikasikan kepada pemangku kepentingan melalui situs web resmi.",
      "Universitas Tulungagung mengembangkan sumber pendanaan alternatif (RGU, hibah, kerjasama DUDI) untuk memperkuat kemandirian finansial.",
      "Universitas Tulungagung menerapkan anggaran berbasis kinerja, dengan indikator kinerja yang terukur untuk setiap program.",
      "Universitas Tulungagung menargetkan opini audit Wajar Tanpa Pengecualian (WTP) setiap tahun, sebagai indikator tata kelola yang baik.",
      "Universitas Tulungagung menyediakan beasiswa bagi mahasiswa kurang mampu, minimal 5% dari pendapatan SPP.",
      "Universitas Tulungagung mengelola dana secara efisien, dengan rasio biaya operasional terhadap pendapatan yang sehat.",
      "Universitas Tulungagung menyusun laporan keuangan tahunan yang sesuai standar akuntansi (PSAK / SAK ETAP / ISAK).",
    ],
    strategi: [
      "Menyusun anggaran berbasis kinerja dengan indikator yang terukur, dan monitoring pelaksanaan setiap kuartal.",
      "Mengembangkan RGU untuk meningkatkan pendapatan non-SPP, melalui layanan konsultan, sertifikasi, dan kerja sama DUDI.",
      "Melakukan audit keuangan internal oleh SPI setiap tahun dan audit eksternal oleh KAP, dengan target opini WTP.",
      "Mempublikasikan laporan keuangan tahunan melalui situs web resmi, sebagai bentuk transparansi dan akuntabilitas.",
      "Mengembangkan kerja sama strategis dengan DUDI untuk pendanaan penelitian dan PkM, melalui proposal hibah.",
      "Menyusun laporan keuangan sesuai standar akuntansi (PSAK), dengan dukungan sistem akuntansi berbasis accrual.",
      "Memberikan beasiswa bagi mahasiswa kurang mampu, dengan target ≥5% dari pendapatan SPP.",
      "Mengembangkan sistem informasi manajemen keuangan terintegrasi, dengan dashboard real-time untuk pimpinan.",
    ],
    indikator: [
      { indikator: "BOP per mahasiswa per tahun (Rp juta)", strategi: "Alokasi anggaran", unit: "BAKU", baseline: 8, target: [9.5, 11, 12.5, 14, 16] },
      { indikator: "Persentase pendapatan dari RGU", strategi: "Pengembangan RGU", unit: "BAKU", baseline: 5, target: [9, 14, 19, 25, 30] },
      { indikator: "Persentase anggaran untuk penelitian", strategi: "Realokasi", unit: "BAKU", baseline: 10, target: [12, 14, 16, 18, 20] },
      { indikator: "Persentase anggaran untuk PkM", strategi: "Realokasi", unit: "BAKU", baseline: 5, target: [6, 7, 8, 10, 12] },
      { indikator: "Opini audit eksternal", strategi: "Tata kelola keuangan", unit: "SPI", baseline: "WDP", target: ["WTP", "WTP", "WTP", "WTP", "WTP"] },
      { indikator: "Persentase laporan keuangan dipublikasikan", strategi: "Transparansi", unit: "BAKU", baseline: 80, target: [95, 100, 100, 100, 100] },
      { indikator: "Persentase beasiswa dari pendapatan SPP", strategi: "CSR & anggaran", unit: "BAKU", baseline: 3, target: [4, 5, 6, 7, 8] },
      { indikator: "Rasio biaya operasional terhadap pendapatan", strategi: "Efisiensi", unit: "BAKU", baseline: 85, target: [82, 80, 78, 75, 72] },
      { indikator: "Jumlah kerjasama DUDI untuk pendanaan", strategi: "Networking", unit: "LPPM", baseline: 8, target: [15, 25, 38, 55, 75] },
      { indikator: "Pendapatan hibah eksternal (Rp juta/tahun)", strategi: "Proposal hibah", unit: "LPPM", baseline: 300, target: [500, 800, 1200, 1800, 2500] },
      { indikator: "Persentase sistem akuntansi berbasis accrual", strategi: "Pengembangan", unit: "BAKU", baseline: 70, target: [85, 95, 100, 100, 100] },
      { indikator: "Jumlah RGU yang aktif", strategi: "Pengembangan", unit: "BAKU", baseline: 3, target: [6, 10, 15, 22, 30] },
      { indikator: "Persentase program dengan indikator kinerja terukur", strategi: "Anggaran berbasis kinerja", unit: "BAKU", baseline: 60, target: [75, 88, 95, 100, 100] },
      { indikator: "Tingkat kepuasan pemangku kepentingan terhadap transparansi keuangan", strategi: "Survey", unit: "SPI", baseline: 65, target: [74, 82, 88, 93, 96] },
      { indikator: "Jumlah audit internal SPI per tahun", strategi: "Program audit", unit: "SPI", baseline: 3, target: [6, 10, 14, 18, 22] },
    ],
    dokumenTerkait: DOKUMEN_TERKAIT_DEFAULT,
  },
];

module.exports = {
  STANDAR_PENDIDIKAN,
  PJ_DEFAULT_AKADEMIK,
  PJ_DEFAULT_PENELITIAN,
  PJ_DEFAULT_PKM,
  PJ_DEFAULT_NONAKADEMIK,
  DOKUMEN_TERKAIT_DEFAULT,
};
