// ============================================================
// DATA: 8 STANDAR PENDIDIKAN + 8 STANDAR PENELITIAN
// ============================================================

// Helper: Pihak PJ default (kombinasi yang sering dipakai)
const PJ_DEFAULT_AKADEMIK = [
  { pihak: "Senat Universitas", penetapan: true, pelaksanaan: false, evaluasi: false, pengendalian: false, peningkatan: true },
  { pihak: "Rektor", penetapan: false, pelaksanaan: true, evaluasi: true, pengendalian: true, peningkatan: true },
  { pihak: "Wakil Rektor I (Akademik)", penetapan: false, pelaksanaan: true, evaluasi: true, pengendalian: true, peningkatan: true },
  { pihak: "Dekan", penetapan: false, pelaksanaan: true, evaluasi: true, pengendalian: true, peningkatan: true },
  { pihak: "Ka. Prodi (UPPS)", penetapan: false, pelaksanaan: true, evaluasi: true, pengendalian: true, peningkatan: true },
  { pihak: "Ka. PPM", penetapan: false, pelaksanaan: true, evaluasi: true, pengendalian: true, peningkatan: true },
  { pihak: "Ka. LPM Fakultas", penetapan: false, pelaksanaan: true, evaluasi: true, pengendalian: true, peningkatan: true },
  { pihak: "GKM Prodi", penetapan: false, pelaksanaan: true, evaluasi: true, pengendalian: true, peningkatan: true },
];

const PJ_DEFAULT_PENELITIAN = [
  { pihak: "Senat Universitas", penetapan: true, pelaksanaan: false, evaluasi: false, pengendalian: false, peningkatan: true },
  { pihak: "Rektor", penetapan: false, pelaksanaan: true, evaluasi: true, pengendalian: true, peningkatan: true },
  { pihak: "Wakil Rektor I (Akademik)", penetapan: false, pelaksanaan: true, evaluasi: true, pengendalian: true, peningkatan: true },
  { pihak: "Ka. LPPM", penetapan: false, pelaksanaan: true, evaluasi: true, pengendalian: true, peningkatan: true },
  { pihak: "Ka. PPM", penetapan: false, pelaksanaan: true, evaluasi: true, pengendalian: true, peningkatan: true },
  { pihak: "Dekan", penetapan: false, pelaksanaan: true, evaluasi: true, pengendalian: true, peningkatan: true },
  { pihak: "Ka. Prodi (UPPS)", penetapan: false, pelaksanaan: true, evaluasi: true, pengendalian: true, peningkatan: true },
  { pihak: "GKM Prodi", penetapan: false, pelaksanaan: true, evaluasi: true, pengendalian: true, peningkatan: true },
];

const PJ_DEFAULT_NONAKADEMIK = [
  { pihak: "Senat Universitas", penetapan: true, pelaksanaan: false, evaluasi: false, pengendalian: false, peningkatan: true },
  { pihak: "Rektor", penetapan: false, pelaksanaan: true, evaluasi: true, pengendalian: true, peningkatan: true },
  { pihak: "Wakil Rektor II (Umum & Keuangan)", penetapan: false, pelaksanaan: true, evaluasi: true, pengendalian: true, peningkatan: true },
  { pihak: "Wakil Rektor III (Kemahasiswaan)", penetapan: false, pelaksanaan: true, evaluasi: true, pengendalian: true, peningkatan: true },
  { pihak: "Ka. PPM", penetapan: false, pelaksanaan: true, evaluasi: true, pengendalian: true, peningkatan: true },
  { pihak: "Ka. BAKU", penetapan: false, pelaksanaan: true, evaluasi: true, pengendalian: true, peningkatan: true },
  { pihak: "Ka. BAA", penetapan: false, pelaksanaan: true, evaluasi: true, pengendalian: true, peningkatan: true },
  { pihak: "Dekan", penetapan: false, pelaksanaan: true, evaluasi: true, pengendalian: true, peningkatan: true },
];

const DOKUMEN_TERKAIT_DEFAULT = [
  "Dokumen Kebijakan Mutu SPMI UNITA 2025",
  "Dokumen Manual Mutu SPMI UNITA 2025",
  "Statuta Universitas Tulungagung",
  "Rencana Strategis (Renstra) Universitas Tulungagung",
  "Laporan Audit Mutu Internal (AMI)",
  "Berita Acara Rapat Tinjauan Manajemen (RTM)",
];

// ============================================================
// 8 STANDAR PENDIDIKAN
// ============================================================
const STANDAR_PENDIDIKAN = [
  {
    namaStandar: "STANDAR KOMPETENSI LULUSAN",
    kodeStandar: "SKL",
    rasional: [
      "Standar Kompetensi Lulusan merupakan standar luaran pendidikan yang menjadi acuan utama bagi setiap program studi dalam menyelenggarakan pendidikan tinggi. Sesuai dengan Peraturan Menteri Pendidikan Tinggi, Sains, dan Teknologi Nomor 39 Tahun 2025, standar kompetensi lulusan merupakan kriteria minimal mengenai kesatuan kompetensi sikap, keterampilan, dan pengetahuan yang menunjukkan capaian mahasiswa dari hasil pembelajarannya pada akhir program pendidikan tinggi. Standar ini menjadi tolok ukur utama bagi evaluasi kualitas lulusan dan menjadi dasar bagi penyusunan kurikulum, proses pembelajaran, dan penilaian.",
      "Universitas Tulungagung memandang Standar Kompetensi Lulusan sebagai standar strategis yang menentukan daya saing lulusan di pasar kerja nasional dan internasional. Dalam konteks akreditasi sebagaimana diatur dalam Pasal 75 ayat (2) Permen 39 Tahun 2025, instrumen Akreditasi disusun berdasarkan kriteria pada standar luaran, standar proses, dan standar masukan dengan mengutamakan kriteria pada standar luaran. Oleh karena itu, pemenuhan Standar Kompetensi Lulusan menjadi prioritas tertinggi bagi setiap program studi di Universitas Tulungagung.",
    ],
    pihakPJ: PJ_DEFAULT_AKADEMIK,
    definisi: [
      ["a.", "Kompetensi", "kesatuan sikap, keterampilan, dan pengetahuan yang dimiliki oleh lulusan."],
      ["b.", "Capaian Pembelajaran Lulusan (CPL)", "rumusan kompetensi lulusan yang dirumuskan dari standar kompetensi lulusan untuk setiap program studi."],
      ["c.", "Capaian Pembelajaran Mata Kuliah (CPMK)", "rumusan kompetensi mata kuliah yang berkontribusi pada pencapaian CPL."],
      ["d.", "Kurikulum", "seperangkat rencana dan pengaturan mengenai capaian pembelajaran lulusan, mata kuliah, beban belajar, dan strategi pembelajaran."],
      ["e.", "Asosiasi Program Studi", "lembaga yang merumuskan kompetensi utama lulusan program studi sejenis bersama pihak lain yang terkait."],
    ],
    pernyataan: [
      "Setiap program studi di Universitas Tulungagung wajib menyusun Capaian Pembelajaran Lulusan (CPL) yang mencakup kompetensi sikap, keterampilan, dan pengetahuan, sesuai dengan jenjang program dan ranah keilmuan.",
      "CPL disusun oleh Unit Pengelola Program Studi (UPPS) dengan melibatkan pemangku kepentingan dan/atau dunia usaha, dunia industri, dan dunia kerja (DUDI).",
      "CPL memperhatikan visi dan misi perguruan tinggi, KKNI, perkembangan IPTEK, kebutuhan kompetensi kerja, ranah keilmuan program studi, kompetensi utama lulusan program studi, dan kurikulum program studi sejenis.",
      "CPL diinformasikan kepada mahasiswa pada program studi tersebut, dan disusun ke dalam mata kuliah pada setiap program studi.",
      "Setiap mata kuliah memiliki Capaian Pembelajaran Mata Kuliah (CPMK) yang berkontribusi pada pencapaian CPL.",
      "Kompetensi utama lulusan program studi memenuhi ketentuan minimal sesuai jenjang (D1, D2, D3, S1, S1 Terapan, Profesi, S2, S2 Terapan, Spesialis, S3, S3 Terapan, Subspesialis).",
      "CPL mengacu pada kompetensi utama lulusan yang disusun oleh asosiasi program studi sejenis, apabila asosiasi telah terbentuk. Apabila belum terbentuk, CPL disusun oleh Universitas Tulungagung.",
    ],
    strategi: [
      "Melakukan kaji ulang CPL setiap program studi setiap dua tahun atau sesuai perubahan regulasi, dengan melibatkan DUDI dan asosiasi program studi.",
      "Menyelenggarakan rapat kurikulum tahunan di tingkat program studi untuk memastikan keselarasan CPL dengan CPMK dan materi mata kuliah.",
      "Melakukan tracer study secara berkala untuk memperoleh umpan balik dari pengguna lulusan dan menyelaraskan CPL dengan kebutuhan dunia kerja.",
      "Mengintegrasikan CPL dalam Sistem Informasi Akademik (SIAKAD) sehingga dapat diakses oleh mahasiswa, dosen, dan pemangku kepentingan.",
      "Menyelenggarakan workshop penyusunan CPL bagi pengelola program studi dan dosen, dengan narasumber dari asosiasi program studi atau ahli kurikulum.",
    ],
    indikator: [
      { indikator: "Persentase program studi yang telah menyusun CPL sesuai Permen 39/2025", strategi: "Sosialisasi & pendampingan", unit: "UPPS", baseline: 100, target: [100, 100, 100, 100, 100] },
      { indikator: "Persentase CPL yang diinformasikan kepada mahasiswa", strategi: "Integrasi SIAKAD", unit: "UPPS", baseline: 95, target: [100, 100, 100, 100, 100] },
      { indikator: "Jumlah program studi yang mengikuti CPL asosiasi", strategi: "Koordinasi asosiasi", unit: "UPPS", baseline: 15, target: [20, 25, 30, 35, 40] },
      { indikator: "Persentase mata kuliah dengan CPMK yang terdokumentasi", strategi: "Audit RPS", unit: "GKM", baseline: 90, target: [95, 100, 100, 100, 100] },
      { indikator: "Tingkat kepuasan pengguna lulusan terhadap kompetensi", strategi: "Tracer study", unit: "PPM", baseline: 75, target: [78, 80, 82, 85, 88] },
    ],
    dokumenTerkait: DOKUMEN_TERKAIT_DEFAULT,
  },
  {
    namaStandar: "STANDAR PROSES PEMBELAJARAN",
    kodeStandar: "SPB",
    rasional: [
      "Standar Proses Pembelajaran merupakan bagian dari standar proses pendidikan yang mengatur kriteria minimal proses pembelajaran untuk mencapai standar kompetensi lulusan. Sesuai Permen 39 Tahun 2025, standar proses pembelajaran meliputi perencanaan, pelaksanaan, dan penilaian proses pembelajaran. Standar ini menjadi acuan operasional bagi dosen dalam menyelenggarakan kegiatan pembelajaran yang efektif, interaktif, dan bermutu.",
      "Universitas Tulungagung memandang proses pembelajaran sebagai jantung dari penyelenggaraan pendidikan tinggi. Kualitas proses pembelajaran menentukan kualitas lulusan, sehingga standar ini dikelola dengan sangat hati-hati melalui siklus PPEPP yang konsisten. Universitas Tulungagung juga mendorong inovasi pembelajaran—seperti project-based learning, case-based learning, blended learning, dan pemanfaatan teknologi—untuk meningkatkan kualitas pengalaman belajar mahasiswa.",
    ],
    pihakPJ: PJ_DEFAULT_AKADEMIK,
    definisi: [
      ["a.", "Proses Pembelajaran", "proses interaksi mahasiswa dengan dosen dan sumber belajar pada suatu lingkungan belajar."],
      ["b.", "Rencana Pembelajaran Semester (RPS)", "dokumen perencanaan pembelajaran untuk satu semester yang memuat capaian, materi, metode, dan penilaian."],
      ["c.", "Bentuk Pembelajaran", "metode pelaksanaan pembelajaran meliputi kuliah, praktikum, kerja lapangan, daring, dan/atau blended learning."],
      ["d.", "Beban Belajar", "jumlah waktu yang dibutuhkan mahasiswa untuk menyelesaikan suatu mata kuliah, dinyatakan dalam Satuan Kredit Semester (SKS)."],
    ],
    pernyataan: [
      "Perencanaan proses pembelajaran meliputi perumusan capaian pembelajaran mata kuliah, materi, metode, sumber belajar, dan kriteria penilaian.",
      "Pelaksanaan proses pembelajaran dilakukan melalui berbagai bentuk interaksi akademik—kuliah, praktikum, kerja lapangan, daring, dan/atau blended learning—sesuai karakteristik program studi.",
      "Setiap dosen wajib menyusun Rencana Pembelajaran Semester (RPS) untuk setiap mata kuliah yang diampu, dengan mengacu pada CPMK.",
      "Beban belajar mahasiswa dihitung berdasarkan waktu yang dibutuhkan untuk aktivitas pembelajaran terstruktur dan mandiri.",
      "Proses pembelajaran dilaksanakan secara interaktif, kolaboratif, dan mendorong kemandirian mahasiswa dalam belajar.",
      "Universitas Tulungagung mendorong inovasi pembelajaran melalui pemanfaatan teknologi informasi dan pendekatan student-centered learning.",
    ],
    strategi: [
      "Menyelenggarakan pelatihan penyusunan RPS bagi dosen setiap awal semester.",
      "Mengembangkan sistem informasi akademik yang mendukung pengelolaan RPS secara digital.",
      "Mendorong dosen untuk mengadopsi metode pembelajaran inovatif melalui workshop dan sharing session.",
      "Melakukan peer teaching observation untuk monitoring kualitas pembelajaran.",
      "Menyediakan fasilitas pembelajaran yang memadai—ruang kelas, laboratorium, akses internet, dan platform LMS.",
    ],
    indikator: [
      { indikator: "Persentase dosen yang menyusun RPS", strategi: "Pelatihan & monitoring", unit: "GKM", baseline: 95, target: [100, 100, 100, 100, 100] },
      { indikator: "Persentase RPS yang sesuai CPMK", strategi: "Audit RPS", unit: "GKM", baseline: 85, target: [90, 95, 100, 100, 100] },
      { indikator: "Persentase mata kuliah dengan metode inovatif", strategi: "Workshop & reward", unit: "UPPS", baseline: 40, target: [50, 60, 70, 80, 90] },
      { indikator: "Tingkat kepuasan mahasiswa terhadap proses pembelajaran", strategi: "Survey emonev", unit: "PPM", baseline: 75, target: [78, 80, 83, 85, 88] },
      { indikator: "Jumlah mata kuliah yang menggunakan LMS", strategi: "Integrasi IT", unit: "UPT SI", baseline: 60, target: [70, 80, 90, 100, 100] },
    ],
    dokumenTerkait: DOKUMEN_TERKAIT_DEFAULT,
  },
  {
    namaStandar: "STANDAR PENILAIAN",
    kodeStandar: "SPN",
    rasional: [
      "Standar Penilaian merupakan bagian dari standar proses pendidikan yang mengatur kriteria minimal penilaian proses pembelajaran oleh dosen dan penilaian capaian pembelajaran. Penilaian dilakukan secara objektif, transparan, akuntabel, dan berkeadilan, menggunakan berbagai metode yang sesuai dengan karakteristik mata kuliah dan capaian pembelajaran. Hasil penilaian digunakan untuk perbaikan proses pembelajaran dan menjadi bahan evaluasi kinerja dosen serta kualitas kurikulum.",
      "Universitas Tulungagung memandang penilaian sebagai instrumen strategis untuk memastikan ketercapaian CPL dan kualitas lulusan. Penilaian yang baik bukan sekadar pemberian angka, melainkan proses sistematis untuk mengukur, menganalisis, dan memperbaiki pembelajaran. Universitas Tulungagung mendorong pendekatan penilaian autentik (authentic assessment) yang mengukur kompetensi nyata mahasiswa, bukan sekadar hafalan.",
    ],
    pihakPJ: PJ_DEFAULT_AKADEMIK,
    definisi: [
      ["a.", "Penilaian", "proses pengumpulan dan pengolahan informasi untuk mengukur ketercapaian capaian pembelajaran."],
      ["b.", "Penilaian Formatif", "penilaian yang dilakukan selama proses pembelajaran untuk monitoring dan perbaikan."],
      ["c.", "Penilaian Sumatif", "penilaian yang dilakukan pada akhir periode pembelajaran untuk menentukan kelulusan."],
      ["d.", "Penilaian Autentik", "penilaian yang mengukur kompetensi nyata mahasiswa melalui tugas atau proyek kontekstual."],
    ],
    pernyataan: [
      "Penilaian proses pembelajaran oleh dosen dilakukan secara objektif, transparan, akuntabel, dan berkeadilan.",
      "Penilaian menggunakan berbagai metode yang sesuai dengan karakteristik mata kuliah dan capaian pembelajaran, meliputi penilaian formatif dan sumatif.",
      "Kriteria dan rubrik penilaian disampaikan kepada mahasiswa pada awal semester melalui RPS.",
      "Hasil penilaian didokumentasikan secara sistematis dan dapat diakses oleh mahasiswa melalui SIAKAD.",
      "Universitas Tulungagung mendorong penerapan penilaian autentik yang mengukur kompetensi nyata mahasiswa.",
      "Hasil penilaian dianalisis untuk perbaikan proses pembelajaran dan evaluasi kualitas kurikulum.",
    ],
    strategi: [
      "Menyelenggarakan pelatihan penilaian autentik bagi dosen setiap tahun.",
      "Menyediakan template rubrik penilaian yang dapat diadaptasi dosen untuk berbagai jenis tugas.",
      "Mengintegrasikan sistem penilaian dengan SIAKAD untuk transparansi dan dokumentasi.",
      "Melakukan audit penilaian oleh GKM untuk memastikan objektivitas dan konsistensi.",
      "Menggunakan hasil penilaian sebagai bahan analisis kelulusan dan capaian CPL dalam RTM tahunan.",
    ],
    indikator: [
      { indikator: "Persentase mata kuliah dengan rubrik penilaian", strategi: "Audit rubrik", unit: "GKM", baseline: 70, target: [80, 90, 100, 100, 100] },
      { indikator: "Persentase dosen yang menerapkan penilaian autentik", strategi: "Pelatihan", unit: "UPPS", baseline: 35, target: [45, 55, 65, 75, 85] },
      { indikator: "Tingkat kepuasan mahasiswa terhadap transparansi penilaian", strategi: "Survey emonev", unit: "PPM", baseline: 70, target: [75, 80, 83, 85, 88] },
      { indikator: "Persentase nilai yang diinput tepat waktu di SIAKAD", strategi: "Monitoring", unit: "BAA", baseline: 85, target: [90, 95, 100, 100, 100] },
      { indikator: "Jumlah analisis capaian CPL berbasis hasil penilaian", strategi: "Workshop", unit: "GKM", baseline: 10, target: [15, 20, 25, 30, 35] },
    ],
    dokumenTerkait: DOKUMEN_TERKAIT_DEFAULT,
  },
  {
    namaStandar: "STANDAR PENGELOLAAN",
    kodeStandar: "SPP",
    rasional: [
      "Standar Pengelolaan merupakan bagian dari standar proses pendidikan yang mengatur kriteria minimal pengelolaan program studi oleh Unit Pengelola Program Studi (UPPS). Standar ini mencakup perencanaan, pelaksanaan, monitoring, evaluasi, dan perbaikan. UPPS bertanggung jawab atas penyelenggaraan program studi secara menyeluruh, termasuk pengelolaan kurikulum, dosen, mahasiswa, sarana prasarana, dan kerja sama. Standar ini memastikan bahwa setiap program studi dikelola secara profesional dan akuntabel.",
      "Universitas Tulungagung memandang pengelolaan program studi sebagai proses manajemen yang memerlukan kapasitas struktural, sistem informasi, dan mekanisme evaluasi yang kuat. Pengelolaan yang baik menjadi prasyarat bagi tercapainya kualitas Tridharma, sehingga standar ini menjadi fondasi bagi standar-standar lainnya. Universitas Tulungagung berkomitmen untuk memperkuat kapasitas UPPS melalui pelatihan, pendampingan, dan pemanfaatan teknologi informasi.",
    ],
    pihakPJ: PJ_DEFAULT_AKADEMIK,
    definisi: [
      ["a.", "Pengelolaan", "serangkaian kegiatan perencanaan, pelaksanaan, monitoring, evaluasi, dan perbaikan program studi."],
      ["b.", "UPPS", "Unit Pengelola Program Studi yang bertanggung jawab atas penyelenggaraan program studi."],
      ["c.", "SOTK", "Struktur Organisasi dan Tata Kerja yang mengatur pembagian tugas dan wewenang."],
      ["d.", "Sistem Informasi", "platform digital untuk pengelolaan data dan informasi program studi."],
    ],
    pernyataan: [
      "UPPS memiliki struktur organisasi dan tata kerja yang jelas, dengan pembagian tugas dan wewenang yang terdokumentasi.",
      "UPPS menyusun rencana operasional tahunan yang diturunkan dari Renstra universitas dan fakultas.",
      "UPPS melakukan monitoring dan evaluasi berkala terhadap pelaksanaan program studi.",
      "UPPS memiliki sistem informasi yang terintegrasi untuk pengelolaan data mahasiswa, dosen, kurikulum, dan lulusan.",
      "UPPS berkoordinasi dengan GKM, LPM, dan PPM dalam pelaksanaan SPMI di tingkat program studi.",
      "UPPS menyusun laporan kinerja tahunan yang disampaikan kepada Dekan dan Rektor.",
    ],
    strategi: [
      "Memperkuat kapasitas UPPS melalui pelatihan manajemen pendidikan tinggi.",
      "Mengembangkan sistem informasi terintegrasi untuk pengelolaan program studi.",
      "Melakukan monitoring dan evaluasi berkala oleh Dekan terhadap kinerja UPPS.",
      "Menyelenggarakan rapat koordinasi rutin antara UPPS, GKM, LPM, dan PPM.",
      "Mengembangkan dashboard kinerja program studi yang dapat diakses real-time.",
    ],
    indikator: [
      { indikator: "Persentase prodi dengan SOTK terdokumentasi", strategi: "Audit SOTK", unit: "UPPS", baseline: 90, target: [95, 100, 100, 100, 100] },
      { indikator: "Persentase prodi dengan rencana operasional tahunan", strategi: "Monitoring", unit: "UPPS", baseline: 85, target: [95, 100, 100, 100, 100] },
      { indikator: "Persentase prodi dengan laporan kinerja tahunan", strategi: "Audit", unit: "UPPS", baseline: 80, target: [90, 100, 100, 100, 100] },
      { indikator: "Tingkat kepuasan mahasiswa terhadap layanan prodi", strategi: "Survey", unit: "PPM", baseline: 75, target: [78, 80, 83, 85, 88] },
      { indikator: "Jumlah prodi dengan dashboard kinerja digital", strategi: "Pengembangan IT", unit: "UPT SI", baseline: 5, target: [10, 20, 35, 50, 70] },
    ],
    dokumenTerkait: DOKUMEN_TERKAIT_DEFAULT,
  },
  {
    namaStandar: "STANDAR ISI",
    kodeStandar: "SIS",
    rasional: [
      "Standar Isi merupakan bagian dari standar masukan pendidikan yang mengatur kriteria minimal substansi kurikulum dan bahan ajar. Standar ini mencakup struktur kurikulum, mata kuliah, beban belajar, dan capaian pembelajaran mata kuliah. Standar Isi juga mengatur tentang Merdeka Belajar Kampus Merdeka (MBKM) yang memungkinkan mahasiswa mengambil kegiatan di luar program studi. Standar ini menjadi acuan bagi setiap program studi dalam menyusun dan mengevaluasi kurikulum.",
      "Universitas Tulungagung memandang kurikulum sebagai jantung dari penyelenggaraan pendidikan tinggi. Kurikulum yang baik harus selaras dengan kebutuhan DUDI, perkembangan IPTEK, dan visi-misi perguruan tinggi. Universitas Tulungagung mendorong setiap program studi untuk melakukan review kurikulum secara berkala, dengan melibatkan DUDI, asosiasi program studi, dan alumni.",
    ],
    pihakPJ: PJ_DEFAULT_AKADEMIK,
    definisi: [
      ["a.", "Kurikulum", "seperangkat rencana dan pengaturan mengenai capaian pembelajaran lulusan, mata kuliah, beban belajar, dan strategi pembelajaran."],
      ["b.", "Mata Kuliah", "satuan pendidikan yang memiliki CPL, CPMK, materi, dan beban belajar tertentu."],
      ["c.", "Beban Belajar", "jumlah waktu yang dibutuhkan mahasiswa untuk menyelesaikan suatu mata kuliah, dinyatakan dalam SKS."],
      ["d.", "MBKM", "Merdeka Belajar Kampus Merdeka, kebijakan yang memberikan ruang bagi mahasiswa untuk mengambil kegiatan di luar program studi."],
    ],
    pernyataan: [
      "Setiap program studi memiliki kurikulum yang disusun berdasarkan CPL dan memenuhi struktur kurikulum sesuai jenjang.",
      "Kurikulum memuat mata kuliah wajib, pilihan, dan MBKM dengan proporsi yang sesuai dengan karakteristik program studi.",
      "Kurikulum mengintegrasikan CPNK (Capaian Pembelajaran Nasional Khusus) untuk program studi profesi.",
      "Setiap mata kuliah memiliki bobot SKS yang sesuai dengan beban belajar, dengan 1 SKS setara dengan 170 menit aktivitas per minggu.",
      "Universitas Tulungagung memberikan ruang bagi mahasiswa untuk mengambil kegiatan MBKM selama 1-2 semester dengan pengakuan SKS.",
      "Kurikulum dievaluasi secara berkala minimal setiap dua tahun, dengan melibatkan DUDI, asosiasi program studi, dan alumni.",
    ],
    strategi: [
      "Melakukan review kurikulum setiap dua tahun dengan pendekatan konstruktif alignment.",
      "Mengembangkan model MBKM yang sesuai dengan karakteristik setiap program studi.",
      "Menyelenggarakan rapat kurikulum tahunan di tingkat program studi dan fakultas.",
      "Melibatkan DUDI dan asosiasi program studi dalam penyusunan dan evaluasi kurikulum.",
      "Mengintegrasikan kurikulum dengan SIAKAD untuk monitoring pelaksanaan.",
    ],
    indikator: [
      { indikator: "Persentase prodi yang melakukan review kurikulum 2 tahunan", strategi: "Monitoring", unit: "UPPS", baseline: 70, target: [85, 100, 100, 100, 100] },
      { indikator: "Jumlah prodi yang mengimplementasikan MBKM", strategi: "Sosialisasi", unit: "UPPS", baseline: 25, target: [35, 50, 65, 80, 100] },
      { indikator: "Jumlah mahasiswa yang mengikuti MBKM per tahun", strategi: "Kerjasama DUDI", unit: "UPPS", baseline: 200, target: [300, 450, 600, 800, 1000] },
      { indikator: "Persentase mata kuliah dengan CPL-CPMK terdokumentasi", strategi: "Audit", unit: "GKM", baseline: 85, target: [90, 95, 100, 100, 100] },
      { indikator: "Jumlah kerjasama DUDI untuk MBKM", strategi: "Pengembangan", unit: "UPPS", baseline: 30, target: [45, 60, 80, 100, 120] },
    ],
    dokumenTerkait: DOKUMEN_TERKAIT_DEFAULT,
  },
  {
    namaStandar: "STANDAR DOSEN DAN TENAGA KEPENDIDIKAN",
    kodeStandar: "SDT",
    rasional: [
      "Standar Dosen dan Tenaga Kependidikan merupakan bagian dari standar masukan pendidikan yang mengatur kriteria minimal kualifikasi, kompetensi, dan beban kerja dosen serta tenaga kependidikan. Dosen wajib memiliki kualifikasi minimal magister untuk program sarjana dan doktor untuk program magister/doktor, serta memiliki sertifikat pendidik. Tenaga kependidikan wajib memiliki kualifikasi dan kompetensi yang sesuai dengan tugasnya.",
      "Universitas Tulungagung memandang dosen dan tenaga kependidikan sebagai aset strategis yang menentukan kualitas Tridharma. Universitas Tulungagung berkomitmen untuk meningkatkan kualifikasi dan kompetensi dosen melalui studi lanjut, pelatihan, dan sertifikasi. Selain itu, Universitas Tulungagung juga memastikan rasio dosen-mahasiswa memenuhi standar dan beban kerja dosen seimbang antara pendidikan, penelitian, dan PkM.",
    ],
    pihakPJ: PJ_DEFAULT_NONAKADEMIK,
    definisi: [
      ["a.", "Dosen", "pendidik profesional dan ilmuwan dengan tugas utama mentransformasi, mengembangkan, dan menyebarluaskan IPTEK melalui pendidikan, penelitian, dan PkM."],
      ["b.", "Tenaga Kependidikan", "anggota sivitas akademika yang bertugas mengelola, menyelenggarakan, dan/atau melayani urusan administrasi pendidikan."],
      ["c.", "Sertifikat Pendidik", "pengakuan formal terhadap kompetensi dosen sebagai pendidik."],
      ["d.", "Beban Kerja Dosen", "jumlah kegiatan dosen dalam pendidikan, penelitian, dan PkM, dinyatakan dalam ekuivalen SKS."],
    ],
    pernyataan: [
      "Dosen wajib memiliki kualifikasi minimal magister untuk program sarjana dan doktor untuk program magister/doktor.",
      "Dosen wajib memiliki sertifikat pendidik profesional (Serdos).",
      "Rasio dosen-mahasiswa memenuhi standar minimal sesuai jenjang program.",
      "Beban kerja dosen seimbang antara pendidikan, penelitian, dan PkM, dengan total minimal 12 SKS dan maksimal 16 SKS per semester.",
      "Tenaga kependidikan memiliki kualifikasi dan kompetensi yang sesuai dengan tugasnya.",
      "Universitas Tulungagung menyediakan program pengembangan kapasitas dosen dan tenaga kependidikan secara berkelanjutan.",
    ],
    strategi: [
      "Memberikan dukungan studi lanjut bagi dosen untuk mencapai kualifikasi minimal yang dipersyaratkan.",
      "Menyelenggarakan pelatihan Serdos dan sertifikasi profesi bagi dosen.",
      "Melakukan audit beban kerja dosen setiap semester untuk memastikan keseimbangan.",
      "Menyelenggarakan pelatihan kompetensi bagi tenaga kependidikan sesuai bidang tugas.",
      "Mengembangkan sistem informasi SDM untuk monitoring kualifikasi dan beban kerja.",
    ],
    indikator: [
      { indikator: "Persentase dosen S1 yang sedang studi lanjut S2/S3", strategi: "Dukungan studi", unit: "BAKU", baseline: 15, target: [20, 25, 30, 35, 40] },
      { indikator: "Persentase dosen dengan Serdos", strategi: "Pelatihan Serdos", unit: "BAKU", baseline: 40, target: [50, 60, 70, 80, 90] },
      { indikator: "Rasio dosen-mahasiswa rata-rata", strategi: "Rekrutmen", unit: "BAKU", baseline: "1:35", target: ["1:32", "1:30", "1:28", "1:25", "1:22"] },
      { indikator: "Persentase dosen dengan beban kerja seimbang", strategi: "Audit beban", unit: "GKM", baseline: 70, target: [80, 88, 95, 100, 100] },
      { indikator: "Jumlah pelatihan tenaga kependidikan per tahun", strategi: "Program diklat", unit: "BAKU", baseline: 10, target: [15, 20, 25, 30, 35] },
    ],
    dokumenTerkait: DOKUMEN_TERKAIT_DEFAULT,
  },
  {
    namaStandar: "STANDAR SARANA DAN PRASARANA",
    kodeStandar: "SSP",
    rasional: [
      "Standar Sarana dan Prasarana merupakan bagian dari standar masukan pendidikan yang mengatur kriteria minimal sarana fisik dan prasarana pendukung penyelenggaraan pendidikan. Standar ini mencakup ruang perkuliahan, laboratorium, perpustakaan, fasilitas ibadah, fasilitas olahraga, dan fasilitas penunjang lainnya. Universitas Tulungagung memastikan bahwa setiap program studi memiliki sarana dan prasarana yang memadai, sesuai dengan karakteristik keilmuan dan jumlah mahasiswa, serta terpelihara dengan baik melalui sistem manajemen fasilitas yang terdokumentasi.",
      "Sarana dan prasarana yang memadai menjadi prasyarat bagi penyelenggaraan Tridharma yang bermutu. Universitas Tulungagung berkomitmen untuk berinvestasi dalam pengembangan sarana dan prasarana secara berkala, dengan prioritas pada laboratorium, perpustakaan digital, dan fasilitas pembelajaran berbasis teknologi. Selain itu, Universitas Tulungagung juga memastikan aksesibilitas sarana bagi seluruh sivitas akademika, termasuk penyandang disabilitas.",
    ],
    pihakPJ: PJ_DEFAULT_NONAKADEMIK,
    definisi: [
      ["a.", "Sarana", "peralatan dan bahan yang diperlukan untuk penyelenggaraan pendidikan."],
      ["b.", "Prasarana", "fasilitas fisik seperti gedung, ruang, lapangan, dan jaringan utilitas."],
      ["c.", "Laboratorium", "fasilitas untuk kegiatan praktikum dan eksperimen."],
      ["d.", "Perpustakaan", "fasilitas untuk menyediakan sumber belajar dan referensi akademik."],
    ],
    pernyataan: [
      "Setiap program studi memiliki ruang perkuliahan yang memadai sesuai jumlah mahasiswa.",
      "Setiap program studi memiliki laboratorium yang sesuai dengan karakteristik keilmuan.",
      "Universitas Tulungagung menyediakan perpustakaan dengan koleksi cetak dan digital yang relevan.",
      "Fasilitas ibadah, fasilitas olahraga, dan fasilitas penunjang tersedia bagi seluruh sivitas akademika.",
      "Sarana dan prasarana terpelihara dengan baik melalui sistem manajemen fasilitas yang terdokumentasi.",
      "Sarana dan prasarana dapat diakses oleh seluruh sivitas akademika, termasuk penyandang disabilitas.",
    ],
    strategi: [
      "Menyusun rencana investasi sarana dan prasarana jangka menengah 5 tahunan.",
      "Melakukan audit fasilitas secara berkala untuk memastikan kelayakan.",
      "Mengembangkan perpustakaan digital dengan akses jurnal dan e-book internasional.",
      "Memperluas laboratorium dengan peralatan terkini sesuai kebutuhan program studi.",
      "Mengimplementasikan sistem manajemen fasilitas berbasis IT untuk monitoring dan maintenance.",
    ],
    indikator: [
      { indikator: "Rasio ruang kelas terhadap mahasiswa (m² per mahasiswa)", strategi: "Investasi", unit: "BAU", baseline: 1.5, target: [1.7, 1.9, 2.1, 2.3, 2.5] },
      { indikator: "Persentase laboratorium dengan peralatan standar", strategi: "Audit", unit: "UPPS", baseline: 75, target: [82, 88, 93, 97, 100] },
      { indikator: "Jumlah koleksi perpustakaan (cetak + digital)", strategi: "Pengembangan", unit: "UPT Perpus", baseline: 15000, target: [18000, 22000, 27000, 32000, 40000] },
      { indikator: "Persentase gedung dengan akses disabilitas", strategi: "Renovasi", unit: "BAU", baseline: 40, target: [50, 60, 70, 80, 90] },
      { indikator: "Persentase fasilitas terpelihara sesuai standar", strategi: "Sistem manajemen", unit: "BAU", baseline: 80, target: [85, 90, 95, 98, 100] },
    ],
    dokumenTerkait: DOKUMEN_TERKAIT_DEFAULT,
  },
  {
    namaStandar: "STANDAR PEMBIAYAAN",
    kodeStandar: "SPM",
    rasional: [
      "Standar Pembiayaan merupakan bagian dari standar masukan pendidikan yang mengatur kriteria minimal biaya operasional penyelenggaraan pendidikan per mahasiswa. Pembiayaan mencakup biaya pendidikan, biaya penelitian, dan biaya pengabdian kepada masyarakat. Pembiayaan harus dihitung secara transparan dan akuntabel, dengan sumber pendanaan yang berkelanjutan. Universitas Tulungagung memastikan bahwa alokasi anggaran untuk Tridharma mencukupi kebutuhan operasional dan investasi peningkatan mutu, serta dipublikasikan secara terbuka kepada pemangku kepentingan.",
      "Pembiayaan yang memadai menjadi prasyarat bagi penyelenggaraan Tridharma yang bermutu. Universitas Tulungagung mengelola keuangan secara transparan dan akuntabel, dengan mekanisme audit internal dan eksternal yang rutin. Universitas Tulungagung juga mengembangkan sumber pendanaan alternatif—seperti kerja sama DUDI, hibah penelitian, dan program Revenue Generating Unit (RGU)—untuk memperkuat kemandirian finansial.",
    ],
    pihakPJ: PJ_DEFAULT_NONAKADEMIK,
    definisi: [
      ["a.", "Biaya Pendidikan", "biaya operasional untuk penyelenggaraan pendidikan per mahasiswa per tahun."],
      ["b.", "Biaya Penelitian", "biaya untuk pelaksanaan penelitian dan pengembangan IPTEK."],
      ["c.", "Biaya PkM", "biaya untuk pelaksanaan pengabdian kepada masyarakat."],
      ["d.", "BOP", "Biaya Operasional Pendidikan, dana yang dialokasikan untuk operasional pendidikan."],
      ["e.", "RGU", "Revenue Generating Unit, unit yang menghasilkan pendapatan bagi universitas."],
    ],
    pernyataan: [
      "Universitas Tulungagung mengalokasikan anggaran untuk Tridharma sesuai standar minimal BOP per mahasiswa.",
      "Pembiayaan dihitung secara transparan dan akuntabel, dengan dokumentasi yang sistematis.",
      "Sumber pendanaan Universitas Tulungagung bersifat berkelanjutan, mencakup SPP, hibah, kerja sama, dan RGU.",
      "Universitas Tulungagung menjalankan audit keuangan internal dan eksternal secara rutin.",
      "Laporan keuangan Universitas Tulungagung dipublikasikan kepada pemangku kepentingan.",
      "Universitas Tulungagung mengembangkan sumber pendanaan alternatif untuk memperkuat kemandirian finansial.",
    ],
    strategi: [
      "Menyusun anggaran berbasis kinerja dengan indikator yang terukur.",
      "Mengembangkan RGU untuk meningkatkan pendapatan non-SPP.",
      "Melakukan audit keuangan internal oleh SPI setiap tahun dan audit eksternal oleh KAP.",
      "Mempublikasikan laporan keuangan tahunan melalui situs web resmi.",
      "Mengembangkan kerja sama strategis dengan DUDI untuk pendanaan penelitian dan PkM.",
    ],
    indikator: [
      { indikator: "BOP per mahasiswa per tahun (Rp juta)", strategi: "Alokasi anggaran", unit: "BAKU", baseline: 8, target: [9, 10, 11, 12, 14] },
      { indikator: "Persentase pendapatan dari RGU", strategi: "Pengembangan RGU", unit: "BAKU", baseline: 5, target: [8, 12, 16, 20, 25] },
      { indikator: "Persentase anggaran untuk penelitian", strategi: "Realokasi", unit: "BAKU", baseline: 10, target: [12, 14, 16, 18, 20] },
      { indikator: "Persentase anggaran untuk PkM", strategi: "Realokasi", unit: "BAKU", baseline: 5, target: [6, 7, 8, 10, 12] },
      { indikator: "Opini audit eksternal", strategi: "Tata kelola keuangan", unit: "SPI", baseline: "WDP", target: ["WDP", "WTP", "WTP", "WTP", "WTP"] },
    ],
    dokumenTerkait: DOKUMEN_TERKAIT_DEFAULT,
  },
];

// ============================================================
// 8 STANDAR PENELITIAN
// ============================================================
const STANDAR_PENELITIAN = [
  {
    namaStandar: "STANDAR LUARAN PENELITIAN",
    kodeStandar: "PEN-LRN",
    rasional: [
      "Standar Luaran Penelitian mengatur kriteria minimal hasil penelitian yang dihasilkan oleh perguruan tinggi. Luaran penelitian mencakup publikasi ilmiah, buku, paten, karya inovatif, dan teknologi tepat guna. Standar ini menjadi tolok ukur kualitas dan produktivitas penelitian Universitas Tulungagung, serta menjadi indikator utama bagi evaluasi eksternal dalam akreditasi.",
      "Universitas Tulungagung menargetkan peningkatan kuantitas dan kualitas luaran penelitian, khususnya publikasi pada jurnal terakreditasi nasional dan internasional bereputasi. Hal ini sejalan dengan sasaran strategis ke-4 Universitas Tulungagung, yaitu tercapainya kualitas dan kuantitas kegiatan penelitian berupa publikasi hasil penelitian pada jurnal terakreditasi nasional dan internasional.",
    ],
    pihakPJ: PJ_DEFAULT_PENELITIAN,
    definisi: [
      ["a.", "Luaran Penelitian", "hasil penelitian yang dapat berupa publikasi, paten, karya inovatif, atau teknologi tepat guna."],
      ["b.", "Publikasi Ilmiah", "karya tulis ilmiah yang dipublikasikan dalam jurnal, prosiding, atau buku."],
      ["c.", "Paten", "hak eksklusif atas invensi yang diberikan oleh negara."],
      ["d.", "Jurnal Terakreditasi", "jurnal yang telah terakreditasi oleh Diktiristek atau lembaga akreditasi internasional."],
    ],
    pernyataan: [
      "Setiap dosen wajib menghasilkan luaran penelitian minimal satu per tahun, berupa publikasi atau karya ilmiah lainnya.",
      "Universitas Tulungagung menargetkan peningkatan publikasi pada jurnal terakreditasi nasional (SINTA) dan internasional bereputasi.",
      "Luaran penelitian didokumentasikan dalam sistem informasi LPPM dan PD Dikti.",
      "Universitas Tulungagung mendorong pengajuan paten dan HKI atas hasil penelitian yang berpotensi komersialisasi.",
      "Luaran penelitian menjadi salah satu kriteria penilaian kinerja dosen dan promosi jabatan akademik.",
    ],
    strategi: [
      "Memberikan insentif bagi dosen yang mempublikasikan artikel di jurnal terakreditasi.",
      "Menyelenggarakan workshop penulisan artikel ilmiah berkala.",
      "Menyediakan dana hibah penelitian internal dengan skema kompetitif.",
      "Mengembangkan kerja sama dengan jurnal-jurnal terakreditasi untuk memfasilitasi publikasi dosen.",
      "Mengintegrasikan sistem informasi LPPM dengan PD Dikti untuk dokumentasi luaran.",
    ],
    indikator: [
      { indikator: "Jumlah publikasi jurnal per tahun", strategi: "Insentif & workshop", unit: "LPPM", baseline: 150, target: [200, 250, 320, 400, 500] },
      { indikator: "Jumlah publikasi jurnal internasional bereputasi", strategi: "Pendanaan", unit: "LPPM", baseline: 20, target: [30, 45, 60, 80, 100] },
      { indikator: "Jumlah paten yang diajukan per tahun", strategi: "Pendampingan HKI", unit: "LPPM", baseline: 3, target: [5, 8, 12, 18, 25] },
      { indikator: "Jumlah buku/textbook per tahun", strategi: "Hibah buku", unit: "LPPM", baseline: 8, target: [12, 18, 25, 32, 40] },
      { indikator: "Persentase dosen dengan publikasi per tahun", strategi: "SKP & insentif", unit: "LPPM", baseline: 35, target: [45, 55, 65, 75, 85] },
    ],
    dokumenTerkait: DOKUMEN_TERKAIT_DEFAULT,
  },
  {
    namaStandar: "STANDAR PROSES PENELITIAN",
    kodeStandar: "PEN-PRS",
    rasional: [
      "Standar Proses Penelitian mengatur kriteria minimal pelaksanaan penelitian, mulai dari perencanaan, pelaksanaan, hingga pelaporan. Standar ini memastikan bahwa penelitian di Universitas Tulungagung dilaksanakan secara sistematis, etis, dan akuntabel. Proses penelitian yang baik menjadi prasyarat bagi dihasilkannya luaran penelitian yang bermutu dan berdampak.",
      "Universitas Tulungagung menerapkan mekanisme penelitian yang terstruktur, mulai dari pengajuan proposal, review, pelaksanaan, monitoring, hingga pelaporan akhir. Setiap tahapan didokumentasikan secara sistematis, dan dosen peneliti wajib mematuhi etika penelitian dan prinsip-prinsip penelitian yang baik.",
    ],
    pihakPJ: PJ_DEFAULT_PENELITIAN,
    definisi: [
      ["a.", "Proposal Penelitian", "dokumen rencana penelitian yang memuat latar belakang, tujuan, metode, dan jadwal."],
      ["b.", "Review Proposal", "proses penilaian proposal oleh reviewer untuk menilai kelayakan dan kualitas."],
      ["c.", "Monitoring", "kegiatan pengawasan dan pendampingan selama pelaksanaan penelitian."],
      ["d.", "Laporan Akhir", "dokumen yang berisi hasil pelaksanaan penelitian dan luaran yang dihasilkan."],
    ],
    pernyataan: [
      "Setiap penelitian diawali dengan pengajuan proposal yang memuat latar belakang, tujuan, metode, dan jadwal.",
      "Proposal penelitian direview oleh reviewer internal atau eksternal untuk menilai kelayakan dan kualitas.",
      "Pelaksanaan penelitian mengikuti etika penelitian dan prinsip-prinsip penelitian yang baik.",
      "LPPM melakukan monitoring berkala terhadap pelaksanaan penelitian.",
      "Peneliti wajib menyusun laporan akhir dan laporan keuangan setelah penelitian selesai.",
      "Seluruh proses penelitian didokumentasikan dalam sistem informasi LPPM.",
    ],
    strategi: [
      "Menyusun panduan penelitian yang jelas dan mudah diakses oleh dosen.",
      "Mengembangkan sistem informasi LPPM terintegrasi untuk pengelolaan proposal hingga laporan.",
      "Menyelenggarakan workshop penulisan proposal bagi dosen muda.",
      "Membentuk tim reviewer internal yang kompeten dan independen.",
      "Melakukan monitoring lapangan untuk penelitian yang memerlukan verifikasi.",
    ],
    indikator: [
      { indikator: "Persentase proposal dengan dokumentasi lengkap", strategi: "Audit", unit: "LPPM", baseline: 75, target: [85, 92, 97, 100, 100] },
      { indikator: "Persentase penelitian dengan laporan akhir tepat waktu", strategi: "Monitoring", unit: "LPPM", baseline: 70, target: [80, 88, 95, 100, 100] },
      { indikator: "Jumlah penelitian dengan monitoring lapangan", strategi: "Pendampingan", unit: "LPPM", baseline: 30, target: [40, 55, 70, 90, 110] },
      { indikator: "Persentase penelitian sesuai etika", strategi: "Komisi etik", unit: "LPPM", baseline: 85, target: [92, 97, 100, 100, 100] },
      { indikator: "Jumlah reviewer internal bersertifikat", strategi: "Pelatihan", unit: "LPPM", baseline: 15, target: [20, 28, 35, 45, 55] },
    ],
    dokumenTerkait: DOKUMEN_TERKAIT_DEFAULT,
  },
  {
    namaStandar: "STANDAR MASUKAN PENELITIAN",
    kodeStandar: "PEN-MSK",
    rasional: [
      "Standar Masukan Penelitian mengatur kriteria minimal sumber daya yang diperlukan untuk pelaksanaan penelitian, mencakup pendanaan, SDM, sarana prasarana, dan sistem informasi. Standar ini memastikan bahwa penelitian di Universitas Tulungagung didukung oleh sumber daya yang memadai untuk menghasilkan luaran yang bermutu.",
      "Universitas Tulungagung berkomitmen untuk menyediakan sumber daya penelitian yang memadai, melalui alokasi anggaran internal, pengembangan SDM, investasi sarana prasarana, dan pengembangan sistem informasi. Selain itu, Universitas Tulungagung juga aktif mencari pendanaan eksternal dari Diktiristek, DUDI, dan lembaga internasional.",
    ],
    pihakPJ: PJ_DEFAULT_PENELITIAN,
    definisi: [
      ["a.", "Pendanaan Penelitian", "dana yang dialokasikan untuk pelaksanaan penelitian, dari internal atau eksternal."],
      ["b.", "Peneliti", "dosen atau tim dosen yang melaksanakan penelitian."],
      ["c.", "Sarana Penelitian", "peralatan dan fasilitas untuk pelaksanaan penelitian."],
      ["d.", "Sistem Informasi Penelitian", "platform digital untuk pengelolaan data dan informasi penelitian."],
    ],
    pernyataan: [
      "Universitas Tulungagung mengalokasikan dana penelitian internal minimal 10% dari anggaran tahunan.",
      "Universitas Tulungagung aktif mencari pendanaan eksternal dari Diktiristek, DUDI, dan lembaga internasional.",
      "Setiap peneliti memiliki kualifikasi dan kompetensi yang sesuai dengan bidang penelitian.",
      "Universitas Tulungagung menyediakan sarana penelitian yang memadai, termasuk laboratorium dan peralatan.",
      "Sistem informasi LPPM terintegrasi dengan PD Dikti untuk pengelolaan data penelitian.",
    ],
    strategi: [
      "Meningkatkan alokasi anggaran penelitian internal secara bertahap.",
      "Membentuk tim khusus untuk pencarian pendanaan eksternal.",
      "Mengembangkan laboratorium riset dengan peralatan terkini.",
      "Menyelenggarakan pelatihan metodologi penelitian bagi dosen.",
      "Mengintegrasikan sistem informasi LPPM dengan PD Dikti.",
    ],
    indikator: [
      { indikator: "Pendanaan penelitian internal (Rp juta/tahun)", strategi: "Alokasi anggaran", unit: "BAKU", baseline: 500, target: [700, 900, 1200, 1500, 2000] },
      { indikator: "Pendanaan penelitian eksternal (Rp juta/tahun)", strategi: "Pencarian hibah", unit: "LPPM", baseline: 300, target: [500, 800, 1200, 1800, 2500] },
      { indikator: "Jumlah peneliti aktif per tahun", strategi: "Pendampingan", unit: "LPPM", baseline: 80, target: [100, 130, 160, 200, 250] },
      { indikator: "Persentase laboratorium dengan peralatan standar", strategi: "Investasi", unit: "UPPS", baseline: 70, target: [78, 85, 92, 97, 100] },
      { indikator: "Persentase data penelitian terintegrasi PD Dikti", strategi: "IT integration", unit: "UPT SI", baseline: 60, target: [75, 88, 95, 100, 100] },
    ],
    dokumenTerkait: DOKUMEN_TERKAIT_DEFAULT,
  },
  {
    namaStandar: "STANDAR HASIL PENELITIAN",
    kodeStandar: "PEN-HSL",
    rasional: [
      "Standar Hasil Penelitian mengatur kriteria minimal kualitas hasil penelitian yang dihasilkan oleh Universitas Tulungagung. Hasil penelitian yang baik harus orisinal, bermutu, dan berdampak bagi pengembangan IPTEK dan kesejahteraan masyarakat. Standar ini berbeda dengan Standar Luaran yang lebih fokus pada produk publikasi, karena Standar Hasil fokus pada substansi kontribusi penelitian.",
      "Universitas Tulungagung mendorong dosen untuk menghasilkan penelitian yang tidak hanya publikasi, tetapi juga memberikan kontribusi nyata bagi pengembangan ilmu dan masyarakat. Hal ini sejalan dengan sasaran strategis ke-5 Universitas Tulungagung, yaitu menghasilkan produk unggulan berbasis Teknologi Tepat Guna yang berdampak untuk kesejahteraan masyarakat.",
    ],
    pihakPJ: PJ_DEFAULT_PENELITIAN,
    definisi: [
      ["a.", "Hasil Penelitian", "substansi kontribusi penelitian terhadap pengembangan IPTEK."],
      ["b.", "Orisinalitas", "kebaruan hasil penelitian dibandingkan dengan penelitian sebelumnya."],
      ["c.", "Dampak", "kontribusi penelitian terhadap pengembangan ilmu, masyarakat, atau industri."],
      ["d.", "Teknologi Tepat Guna", "teknologi yang sesuai dengan kebutuhan dan kondisi masyarakat pengguna."],
    ],
    pernyataan: [
      "Hasil penelitian harus orisinal dan memberikan kontribusi terhadap pengembangan IPTEK.",
      "Universitas Tulungagung mendorong penelitian yang berdampak bagi masyarakat dan industri.",
      "Hasil penelitian didokumentasikan dalam bentuk laporan akhir, publikasi, atau karya inovatif.",
      "Universitas Tulungagung mendorong komersialisasi hasil penelitian yang berpotensi.",
      "Hasil penelitian menjadi bahan bagi pengembangan kurikulum dan pembelajaran.",
    ],
    strategi: [
      "Menyelenggarakan forum diskusi hasil penelitian setiap semester.",
      "Mengembangkan inkubator bisnis untuk komersialisasi hasil penelitian.",
      "Mengintegrasikan hasil penelitian dalam pembelajaran melalui research-based learning.",
      "Mengundang DUDI untuk mengidentifikasi hasil penelitian yang berpotensi komersialisasi.",
      "Mengembangkan sistem informasi untuk dokumentasi hasil penelitian.",
    ],
    indikator: [
      { indikator: "Jumlah hasil penelitian yang dikomersialisasi per tahun", strategi: "Inkubator bisnis", unit: "LPPM", baseline: 2, target: [4, 7, 12, 18, 25] },
      { indikator: "Jumlah Teknologi Tepat Guna yang dihasilkan", strategi: "Hibah TTG", unit: "LPPM", baseline: 10, target: [15, 22, 30, 40, 50] },
      { indikator: "Jumlah sitasi publikasi per tahun", strategi: "Diseminasi", unit: "LPPM", baseline: 200, target: [300, 450, 650, 900, 1200] },
      { indikator: "Jumlah penelitian yang diintegrasikan ke kurikulum", strategi: "RBL", unit: "UPPS", baseline: 25, target: [40, 60, 85, 110, 140] },
      { indikator: "Tingkat adopsi hasil penelitian oleh masyarakat/industri", strategi: "Diseminasi", unit: "LPPM", baseline: 30, target: [40, 55, 70, 85, 100] },
    ],
    dokumenTerkait: DOKUMEN_TERKAIT_DEFAULT,
  },
  {
    namaStandar: "STANDAR PUBLIKASI ILMIAH PENELITIAN",
    kodeStandar: "PEN-PUB",
    rasional: [
      "Standar Publikasi Ilmiah Penelitian mengatur kriteria minimal publikasi hasil penelitian. Publikasi menjadi sarana diseminasi pengetahuan dan indikator utama produktivitas ilmiah perguruan tinggi. Universitas Tulungagung menargetkan peningkatan publikasi pada jurnal terakreditasi nasional dan internasional bereputasi, sebagaimana tertuang dalam sasaran strategis ke-4.",
      "Universitas Tulungagung menyadari bahwa publikasi yang bermutu memerlukan dukungan sistemik—mulai dari pendanaan, pelatihan, hingga akses jurnal. Oleh karena itu, Universitas Tulungagung mengembangkan ekosistem publikasi yang mendukung dosen untuk mempublikasikan hasil penelitiannya pada jurnal-jurnal berkualitas.",
    ],
    pihakPJ: PJ_DEFAULT_PENELITIAN,
    definisi: [
      ["a.", "Publikasi Ilmiah", "karya tulis ilmiah yang dipublikasikan dalam jurnal, prosiding, atau buku."],
      ["b.", "Jurnal Terakreditasi", "jurnal yang terakreditasi SINTA 1-6 oleh Diktiristek."],
      ["c.", "Jurnal Internasional Bereputasi", "jurnal internasional yang terindeks Scopus atau Web of Science."],
      ["d.", "Prosiding", "kumpulan makalah yang dipresentasikan dalam seminar ilmiah dan diterbitkan."],
    ],
    pernyataan: [
      "Setiap penelitian wajib menghasilkan publikasi ilmiah minimal satu artikel.",
      "Universitas Tulungagung menargetkan publikasi pada jurnal terakreditasi SINTA dan internasional bereputasi.",
      "Publikasi didokumentasikan dalam sistem informasi LPPM dan PD Dikti.",
      "Universitas Tulungagung menyediakan dana pendukung publikasi (page charges) bagi dosen.",
      "Universitas Tulungagung mendorong publikasi pada prosiding seminar internasional bereputasi.",
    ],
    strategi: [
      "Menyediakan dana page charges untuk publikasi di jurnal internasional bereputasi.",
      "Menyelenggarakan workshop penulisan artikel ilmiah berkala.",
      "Mengembangkan jurnal universitas dengan target akreditasi SINTA.",
      "Mengundang editor jurnal untuk memberikan pelatihan kepada dosen.",
      "Mengembangkan sistem informasi publikasi yang terintegrasi dengan PD Dikti.",
    ],
    indikator: [
      { indikator: "Jumlah publikasi jurnal SINTA 1-3 per tahun", strategi: "Insentif", unit: "LPPM", baseline: 30, target: [45, 65, 90, 120, 160] },
      { indikator: "Jumlah publikasi Scopus/Web of Science per tahun", strategi: "Pendanaan", unit: "LPPM", baseline: 15, target: [25, 40, 60, 85, 110] },
      { indikator: "Jumlah prosiding seminar internasional per tahun", strategi: "Hibat", unit: "LPPM", baseline: 40, target: [55, 75, 100, 130, 160] },
      { indikator: "Persentase penelitian dengan publikasi", strategi: "Monitoring", unit: "LPPM", baseline: 75, target: [85, 92, 97, 100, 100] },
      { indikator: "Jumlah dosen dengan publikasi internasional per tahun", strategi: "Pendampingan", unit: "LPPM", baseline: 25, target: [40, 60, 85, 110, 140] },
    ],
    dokumenTerkait: DOKUMEN_TERKAIT_DEFAULT,
  },
  {
    namaStandar: "STANDAR PATEN DAN HKI PENELITIAN",
    kodeStandar: "PEN-PTN",
    rasional: [
      "Standar Paten dan HKI Penelitian mengatur kriteria minimal pengelolaan hak kekayaan intelektual atas hasil penelitian. Paten dan HKI menjadi indikator inovasi perguruan tinggi dan menjadi sumber pendapatan potensial melalui komersialisasi. Universitas Tulungagung mendorong dosen untuk mengajukan paten dan HKI atas hasil penelitian yang berpotensi komersial.",
      "Pengelolaan HKI yang baik juga melindungi hak dosen dan Universitas Tulungagung atas karya intelektual yang dihasilkan. Universitas Tulungagung menyediakan pendampingan untuk pengajuan paten dan HKI, serta mengembangkan mekanisme pembagian keuntungan dari komersialisasi yang adil.",
    ],
    pihakPJ: PJ_DEFAULT_PENELITIAN,
    definisi: [
      ["a.", "Paten", "hak eksklusif atas invensi yang diberikan oleh negara untuk jangka waktu tertentu."],
      ["b.", "HKI", "Hak Kekayaan Intelektual, mencakup paten, merek, hak cipta, desain industri, dan rahasia dagang."],
      ["c.", "Komersialisasi", "proses mengubah hasil penelitian menjadi produk atau jasa komersial."],
      ["d.", "Lisensi", "izin penggunaan HKI kepada pihak lain dengan kompensasi tertentu."],
    ],
    pernyataan: [
      "Universitas Tulungagung mendorong pengajuan paten dan HKI atas hasil penelitian yang berpotensi.",
      "Universitas Tulungagung menyediakan pendampingan untuk pengajuan paten dan HKI.",
      "Universitas Tulungagung memiliki kebijakan pembagian keuntungan dari komersialisasi HKI yang adil.",
      "Paten dan HKI didokumentasikan dalam sistem informasi LPPM dan PD Dikti.",
      "Universitas Tulungagung mengembangkan kerja sama dengan DUDI untuk komersialisasi HKI.",
    ],
    strategi: [
      "Menyelenggarakan workshop HKI bagi dosen peneliti.",
      "Menyediakan dana untuk pengajuan paten dan HKI.",
      "Bekerja sama dengan konsultan HKI profesional untuk pendampingan.",
      "Mengembangkan inkubator bisnis untuk komersialisasi HKI.",
      "Mengintegrasikan dokumentasi HKI dengan PD Dikti.",
    ],
    indikator: [
      { indikator: "Jumlah paten diajukan per tahun", strategi: "Pendampingan", unit: "LPPM", baseline: 3, target: [6, 10, 15, 22, 30] },
      { indikator: "Jumlah paten granted per tahun", strategi: "Kualitas penelitian", unit: "LPPM", baseline: 1, target: [2, 4, 7, 10, 15] },
      { indikator: "Jumlah HKI lainnya (hak cipta, merek) per tahun", strategi: "Sosialisasi", unit: "LPPM", baseline: 10, target: [15, 22, 30, 40, 50] },
      { indikator: "Jumlah HKI yang dikomersialisasi", strategi: "Inkubator bisnis", unit: "LPPM", baseline: 1, target: [2, 4, 7, 10, 15] },
      { indikator: "Pendapatan dari komersialisasi HKI (Rp juta)", strategi: "Kerjasama DUDI", unit: "BAKU", baseline: 10, target: [25, 50, 100, 200, 350] },
    ],
    dokumenTerkait: DOKUMEN_TERKAIT_DEFAULT,
  },
  {
    namaStandar: "STANDAR DISEMINASI PENELITIAN",
    kodeStandar: "PEN-DSM",
    rasional: [
      "Standar Diseminasi Penelitian mengatur kriteria minimal penyebarluasan hasil penelitian kepada masyarakat akademik dan publik. Diseminasi yang baik meningkatkan dampak penelitian dan reputasi perguruan tinggi. Universitas Tulungagung menyelenggarakan berbagai forum diseminasi—seperti seminar, konferensi, dan publikasi media—untuk menyebarluaskan hasil penelitian.",
      "Diseminasi juga menjadi sarana untuk memperoleh umpan balik dari masyarakat akademik dan publik, sehingga dapat meningkatkan kualitas penelitian selanjutnya. Universitas Tulungagung mendorong dosen untuk aktif menyebarkan hasil penelitian melalui berbagai saluran, baik akademik maupun publik.",
    ],
    pihakPJ: PJ_DEFAULT_PENELITIAN,
    definisi: [
      ["a.", "Diseminasi", "penyebarluasan hasil penelitian kepada masyarakat akademik dan publik."],
      ["b.", "Seminar", "forum pertemuan ilmiah untuk presentasi dan diskusi hasil penelitian."],
      ["c.", "Konferensi", "pertemuan ilmiah berskala besar dengan peserta dari berbagai institusi."],
      ["d.", "Publikasi Media", "penyampaian hasil penelitian melalui media massa untuk publik luas."],
    ],
    pernyataan: [
      "Universitas Tulungagung menyelenggarakan seminar dan konferensi ilmiah secara berkala.",
      "Universitas Tulungagung mendorong dosen untuk mempresentasikan hasil penelitian di forum ilmiah.",
      "Hasil penelitian disebarkan juga melalui media massa untuk publik luas.",
      "Universitas Tulungagung mengembangkan platform digital untuk diseminasi penelitian.",
      "Hasil diseminasi didokumentasikan dalam sistem informasi LPPM.",
    ],
    strategi: [
      "Menyelenggarakan seminar nasional tahunan Universitas Tulungagung.",
      "Memberikan pendanaan bagi dosen yang presentasi di konferensi internasional.",
      "Bekerja sama dengan media massa untuk publikasi hasil penelitian.",
      "Mengembangkan repository digital untuk dokumentasi hasil penelitian.",
      "Mengundang akademisi eksternal untuk seminar di Universitas Tulungagung.",
    ],
    indikator: [
      { indikator: "Jumlah seminar/konferensi diselenggarakan per tahun", strategi: "Pendanaan", unit: "LPPM", baseline: 5, target: [8, 12, 16, 22, 30] },
      { indikator: "Jumlah dosen presentasi di konferensi internasional", strategi: "Hibah", unit: "LPPM", baseline: 30, target: [45, 65, 90, 120, 150] },
      { indikator: "Jumlah publikasi di media massa per tahun", strategi: "Kerjasama media", unit: "LPPM", baseline: 15, target: [25, 40, 60, 85, 110] },
      { indikator: "Jumlah akses repository per tahun", strategi: "Pengembangan digital", unit: "UPT SI", baseline: 5000, target: [8000, 12000, 18000, 25000, 35000] },
      { indikator: "Jumlah undangan akademisi eksternal", strategi: "Networking", unit: "LPPM", baseline: 10, target: [15, 22, 30, 40, 50] },
    ],
    dokumenTerkait: DOKUMEN_TERKAIT_DEFAULT,
  },
  {
    namaStandar: "STANDAR KOLABORASI PENELITIAN",
    kodeStandar: "PEN-KLB",
    rasional: [
      "Standar Kolaborasi Penelitian mengatur kriteria minimal kerja sama penelitian dengan institusi lain, baik nasional maupun internasional. Kolaborasi menjadi sarana untuk memperluas jaringan, berbagi sumber daya, dan meningkatkan kualitas penelitian. Universitas Tulungagung aktif mengembangkan kerja sama penelitian dengan perguruan tinggi lain, DUDI, dan lembaga penelitian.",
      "Kolaborasi internasional menjadi salah satu indikator reputasi perguruan tinggi. Universitas Tulungagung menargetkan peningkatan kerja sama internasional, khususnya dengan perguruan tinggi di Asia Tenggara, Australia, dan Eropa. Hal ini sejalan dengan visi Universitas Tulungagung untuk berkompetisi berskala internasional.",
    ],
    pihakPJ: PJ_DEFAULT_PENELITIAN,
    definisi: [
      ["a.", "Kolaborasi Penelitian", "kerja sama penelitian antara dua atau lebih institusi."],
      ["b.", "MoU", "Memorandum of Understanding, perjanjian kerja sama tingkat umum."],
      ["c.", "MoA", "Memorandum of Agreement, perjanjian kerja sama spesifik."],
      ["d.", "Joint Research", "penelitian bersama yang melibatkan peneliti dari beberapa institusi."],
    ],
    pernyataan: [
      "Universitas Tulungagung aktif mengembangkan kerja sama penelitian dengan PT lain, DUDI, dan lembaga penelitian.",
      "Kerja sama penelitian didokumentasikan dalam bentuk MoU/MoA yang jelas.",
      "Universitas Tulungagung mengembangkan joint research dengan institusi nasional dan internasional.",
      "Kerja sama penelitian dilaporkan dalam sistem informasi LPPM dan PD Dikti.",
      "Universitas Tulungagung memberikan dukungan administratif dan finansial untuk kolaborasi penelitian.",
    ],
    strategi: [
      "Mengembangkan kerja sama strategis dengan PT unggulan nasional dan internasional.",
      "Mengundang peneliti eksternal sebagai visiting researcher.",
      "Menyelenggarakan joint conference dengan PT mitra.",
      "Mengembangkan program joint degree dengan PT internasional.",
      "Memberikan insentif bagi dosen yang aktif dalam kolaborasi penelitian.",
    ],
    indikator: [
      { indikator: "Jumlah MoU/MoA penelitian aktif", strategi: "Networking", unit: "LPPM", baseline: 20, target: [30, 45, 65, 90, 120] },
      { indikator: "Jumlah joint research per tahun", strategi: "Pendanaan", unit: "LPPM", baseline: 5, target: [10, 18, 28, 40, 55] },
      { indikator: "Jumlah kerjasama internasional aktif", strategi: "Ekspansi", unit: "LPPM", baseline: 5, target: [10, 18, 28, 40, 55] },
      { indikator: "Jumlah visiting researcher per tahun", strategi: "Pendanaan", unit: "LPPM", baseline: 3, target: [6, 10, 15, 22, 30] },
      { indikator: "Jumlah joint publication per tahun", strategi: "Insentif", unit: "LPPM", baseline: 10, target: [18, 28, 40, 55, 70] },
    ],
    dokumenTerkait: DOKUMEN_TERKAIT_DEFAULT,
  },
];

module.exports = {
  STANDAR_PENDIDIKAN,
  STANDAR_PENELITIAN,
  PJ_DEFAULT_AKADEMIK,
  PJ_DEFAULT_PENELITIAN,
  PJ_DEFAULT_NONAKADEMIK,
  DOKUMEN_TERKAIT_DEFAULT,
};
