// ============================================================
// DATA: 8 STANDAR PkM + 9 STANDAR TAMBAHAN
// ============================================================

const {
  PJ_DEFAULT_AKADEMIK,
  PJ_DEFAULT_PENELITIAN,
  PJ_DEFAULT_NONAKADEMIK,
  DOKUMEN_TERKAIT_DEFAULT,
} = require("./standar_mutu_data1.js");

// Pihak PJ khusus untuk PkM (menggunakan PJ_DEFAULT_PENELITIAN karena LPPM handle)
const PJ_DEFAULT_PKM = PJ_DEFAULT_PENELITIAN;

// ============================================================
// 8 STANDAR PENGABDIAN KEPADA MASYARAKAT (PkM)
// ============================================================
const STANDAR_PKM = [
  {
    namaStandar: "STANDAR LUARAN PkM",
    kodeStandar: "PKM-LRN",
    rasional: [
      "Standar Luaran PkM mengatur kriteria minimal hasil Pengabdian kepada Masyarakat yang dihasilkan oleh Universitas Tulungagung. Luaran PkM mencakup produk, jasa, metode, dan publikasi PkM. Standar ini menjadi tolok ukur kualitas dan produktivitas PkM Universitas Tulungagung, serta menjadi indikator dampak perguruan tinggi terhadap masyarakat.",
      "Universitas Tulungagung memandang PkM sebagai wujud nyata kontribusi perguruan tinggi kepada masyarakat, sebagaimana diamanatkan dalam Tujuan ke-4: terwujudnya pengabdian kepada masyarakat berbasis penalaran dan karya penelitian yang bermanfaat dalam memajukan kesejahteraan umum dan mencerdaskan kehidupan bangsa. Universitas Tulungagung menargetkan peningkatan kuantitas dan kualitas luaran PkM yang berdampak nyata bagi masyarakat.",
    ],
    pihakPJ: PJ_DEFAULT_PKM,
    definisi: [
      ["a.", "Luaran PkM", "hasil PkM yang dapat berupa produk, jasa, metode, atau publikasi."],
      ["b.", "Produk PkM", "barang hasil PkM yang dapat dimanfaatkan oleh masyarakat."],
      ["c.", "Jasa PkM", "layanan hasil PkM yang diberikan kepada masyarakat."],
      ["d.", "Publikasi PkM", "karya tulis yang memublikasikan hasil PkM."],
    ],
    pernyataan: [
      "Setiap dosen wajib menghasilkan luaran PkM minimal satu per tahun, berupa produk, jasa, metode, atau publikasi.",
      "Universitas Tulungagung menargetkan peningkatan luaran PkM yang berdampak nyata bagi masyarakat.",
      "Luaran PkM didokumentasikan dalam sistem informasi LPPM dan PD Dikti.",
      "Luaran PkM menjadi salah satu kriteria penilaian kinerja dosen dan promosi jabatan akademik.",
      "Universitas Tulungagung mendorong luaran PkM yang berkelanjutan dan dapat direplikasi.",
    ],
    strategi: [
      "Memberikan insentif bagi dosen yang menghasilkan luaran PkM berdampak.",
      "Menyelenggarakan workshop penulisan proposal PkM berkala.",
      "Menyediakan dana hibah PkM internal dengan skema kompetitif.",
      "Mengembangkan kerja sama dengan DUDI untuk PkM berbasis kebutuhan masyarakat.",
      "Mengintegrasikan sistem informasi LPPM dengan PD Dikti untuk dokumentasi luaran.",
    ],
    indikator: [
      { indikator: "Jumlah luaran PkM per tahun", strategi: "Insentif & pendampingan", unit: "LPPM", baseline: 80, target: [110, 150, 200, 260, 330] },
      { indikator: "Jumlah produk PkM yang diadopsi masyarakat", strategi: "Pendampingan", unit: "LPPM", baseline: 15, target: [22, 32, 45, 60, 80] },
      { indikator: "Jumlah publikasi PkM di jurnal per tahun", strategi: "Workshop", unit: "LPPM", baseline: 30, target: [45, 65, 90, 120, 160] },
      { indikator: "Jumlah metode PkM yang diadopsi mitra", strategi: "Kerjasama", unit: "LPPM", baseline: 8, target: [12, 18, 25, 35, 45] },
      { indikator: "Persentase dosen dengan luaran PkM per tahun", strategi: "SKP", unit: "LPPM", baseline: 30, target: [40, 50, 60, 70, 80] },
    ],
    dokumenTerkait: DOKUMEN_TERKAIT_DEFAULT,
  },
  {
    namaStandar: "STANDAR PROSES PkM",
    kodeStandar: "PKM-PRS",
    rasional: [
      "Standar Proses PkM mengatur kriteria minimal pelaksanaan PkM, mulai dari perencanaan, pelaksanaan, hingga pelaporan. Standar ini memastikan bahwa PkM di Universitas Tulungagung dilaksanakan secara sistematis, etis, dan akuntabel. Proses PkM yang baik menjadi prasyarat bagi dihasilkannya luaran PkM yang bermutu dan berdampak.",
      "Universitas Tulungagung menerapkan mekanisme PkM yang terstruktur, mulai dari pengajuan proposal, review, pelaksanaan, monitoring, hingga pelaporan akhir. Setiap tahapan didokumentasikan secara sistematis, dan dosen pelaksana wajib mematuhi etika PkM dan prinsip-prinsip pengabdian yang baik.",
    ],
    pihakPJ: PJ_DEFAULT_PKM,
    definisi: [
      ["a.", "Proposal PkM", "dokumen rencana PkM yang memuat latar belakang, tujuan, metode, dan jadwal."],
      ["b.", "Review Proposal PkM", "proses penilaian proposal PkM oleh reviewer untuk menilai kelayakan dan kualitas."],
      ["c.", "Monitoring PkM", "kegiatan pengawasan dan pendampingan selama pelaksanaan PkM."],
      ["d.", "Laporan Akhir PkM", "dokumen yang berisi hasil pelaksanaan PkM dan luaran yang dihasilkan."],
    ],
    pernyataan: [
      "Setiap PkM diawali dengan pengajuan proposal yang memuat latar belakang, tujuan, metode, dan jadwal.",
      "Proposal PkM direview oleh reviewer internal atau eksternal untuk menilai kelayakan dan kualitas.",
      "Pelaksanaan PkM mengikuti etika PkM dan prinsip-prinsip pengabdian yang baik.",
      "LPPM melakukan monitoring berkala terhadap pelaksanaan PkM.",
      "Dosen pelaksana wajib menyusun laporan akhir dan laporan keuangan setelah PkM selesai.",
      "Seluruh proses PkM didokumentasikan dalam sistem informasi LPPM.",
    ],
    strategi: [
      "Menyusun panduan PkM yang jelas dan mudah diakses oleh dosen.",
      "Mengembangkan sistem informasi LPPM terintegrasi untuk pengelolaan proposal hingga laporan.",
      "Menyelenggarakan workshop penulisan proposal PkM bagi dosen muda.",
      "Membentuk tim reviewer internal yang kompeten dan independen.",
      "Melakukan monitoring lapangan untuk PkM yang memerlukan verifikasi.",
    ],
    indikator: [
      { indikator: "Persentase proposal PkM dengan dokumentasi lengkap", strategi: "Audit", unit: "LPPM", baseline: 70, target: [82, 90, 96, 100, 100] },
      { indikator: "Persentase PkM dengan laporan akhir tepat waktu", strategi: "Monitoring", unit: "LPPM", baseline: 65, target: [78, 88, 95, 100, 100] },
      { indikator: "Jumlah PkM dengan monitoring lapangan", strategi: "Pendampingan", unit: "LPPM", baseline: 25, target: [35, 50, 70, 90, 110] },
      { indikator: "Persentase PkM sesuai etika", strategi: "Komisi etik", unit: "LPPM", baseline: 85, target: [92, 97, 100, 100, 100] },
      { indikator: "Jumlah reviewer internal PkM bersertifikat", strategi: "Pelatihan", unit: "LPPM", baseline: 10, target: [15, 22, 30, 40, 50] },
    ],
    dokumenTerkait: DOKUMEN_TERKAIT_DEFAULT,
  },
  {
    namaStandar: "STANDAR MASUKAN PkM",
    kodeStandar: "PKM-MSK",
    rasional: [
      "Standar Masukan PkM mengatur kriteria minimal sumber daya yang diperlukan untuk pelaksanaan PkM, mencakup pendanaan, SDM, sarana prasarana, dan sistem informasi. Standar ini memastikan bahwa PkM di Universitas Tulungagung didukung oleh sumber daya yang memadai untuk menghasilkan luaran yang bermutu dan berdampak.",
      "Universitas Tulungagung berkomitmen untuk menyediakan sumber daya PkM yang memadai, melalui alokasi anggaran internal, pengembangan SDM, investasi sarana prasarana, dan pengembangan sistem informasi. Universitas Tulungagung juga aktif mencari pendanaan eksternal dari Diktiristek, DUDI, dan lembaga internasional untuk PkM.",
    ],
    pihakPJ: PJ_DEFAULT_PKM,
    definisi: [
      ["a.", "Pendanaan PkM", "dana yang dialokasikan untuk pelaksanaan PkM, dari internal atau eksternal."],
      ["b.", "Pelaksana PkM", "dosen atau tim dosen yang melaksanakan PkM."],
      ["c.", "Sarana PkM", "peralatan dan fasilitas untuk pelaksanaan PkM."],
      ["d.", "Sistem Informasi PkM", "platform digital untuk pengelolaan data dan informasi PkM."],
    ],
    pernyataan: [
      "Universitas Tulungagung mengalokasikan dana PkM internal minimal 5% dari anggaran tahunan.",
      "Universitas Tulungagung aktif mencari pendanaan eksternal dari Diktiristek, DUDI, dan lembaga internasional.",
      "Setiap pelaksana PkM memiliki kualifikasi dan kompetensi yang sesuai dengan bidang PkM.",
      "Universitas Tulungagung menyediakan sarana PkM yang memadai, termasuk peralatan dan transportasi.",
      "Sistem informasi LPPM terintegrasi dengan PD Dikti untuk pengelolaan data PkM.",
    ],
    strategi: [
      "Meningkatkan alokasi anggaran PkM internal secara bertahap.",
      "Membentuk tim khusus untuk pencarian pendanaan eksternal.",
      "Mengembangkan kerjasama dengan DUDI untuk PkM berbasis kebutuhan masyarakat.",
      "Menyelenggarakan pelatihan metodologi PkM bagi dosen.",
      "Mengintegrasikan sistem informasi LPPM dengan PD Dikti.",
    ],
    indikator: [
      { indikator: "Pendanaan PkM internal (Rp juta/tahun)", strategi: "Alokasi anggaran", unit: "BAKU", baseline: 250, target: [350, 480, 650, 850, 1100] },
      { indikator: "Pendanaan PkM eksternal (Rp juta/tahun)", strategi: "Pencarian hibah", unit: "LPPM", baseline: 150, target: [250, 400, 600, 900, 1300] },
      { indikator: "Jumlah pelaksana PkM aktif per tahun", strategi: "Pendampingan", unit: "LPPM", baseline: 60, target: [80, 105, 135, 170, 210] },
      { indikator: "Persentase sarana PkM yang memadai", strategi: "Investasi", unit: "LPPM", baseline: 70, target: [78, 85, 92, 97, 100] },
      { indikator: "Persentase data PkM terintegrasi PD Dikti", strategi: "IT integration", unit: "UPT SI", baseline: 55, target: [72, 85, 93, 100, 100] },
    ],
    dokumenTerkait: DOKUMEN_TERKAIT_DEFAULT,
  },
  {
    namaStandar: "STANDAR HASIL PkM",
    kodeStandar: "PKM-HSL",
    rasional: [
      "Standar Hasil PkM mengatur kriteria minimal kualitas hasil PkM yang dihasilkan oleh Universitas Tulungagung. Hasil PkM yang baik harus berdampak nyata bagi masyarakat, dapat direplikasi, dan berkelanjutan. Standar ini berbeda dengan Standar Luaran yang lebih fokus pada produk, karena Standar Hasil fokus pada substansi dampak PkM.",
      "Universitas Tulungagung mendorong dosen untuk menghasilkan PkM yang tidak hanya produk, tetapi juga memberikan kontribusi nyata bagi peningkatan kesejahteraan masyarakat. Hal ini sejalan dengan sasaran strategis ke-5 Universitas Tulungagung, yaitu menghasilkan produk unggulan berbasis Teknologi Tepat Guna yang berdampak untuk kesejahteraan masyarakat.",
    ],
    pihakPJ: PJ_DEFAULT_PKM,
    definisi: [
      ["a.", "Hasil PkM", "substansi dampak PkM terhadap peningkatan kesejahteraan masyarakat."],
      ["b.", "Dampak PkM", "perubahan yang terjadi pada masyarakat akibat PkM."],
      ["c.", "Replikasi", "pengulangan PkM di lokasi atau masyarakat lain."],
      ["d.", "Berkelanjutan", "PkM yang memberikan dampak jangka panjang dan dapat dipertahankan."],
    ],
    pernyataan: [
      "Hasil PkM harus berdampak nyata bagi masyarakat, dapat diukur dan didokumentasikan.",
      "Universitas Tulungagung mendorong PkM yang dapat direplikasi di lokasi atau masyarakat lain.",
      "Hasil PkM harus berkelanjutan, tidak hanya satu kali kegiatan.",
      "Hasil PkM didokumentasikan dalam bentuk laporan akhir, publikasi, atau karya inovatif.",
      "Hasil PkM menjadi bahan bagi pengembangan kurikulum dan pembelajaran.",
    ],
    strategi: [
      "Menyelenggarakan forum diskusi hasil PkM setiap semester.",
      "Mengembangkan kerjasama dengan DUDI untuk replikasi PkM.",
      "Mengintegrasikan hasil PkM dalam pembelajaran melalui community-based learning.",
      "Mengundang DUDI untuk mengidentifikasi hasil PkM yang berpotensi komersialisasi.",
      "Mengembangkan sistem informasi untuk dokumentasi hasil PkM.",
    ],
    indikator: [
      { indikator: "Jumlah PkM dengan dampak terukur per tahun", strategi: "Pendampingan", unit: "LPPM", baseline: 20, target: [30, 45, 60, 80, 100] },
      { indikator: "Jumlah PkM yang direplikasi", strategi: "Kerjasama", unit: "LPPM", baseline: 5, target: [8, 13, 20, 30, 40] },
      { indikator: "Jumlah PkM berkelanjutan (>2 tahun)", strategi: "Pendanaan", unit: "LPPM", baseline: 15, target: [22, 32, 45, 60, 80] },
      { indikator: "Tingkat kepuasan masyarakat terhadap PkM", strategi: "Survey", unit: "LPPM", baseline: 75, target: [80, 85, 90, 93, 96] },
      { indikator: "Jumlah PkM diintegrasikan ke kurikulum", strategi: "CBL", unit: "UPPS", baseline: 15, target: [25, 38, 55, 75, 100] },
    ],
    dokumenTerkait: DOKUMEN_TERKAIT_DEFAULT,
  },
  {
    namaStandar: "STANDAR PUBLIKASI PkM",
    kodeStandar: "PKM-PUB",
    rasional: [
      "Standar Publikasi PkM mengatur kriteria minimal publikasi hasil PkM. Publikasi PkM menjadi sarana diseminasi pengetahuan tentang praktik pengabdian yang baik dan indikator dampak perguruan tinggi terhadap masyarakat. Universitas Tulungagung menargetkan peningkatan publikasi PkM pada jurnal terakreditasi dan forum ilmiah.",
      "Publikasi PkM berbeda dengan publikasi penelitian, karena fokus pada pengalaman dan dampak pengabdian kepada masyarakat. Universitas Tulungagung mengembangkan ekosistem publikasi PkM yang mendukung dosen untuk mempublikasikan hasil PkM pada forum-forum berkualitas.",
    ],
    pihakPJ: PJ_DEFAULT_PKM,
    definisi: [
      ["a.", "Publikasi PkM", "karya tulis yang mempublikasikan hasil PkM."],
      ["b.", "Jurnal PkM", "jurnal khusus yang memublikasikan artikel tentang PkM."],
      ["c.", "Prosiding PkM", "kumpulan makalah PkM yang dipresentasikan dalam seminar."],
      ["d.", "Best Practice PkM", "praktik baik PkM yang didokumentasikan untuk replikasi."],
    ],
    pernyataan: [
      "Setiap PkM wajib menghasilkan publikasi minimal satu artikel atau laporan.",
      "Universitas Tulungagung menargetkan publikasi PkM pada jurnal terakreditasi.",
      "Publikasi PkM didokumentasikan dalam sistem informasi LPPM dan PD Dikti.",
      "Universitas Tulungagung menyediakan dana pendukung publikasi PkM.",
      "Universitas Tulungagung mendorong dokumentasi best practice PkM untuk replikasi.",
    ],
    strategi: [
      "Menyediakan dana page charges untuk publikasi PkM di jurnal terakreditasi.",
      "Menyelenggarakan workshop penulisan artikel PkM berkala.",
      "Mengembangkan jurnal PkM universitas dengan target akreditasi SINTA.",
      "Mengundang editor jurnal PkM untuk memberikan pelatihan kepada dosen.",
      "Mengembangkan sistem informasi publikasi PkM yang terintegrasi dengan PD Dikti.",
    ],
    indikator: [
      { indikator: "Jumlah publikasi PkM jurnal SINTA per tahun", strategi: "Insentif", unit: "LPPM", baseline: 15, target: [25, 38, 55, 75, 100] },
      { indikator: "Jumlah prosiding seminar PkM per tahun", strategi: "Hibah", unit: "LPPM", baseline: 25, target: [40, 60, 85, 115, 150] },
      { indikator: "Persentase PkM dengan publikasi", strategi: "Monitoring", unit: "LPPM", baseline: 60, target: [72, 82, 90, 96, 100] },
      { indikator: "Jumlah best practice PkM terdokumentasi", strategi: "Dokumentasi", unit: "LPPM", baseline: 10, target: [18, 28, 40, 55, 70] },
      { indikator: "Jumlah dosen dengan publikasi PkM per tahun", strategi: "Pendampingan", unit: "LPPM", baseline: 20, target: [30, 45, 65, 90, 120] },
    ],
    dokumenTerkait: DOKUMEN_TERKAIT_DEFAULT,
  },
  {
    namaStandar: "STANDAR PRODUK DAN JASA PkM",
    kodeStandar: "PKM-PRD",
    rasional: [
      "Standar Produk dan Jasa PkM mengatur kriteria minimal produk dan jasa yang dihasilkan dari PkM. Produk dan jasa PkM menjadi wujud nyata kontribusi perguruan tinggi kepada masyarakat, dan menjadi indikator dampak langsung PkM. Universitas Tulungagung mendorong dosen untuk menghasilkan produk dan jasa PkM yang sesuai dengan kebutuhan masyarakat.",
      "Produk dan jasa PkM yang baik harus praktis, terjangkau, dan dapat diadopsi masyarakat. Universitas Tulungagung mengembangkan ekosistem yang mendukung dosen untuk menghasilkan produk dan jasa PkM yang berkualitas, mulai dari riset awal hingga komersialisasi.",
    ],
    pihakPJ: PJ_DEFAULT_PKM,
    definisi: [
      ["a.", "Produk PkM", "barang hasil PkM yang dapat dimanfaatkan oleh masyarakat."],
      ["b.", "Jasa PkM", "layanan hasil PkM yang diberikan kepada masyarakat."],
      ["c.", "Teknologi Tepat Guna", "teknologi yang sesuai dengan kebutuhan dan kondisi masyarakat pengguna."],
      ["d.", "Adopsi", "penggunaan produk atau jasa PkM oleh masyarakat."],
    ],
    pernyataan: [
      "Universitas Tulungagung mendorong dosen untuk menghasilkan produk dan jasa PkM yang sesuai kebutuhan masyarakat.",
      "Produk dan jasa PkM harus praktis, terjangkau, dan dapat diadopsi masyarakat.",
      "Produk dan jasa PkM didokumentasikan dalam sistem informasi LPPM dan PD Dikti.",
      "Universitas Tulungagung mengembangkan kerjasama dengan DUDI untuk komersialisasi produk PkM.",
      "Produk dan jasa PkM menjadi salah satu kriteria penilaian kinerja dosen.",
    ],
    strategi: [
      "Menyediakan dana hibah untuk pengembangan produk dan jasa PkM.",
      "Mengembangkan inkubator bisnis untuk komersialisasi produk PkM.",
      "Mengundang DUDI untuk identifikasi produk PkM yang berpotensi komersialisasi.",
      "Menyelenggarakan pameran produk PkM tahunan.",
      "Mengintegrasikan dokumentasi produk dan jasa PkM dengan PD Dikti.",
    ],
    indikator: [
      { indikator: "Jumlah produk PkM dihasilkan per tahun", strategi: "Hibah", unit: "LPPM", baseline: 20, target: [30, 45, 65, 90, 120] },
      { indikator: "Jumlah jasa PkM diberikan per tahun", strategi: "Pendampingan", unit: "LPPM", baseline: 35, target: [50, 70, 95, 125, 160] },
      { indikator: "Jumlah produk PkM diadopsi masyarakat", strategi: "Diseminasi", unit: "LPPM", baseline: 10, target: [18, 28, 40, 55, 70] },
      { indikator: "Jumlah produk PkM dikomersialisasi", strategi: "Inkubator bisnis", unit: "LPPM", baseline: 2, target: [4, 7, 12, 18, 25] },
      { indikator: "Pendapatan dari produk PkM (Rp juta)", strategi: "Kerjasama DUDI", unit: "BAKU", baseline: 5, target: [15, 35, 70, 130, 200] },
    ],
    dokumenTerkait: DOKUMEN_TERKAIT_DEFAULT,
  },
  {
    namaStandar: "STANDAR DISEMINASI PkM",
    kodeStandar: "PKM-DSM",
    rasional: [
      "Standar Diseminasi PkM mengatur kriteria minimal penyebarluasan hasil PkM kepada masyarakat akademik dan publik. Diseminasi yang baik meningkatkan dampak PkM dan reputasi perguruan tinggi. Universitas Tulungagung menyelenggarakan berbagai forum diseminasi—seperti seminar, konferensi, dan pameran—untuk menyebarluaskan hasil PkM.",
      "Diseminasi PkM juga menjadi sarana untuk memperoleh umpan balik dari masyarakat akademik dan publik, sehingga dapat meningkatkan kualitas PkM selanjutnya. Universitas Tulungagung mendorong dosen untuk aktif menyebarkan hasil PkM melalui berbagai saluran, baik akademik maupun publik.",
    ],
    pihakPJ: PJ_DEFAULT_PKM,
    definisi: [
      ["a.", "Diseminasi PkM", "penyebarluasan hasil PkM kepada masyarakat akademik dan publik."],
      ["b.", "Seminar PkM", "forum pertemuan untuk presentasi dan diskusi hasil PkM."],
      ["c.", "Pameran PkM", "kegiatan pameran produk dan jasa PkM kepada masyarakat."],
      ["d.", "Publikasi Media PkM", "penyampaian hasil PkM melalui media massa."],
    ],
    pernyataan: [
      "Universitas Tulungagung menyelenggarakan seminar dan pameran PkM secara berkala.",
      "Universitas Tulungagung mendorong dosen untuk mempresentasikan hasil PkM di forum ilmiah.",
      "Hasil PkM disebarkan juga melalui media massa untuk publik luas.",
      "Universitas Tulungagung mengembangkan platform digital untuk diseminasi PkM.",
      "Hasil diseminasi didokumentasikan dalam sistem informasi LPPM.",
    ],
    strategi: [
      "Menyelenggarakan seminar nasional PkM tahunan Universitas Tulungagung.",
      "Memberikan pendanaan bagi dosen yang presentasi di konferensi PkM.",
      "Bekerja sama dengan media massa untuk publikasi hasil PkM.",
      "Mengembangkan repository digital untuk dokumentasi hasil PkM.",
      "Menyelenggarakan pameran produk PkM tahunan.",
    ],
    indikator: [
      { indikator: "Jumlah seminar/pameran PkM diselenggarakan per tahun", strategi: "Pendanaan", unit: "LPPM", baseline: 3, target: [5, 8, 12, 16, 22] },
      { indikator: "Jumlah dosen presentasi PkM di konferensi", strategi: "Hibah", unit: "LPPM", baseline: 20, target: [32, 48, 68, 92, 120] },
      { indikator: "Jumlah publikasi PkM di media massa per tahun", strategi: "Kerjasama media", unit: "LPPM", baseline: 10, target: [18, 28, 40, 55, 75] },
      { indikator: "Jumlah akses repository PkM per tahun", strategi: "Pengembangan digital", unit: "UPT SI", baseline: 2000, target: [3500, 5500, 8000, 11000, 15000] },
      { indikator: "Jumlah peserta pameran PkM per tahun", strategi: "Promosi", unit: "LPPM", baseline: 200, target: [350, 550, 800, 1100, 1500] },
    ],
    dokumenTerkait: DOKUMEN_TERKAIT_DEFAULT,
  },
  {
    namaStandar: "STANDAR KOLABORASI PkM",
    kodeStandar: "PKM-KLB",
    rasional: [
      "Standar Kolaborasi PkM mengatur kriteria minimal kerja sama PkM dengan institusi lain, baik nasional maupun internasional. Kolaborasi menjadi sarana untuk memperluas jaringan, berbagi sumber daya, dan meningkatkan kualitas PkM. Universitas Tulungagung aktif mengembangkan kerja sama PkM dengan perguruan tinggi lain, DUDI, dan lembaga PkM.",
      "Kolaborasi dengan DUDI dan pemerintah daerah menjadi salah satu indikator dampak PkM. Universitas Tulungagung menargetkan peningkatan kerja sama PkM, khususnya dengan pemerintah daerah di Jawa Timur dan DUDI di sektor strategis. Hal ini sejalan dengan visi Universitas Tulungagung untuk memberikan kontribusi nyata kepada masyarakat.",
    ],
    pihakPJ: PJ_DEFAULT_PKM,
    definisi: [
      ["a.", "Kolaborasi PkM", "kerja sama PkM antara dua atau lebih institusi."],
      ["b.", "MoU PkM", "Memorandum of Understanding tingkat umum untuk PkM."],
      ["c.", "MoA PkM", "Memorandum of Agreement spesifik untuk PkM."],
      ["d.", "Joint PkM", "PkM bersama yang melibatkan pelaksana dari beberapa institusi."],
    ],
    pernyataan: [
      "Universitas Tulungagung aktif mengembangkan kerja sama PkM dengan PT lain, DUDI, dan pemerintah.",
      "Kerja sama PkM didokumentasikan dalam bentuk MoU/MoA yang jelas.",
      "Universitas Tulungagung mengembangkan joint PkM dengan institusi nasional dan internasional.",
      "Kerja sama PkM dilaporkan dalam sistem informasi LPPM dan PD Dikti.",
      "Universitas Tulungagung memberikan dukungan administratif dan finansial untuk kolaborasi PkM.",
    ],
    strategi: [
      "Mengembangkan kerja sama strategis dengan pemerintah daerah Jawa Timur.",
      "Mengundang pelaksana PkM eksternal sebagai mitra.",
      "Menyelenggarakan joint conference PkM dengan PT mitra.",
      "Mengembangkan program PkM bersama dengan DUDI.",
      "Memberikan insentif bagi dosen yang aktif dalam kolaborasi PkM.",
    ],
    indikator: [
      { indikator: "Jumlah MoU/MoA PkM aktif", strategi: "Networking", unit: "LPPM", baseline: 15, target: [22, 32, 45, 60, 80] },
      { indikator: "Jumlah joint PkM per tahun", strategi: "Pendanaan", unit: "LPPM", baseline: 4, target: [7, 12, 18, 25, 35] },
      { indikator: "Jumlah kerjasama PkM dengan pemerintah daerah", strategi: "Kerjasama strategis", unit: "LPPM", baseline: 5, target: [8, 13, 18, 25, 32] },
      { indikator: "Jumlah kerjasama PkM dengan DUDI", strategi: "Pendekatan DUDI", unit: "LPPM", baseline: 8, target: [13, 20, 30, 42, 55] },
      { indikator: "Jumlah kerjasama PkM internasional", strategi: "Ekspansi", unit: "LPPM", baseline: 2, target: [4, 7, 12, 18, 25] },
    ],
    dokumenTerkait: DOKUMEN_TERKAIT_DEFAULT,
  },
];

// ============================================================
// 9 STANDAR TAMBAHAN PELAMPAUAN SN DIKTI
// ============================================================
const STANDAR_TAMBAHAN = [
  {
    namaStandar: "STANDAR VISI, MISI, TUJUAN, DAN STRATEGI",
    kodeStandar: "VMTS",
    rasional: [
      "Standar Visi, Misi, Tujuan, dan Strategi (VMTS) merupakan standar tambahan yang mengatur kriteria minimal perumusan, sosialisasi, dan implementasi VMTS di Universitas Tulungagung. VMTS menjadi landasan filosofis dan strategis bagi seluruh kegiatan perguruan tinggi, sehingga standar ini menempati posisi penting dalam sistem SPMI.",
      "Universitas Tulungagung memandang VMTS sebagai cita-cita bersama yang menjadi sumber inspirasi, motivasi, dan kekuatan pembimbing bagi segenap pihak yang berkepentingan. VMTS harus jelas, realistik, dan saling terkait satu dengan yang lain. Selain itu, VMTS harus disosialisasikan secara teratur, sistematis, dan berkelanjutan kepada semua pemangku kepentingan, internal maupun eksternal.",
    ],
    pihakPJ: PJ_DEFAULT_NONAKADEMIK,
    definisi: [
      ["a.", "Visi", "pernyataan yang menggambarkan cita-cita institusi tentang keadaannya di masa depan."],
      ["b.", "Misi", "pernyataan tentang keadaan/situasi/posisi yang saat ini sedang dijalankan institusi."],
      ["c.", "Tujuan", "penjabaran visi dan misi, hal yang akan dicapai atau dihasilkan institusi."],
      ["d.", "Strategi", "cara institusi mencapai tujuan, diturunkan ke dalam sasaran dan indikator."],
    ],
    pernyataan: [
      "Senat Universitas bersama pemangku kepentingan wajib merumuskan VMTS UNITA yang jelas, realistik, dan saling terkait.",
      "Pimpinan Universitas mensosialisasikan VMTS secara teratur, sistematis, dan berkelanjutan kepada pemangku kepentingan.",
      "Seluruh sivitas akademika memahami VMTS dengan baik.",
      "Semua unit kerja menggunakan VMTS sebagai acuan dalam penjabaran renstra dan rencana kinerja tahunan.",
      "Pimpinan Universitas menetapkan rencana induk pengembangan untuk jangka panjang dalam rangka penjabaran VMTS.",
      "Pimpinan Universitas menetapkan tonggak capaian (milestones) setiap lima tahun sebagai penjabaran renstra.",
    ],
    strategi: [
      "Mengundang DUDI, mitra, dan stakeholder yang relevan dengan lulusan dalam menyusun VMTS.",
      "Mensosialisasikan VMTS kepada seluruh sivitas akademika secara berkelanjutan.",
      "Melakukan review VMTS setiap lima tahun untuk memastikan relevansi.",
      "Mengintegrasikan VMTS dalam semua dokumen perencanaan dan operasional.",
      "Mengembangkan sistem informasi untuk monitoring ketercapaian VMTS.",
    ],
    indikator: [
      { indikator: "Universitas memiliki RIP, Renstra, dan Renop", strategi: "Penyusunan dokumen", unit: "Rektor", baseline: 1, target: [1, 1, 1, 1, 1] },
      { indikator: "Fakultas memiliki Renstra dan Renop", strategi: "Penyusunan dokumen", unit: "Dekan", baseline: 5, target: [5, 5, 5, 5, 5] },
      { indikator: "Tingkat pemahaman sivitas akademika terhadap VMTS", strategi: "Sosialisasi", unit: "PPM", baseline: 75, target: [80, 85, 90, 93, 96] },
      { indikator: "Jumlah review VMTS per 5 tahun", strategi: "Workshop", unit: "Senat", baseline: 1, target: [1, 1, 1, 1, 1] },
      { indikator: "Persentase unit kerja yang mengintegrasikan VMTS dalam Renop", strategi: "Monitoring", unit: "PPM", baseline: 80, target: [88, 94, 98, 100, 100] },
    ],
    dokumenTerkait: DOKUMEN_TERKAIT_DEFAULT,
  },
  {
    namaStandar: "STANDAR TATA PAMONG DAN TATA KELOLA",
    kodeStandar: "TPTK",
    rasional: [
      "Standar Tata Pamong dan Tata Kelola merupakan standar tambahan yang mengatur kriteria minimal struktur tata pamong, sistem pengelolaan, dan sistem penjaminan mutu. Tata pamong yang baik diperlukan agar sistem pengelolaan dapat berjalan efektif melalui mekanisme yang disepakati bersama, serta dapat memelihara dan mengakomodasi semua unsur, fungsi, dan peran dalam institusi.",
      "Sesuai Pasal 67 ayat (2) Permen 39 Tahun 2025, Universitas Tulungagung menerapkan tata kelola perguruan tinggi yang baik berdasarkan prinsip akuntabilitas, transparansi, nirlaba, efektivitas, efisiensi, dan peningkatan mutu berkelanjutan, yang saling menilik dan mengimbangi satu terhadap yang lain. Standar ini menjadi acuan operasional bagi seluruh kebijakan, prosedur, dan aktivitas SPMI.",
    ],
    pihakPJ: PJ_DEFAULT_NONAKADEMIK,
    definisi: [
      ["a.", "Tata Pamong", "struktur dan mekanisme pengelolaan perguruan tinggi."],
      ["b.", "Tata Kelola", "sistem pengelolaan yang mengatur hubungan antar-organ dalam perguruan tinggi."],
      ["c.", "Akuntabilitas", "kewajiban untuk mempertanggungjawabkan keputusan dan tindakan."],
      ["d.", "Transparansi", "keterbukaan informasi kepada pemangku kepentingan."],
    ],
    pernyataan: [
      "Universitas Tulungagung memiliki struktur tata pamong yang jelas, dengan pembagian tugas dan wewenang yang terdokumentasi.",
      "Universitas Tulungagung menerapkan tata kelola yang baik berdasarkan prinsip akuntabilitas, transparansi, nirlaba, efektivitas, efisiensi, dan peningkatan mutu berkelanjutan.",
      "Universitas Tulungagung memiliki sistem pengelolaan strategis dan operasional yang efektif.",
      "Universitas Tulungagung memiliki sistem penjaminan mutu yang sahih dan andal.",
      "Universitas Tulungagung memiliki mekanisme pengawasan oleh Senat dan Satuan Pengawas Internal (SPI).",
      "Universitas Tulungagung melakukan review tata pamong secara berkala untuk memastikan efektivitas.",
    ],
    strategi: [
      "Menyusun dan meninjau SOTK secara berkala.",
      "Mengembangkan sistem informasi untuk transparansi pengelolaan.",
      "Melakukan audit internal oleh SPI secara berkala.",
      "Menyelenggarakan rapat Senat secara rutin untuk pengawasan.",
      "Mengimplementasikan sistem manajemen mutu berbasis IT.",
    ],
    indikator: [
      { indikator: "Persentase SOTK yang terdokumentasi dan disosialisasikan", strategi: "Audit", unit: "BAU", baseline: 85, target: [92, 97, 100, 100, 100] },
      { indikator: "Jumlah audit internal SPI per tahun", strategi: "Program audit", unit: "SPI", baseline: 5, target: [8, 12, 16, 22, 28] },
      { indikator: "Persentase rekomendasi audit yang ditindaklanjuti", strategi: "Monitoring", unit: "SPI", baseline: 70, target: [80, 88, 94, 98, 100] },
      { indikator: "Tingkat kepuasan pemangku kepentingan terhadap transparansi", strategi: "Survey", unit: "PPM", baseline: 70, target: [76, 82, 87, 92, 96] },
      { indikator: "Jumlah rapat Senat per tahun", strategi: "Jadwal rutin", unit: "Senat", baseline: 4, target: [6, 8, 10, 12, 12] },
    ],
    dokumenTerkait: DOKUMEN_TERKAIT_DEFAULT,
  },
  {
    namaStandar: "STANDAR MAHASISWA",
    kodeStandar: "MHS",
    rasional: [
      "Standar Mahasiswa merupakan standar tambahan yang mengatur kriteria minimal pengelolaan mahasiswa di Universitas Tulungagung. Standar ini mencakup penerimaan, pembinaan, pengembangan, dan layanan kemahasiswaan. Mahasiswa adalah pelanggan utama perguruan tinggi, sehingga pengelolaan mahasiswa yang baik menjadi prasyarat bagi tercapainya mutu pendidikan.",
      "Universitas Tulungagung memandang mahasiswa tidak hanya sebagai objek pendidikan, tetapi juga sebagai mitra dalam pengembangan akademik. Universitas Tulungagung menyediakan berbagai layanan kemahasiswaan—seperti beasiswa, konseling, pengembangan minat-bakat, dan layanan karir—untuk mendukung keberhasilan studi dan kesiapan kerja mahasiswa.",
    ],
    pihakPJ: PJ_DEFAULT_NONAKADEMIK,
    definisi: [
      ["a.", "Mahasiswa", "peserta program pendidikan tinggi yang terdaftar di Universitas Tulungagung."],
      ["b.", "Layanan Kemahasiswaan", "layanan yang diberikan untuk mendukung keberhasilan studi mahasiswa."],
      ["c.", "Beasiswa", "bantuan finansial kepada mahasiswa untuk mendukung studi."],
      ["d.", "Konseling", "layanan bimbingan akademik dan psikologis kepada mahasiswa."],
    ],
    pernyataan: [
      "Universitas Tulungagung memiliki sistem penerimaan mahasiswa yang transparan dan akuntabel.",
      "Universitas Tulungagung menyediakan layanan kemahasiswaan yang lengkap, mencakup beasiswa, konseling, dan pengembangan minat-bakat.",
      "Universitas Tulungagung memiliki organisasi kemahasiswaan yang aktif dan demokratis.",
      "Universitas Tulungagung menyediakan layanan karir untuk mendukung kesiapan kerja lulusan.",
      "Universitas Tulungagung melakukan monitoring dan evaluasi layanan kemahasiswaan secara berkala.",
      "Universitas Tulungagung memastikan akses pendidikan bagi mahasiswa dari kelompok rentan.",
    ],
    strategi: [
      "Mengembangkan sistem informasi kemahasiswaan terintegrasi.",
      "Menyelenggarakan pelatihan kepemimpinan mahasiswa.",
      "Mengembangkan kemitraan dengan DUDI untuk beasiswa dan magang.",
      "Menyediakan layanan konseling profesional.",
      "Mengembangkan pusat karir untuk meningkatkan kesiapan kerja lulusan.",
    ],
    indikator: [
      { indikator: "Jumlah mahasiswa aktif", strategi: "Penerimaan", unit: "BAA", baseline: 8000, target: [8500, 9000, 9500, 10000, 10500] },
      { indikator: "Persentase mahasiswa menerima beasiswa", strategi: "Kemitraan", unit: "BAA", baseline: 15, target: [20, 25, 30, 35, 40] },
      { indikator: "Tingkat kepuasan mahasiswa terhadap layanan", strategi: "Survey", unit: "PPM", baseline: 70, target: [76, 82, 87, 92, 96] },
      { indikator: "Jumlah organisasi mahasiswa aktif", strategi: "Pembinaan", unit: "Wakil Rektor III", baseline: 25, target: [30, 35, 40, 45, 50] },
      { indikator: "Persentase lulusan terserap DUDI <6 bulan", strategi: "Pusat karir", unit: "Wakil Rektor III", baseline: 60, target: [65, 70, 75, 80, 85] },
    ],
    dokumenTerkait: DOKUMEN_TERKAIT_DEFAULT,
  },
  {
    namaStandar: "STANDAR SUMBER DAYA MANUSIA",
    kodeStandar: "SDM",
    rasional: [
      "Standar Sumber Daya Manusia merupakan standar tambahan yang mengatur kriteria minimal pengelolaan SDM di Universitas Tulungagung, baik dosen maupun tenaga kependidikan. SDM yang kompeten menjadi prasyarat bagi penyelenggaraan Tridharma yang bermutu. Standar ini berbeda dengan Standar Dosen dan Tenaga Kependidikan yang fokus pada kualifikasi dan beban kerja, karena Standar SDM fokus pada pengelolaan SDM secara menyeluruh.",
      "Universitas Tulungagung memandang SDM sebagai aset strategis yang perlu dikelola secara profesional. Pengelolaan SDM mencakup perencanaan, rekrutmen, pengembangan, penilaian, dan retensi. Universitas Tulungagung mengembangkan sistem manajemen SDM yang berbasis kinerja, untuk memastikan bahwa SDM yang ada dapat memberikan kontribusi optimal bagi pencapaian visi-misi.",
    ],
    pihakPJ: PJ_DEFAULT_NONAKADEMIK,
    definisi: [
      ["a.", "SDM", "Sumber Daya Manusia, mencakup dosen dan tenaga kependidikan."],
      ["b.", "Rekrutmen", "proses penerimaan SDM baru sesuai kebutuhan."],
      ["c.", "Pengembangan SDM", "kegiatan peningkatan kompetensi SDM."],
      ["d.", "Penilaian Kinerja", "proses penilaian capaian kinerja SDM."],
    ],
    pernyataan: [
      "Universitas Tulungagung memiliki rencana SDM jangka menengah yang diturunkan dari Renstra.",
      "Rekrutmen SDM dilakukan secara transparan, akuntabel, dan berbasis kompetensi.",
      "Universitas Tulungagung menyediakan program pengembangan SDM secara berkelanjutan.",
      "Universitas Tulungagung menerapkan sistem penilaian kinerja yang objektif dan transparan.",
      "Universitas Tulungagung memiliki sistem retensi SDM yang adil, termasuk kompensasi dan benefit.",
      "Universitas Tulungagung memiliki sistem informasi SDM yang terintegrasi.",
    ],
    strategi: [
      "Menyusun rencana SDM 5 tahunan dengan proyeksi kebutuhan.",
      "Mengembangkan sistem rekrutmen berbasis kompetensi.",
      "Menyelenggarakan program pelatihan dan pengembangan SDM berkala.",
      "Mengimplementasikan sistem penilaian kinerja berbasis SKP.",
      "Mengembangkan sistem informasi SDM terintegrasi dengan PD Dikti.",
    ],
    indikator: [
      { indikator: "Jumlah SDM (dosen + tendik)", strategi: "Rekrutmen", unit: "BAKU", baseline: 350, target: [380, 410, 440, 470, 500] },
      { indikator: "Persentase SDM dengan kompetensi sesuai tugas", strategi: "Pelatihan", unit: "BAKU", baseline: 75, target: [82, 88, 93, 97, 100] },
      { indikator: "Jumlah program pelatihan SDM per tahun", strategi: "Program diklat", unit: "BAKU", baseline: 15, target: [22, 30, 40, 50, 60] },
      { indikator: "Tingkat kepuasan SDM terhadap lingkungan kerja", strategi: "Survey", unit: "SPI", baseline: 70, target: [76, 82, 87, 92, 96] },
      { indikator: "Persentase SDM dengan SKP >80", strategi: "Penilaian kinerja", unit: "BAKU", baseline: 60, target: [70, 78, 85, 92, 96] },
    ],
    dokumenTerkait: DOKUMEN_TERKAIT_DEFAULT,
  },
  {
    namaStandar: "STANDAR KEUANGAN, SARANA, DAN PRASARANA",
    kodeStandar: "KSP",
    rasional: [
      "Standar Keuangan, Sarana, dan Prasarana merupakan standar tambahan yang mengatur kriteria minimal pengelolaan keuangan, sarana, dan prasarana di Universitas Tulungagung secara terintegrasi. Standar ini berbeda dengan Standar Pembiayaan (yang fokus pada biaya operasional pendidikan) dan Standar Sarana dan Prasarana (yang fokus pada fasilitas pendidikan), karena Standar KSP fokus pada tata kelola keuangan dan sarana secara menyeluruh.",
      "Universitas Tulungagung memandang keuangan, sarana, dan prasarana sebagai sistem yang terintegrasi. Pengelolaan yang baik dari ketiga aspek ini menjadi prasyarat bagi keberlanjutan institusi. Universitas Tulungagung menerapkan prinsip-prinsip tata kelola yang baik dalam pengelolaan keuangan, sarana, dan prasarana, dengan audit internal dan eksternal secara berkala.",
    ],
    pihakPJ: PJ_DEFAULT_NONAKADEMIK,
    definisi: [
      ["a.", "Keuangan", "pengelolaan dana Universitas Tulungagung, mencakup penerimaan dan belanja."],
      ["b.", "Sarana", "peralatan dan bahan untuk penyelenggaraan Tridharma."],
      ["c.", "Prasarana", "fasilitas fisik seperti gedung, ruang, dan jaringan utilitas."],
      ["d.", "Audit", "pemeriksaan independen terhadap pengelolaan keuangan dan sarana."],
    ],
    pernyataan: [
      "Universitas Tulungagung mengelola keuangan secara transparan, akuntabel, dan efisien.",
      "Universitas Tulungagung memiliki sistem akuntansi keuangan yang sesuai standar.",
      "Universitas Tulungagung melakukan audit internal oleh SPI dan audit eksternal oleh KAP.",
      "Universitas Tulungagung mengelola sarana dan prasarana secara terencana dan terdokumentasi.",
      "Universitas Tulungagung memiliki sistem inventarisasi sarana dan prasarana.",
      "Universitas Tulungagung mengembangkan sarana dan prasarana berbasis IT untuk efisiensi.",
    ],
    strategi: [
      "Mengimplementasikan sistem akuntansi berbasis accrual.",
      "Mengembangkan sistem informasi manajemen keuangan terintegrasi.",
      "Melakukan audit internal dan eksternal secara rutin.",
      "Mengembangkan sistem inventarisasi berbasis barcode/RFID.",
      "Menginvestasikan dana untuk pemeliharaan sarana dan prasarana secara berkala.",
    ],
    indikator: [
      { indikator: "Anggaran tahunan (Rp miliar)", strategi: "Pengembangan", unit: "BAKU", baseline: 80, target: [90, 100, 115, 130, 150] },
      { indikator: "Opini audit eksternal", strategi: "Tata kelola", unit: "SPI", baseline: "WDP", target: ["WDP", "WTP", "WTP", "WTP", "WTP"] },
      { indikator: "Persentase sarana terinventarisasi", strategi: "Sistem inventaris", unit: "BAU", baseline: 85, target: [92, 97, 100, 100, 100] },
      { indikator: "Persentase prasarana terpelihara sesuai standar", strategi: "Maintenance", unit: "BAU", baseline: 80, target: [86, 92, 96, 100, 100] },
      { indikator: "Persentase sistem keuangan terintegrasi IT", strategi: "Pengembangan IT", unit: "UPT SI", baseline: 75, target: [85, 92, 97, 100, 100] },
    ],
    dokumenTerkait: DOKUMEN_TERKAIT_DEFAULT,
  },
  {
    namaStandar: "STANDAR KERJASAMA",
    kodeStandar: "KJS",
    rasional: [
      "Standar Kerjasama merupakan standar tambahan yang mengatur kriteria minimal pengelolaan kerja sama Universitas Tulungagung dengan pihak eksternal, baik nasional maupun internasional. Kerja sama menjadi sarana untuk memperluas jaringan, berbagi sumber daya, dan meningkatkan kualitas Tridharma. Universitas Tulungagung aktif mengembangkan kerja sama strategis dengan PT lain, DUDI, pemerintah, dan lembaga internasional.",
      "Kerja sama yang baik harus saling menguntungkan, terdokumentasi, dan dievaluasi secara berkala. Universitas Tulungagung memiliki sistem pengelolaan kerja sama yang transparan, mulai dari pengajuan MoU/MoA, pelaksanaan, hingga evaluasi. Hal ini sejalan dengan sasaran strategis ke-6 Universitas Tulungagung, yaitu terjalinnya kerja sama nasional dan internasional yang berorientasi pada output berkelanjutan.",
    ],
    pihakPJ: PJ_DEFAULT_NONAKADEMIK,
    definisi: [
      ["a.", "Kerja sama", "hubungan formal antara Universitas Tulungagung dengan pihak eksternal untuk tujuan tertentu."],
      ["b.", "MoU", "Memorandum of Understanding, perjanjian kerja sama tingkat umum."],
      ["c.", "MoA", "Memorandum of Agreement, perjanjian kerja sama spesifik."],
      ["d.", "IA", "Implementation Agreement, perjanjian implementasi spesifik."],
    ],
    pernyataan: [
      "Universitas Tulungagung aktif mengembangkan kerja sama dengan PT lain, DUDI, pemerintah, dan lembaga internasional.",
      "Kerja sama didokumentasikan dalam bentuk MoU/MoA/IA yang jelas dan terdaftar.",
      "Universitas Tulungagung memiliki sistem pengelolaan kerja sama yang transparan.",
      "Kerja sama dievaluasi secara berkala untuk memastikan manfaat dan keberlanjutan.",
      "Universitas Tulungagung mengembangkan kerja sama strategis yang berorientasi pada output berkelanjutan.",
      "Universitas Tulungagung mendorong kerja sama internasional untuk meningkatkan reputasi global.",
    ],
    strategi: [
      "Mengembangkan kerja sama strategis dengan PT unggulan nasional dan internasional.",
      "Mengembangkan kemitraan DUDI untuk MBKM, magang, dan penelitian.",
      "Menyusun database kerja sama yang terintegrasi.",
      "Melakukan evaluasi kerja sama setiap tahun.",
      "Mengembangkan program joint degree dengan PT internasional.",
    ],
    indikator: [
      { indikator: "Jumlah MoU aktif", strategi: "Networking", unit: "BAU", baseline: 40, target: [55, 75, 100, 130, 165] },
      { indikator: "Jumlah MoA aktif", strategi: "Pendekatan", unit: "BAU", baseline: 60, target: [85, 115, 150, 190, 235] },
      { indikator: "Jumlah kerjasama internasional aktif", strategi: "Ekspansi", unit: "BAU", baseline: 10, target: [16, 25, 35, 48, 62] },
      { indikator: "Persentase kerjasama dengan implementasi nyata", strategi: "Monitoring", unit: "BAU", baseline: 60, target: [72, 82, 90, 96, 100] },
      { indikator: "Jumlah joint program dengan PT mitra", strategi: "Pengembangan", unit: "BAU", baseline: 3, target: [5, 8, 12, 17, 22] },
    ],
    dokumenTerkait: DOKUMEN_TERKAIT_DEFAULT,
  },
  {
    namaStandar: "STANDAR MERDEKA BELAJAR KAMPUS MERDEKA",
    kodeStandar: "MBKM",
    rasional: [
      "Standar Merdeka Belajar Kampus Merdeka (MBKM) merupakan standar tambahan yang mengatur kriteria minimal pelaksanaan MBKM di Universitas Tulungagung. MBKM memberikan ruang bagi mahasiswa untuk mengambil kegiatan di luar program studi selama 1-2 semester, dengan pengakuan SKS. Standar ini sejalan dengan kebijakan Kementerian Pendidikan Tinggi untuk memberikan keleluasaan kepada mahasiswa dalam mengembangkan kompetensi.",
      "Universitas Tulungagung memandang MBKM sebagai strategi penting untuk meningkatkan kualitas lulusan dan kesiapan kerja. Melalui MBKM, mahasiswa dapat memperoleh pengalaman praktis di DUDI, mengembangkan kompetensi lintas disiplin, dan memperluas jaringan. Universitas Tulungagung mengembangkan berbagai skema MBKM—seperti magang, studi independen, pertukaran, dan proyek kemanusiaan—yang sesuai dengan karakteristik program studi.",
    ],
    pihakPJ: PJ_DEFAULT_AKADEMIK,
    definisi: [
      ["a.", "MBKM", "Merdeka Belajar Kampus Merdeka, kebijakan yang memberikan ruang bagi mahasiswa untuk mengambil kegiatan di luar program studi."],
      ["b.", "Magang", "kegiatan MBKM di DUDI untuk pengalaman praktis."],
      ["c.", "Studi Independen", "kegiatan MBKM di lembaga eksternal untuk pengembangan kompetensi tertentu."],
      ["d.", "Pertukaran Pelajar", "kegiatan MBKM di PT lain untuk pengalaman akademik berbeda."],
    ],
    pernyataan: [
      "Universitas Tulungagung memberikan ruang bagi mahasiswa untuk mengambil kegiatan MBKM selama 1-2 semester.",
      "Universitas Tulungagung mengembangkan berbagai skema MBKM—magang, studi independen, pertukaran, dan proyek kemanusiaan.",
      "Universitas Tulungagung memberikan pengakuan SKS atas kegiatan MBKM yang diambil mahasiswa.",
      "Universitas Tulungagung mengembangkan kemitraan DUDI untuk menyediakan kesempatan MBKM.",
      "Universitas Tulungagung memiliki sistem pengelolaan MBKM yang transparan dan akuntabel.",
      "Universitas Tulungagung melakukan monitoring dan evaluasi pelaksanaan MBKM secara berkala.",
    ],
    strategi: [
      "Mengembangkan kerja sama DUDI untuk menyediakan kesempatan MBKM.",
      "Menyusun panduan MBKM yang jelas untuk mahasiswa dan dosen.",
      "Menyelenggarakan sosialisasi MBKM kepada mahasiswa setiap semester.",
      "Mengembangkan sistem informasi MBKM terintegrasi.",
      "Melakukan evaluasi pelaksanaan MBKM setiap tahun.",
    ],
    indikator: [
      { indikator: "Persentase prodi yang menerapkan MBKM", strategi: "Sosialisasi", unit: "UPPS", baseline: 70, target: [85, 95, 100, 100, 100] },
      { indikator: "Jumlah mahasiswa mengikuti MBKM per tahun", strategi: "Kerjasama DUDI", unit: "UPPS", baseline: 200, target: [350, 550, 800, 1100, 1500] },
      { indikator: "Jumlah mitra DUDI untuk MBKM", strategi: "Pengembangan", unit: "BAU", baseline: 30, target: [45, 65, 90, 120, 155] },
      { indikator: "Tingkat kepuasan mahasiswa terhadap MBKM", strategi: "Survey", unit: "PPM", baseline: 75, target: [80, 85, 90, 93, 96] },
      { indikator: "Persentase mahasiswa MBKM terserap DUDI", strategi: "Pendampingan", unit: "UPPS", baseline: 30, target: [40, 50, 60, 70, 80] },
    ],
    dokumenTerkait: DOKUMEN_TERKAIT_DEFAULT,
  },
  {
    namaStandar: "STANDAR LUARAN DAN CAPAIAN TRIDHARMA",
    kodeStandar: "LCT",
    rasional: [
      "Standar Luaran dan Capaian Tridharma merupakan standar tambahan yang mengatur kriteria minimal luaran dan capaian Tridharma Universitas Tulungagung. Standar ini berbeda dengan standar luaran per Tridharma (penelitian/PkM), karena Standar LCT fokus pada integrasi luaran Tridharma sebagai indikator kinerja perguruan tinggi secara menyeluruh.",
      "Universitas Tulungagung memandang luaran dan capaian Tridharma sebagai indikator utama kinerja perguruan tinggi. Luaran Tridharma mencakup lulusan, publikasi, paten, produk, jasa, dan kontribusi nyata kepada masyarakat. Universitas Tulungagung menargetkan peningkatan kuantitas dan kualitas luaran Tridharma, sebagaimana tertuang dalam sasaran strategis ke-3, 4, dan 5.",
    ],
    pihakPJ: PJ_DEFAULT_NONAKADEMIK,
    definisi: [
      ["a.", "Luaran Tridharma", "hasil pelaksanaan Tridharma, mencakup lulusan, publikasi, paten, produk, dan jasa."],
      ["b.", "Capaian Tridharma", "pencapaian target Tridharma yang telah ditetapkan."],
      ["c.", "IKU", "Indikator Kinerja Utama, ukuran kuantitatif kinerja perguruan tinggi."],
      ["d.", "IKT", "Indikator Kinerja Tambahan, ukuran kuantitatif tambahan di luar IKU."],
    ],
    pernyataan: [
      "Universitas Tulungagung menetapkan target luaran dan capaian Tridharma dalam Renstra.",
      "Universitas Tulungagung mengintegrasikan luaran Tridharma dalam Indikator Kinerja Utama (IKU) dan Tambahan (IKT).",
      "Universitas Tulungagung melakukan monitoring dan evaluasi capaian Tridharma secara berkala.",
      "Universitas Tulungagung mempublikasikan capaian Tridharma kepada pemangku kepentingan.",
      "Universitas Tulungagung menggunakan capaian Tridharma sebagai dasar perbaikan berkelanjutan.",
      "Universitas Tulungagung menargetkan peningkatan luaran Tridharma setiap tahun.",
    ],
    strategi: [
      "Menyusun target luaran Tridharma 5 tahunan dalam Renstra.",
      "Mengembangkan dashboard IKU/IKT yang dapat diakses real-time.",
      "Melakukan monitoring dan evaluasi capaian Tridharma setiap semester.",
      "Mempublikasikan capaian Tridharma melalui situs web dan laporan tahunan.",
      "Mengintegrasikan data luaran Tridharma dengan PD Dikti.",
    ],
    indikator: [
      { indikator: "Jumlah lulusan per tahun", strategi: "Penerimaan & retensi", unit: "BAA", baseline: 1500, target: [1700, 1900, 2100, 2300, 2500] },
      { indikator: "Jumlah publikasi Tridharma per tahun", strategi: "Insentif", unit: "LPPM", baseline: 200, target: [280, 380, 500, 650, 820] },
      { indikator: "Jumlah paten/HKI per tahun", strategi: "Pendampingan", unit: "LPPM", baseline: 15, target: [25, 38, 55, 75, 100] },
      { indikator: "Jumlah produk PkM per tahun", strategi: "Hibah", unit: "LPPM", baseline: 30, target: [45, 65, 90, 120, 155] },
      { indikator: "Persentase IKU yang tercapai", strategi: "Monitoring", unit: "PPM", baseline: 65, target: [72, 80, 88, 94, 98] },
    ],
    dokumenTerkait: DOKUMEN_TERKAIT_DEFAULT,
  },
  {
    namaStandar: "STANDAR PELAYANAN KEPADA MAHASISWA",
    kodeStandar: "PKM-MHS",
    rasional: [
      "Standar Pelayanan Kepada Mahasiswa merupakan standar tambahan yang mengatur kriteria minimal pelayanan kepada mahasiswa di Universitas Tulungagung. Pelayanan yang baik menjadi prasyarat bagi keberhasilan studi mahasiswa dan kepuasan pemangku kepentingan. Standar ini mencakup layanan akademik, layanan administrasi, layanan kemahasiswaan, dan layanan penunjang lainnya.",
      "Universitas Tulungagung memandang mahasiswa sebagai pelanggan utama yang berhak mendapatkan pelayanan yang prima. Universitas Tulungagung mengembangkan sistem pelayanan terintegrasi—One-Stop Service—untuk memudahkan mahasiswa dalam mengakses berbagai layanan. Selain itu, Universitas Tulungagung juga mengembangkan sistem informasi yang memungkinkan mahasiswa mengakses layanan secara digital.",
    ],
    pihakPJ: PJ_DEFAULT_NONAKADEMIK,
    definisi: [
      ["a.", "Pelayanan Mahasiswa", "layanan yang diberikan kepada mahasiswa untuk mendukung keberhasilan studi."],
      ["b.", "One-Stop Service", "sistem pelayanan terintegrasi yang menyediakan berbagai layanan dalam satu tempat."],
      ["c.", "Layanan Akademik", "layanan terkait kegiatan akademik, seperti KRS, ujian, dan nilai."],
      ["d.", "Layanan Administrasi", "layanan terkait administrasi mahasiswa, seperti KTM, transkrip, dan ijazah."],
    ],
    pernyataan: [
      "Universitas Tulungagung menyediakan layanan akademik yang lengkap dan mudah diakses.",
      "Universitas Tulungagung menyediakan layanan administrasi yang cepat dan akurat.",
      "Universitas Tulungagung mengembangkan One-Stop Service untuk memudahkan mahasiswa.",
      "Universitas Tulungagung menyediakan sistem informasi yang memungkinkan mahasiswa mengakses layanan secara digital.",
      "Universitas Tulungagung melakukan survey kepuasan mahasiswa secara berkala.",
      "Universitas Tulungagung menindaklanjuti setiap pengaduan mahasiswa secara cepat dan transparan.",
    ],
    strategi: [
      "Mengembangkan One-Stop Service di tingkat universitas dan fakultas.",
      "Mengembangkan aplikasi mobile untuk akses layanan mahasiswa.",
      "Melakukan survey kepuasan mahasiswa setiap semester.",
      "Mengembangkan sistem pengaduan mahasiswa yang mudah diakses.",
      "Menyelenggarakan pelatihan customer service bagi staff pelayanan.",
    ],
    indikator: [
      { indikator: "Tingkat kepuasan mahasiswa terhadap layanan akademik", strategi: "Survey", unit: "PPM", baseline: 70, target: [76, 82, 87, 92, 96] },
      { indikator: "Tingkat kepuasan mahasiswa terhadap layanan administrasi", strategi: "Survey", unit: "PPM", baseline: 65, target: [72, 80, 86, 91, 95] },
      { indikator: "Persentase layanan yang dapat diakses digital", strategi: "Pengembangan IT", unit: "UPT SI", baseline: 50, target: [65, 78, 88, 95, 100] },
      { indikator: "Waktu rata-rata penyelesaian pengaduan (hari)", strategi: "Standardisasi SOP", unit: "BAA", baseline: 7, target: [5, 4, 3, 2, 1] },
      { indikator: "Jumlah layanan One-Stop Service yang aktif", strategi: "Pengembangan", unit: "BAA", baseline: 3, target: [5, 8, 12, 16, 20] },
    ],
    dokumenTerkait: DOKUMEN_TERKAIT_DEFAULT,
  },
];

module.exports = {
  STANDAR_PKM,
  STANDAR_TAMBAHAN,
};
